update cidade set cod_tom = '0601' where uf = 4 and upper(trim(unaccent(nome))) like 'AMAPA'; 
update cidade set cod_tom = '0603' where uf = 4 and upper(trim(unaccent(nome))) like 'CALCOENE'; 
update cidade set cod_tom = '0667' where uf = 4 and upper(trim(unaccent(nome))) like 'CUTIAS'; 
update cidade set cod_tom = '0611' where uf = 4 and upper(trim(unaccent(nome))) like 'FERREIRA GOMES'; 
update cidade set cod_tom = '0669' where uf = 4 and upper(trim(unaccent(nome))) like 'ITAUBAL'; 
update cidade set cod_tom = '0613' where uf = 4 and upper(trim(unaccent(nome))) like 'LARANJAL DO JARI'; 
update cidade set cod_tom = '0605' where uf = 4 and upper(trim(unaccent(nome))) like 'MACAPA'; 
update cidade set cod_tom = '0607' where uf = 4 and upper(trim(unaccent(nome))) like 'MAZAGAO'; 
update cidade set cod_tom = '0609' where uf = 4 and upper(trim(unaccent(nome))) like 'OIAPOQUE'; 
update cidade set cod_tom = '0663' where uf = 4 and upper(trim(unaccent(nome))) like 'PEDRA BRANCA DO AMAPARI'; 
update cidade set cod_tom = '0' where uf = 4 and upper(trim(unaccent(nome))) like 'PORTO BRANCO'; 
update cidade set cod_tom = '0671' where uf = 4 and upper(trim(unaccent(nome))) like 'PORTO GRANDE'; 
update cidade set cod_tom = '0673' where uf = 4 and upper(trim(unaccent(nome))) like 'PRACUUBA'; 
update cidade set cod_tom = '0615' where uf = 4 and upper(trim(unaccent(nome))) like 'SANTANA'; 
update cidade set cod_tom = '0665' where uf = 4 and upper(trim(unaccent(nome))) like 'SERRA DO NAVIO'; 
update cidade set cod_tom = '0617' where uf = 4 and upper(trim(unaccent(nome))) like 'TARTARUGALZINHO'; 
update cidade set cod_tom = '0070' where uf = 4 and upper(trim(unaccent(nome))) like 'VITORIA DO JARI'; 
