update cidade set cod_tom = '6101' where uf = 26 and upper(trim(unaccent(nome))) like 'ADAMANTINA'; 
update cidade set cod_tom = '6103' where uf = 26 and upper(trim(unaccent(nome))) like 'ADOLFO'; 
update cidade set cod_tom = '6105' where uf = 26 and upper(trim(unaccent(nome))) like 'AGUAI'; 
update cidade set cod_tom = '6107' where uf = 26 and upper(trim(unaccent(nome))) like 'AGUAS DA PRATA'; 
update cidade set cod_tom = '6109' where uf = 26 and upper(trim(unaccent(nome))) like 'AGUAS DE LINDOIA'; 
update cidade set cod_tom = '7019' where uf = 26 and upper(trim(unaccent(nome))) like 'AGUAS DE SANTA BARBARA'; 
update cidade set cod_tom = '6111' where uf = 26 and upper(trim(unaccent(nome))) like 'AGUAS DE SAO PEDRO'; 
update cidade set cod_tom = '6113' where uf = 26 and upper(trim(unaccent(nome))) like 'AGUDOS'; 
update cidade set cod_tom = '2995' where uf = 26 and upper(trim(unaccent(nome))) like 'ALAMBARI'; 
update cidade set cod_tom = '6115' where uf = 26 and upper(trim(unaccent(nome))) like 'ALFREDO MARCONDES'; 
update cidade set cod_tom = '6117' where uf = 26 and upper(trim(unaccent(nome))) like 'ALTAIR'; 
update cidade set cod_tom = '6119' where uf = 26 and upper(trim(unaccent(nome))) like 'ALTINOPOLIS'; 
update cidade set cod_tom = '6121' where uf = 26 and upper(trim(unaccent(nome))) like 'ALTO ALEGRE'; 
update cidade set cod_tom = '3065' where uf = 26 and upper(trim(unaccent(nome))) like 'ALUMINIO'; 
update cidade set cod_tom = '6123' where uf = 26 and upper(trim(unaccent(nome))) like 'ALVARES FLORENCE'; 
update cidade set cod_tom = '6125' where uf = 26 and upper(trim(unaccent(nome))) like 'ALVARES MACHADO'; 
update cidade set cod_tom = '6127' where uf = 26 and upper(trim(unaccent(nome))) like 'ALVARO DE CARVALHO'; 
update cidade set cod_tom = '6129' where uf = 26 and upper(trim(unaccent(nome))) like 'ALVINLANDIA'; 
update cidade set cod_tom = '6131' where uf = 26 and upper(trim(unaccent(nome))) like 'AMERICANA'; 
update cidade set cod_tom = '6133' where uf = 26 and upper(trim(unaccent(nome))) like 'AMERICO BRASILIENSE'; 
update cidade set cod_tom = '6135' where uf = 26 and upper(trim(unaccent(nome))) like 'AMERICO DE CAMPOS'; 
update cidade set cod_tom = '6137' where uf = 26 and upper(trim(unaccent(nome))) like 'AMPARO'; 
update cidade set cod_tom = '6139' where uf = 26 and upper(trim(unaccent(nome))) like 'ANALANDIA'; 
update cidade set cod_tom = '6141' where uf = 26 and upper(trim(unaccent(nome))) like 'ANDRADINA'; 
update cidade set cod_tom = '6143' where uf = 26 and upper(trim(unaccent(nome))) like 'ANGATUBA'; 
update cidade set cod_tom = '6145' where uf = 26 and upper(trim(unaccent(nome))) like 'ANHEMBI'; 
update cidade set cod_tom = '6147' where uf = 26 and upper(trim(unaccent(nome))) like 'ANHUMAS'; 
update cidade set cod_tom = '6149' where uf = 26 and upper(trim(unaccent(nome))) like 'APARECIDA'; 
update cidade set cod_tom = '6151' where uf = 26 and upper(trim(unaccent(nome))) like 'APARECIDA D`OESTE'; 
update cidade set cod_tom = '6153' where uf = 26 and upper(trim(unaccent(nome))) like 'APIAI'; 
update cidade set cod_tom = '3067' where uf = 26 and upper(trim(unaccent(nome))) like 'ARACARIGUAMA'; 
update cidade set cod_tom = '6155' where uf = 26 and upper(trim(unaccent(nome))) like 'ARACATUBA'; 
update cidade set cod_tom = '6157' where uf = 26 and upper(trim(unaccent(nome))) like 'ARACOIABA DA SERRA'; 
update cidade set cod_tom = '6159' where uf = 26 and upper(trim(unaccent(nome))) like 'ARAMINA'; 
update cidade set cod_tom = '6161' where uf = 26 and upper(trim(unaccent(nome))) like 'ARANDU'; 
update cidade set cod_tom = '2991' where uf = 26 and upper(trim(unaccent(nome))) like 'ARAPEI'; 
update cidade set cod_tom = '6163' where uf = 26 and upper(trim(unaccent(nome))) like 'ARARAQUARA'; 
update cidade set cod_tom = '6165' where uf = 26 and upper(trim(unaccent(nome))) like 'ARARAS'; 
update cidade set cod_tom = '0790' where uf = 26 and upper(trim(unaccent(nome))) like 'ARCO-IRIS'; 
update cidade set cod_tom = '6167' where uf = 26 and upper(trim(unaccent(nome))) like 'AREALVA'; 
update cidade set cod_tom = '6169' where uf = 26 and upper(trim(unaccent(nome))) like 'AREIAS'; 
update cidade set cod_tom = '6171' where uf = 26 and upper(trim(unaccent(nome))) like 'AREIOPOLIS'; 
update cidade set cod_tom = '6173' where uf = 26 and upper(trim(unaccent(nome))) like 'ARIRANHA'; 
update cidade set cod_tom = '6175' where uf = 26 and upper(trim(unaccent(nome))) like 'ARTUR NOGUEIRA'; 
update cidade set cod_tom = '6177' where uf = 26 and upper(trim(unaccent(nome))) like 'ARUJA'; 
update cidade set cod_tom = '2981' where uf = 26 and upper(trim(unaccent(nome))) like 'ASPASIA'; 
update cidade set cod_tom = '6179' where uf = 26 and upper(trim(unaccent(nome))) like 'ASSIS'; 
update cidade set cod_tom = '6181' where uf = 26 and upper(trim(unaccent(nome))) like 'ATIBAIA'; 
update cidade set cod_tom = '6183' where uf = 26 and upper(trim(unaccent(nome))) like 'AURIFLAMA'; 
update cidade set cod_tom = '6185' where uf = 26 and upper(trim(unaccent(nome))) like 'AVAI'; 
update cidade set cod_tom = '6187' where uf = 26 and upper(trim(unaccent(nome))) like 'AVANHANDAVA'; 
update cidade set cod_tom = '6189' where uf = 26 and upper(trim(unaccent(nome))) like 'AVARE'; 
update cidade set cod_tom = '6191' where uf = 26 and upper(trim(unaccent(nome))) like 'BADY BASSITT'; 
update cidade set cod_tom = '6193' where uf = 26 and upper(trim(unaccent(nome))) like 'BALBINOS'; 
update cidade set cod_tom = '6195' where uf = 26 and upper(trim(unaccent(nome))) like 'BALSAMO'; 
update cidade set cod_tom = '6197' where uf = 26 and upper(trim(unaccent(nome))) like 'BANANAL'; 
update cidade set cod_tom = '6201' where uf = 26 and upper(trim(unaccent(nome))) like 'BARAO DE ANTONINA'; 
update cidade set cod_tom = '6199' where uf = 26 and upper(trim(unaccent(nome))) like 'BARBOSA'; 
update cidade set cod_tom = '6203' where uf = 26 and upper(trim(unaccent(nome))) like 'BARIRI'; 
update cidade set cod_tom = '6205' where uf = 26 and upper(trim(unaccent(nome))) like 'BARRA BONITA'; 
update cidade set cod_tom = '2997' where uf = 26 and upper(trim(unaccent(nome))) like 'BARRA DO CHAPEU'; 
update cidade set cod_tom = '6207' where uf = 26 and upper(trim(unaccent(nome))) like 'BARRA DO TURVO'; 
update cidade set cod_tom = '6209' where uf = 26 and upper(trim(unaccent(nome))) like 'BARRETOS'; 
update cidade set cod_tom = '6211' where uf = 26 and upper(trim(unaccent(nome))) like 'BARRINHA'; 
update cidade set cod_tom = '6213' where uf = 26 and upper(trim(unaccent(nome))) like 'BARUERI'; 
update cidade set cod_tom = '6215' where uf = 26 and upper(trim(unaccent(nome))) like 'BASTOS'; 
update cidade set cod_tom = '6217' where uf = 26 and upper(trim(unaccent(nome))) like 'BATATAIS'; 
update cidade set cod_tom = '6219' where uf = 26 and upper(trim(unaccent(nome))) like 'BAURU'; 
update cidade set cod_tom = '6221' where uf = 26 and upper(trim(unaccent(nome))) like 'BEBEDOURO'; 
update cidade set cod_tom = '6223' where uf = 26 and upper(trim(unaccent(nome))) like 'BENTO DE ABREU'; 
update cidade set cod_tom = '6225' where uf = 26 and upper(trim(unaccent(nome))) like 'BERNARDINO DE CAMPOS'; 
update cidade set cod_tom = '2965' where uf = 26 and upper(trim(unaccent(nome))) like 'BERTIOGA'; 
update cidade set cod_tom = '6227' where uf = 26 and upper(trim(unaccent(nome))) like 'BILAC'; 
update cidade set cod_tom = '6229' where uf = 26 and upper(trim(unaccent(nome))) like 'BIRIGUI'; 
update cidade set cod_tom = '6231' where uf = 26 and upper(trim(unaccent(nome))) like 'BIRITIBA-MIRIM'; 
update cidade set cod_tom = '6233' where uf = 26 and upper(trim(unaccent(nome))) like 'BOA ESPERANCA DO SUL'; 
update cidade set cod_tom = '6235' where uf = 26 and upper(trim(unaccent(nome))) like 'BOCAINA'; 
update cidade set cod_tom = '6237' where uf = 26 and upper(trim(unaccent(nome))) like 'BOFETE'; 
update cidade set cod_tom = '6239' where uf = 26 and upper(trim(unaccent(nome))) like 'BOITUVA'; 
update cidade set cod_tom = '6241' where uf = 26 and upper(trim(unaccent(nome))) like 'BOM JESUS DOS PERDOES'; 
update cidade set cod_tom = '3059' where uf = 26 and upper(trim(unaccent(nome))) like 'BOM SUCESSO DE ITARARE'; 
update cidade set cod_tom = '6243' where uf = 26 and upper(trim(unaccent(nome))) like 'BORA'; 
update cidade set cod_tom = '6245' where uf = 26 and upper(trim(unaccent(nome))) like 'BORACEIA'; 
update cidade set cod_tom = '6247' where uf = 26 and upper(trim(unaccent(nome))) like 'BORBOREMA'; 
update cidade set cod_tom = '7247' where uf = 26 and upper(trim(unaccent(nome))) like 'BOREBI'; 
update cidade set cod_tom = '6249' where uf = 26 and upper(trim(unaccent(nome))) like 'BOTUCATU'; 
update cidade set cod_tom = '6251' where uf = 26 and upper(trim(unaccent(nome))) like 'BRAGANCA PAULISTA'; 
update cidade set cod_tom = '6255' where uf = 26 and upper(trim(unaccent(nome))) like 'BRAUNA'; 
update cidade set cod_tom = '0792' where uf = 26 and upper(trim(unaccent(nome))) like 'BREJO ALEGRE'; 
update cidade set cod_tom = '6257' where uf = 26 and upper(trim(unaccent(nome))) like 'BRODOWSKI'; 
update cidade set cod_tom = '6259' where uf = 26 and upper(trim(unaccent(nome))) like 'BROTAS'; 
update cidade set cod_tom = '6261' where uf = 26 and upper(trim(unaccent(nome))) like 'BURI'; 
update cidade set cod_tom = '6263' where uf = 26 and upper(trim(unaccent(nome))) like 'BURITAMA'; 
update cidade set cod_tom = '6265' where uf = 26 and upper(trim(unaccent(nome))) like 'BURITIZAL'; 
update cidade set cod_tom = '6267' where uf = 26 and upper(trim(unaccent(nome))) like 'CABRALIA PAULISTA'; 
update cidade set cod_tom = '6269' where uf = 26 and upper(trim(unaccent(nome))) like 'CABREUVA'; 
update cidade set cod_tom = '6271' where uf = 26 and upper(trim(unaccent(nome))) like 'CACAPAVA'; 
update cidade set cod_tom = '6273' where uf = 26 and upper(trim(unaccent(nome))) like 'CACHOEIRA PAULISTA'; 
update cidade set cod_tom = '6275' where uf = 26 and upper(trim(unaccent(nome))) like 'CACONDE'; 
update cidade set cod_tom = '6277' where uf = 26 and upper(trim(unaccent(nome))) like 'CAFELANDIA'; 
update cidade set cod_tom = '6279' where uf = 26 and upper(trim(unaccent(nome))) like 'CAIABU'; 
update cidade set cod_tom = '6281' where uf = 26 and upper(trim(unaccent(nome))) like 'CAIEIRAS'; 
update cidade set cod_tom = '6283' where uf = 26 and upper(trim(unaccent(nome))) like 'CAIUA'; 
update cidade set cod_tom = '6285' where uf = 26 and upper(trim(unaccent(nome))) like 'CAJAMAR'; 
update cidade set cod_tom = '2967' where uf = 26 and upper(trim(unaccent(nome))) like 'CAJATI'; 
update cidade set cod_tom = '6287' where uf = 26 and upper(trim(unaccent(nome))) like 'CAJOBI'; 
update cidade set cod_tom = '6289' where uf = 26 and upper(trim(unaccent(nome))) like 'CAJURU'; 
update cidade set cod_tom = '2999' where uf = 26 and upper(trim(unaccent(nome))) like 'CAMPINA DO MONTE ALEGRE'; 
update cidade set cod_tom = '6291' where uf = 26 and upper(trim(unaccent(nome))) like 'CAMPINAS'; 
update cidade set cod_tom = '6293' where uf = 26 and upper(trim(unaccent(nome))) like 'CAMPO LIMPO PAULISTA'; 
update cidade set cod_tom = '6295' where uf = 26 and upper(trim(unaccent(nome))) like 'CAMPOS DO JORDAO'; 
update cidade set cod_tom = '6297' where uf = 26 and upper(trim(unaccent(nome))) like 'CAMPOS NOVOS PAULISTA'; 
update cidade set cod_tom = '6299' where uf = 26 and upper(trim(unaccent(nome))) like 'CANANEIA'; 
update cidade set cod_tom = '0794' where uf = 26 and upper(trim(unaccent(nome))) like 'CANAS'; 
update cidade set cod_tom = '6301' where uf = 26 and upper(trim(unaccent(nome))) like 'CANDIDO MOTA'; 
update cidade set cod_tom = '6303' where uf = 26 and upper(trim(unaccent(nome))) like 'CANDIDO RODRIGUES'; 
update cidade set cod_tom = '2947' where uf = 26 and upper(trim(unaccent(nome))) like 'CANITAR'; 
update cidade set cod_tom = '6305' where uf = 26 and upper(trim(unaccent(nome))) like 'CAPAO BONITO'; 
update cidade set cod_tom = '6307' where uf = 26 and upper(trim(unaccent(nome))) like 'CAPELA DO ALTO'; 
update cidade set cod_tom = '6309' where uf = 26 and upper(trim(unaccent(nome))) like 'CAPIVARI'; 
update cidade set cod_tom = '6311' where uf = 26 and upper(trim(unaccent(nome))) like 'CARAGUATATUBA'; 
update cidade set cod_tom = '6313' where uf = 26 and upper(trim(unaccent(nome))) like 'CARAPICUIBA'; 
update cidade set cod_tom = '6315' where uf = 26 and upper(trim(unaccent(nome))) like 'CARDOSO'; 
update cidade set cod_tom = '6317' where uf = 26 and upper(trim(unaccent(nome))) like 'CASA BRANCA'; 
update cidade set cod_tom = '6319' where uf = 26 and upper(trim(unaccent(nome))) like 'CASSIA DOS COQUEIROS'; 
update cidade set cod_tom = '6321' where uf = 26 and upper(trim(unaccent(nome))) like 'CASTILHO'; 
update cidade set cod_tom = '6323' where uf = 26 and upper(trim(unaccent(nome))) like 'CATANDUVA'; 
update cidade set cod_tom = '6325' where uf = 26 and upper(trim(unaccent(nome))) like 'CATIGUA'; 
update cidade set cod_tom = '6327' where uf = 26 and upper(trim(unaccent(nome))) like 'CEDRAL'; 
update cidade set cod_tom = '6329' where uf = 26 and upper(trim(unaccent(nome))) like 'CERQUEIRA CESAR'; 
update cidade set cod_tom = '6331' where uf = 26 and upper(trim(unaccent(nome))) like 'CERQUILHO'; 
update cidade set cod_tom = '6333' where uf = 26 and upper(trim(unaccent(nome))) like 'CESARIO LANGE'; 
update cidade set cod_tom = '6335' where uf = 26 and upper(trim(unaccent(nome))) like 'CHARQUEADA'; 
update cidade set cod_tom = '6337' where uf = 26 and upper(trim(unaccent(nome))) like 'CHAVANTES'; 
update cidade set cod_tom = '6339' where uf = 26 and upper(trim(unaccent(nome))) like 'CLEMENTINA'; 
update cidade set cod_tom = '6341' where uf = 26 and upper(trim(unaccent(nome))) like 'COLINA'; 
update cidade set cod_tom = '6343' where uf = 26 and upper(trim(unaccent(nome))) like 'COLOMBIA'; 
update cidade set cod_tom = '6345' where uf = 26 and upper(trim(unaccent(nome))) like 'CONCHAL'; 
update cidade set cod_tom = '6347' where uf = 26 and upper(trim(unaccent(nome))) like 'CONCHAS'; 
update cidade set cod_tom = '6349' where uf = 26 and upper(trim(unaccent(nome))) like 'CORDEIROPOLIS'; 
update cidade set cod_tom = '6351' where uf = 26 and upper(trim(unaccent(nome))) like 'COROADOS'; 
update cidade set cod_tom = '6353' where uf = 26 and upper(trim(unaccent(nome))) like 'CORONEL MACEDO'; 
update cidade set cod_tom = '6355' where uf = 26 and upper(trim(unaccent(nome))) like 'CORUMBATAI'; 
update cidade set cod_tom = '6357' where uf = 26 and upper(trim(unaccent(nome))) like 'COSMOPOLIS'; 
update cidade set cod_tom = '6359' where uf = 26 and upper(trim(unaccent(nome))) like 'COSMORAMA'; 
update cidade set cod_tom = '6361' where uf = 26 and upper(trim(unaccent(nome))) like 'COTIA'; 
update cidade set cod_tom = '6363' where uf = 26 and upper(trim(unaccent(nome))) like 'CRAVINHOS'; 
update cidade set cod_tom = '6365' where uf = 26 and upper(trim(unaccent(nome))) like 'CRISTAIS PAULISTA'; 
update cidade set cod_tom = '6367' where uf = 26 and upper(trim(unaccent(nome))) like 'CRUZALIA'; 
update cidade set cod_tom = '6369' where uf = 26 and upper(trim(unaccent(nome))) like 'CRUZEIRO'; 
update cidade set cod_tom = '6371' where uf = 26 and upper(trim(unaccent(nome))) like 'CUBATAO'; 
update cidade set cod_tom = '6373' where uf = 26 and upper(trim(unaccent(nome))) like 'CUNHA'; 
update cidade set cod_tom = '6375' where uf = 26 and upper(trim(unaccent(nome))) like 'DESCALVADO'; 
update cidade set cod_tom = '6377' where uf = 26 and upper(trim(unaccent(nome))) like 'DIADEMA'; 
update cidade set cod_tom = '7249' where uf = 26 and upper(trim(unaccent(nome))) like 'DIRCE REIS'; 
update cidade set cod_tom = '6379' where uf = 26 and upper(trim(unaccent(nome))) like 'DIVINOLANDIA'; 
update cidade set cod_tom = '6381' where uf = 26 and upper(trim(unaccent(nome))) like 'DOBRADA'; 
update cidade set cod_tom = '6383' where uf = 26 and upper(trim(unaccent(nome))) like 'DOIS CORREGOS'; 
update cidade set cod_tom = '6385' where uf = 26 and upper(trim(unaccent(nome))) like 'DOLCINOPOLIS'; 
update cidade set cod_tom = '6387' where uf = 26 and upper(trim(unaccent(nome))) like 'DOURADO'; 
update cidade set cod_tom = '6389' where uf = 26 and upper(trim(unaccent(nome))) like 'DRACENA'; 
update cidade set cod_tom = '6391' where uf = 26 and upper(trim(unaccent(nome))) like 'DUARTINA'; 
update cidade set cod_tom = '6393' where uf = 26 and upper(trim(unaccent(nome))) like 'DUMONT'; 
update cidade set cod_tom = '6395' where uf = 26 and upper(trim(unaccent(nome))) like 'ECHAPORA'; 
update cidade set cod_tom = '6397' where uf = 26 and upper(trim(unaccent(nome))) like 'ELDORADO'; 
update cidade set cod_tom = '6399' where uf = 26 and upper(trim(unaccent(nome))) like 'ELIAS FAUSTO'; 
update cidade set cod_tom = '2975' where uf = 26 and upper(trim(unaccent(nome))) like 'ELISIARIO'; 
update cidade set cod_tom = '7251' where uf = 26 and upper(trim(unaccent(nome))) like 'EMBAUBA'; 
update cidade set cod_tom = '6401' where uf = 26 and upper(trim(unaccent(nome))) like 'EMBU'; 
update cidade set cod_tom = '6403' where uf = 26 and upper(trim(unaccent(nome))) like 'EMBU-GUACU'; 
update cidade set cod_tom = '2961' where uf = 26 and upper(trim(unaccent(nome))) like 'EMILIANOPOLIS'; 
update cidade set cod_tom = '2949' where uf = 26 and upper(trim(unaccent(nome))) like 'ENGENHEIRO COELHO'; 
update cidade set cod_tom = '6865' where uf = 26 and upper(trim(unaccent(nome))) like 'ESPIRITO SANTO DO PINHAL'; 
update cidade set cod_tom = '7253' where uf = 26 and upper(trim(unaccent(nome))) like 'ESPIRITO SANTO DO TURVO'; 
update cidade set cod_tom = '2959' where uf = 26 and upper(trim(unaccent(nome))) like 'ESTIVA GERBI'; 
update cidade set cod_tom = '6407' where uf = 26 and upper(trim(unaccent(nome))) like 'ESTRELA DO NORTE'; 
update cidade set cod_tom = '6405' where uf = 26 and upper(trim(unaccent(nome))) like 'ESTRELA D`OESTE'; 
update cidade set cod_tom = '7255' where uf = 26 and upper(trim(unaccent(nome))) like 'EUCLIDES DA CUNHA PAULISTA'; 
update cidade set cod_tom = '6409' where uf = 26 and upper(trim(unaccent(nome))) like 'FARTURA'; 
update cidade set cod_tom = '6413' where uf = 26 and upper(trim(unaccent(nome))) like 'FERNANDO PRESTES'; 
update cidade set cod_tom = '6411' where uf = 26 and upper(trim(unaccent(nome))) like 'FERNANDOPOLIS'; 
update cidade set cod_tom = '0796' where uf = 26 and upper(trim(unaccent(nome))) like 'FERNAO'; 
update cidade set cod_tom = '6415' where uf = 26 and upper(trim(unaccent(nome))) like 'FERRAZ DE VASCONCELOS'; 
update cidade set cod_tom = '6417' where uf = 26 and upper(trim(unaccent(nome))) like 'FLORA RICA'; 
update cidade set cod_tom = '6419' where uf = 26 and upper(trim(unaccent(nome))) like 'FLOREAL'; 
update cidade set cod_tom = '6421' where uf = 26 and upper(trim(unaccent(nome))) like 'FLORIDA PAULISTA'; 
update cidade set cod_tom = '6423' where uf = 26 and upper(trim(unaccent(nome))) like 'FLORINEA'; 
update cidade set cod_tom = '6425' where uf = 26 and upper(trim(unaccent(nome))) like 'FRANCA'; 
update cidade set cod_tom = '6427' where uf = 26 and upper(trim(unaccent(nome))) like 'FRANCISCO MORATO'; 
update cidade set cod_tom = '6429' where uf = 26 and upper(trim(unaccent(nome))) like 'FRANCO DA ROCHA'; 
update cidade set cod_tom = '6431' where uf = 26 and upper(trim(unaccent(nome))) like 'GABRIEL MONTEIRO'; 
update cidade set cod_tom = '6433' where uf = 26 and upper(trim(unaccent(nome))) like 'GALIA'; 
update cidade set cod_tom = '6435' where uf = 26 and upper(trim(unaccent(nome))) like 'GARCA'; 
update cidade set cod_tom = '6437' where uf = 26 and upper(trim(unaccent(nome))) like 'GASTAO VIDIGAL'; 
update cidade set cod_tom = '0798' where uf = 26 and upper(trim(unaccent(nome))) like 'GAVIAO PEIXOTO'; 
update cidade set cod_tom = '6439' where uf = 26 and upper(trim(unaccent(nome))) like 'GENERAL SALGADO'; 
update cidade set cod_tom = '6441' where uf = 26 and upper(trim(unaccent(nome))) like 'GETULINA'; 
update cidade set cod_tom = '6443' where uf = 26 and upper(trim(unaccent(nome))) like 'GLICERIO'; 
update cidade set cod_tom = '6445' where uf = 26 and upper(trim(unaccent(nome))) like 'GUAICARA'; 
update cidade set cod_tom = '6447' where uf = 26 and upper(trim(unaccent(nome))) like 'GUAIMBE'; 
update cidade set cod_tom = '6449' where uf = 26 and upper(trim(unaccent(nome))) like 'GUAIRA'; 
update cidade set cod_tom = '6451' where uf = 26 and upper(trim(unaccent(nome))) like 'GUAPIACU'; 
update cidade set cod_tom = '6453' where uf = 26 and upper(trim(unaccent(nome))) like 'GUAPIARA'; 
update cidade set cod_tom = '6455' where uf = 26 and upper(trim(unaccent(nome))) like 'GUARA'; 
update cidade set cod_tom = '6457' where uf = 26 and upper(trim(unaccent(nome))) like 'GUARACAI'; 
update cidade set cod_tom = '6459' where uf = 26 and upper(trim(unaccent(nome))) like 'GUARACI'; 
update cidade set cod_tom = '6461' where uf = 26 and upper(trim(unaccent(nome))) like 'GUARANI D`OESTE'; 
update cidade set cod_tom = '6463' where uf = 26 and upper(trim(unaccent(nome))) like 'GUARANTA'; 
update cidade set cod_tom = '6465' where uf = 26 and upper(trim(unaccent(nome))) like 'GUARARAPES'; 
update cidade set cod_tom = '6467' where uf = 26 and upper(trim(unaccent(nome))) like 'GUARAREMA'; 
update cidade set cod_tom = '6469' where uf = 26 and upper(trim(unaccent(nome))) like 'GUARATINGUETA'; 
update cidade set cod_tom = '6471' where uf = 26 and upper(trim(unaccent(nome))) like 'GUAREI'; 
update cidade set cod_tom = '6473' where uf = 26 and upper(trim(unaccent(nome))) like 'GUARIBA'; 
update cidade set cod_tom = '6475' where uf = 26 and upper(trim(unaccent(nome))) like 'GUARUJA'; 
update cidade set cod_tom = '6477' where uf = 26 and upper(trim(unaccent(nome))) like 'GUARULHOS'; 
update cidade set cod_tom = '7257' where uf = 26 and upper(trim(unaccent(nome))) like 'GUATAPARA'; 
update cidade set cod_tom = '6479' where uf = 26 and upper(trim(unaccent(nome))) like 'GUZOLANDIA'; 
update cidade set cod_tom = '6481' where uf = 26 and upper(trim(unaccent(nome))) like 'HERCULANDIA'; 
update cidade set cod_tom = '2953' where uf = 26 and upper(trim(unaccent(nome))) like 'HOLAMBRA'; 
update cidade set cod_tom = '2951' where uf = 26 and upper(trim(unaccent(nome))) like 'HORTOLANDIA'; 
update cidade set cod_tom = '6483' where uf = 26 and upper(trim(unaccent(nome))) like 'IACANGA'; 
update cidade set cod_tom = '6485' where uf = 26 and upper(trim(unaccent(nome))) like 'IACRI'; 
update cidade set cod_tom = '7259' where uf = 26 and upper(trim(unaccent(nome))) like 'IARAS'; 
update cidade set cod_tom = '6487' where uf = 26 and upper(trim(unaccent(nome))) like 'IBATE'; 
update cidade set cod_tom = '6489' where uf = 26 and upper(trim(unaccent(nome))) like 'IBIRA'; 
update cidade set cod_tom = '6491' where uf = 26 and upper(trim(unaccent(nome))) like 'IBIRAREMA'; 
update cidade set cod_tom = '6493' where uf = 26 and upper(trim(unaccent(nome))) like 'IBITINGA'; 
update cidade set cod_tom = '7261' where uf = 26 and upper(trim(unaccent(nome))) like 'IBITIUVA'; 
update cidade set cod_tom = '6495' where uf = 26 and upper(trim(unaccent(nome))) like 'IBIUNA'; 
update cidade set cod_tom = '6497' where uf = 26 and upper(trim(unaccent(nome))) like 'ICEM'; 
update cidade set cod_tom = '6499' where uf = 26 and upper(trim(unaccent(nome))) like 'IEPE'; 
update cidade set cod_tom = '6501' where uf = 26 and upper(trim(unaccent(nome))) like 'IGARACU DO TIETE'; 
update cidade set cod_tom = '6503' where uf = 26 and upper(trim(unaccent(nome))) like 'IGARAPAVA'; 
update cidade set cod_tom = '6505' where uf = 26 and upper(trim(unaccent(nome))) like 'IGARATA'; 
update cidade set cod_tom = '6507' where uf = 26 and upper(trim(unaccent(nome))) like 'IGUAPE'; 
update cidade set cod_tom = '2969' where uf = 26 and upper(trim(unaccent(nome))) like 'ILHA COMPRIDA'; 
update cidade set cod_tom = '2943' where uf = 26 and upper(trim(unaccent(nome))) like 'ILHA SOLTEIRA'; 
update cidade set cod_tom = '6509' where uf = 26 and upper(trim(unaccent(nome))) like 'ILHABELA'; 
update cidade set cod_tom = '6511' where uf = 26 and upper(trim(unaccent(nome))) like 'INDAIATUBA'; 
update cidade set cod_tom = '6513' where uf = 26 and upper(trim(unaccent(nome))) like 'INDIANA'; 
update cidade set cod_tom = '6515' where uf = 26 and upper(trim(unaccent(nome))) like 'INDIAPORA'; 
update cidade set cod_tom = '6517' where uf = 26 and upper(trim(unaccent(nome))) like 'INUBIA PAULISTA'; 
update cidade set cod_tom = '6519' where uf = 26 and upper(trim(unaccent(nome))) like 'IPAUSSU'; 
update cidade set cod_tom = '6521' where uf = 26 and upper(trim(unaccent(nome))) like 'IPERO'; 
update cidade set cod_tom = '6523' where uf = 26 and upper(trim(unaccent(nome))) like 'IPEUNA'; 
update cidade set cod_tom = '0800' where uf = 26 and upper(trim(unaccent(nome))) like 'IPIGUA'; 
update cidade set cod_tom = '6525' where uf = 26 and upper(trim(unaccent(nome))) like 'IPORANGA'; 
update cidade set cod_tom = '6527' where uf = 26 and upper(trim(unaccent(nome))) like 'IPUA'; 
update cidade set cod_tom = '6529' where uf = 26 and upper(trim(unaccent(nome))) like 'IRACEMAPOLIS'; 
update cidade set cod_tom = '6531' where uf = 26 and upper(trim(unaccent(nome))) like 'IRAPUA'; 
update cidade set cod_tom = '6533' where uf = 26 and upper(trim(unaccent(nome))) like 'IRAPURU'; 
update cidade set cod_tom = '6535' where uf = 26 and upper(trim(unaccent(nome))) like 'ITABERA'; 
update cidade set cod_tom = '6537' where uf = 26 and upper(trim(unaccent(nome))) like 'ITAI'; 
update cidade set cod_tom = '6539' where uf = 26 and upper(trim(unaccent(nome))) like 'ITAJOBI'; 
update cidade set cod_tom = '6541' where uf = 26 and upper(trim(unaccent(nome))) like 'ITAJU'; 
update cidade set cod_tom = '6543' where uf = 26 and upper(trim(unaccent(nome))) like 'ITANHAEM'; 
update cidade set cod_tom = '3053' where uf = 26 and upper(trim(unaccent(nome))) like 'ITAOCA'; 
update cidade set cod_tom = '6545' where uf = 26 and upper(trim(unaccent(nome))) like 'ITAPECERICA DA SERRA'; 
update cidade set cod_tom = '6547' where uf = 26 and upper(trim(unaccent(nome))) like 'ITAPETININGA'; 
update cidade set cod_tom = '6549' where uf = 26 and upper(trim(unaccent(nome))) like 'ITAPEVA'; 
update cidade set cod_tom = '6551' where uf = 26 and upper(trim(unaccent(nome))) like 'ITAPEVI'; 
update cidade set cod_tom = '6553' where uf = 26 and upper(trim(unaccent(nome))) like 'ITAPIRA'; 
update cidade set cod_tom = '3055' where uf = 26 and upper(trim(unaccent(nome))) like 'ITAPIRAPUA PAULISTA'; 
update cidade set cod_tom = '6555' where uf = 26 and upper(trim(unaccent(nome))) like 'ITAPOLIS'; 
update cidade set cod_tom = '6557' where uf = 26 and upper(trim(unaccent(nome))) like 'ITAPORANGA'; 
update cidade set cod_tom = '6559' where uf = 26 and upper(trim(unaccent(nome))) like 'ITAPUI'; 
update cidade set cod_tom = '6561' where uf = 26 and upper(trim(unaccent(nome))) like 'ITAPURA'; 
update cidade set cod_tom = '6563' where uf = 26 and upper(trim(unaccent(nome))) like 'ITAQUAQUECETUBA'; 
update cidade set cod_tom = '6565' where uf = 26 and upper(trim(unaccent(nome))) like 'ITARARE'; 
update cidade set cod_tom = '6567' where uf = 26 and upper(trim(unaccent(nome))) like 'ITARIRI'; 
update cidade set cod_tom = '6569' where uf = 26 and upper(trim(unaccent(nome))) like 'ITATIBA'; 
update cidade set cod_tom = '6571' where uf = 26 and upper(trim(unaccent(nome))) like 'ITATINGA'; 
update cidade set cod_tom = '6573' where uf = 26 and upper(trim(unaccent(nome))) like 'ITIRAPINA'; 
update cidade set cod_tom = '6575' where uf = 26 and upper(trim(unaccent(nome))) like 'ITIRAPUA'; 
update cidade set cod_tom = '6577' where uf = 26 and upper(trim(unaccent(nome))) like 'ITOBI'; 
update cidade set cod_tom = '6579' where uf = 26 and upper(trim(unaccent(nome))) like 'ITU'; 
update cidade set cod_tom = '6581' where uf = 26 and upper(trim(unaccent(nome))) like 'ITUPEVA'; 
update cidade set cod_tom = '6583' where uf = 26 and upper(trim(unaccent(nome))) like 'ITUVERAVA'; 
update cidade set cod_tom = '6585' where uf = 26 and upper(trim(unaccent(nome))) like 'JABORANDI'; 
update cidade set cod_tom = '6587' where uf = 26 and upper(trim(unaccent(nome))) like 'JABOTICABAL'; 
update cidade set cod_tom = '6589' where uf = 26 and upper(trim(unaccent(nome))) like 'JACAREI'; 
update cidade set cod_tom = '6591' where uf = 26 and upper(trim(unaccent(nome))) like 'JACI'; 
update cidade set cod_tom = '6593' where uf = 26 and upper(trim(unaccent(nome))) like 'JACUPIRANGA'; 
update cidade set cod_tom = '6595' where uf = 26 and upper(trim(unaccent(nome))) like 'JAGUARIUNA'; 
update cidade set cod_tom = '6597' where uf = 26 and upper(trim(unaccent(nome))) like 'JALES'; 
update cidade set cod_tom = '6599' where uf = 26 and upper(trim(unaccent(nome))) like 'JAMBEIRO'; 
update cidade set cod_tom = '6601' where uf = 26 and upper(trim(unaccent(nome))) like 'JANDIRA'; 
update cidade set cod_tom = '6603' where uf = 26 and upper(trim(unaccent(nome))) like 'JARDINOPOLIS'; 
update cidade set cod_tom = '6605' where uf = 26 and upper(trim(unaccent(nome))) like 'JARINU'; 
update cidade set cod_tom = '6607' where uf = 26 and upper(trim(unaccent(nome))) like 'JAU'; 
update cidade set cod_tom = '6609' where uf = 26 and upper(trim(unaccent(nome))) like 'JERIQUARA'; 
update cidade set cod_tom = '6611' where uf = 26 and upper(trim(unaccent(nome))) like 'JOANOPOLIS'; 
update cidade set cod_tom = '6613' where uf = 26 and upper(trim(unaccent(nome))) like 'JOAO RAMALHO'; 
update cidade set cod_tom = '6615' where uf = 26 and upper(trim(unaccent(nome))) like 'JOSE BONIFACIO'; 
update cidade set cod_tom = '6617' where uf = 26 and upper(trim(unaccent(nome))) like 'JULIO MESQUITA'; 
update cidade set cod_tom = '0802' where uf = 26 and upper(trim(unaccent(nome))) like 'JUMIRIM'; 
update cidade set cod_tom = '6619' where uf = 26 and upper(trim(unaccent(nome))) like 'JUNDIAI'; 
update cidade set cod_tom = '6621' where uf = 26 and upper(trim(unaccent(nome))) like 'JUNQUEIROPOLIS'; 
update cidade set cod_tom = '6623' where uf = 26 and upper(trim(unaccent(nome))) like 'JUQUIA'; 
update cidade set cod_tom = '6625' where uf = 26 and upper(trim(unaccent(nome))) like 'JUQUITIBA'; 
update cidade set cod_tom = '6627' where uf = 26 and upper(trim(unaccent(nome))) like 'LAGOINHA'; 
update cidade set cod_tom = '6629' where uf = 26 and upper(trim(unaccent(nome))) like 'LARANJAL PAULISTA'; 
update cidade set cod_tom = '6631' where uf = 26 and upper(trim(unaccent(nome))) like 'LAVINIA'; 
update cidade set cod_tom = '6633' where uf = 26 and upper(trim(unaccent(nome))) like 'LAVRINHAS'; 
update cidade set cod_tom = '6635' where uf = 26 and upper(trim(unaccent(nome))) like 'LEME'; 
update cidade set cod_tom = '6637' where uf = 26 and upper(trim(unaccent(nome))) like 'LENCOIS PAULISTA'; 
update cidade set cod_tom = '6639' where uf = 26 and upper(trim(unaccent(nome))) like 'LIMEIRA'; 
update cidade set cod_tom = '6641' where uf = 26 and upper(trim(unaccent(nome))) like 'LINDOIA'; 
update cidade set cod_tom = '6643' where uf = 26 and upper(trim(unaccent(nome))) like 'LINS'; 
update cidade set cod_tom = '6645' where uf = 26 and upper(trim(unaccent(nome))) like 'LORENA'; 
update cidade set cod_tom = '2937' where uf = 26 and upper(trim(unaccent(nome))) like 'LOURDES'; 
update cidade set cod_tom = '6647' where uf = 26 and upper(trim(unaccent(nome))) like 'LOUVEIRA'; 
update cidade set cod_tom = '6649' where uf = 26 and upper(trim(unaccent(nome))) like 'LUCELIA'; 
update cidade set cod_tom = '6651' where uf = 26 and upper(trim(unaccent(nome))) like 'LUCIANOPOLIS'; 
update cidade set cod_tom = '6653' where uf = 26 and upper(trim(unaccent(nome))) like 'LUIS ANTONIO'; 
update cidade set cod_tom = '6655' where uf = 26 and upper(trim(unaccent(nome))) like 'LUIZIANIA'; 
update cidade set cod_tom = '6657' where uf = 26 and upper(trim(unaccent(nome))) like 'LUPERCIO'; 
update cidade set cod_tom = '6659' where uf = 26 and upper(trim(unaccent(nome))) like 'LUTECIA'; 
update cidade set cod_tom = '6661' where uf = 26 and upper(trim(unaccent(nome))) like 'MACATUBA'; 
update cidade set cod_tom = '6663' where uf = 26 and upper(trim(unaccent(nome))) like 'MACAUBAL'; 
update cidade set cod_tom = '6665' where uf = 26 and upper(trim(unaccent(nome))) like 'MACEDONIA'; 
update cidade set cod_tom = '6667' where uf = 26 and upper(trim(unaccent(nome))) like 'MAGDA'; 
update cidade set cod_tom = '6669' where uf = 26 and upper(trim(unaccent(nome))) like 'MAIRINQUE'; 
update cidade set cod_tom = '6671' where uf = 26 and upper(trim(unaccent(nome))) like 'MAIRIPORA'; 
update cidade set cod_tom = '6673' where uf = 26 and upper(trim(unaccent(nome))) like 'MANDURI'; 
update cidade set cod_tom = '6675' where uf = 26 and upper(trim(unaccent(nome))) like 'MARABA PAULISTA'; 
update cidade set cod_tom = '6677' where uf = 26 and upper(trim(unaccent(nome))) like 'MARACAI'; 
update cidade set cod_tom = '2977' where uf = 26 and upper(trim(unaccent(nome))) like 'MARAPOAMA'; 
update cidade set cod_tom = '6679' where uf = 26 and upper(trim(unaccent(nome))) like 'MARIAPOLIS'; 
update cidade set cod_tom = '6681' where uf = 26 and upper(trim(unaccent(nome))) like 'MARILIA'; 
update cidade set cod_tom = '6683' where uf = 26 and upper(trim(unaccent(nome))) like 'MARINOPOLIS'; 
update cidade set cod_tom = '6685' where uf = 26 and upper(trim(unaccent(nome))) like 'MARTINOPOLIS'; 
update cidade set cod_tom = '6687' where uf = 26 and upper(trim(unaccent(nome))) like 'MATAO'; 
update cidade set cod_tom = '6689' where uf = 26 and upper(trim(unaccent(nome))) like 'MAUA'; 
update cidade set cod_tom = '6691' where uf = 26 and upper(trim(unaccent(nome))) like 'MENDONCA'; 
update cidade set cod_tom = '6693' where uf = 26 and upper(trim(unaccent(nome))) like 'MERIDIANO'; 
update cidade set cod_tom = '2983' where uf = 26 and upper(trim(unaccent(nome))) like 'MESOPOLIS'; 
update cidade set cod_tom = '6695' where uf = 26 and upper(trim(unaccent(nome))) like 'MIGUELOPOLIS'; 
update cidade set cod_tom = '6697' where uf = 26 and upper(trim(unaccent(nome))) like 'MINEIROS DO TIETE'; 
update cidade set cod_tom = '6701' where uf = 26 and upper(trim(unaccent(nome))) like 'MIRA ESTRELA'; 
update cidade set cod_tom = '6699' where uf = 26 and upper(trim(unaccent(nome))) like 'MIRACATU'; 
update cidade set cod_tom = '6703' where uf = 26 and upper(trim(unaccent(nome))) like 'MIRANDOPOLIS'; 
update cidade set cod_tom = '6705' where uf = 26 and upper(trim(unaccent(nome))) like 'MIRANTE DO PARANAPANEMA'; 
update cidade set cod_tom = '6707' where uf = 26 and upper(trim(unaccent(nome))) like 'MIRASSOL'; 
update cidade set cod_tom = '6709' where uf = 26 and upper(trim(unaccent(nome))) like 'MIRASSOLANDIA'; 
update cidade set cod_tom = '6711' where uf = 26 and upper(trim(unaccent(nome))) like 'MOCOCA'; 
update cidade set cod_tom = '6713' where uf = 26 and upper(trim(unaccent(nome))) like 'MOGI DAS CRUZES'; 
update cidade set cod_tom = '6715' where uf = 26 and upper(trim(unaccent(nome))) like 'MOGI-GUACU'; 
update cidade set cod_tom = '6717' where uf = 26 and upper(trim(unaccent(nome))) like 'MOGI-MIRIM'; 
update cidade set cod_tom = '6719' where uf = 26 and upper(trim(unaccent(nome))) like 'MOMBUCA'; 
update cidade set cod_tom = '6721' where uf = 26 and upper(trim(unaccent(nome))) like 'MONCOES'; 
update cidade set cod_tom = '6723' where uf = 26 and upper(trim(unaccent(nome))) like 'MONGAGUA'; 
update cidade set cod_tom = '6725' where uf = 26 and upper(trim(unaccent(nome))) like 'MONTE ALEGRE DO SUL'; 
update cidade set cod_tom = '6727' where uf = 26 and upper(trim(unaccent(nome))) like 'MONTE ALTO'; 
update cidade set cod_tom = '6729' where uf = 26 and upper(trim(unaccent(nome))) like 'MONTE APRAZIVEL'; 
update cidade set cod_tom = '6731' where uf = 26 and upper(trim(unaccent(nome))) like 'MONTE AZUL PAULISTA'; 
update cidade set cod_tom = '6733' where uf = 26 and upper(trim(unaccent(nome))) like 'MONTE CASTELO'; 
update cidade set cod_tom = '6737' where uf = 26 and upper(trim(unaccent(nome))) like 'MONTE MOR'; 
update cidade set cod_tom = '6735' where uf = 26 and upper(trim(unaccent(nome))) like 'MONTEIRO LOBATO'; 
update cidade set cod_tom = '6739' where uf = 26 and upper(trim(unaccent(nome))) like 'MORRO AGUDO'; 
update cidade set cod_tom = '6741' where uf = 26 and upper(trim(unaccent(nome))) like 'MORUNGABA'; 
update cidade set cod_tom = '7263' where uf = 26 and upper(trim(unaccent(nome))) like 'MOTUCA'; 
update cidade set cod_tom = '6743' where uf = 26 and upper(trim(unaccent(nome))) like 'MURUTINGA DO SUL'; 
update cidade set cod_tom = '0804' where uf = 26 and upper(trim(unaccent(nome))) like 'NANTES'; 
update cidade set cod_tom = '6745' where uf = 26 and upper(trim(unaccent(nome))) like 'NARANDIBA'; 
update cidade set cod_tom = '6747' where uf = 26 and upper(trim(unaccent(nome))) like 'NATIVIDADE DA SERRA'; 
update cidade set cod_tom = '6749' where uf = 26 and upper(trim(unaccent(nome))) like 'NAZARE PAULISTA'; 
update cidade set cod_tom = '6751' where uf = 26 and upper(trim(unaccent(nome))) like 'NEVES PAULISTA'; 
update cidade set cod_tom = '6753' where uf = 26 and upper(trim(unaccent(nome))) like 'NHANDEARA'; 
update cidade set cod_tom = '6755' where uf = 26 and upper(trim(unaccent(nome))) like 'NIPOA'; 
update cidade set cod_tom = '6757' where uf = 26 and upper(trim(unaccent(nome))) like 'NOVA ALIANCA'; 
update cidade set cod_tom = '3061' where uf = 26 and upper(trim(unaccent(nome))) like 'NOVA CAMPINA'; 
update cidade set cod_tom = '2985' where uf = 26 and upper(trim(unaccent(nome))) like 'NOVA CANAA PAULISTA'; 
update cidade set cod_tom = '0806' where uf = 26 and upper(trim(unaccent(nome))) like 'NOVA CASTILHO'; 
update cidade set cod_tom = '6759' where uf = 26 and upper(trim(unaccent(nome))) like 'NOVA EUROPA'; 
update cidade set cod_tom = '6761' where uf = 26 and upper(trim(unaccent(nome))) like 'NOVA GRANADA'; 
update cidade set cod_tom = '6763' where uf = 26 and upper(trim(unaccent(nome))) like 'NOVA GUATAPORANGA'; 
update cidade set cod_tom = '6765' where uf = 26 and upper(trim(unaccent(nome))) like 'NOVA INDEPENDENCIA'; 
update cidade set cod_tom = '6767' where uf = 26 and upper(trim(unaccent(nome))) like 'NOVA LUZITANIA'; 
update cidade set cod_tom = '6769' where uf = 26 and upper(trim(unaccent(nome))) like 'NOVA ODESSA'; 
update cidade set cod_tom = '2979' where uf = 26 and upper(trim(unaccent(nome))) like 'NOVAIS'; 
update cidade set cod_tom = '6771' where uf = 26 and upper(trim(unaccent(nome))) like 'NOVO HORIZONTE'; 
update cidade set cod_tom = '6773' where uf = 26 and upper(trim(unaccent(nome))) like 'NUPORANGA'; 
update cidade set cod_tom = '6775' where uf = 26 and upper(trim(unaccent(nome))) like 'OCAUCU'; 
update cidade set cod_tom = '6777' where uf = 26 and upper(trim(unaccent(nome))) like 'OLEO'; 
update cidade set cod_tom = '6779' where uf = 26 and upper(trim(unaccent(nome))) like 'OLIMPIA'; 
update cidade set cod_tom = '6781' where uf = 26 and upper(trim(unaccent(nome))) like 'ONDA VERDE'; 
update cidade set cod_tom = '6783' where uf = 26 and upper(trim(unaccent(nome))) like 'ORIENTE'; 
update cidade set cod_tom = '6785' where uf = 26 and upper(trim(unaccent(nome))) like 'ORINDIUVA'; 
update cidade set cod_tom = '6787' where uf = 26 and upper(trim(unaccent(nome))) like 'ORLANDIA'; 
update cidade set cod_tom = '6789' where uf = 26 and upper(trim(unaccent(nome))) like 'OSASCO'; 
update cidade set cod_tom = '6791' where uf = 26 and upper(trim(unaccent(nome))) like 'OSCAR BRESSANE'; 
update cidade set cod_tom = '6793' where uf = 26 and upper(trim(unaccent(nome))) like 'OSVALDO CRUZ'; 
update cidade set cod_tom = '6795' where uf = 26 and upper(trim(unaccent(nome))) like 'OURINHOS'; 
update cidade set cod_tom = '6797' where uf = 26 and upper(trim(unaccent(nome))) like 'OURO VERDE'; 
update cidade set cod_tom = '0808' where uf = 26 and upper(trim(unaccent(nome))) like 'OUROESTE'; 
update cidade set cod_tom = '6799' where uf = 26 and upper(trim(unaccent(nome))) like 'PACAEMBU'; 
update cidade set cod_tom = '6801' where uf = 26 and upper(trim(unaccent(nome))) like 'PALESTINA'; 
update cidade set cod_tom = '6803' where uf = 26 and upper(trim(unaccent(nome))) like 'PALMARES PAULISTA'; 
update cidade set cod_tom = '6805' where uf = 26 and upper(trim(unaccent(nome))) like 'PALMEIRA D`OESTE'; 
update cidade set cod_tom = '6807' where uf = 26 and upper(trim(unaccent(nome))) like 'PALMITAL'; 
update cidade set cod_tom = '6809' where uf = 26 and upper(trim(unaccent(nome))) like 'PANORAMA'; 
update cidade set cod_tom = '6811' where uf = 26 and upper(trim(unaccent(nome))) like 'PARAGUACU PAULISTA'; 
update cidade set cod_tom = '6813' where uf = 26 and upper(trim(unaccent(nome))) like 'PARAIBUNA'; 
update cidade set cod_tom = '6815' where uf = 26 and upper(trim(unaccent(nome))) like 'PARAISO'; 
update cidade set cod_tom = '6817' where uf = 26 and upper(trim(unaccent(nome))) like 'PARANAPANEMA'; 
update cidade set cod_tom = '6819' where uf = 26 and upper(trim(unaccent(nome))) like 'PARANAPUA'; 
update cidade set cod_tom = '6821' where uf = 26 and upper(trim(unaccent(nome))) like 'PARAPUA'; 
update cidade set cod_tom = '6823' where uf = 26 and upper(trim(unaccent(nome))) like 'PARDINHO'; 
update cidade set cod_tom = '6825' where uf = 26 and upper(trim(unaccent(nome))) like 'PARIQUERA-ACU'; 
update cidade set cod_tom = '2989' where uf = 26 and upper(trim(unaccent(nome))) like 'PARISI'; 
update cidade set cod_tom = '6827' where uf = 26 and upper(trim(unaccent(nome))) like 'PATROCINIO PAULISTA'; 
update cidade set cod_tom = '6829' where uf = 26 and upper(trim(unaccent(nome))) like 'PAULICEIA'; 
update cidade set cod_tom = '6831' where uf = 26 and upper(trim(unaccent(nome))) like 'PAULINIA'; 
update cidade set cod_tom = '0810' where uf = 26 and upper(trim(unaccent(nome))) like 'PAULISTANIA'; 
update cidade set cod_tom = '6833' where uf = 26 and upper(trim(unaccent(nome))) like 'PAULO DE FARIA'; 
update cidade set cod_tom = '6835' where uf = 26 and upper(trim(unaccent(nome))) like 'PEDERNEIRAS'; 
update cidade set cod_tom = '6837' where uf = 26 and upper(trim(unaccent(nome))) like 'PEDRA BELA'; 
update cidade set cod_tom = '6839' where uf = 26 and upper(trim(unaccent(nome))) like 'PEDRANOPOLIS'; 
update cidade set cod_tom = '6841' where uf = 26 and upper(trim(unaccent(nome))) like 'PEDREGULHO'; 
update cidade set cod_tom = '6843' where uf = 26 and upper(trim(unaccent(nome))) like 'PEDREIRA'; 
update cidade set cod_tom = '2963' where uf = 26 and upper(trim(unaccent(nome))) like 'PEDRINHAS PAULISTA'; 
update cidade set cod_tom = '6845' where uf = 26 and upper(trim(unaccent(nome))) like 'PEDRO DE TOLEDO'; 
update cidade set cod_tom = '6847' where uf = 26 and upper(trim(unaccent(nome))) like 'PENAPOLIS'; 
update cidade set cod_tom = '6849' where uf = 26 and upper(trim(unaccent(nome))) like 'PEREIRA BARRETO'; 
update cidade set cod_tom = '6851' where uf = 26 and upper(trim(unaccent(nome))) like 'PEREIRAS'; 
update cidade set cod_tom = '6853' where uf = 26 and upper(trim(unaccent(nome))) like 'PERUIBE'; 
update cidade set cod_tom = '6855' where uf = 26 and upper(trim(unaccent(nome))) like 'PIACATU'; 
update cidade set cod_tom = '6857' where uf = 26 and upper(trim(unaccent(nome))) like 'PIEDADE'; 
update cidade set cod_tom = '6859' where uf = 26 and upper(trim(unaccent(nome))) like 'PILAR DO SUL'; 
update cidade set cod_tom = '6861' where uf = 26 and upper(trim(unaccent(nome))) like 'PINDAMONHANGABA'; 
update cidade set cod_tom = '6863' where uf = 26 and upper(trim(unaccent(nome))) like 'PINDORAMA'; 
update cidade set cod_tom = '6867' where uf = 26 and upper(trim(unaccent(nome))) like 'PINHALZINHO'; 
update cidade set cod_tom = '6869' where uf = 26 and upper(trim(unaccent(nome))) like 'PIQUEROBI'; 
update cidade set cod_tom = '6871' where uf = 26 and upper(trim(unaccent(nome))) like 'PIQUETE'; 
update cidade set cod_tom = '6873' where uf = 26 and upper(trim(unaccent(nome))) like 'PIRACAIA'; 
update cidade set cod_tom = '6875' where uf = 26 and upper(trim(unaccent(nome))) like 'PIRACICABA'; 
update cidade set cod_tom = '6877' where uf = 26 and upper(trim(unaccent(nome))) like 'PIRAJU'; 
update cidade set cod_tom = '6879' where uf = 26 and upper(trim(unaccent(nome))) like 'PIRAJUI'; 
update cidade set cod_tom = '6881' where uf = 26 and upper(trim(unaccent(nome))) like 'PIRANGI'; 
update cidade set cod_tom = '6883' where uf = 26 and upper(trim(unaccent(nome))) like 'PIRAPORA DO BOM JESUS'; 
update cidade set cod_tom = '6885' where uf = 26 and upper(trim(unaccent(nome))) like 'PIRAPOZINHO'; 
update cidade set cod_tom = '6887' where uf = 26 and upper(trim(unaccent(nome))) like 'PIRASSUNUNGA'; 
update cidade set cod_tom = '6889' where uf = 26 and upper(trim(unaccent(nome))) like 'PIRATININGA'; 
update cidade set cod_tom = '6891' where uf = 26 and upper(trim(unaccent(nome))) like 'PITANGUEIRAS'; 
update cidade set cod_tom = '6893' where uf = 26 and upper(trim(unaccent(nome))) like 'PLANALTO'; 
update cidade set cod_tom = '6895' where uf = 26 and upper(trim(unaccent(nome))) like 'PLATINA'; 
update cidade set cod_tom = '6897' where uf = 26 and upper(trim(unaccent(nome))) like 'POA'; 
update cidade set cod_tom = '6899' where uf = 26 and upper(trim(unaccent(nome))) like 'POLONI'; 
update cidade set cod_tom = '6901' where uf = 26 and upper(trim(unaccent(nome))) like 'POMPEIA'; 
update cidade set cod_tom = '6903' where uf = 26 and upper(trim(unaccent(nome))) like 'PONGAI'; 
update cidade set cod_tom = '6905' where uf = 26 and upper(trim(unaccent(nome))) like 'PONTAL'; 
update cidade set cod_tom = '2987' where uf = 26 and upper(trim(unaccent(nome))) like 'PONTALINDA'; 
update cidade set cod_tom = '6907' where uf = 26 and upper(trim(unaccent(nome))) like 'PONTES GESTAL'; 
update cidade set cod_tom = '6909' where uf = 26 and upper(trim(unaccent(nome))) like 'POPULINA'; 
update cidade set cod_tom = '6911' where uf = 26 and upper(trim(unaccent(nome))) like 'PORANGABA'; 
update cidade set cod_tom = '6913' where uf = 26 and upper(trim(unaccent(nome))) like 'PORTO FELIZ'; 
update cidade set cod_tom = '6915' where uf = 26 and upper(trim(unaccent(nome))) like 'PORTO FERREIRA'; 
update cidade set cod_tom = '2993' where uf = 26 and upper(trim(unaccent(nome))) like 'POTIM'; 
update cidade set cod_tom = '6917' where uf = 26 and upper(trim(unaccent(nome))) like 'POTIRENDABA'; 
update cidade set cod_tom = '0812' where uf = 26 and upper(trim(unaccent(nome))) like 'PRACINHA'; 
update cidade set cod_tom = '6919' where uf = 26 and upper(trim(unaccent(nome))) like 'PRADOPOLIS'; 
update cidade set cod_tom = '6921' where uf = 26 and upper(trim(unaccent(nome))) like 'PRAIA GRANDE'; 
update cidade set cod_tom = '0814' where uf = 26 and upper(trim(unaccent(nome))) like 'PRATANIA'; 
update cidade set cod_tom = '6923' where uf = 26 and upper(trim(unaccent(nome))) like 'PRESIDENTE ALVES'; 
update cidade set cod_tom = '6925' where uf = 26 and upper(trim(unaccent(nome))) like 'PRESIDENTE BERNARDES'; 
update cidade set cod_tom = '6927' where uf = 26 and upper(trim(unaccent(nome))) like 'PRESIDENTE EPITACIO'; 
update cidade set cod_tom = '6929' where uf = 26 and upper(trim(unaccent(nome))) like 'PRESIDENTE PRUDENTE'; 
update cidade set cod_tom = '6931' where uf = 26 and upper(trim(unaccent(nome))) like 'PRESIDENTE VENCESLAU'; 
update cidade set cod_tom = '6933' where uf = 26 and upper(trim(unaccent(nome))) like 'PROMISSAO'; 
update cidade set cod_tom = '0816' where uf = 26 and upper(trim(unaccent(nome))) like 'QUADRA'; 
update cidade set cod_tom = '6935' where uf = 26 and upper(trim(unaccent(nome))) like 'QUATA'; 
update cidade set cod_tom = '6937' where uf = 26 and upper(trim(unaccent(nome))) like 'QUEIROZ'; 
update cidade set cod_tom = '6939' where uf = 26 and upper(trim(unaccent(nome))) like 'QUELUZ'; 
update cidade set cod_tom = '6941' where uf = 26 and upper(trim(unaccent(nome))) like 'QUINTANA'; 
update cidade set cod_tom = '6943' where uf = 26 and upper(trim(unaccent(nome))) like 'RAFARD'; 
update cidade set cod_tom = '6945' where uf = 26 and upper(trim(unaccent(nome))) like 'RANCHARIA'; 
update cidade set cod_tom = '6947' where uf = 26 and upper(trim(unaccent(nome))) like 'REDENCAO DA SERRA'; 
update cidade set cod_tom = '6949' where uf = 26 and upper(trim(unaccent(nome))) like 'REGENTE FEIJO'; 
update cidade set cod_tom = '6951' where uf = 26 and upper(trim(unaccent(nome))) like 'REGINOPOLIS'; 
update cidade set cod_tom = '6953' where uf = 26 and upper(trim(unaccent(nome))) like 'REGISTRO'; 
update cidade set cod_tom = '6955' where uf = 26 and upper(trim(unaccent(nome))) like 'RESTINGA'; 
update cidade set cod_tom = '6957' where uf = 26 and upper(trim(unaccent(nome))) like 'RIBEIRA'; 
update cidade set cod_tom = '6959' where uf = 26 and upper(trim(unaccent(nome))) like 'RIBEIRAO BONITO'; 
update cidade set cod_tom = '6961' where uf = 26 and upper(trim(unaccent(nome))) like 'RIBEIRAO BRANCO'; 
update cidade set cod_tom = '6963' where uf = 26 and upper(trim(unaccent(nome))) like 'RIBEIRAO CORRENTE'; 
update cidade set cod_tom = '6965' where uf = 26 and upper(trim(unaccent(nome))) like 'RIBEIRAO DO SUL'; 
update cidade set cod_tom = '0818' where uf = 26 and upper(trim(unaccent(nome))) like 'RIBEIRAO DOS INDIOS'; 
update cidade set cod_tom = '3057' where uf = 26 and upper(trim(unaccent(nome))) like 'RIBEIRAO GRANDE'; 
update cidade set cod_tom = '6967' where uf = 26 and upper(trim(unaccent(nome))) like 'RIBEIRAO PIRES'; 
update cidade set cod_tom = '6969' where uf = 26 and upper(trim(unaccent(nome))) like 'RIBEIRAO PRETO'; 
update cidade set cod_tom = '6973' where uf = 26 and upper(trim(unaccent(nome))) like 'RIFAINA'; 
update cidade set cod_tom = '6975' where uf = 26 and upper(trim(unaccent(nome))) like 'RINCAO'; 
update cidade set cod_tom = '6977' where uf = 26 and upper(trim(unaccent(nome))) like 'RINOPOLIS'; 
update cidade set cod_tom = '6979' where uf = 26 and upper(trim(unaccent(nome))) like 'RIO CLARO'; 
update cidade set cod_tom = '6981' where uf = 26 and upper(trim(unaccent(nome))) like 'RIO DAS PEDRAS'; 
update cidade set cod_tom = '6983' where uf = 26 and upper(trim(unaccent(nome))) like 'RIO GRANDE DA SERRA'; 
update cidade set cod_tom = '6985' where uf = 26 and upper(trim(unaccent(nome))) like 'RIOLANDIA'; 
update cidade set cod_tom = '6971' where uf = 26 and upper(trim(unaccent(nome))) like 'RIVERSUL'; 
update cidade set cod_tom = '7265' where uf = 26 and upper(trim(unaccent(nome))) like 'ROSANA'; 
update cidade set cod_tom = '6987' where uf = 26 and upper(trim(unaccent(nome))) like 'ROSEIRA'; 
update cidade set cod_tom = '6989' where uf = 26 and upper(trim(unaccent(nome))) like 'RUBIACEA'; 
update cidade set cod_tom = '6991' where uf = 26 and upper(trim(unaccent(nome))) like 'RUBINEIA'; 
update cidade set cod_tom = '6993' where uf = 26 and upper(trim(unaccent(nome))) like 'SABINO'; 
update cidade set cod_tom = '6995' where uf = 26 and upper(trim(unaccent(nome))) like 'SAGRES'; 
update cidade set cod_tom = '6997' where uf = 26 and upper(trim(unaccent(nome))) like 'SALES'; 
update cidade set cod_tom = '6999' where uf = 26 and upper(trim(unaccent(nome))) like 'SALES OLIVEIRA'; 
update cidade set cod_tom = '7001' where uf = 26 and upper(trim(unaccent(nome))) like 'SALESOPOLIS'; 
update cidade set cod_tom = '7003' where uf = 26 and upper(trim(unaccent(nome))) like 'SALMOURAO'; 
update cidade set cod_tom = '5445' where uf = 26 and upper(trim(unaccent(nome))) like 'SALTINHO'; 
update cidade set cod_tom = '7005' where uf = 26 and upper(trim(unaccent(nome))) like 'SALTO'; 
update cidade set cod_tom = '7007' where uf = 26 and upper(trim(unaccent(nome))) like 'SALTO DE PIRAPORA'; 
update cidade set cod_tom = '7009' where uf = 26 and upper(trim(unaccent(nome))) like 'SALTO GRANDE'; 
update cidade set cod_tom = '7011' where uf = 26 and upper(trim(unaccent(nome))) like 'SANDOVALINA'; 
update cidade set cod_tom = '7013' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA ADELIA'; 
update cidade set cod_tom = '7015' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA ALBERTINA'; 
update cidade set cod_tom = '7017' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA BARBARA D`OESTE'; 
update cidade set cod_tom = '7021' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA BRANCA'; 
update cidade set cod_tom = '7023' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA CLARA D`OESTE'; 
update cidade set cod_tom = '7025' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA CRUZ DA CONCEICAO'; 
update cidade set cod_tom = '0820' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA CRUZ DA ESPERANCA'; 
update cidade set cod_tom = '7027' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA CRUZ DAS PALMEIRAS'; 
update cidade set cod_tom = '7029' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA CRUZ DO RIO PARDO'; 
update cidade set cod_tom = '7031' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA ERNESTINA'; 
update cidade set cod_tom = '7033' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA FE DO SUL'; 
update cidade set cod_tom = '7035' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA GERTRUDES'; 
update cidade set cod_tom = '7037' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA ISABEL'; 
update cidade set cod_tom = '7039' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA LUCIA'; 
update cidade set cod_tom = '7041' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA MARIA DA SERRA'; 
update cidade set cod_tom = '7043' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA MERCEDES'; 
update cidade set cod_tom = '7051' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA RITA DO PASSA QUATRO'; 
update cidade set cod_tom = '7049' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA RITA D`OESTE'; 
update cidade set cod_tom = '7053' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA ROSA DE VITERBO'; 
update cidade set cod_tom = '0822' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTA SALETE'; 
update cidade set cod_tom = '7045' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTANA DA PONTE PENSA'; 
update cidade set cod_tom = '7047' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTANA DE PARNAIBA'; 
update cidade set cod_tom = '7055' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTO ANASTACIO'; 
update cidade set cod_tom = '7057' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTO ANDRE'; 
update cidade set cod_tom = '7059' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DA ALEGRIA'; 
update cidade set cod_tom = '7061' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DE POSSE'; 
update cidade set cod_tom = '2939' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO ARACANGUA'; 
update cidade set cod_tom = '7063' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO JARDIM'; 
update cidade set cod_tom = '7065' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO PINHAL'; 
update cidade set cod_tom = '7067' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTO EXPEDITO'; 
update cidade set cod_tom = '7069' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTOPOLIS DO AGUAPEI'; 
update cidade set cod_tom = '7071' where uf = 26 and upper(trim(unaccent(nome))) like 'SANTOS'; 
update cidade set cod_tom = '7073' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO BENTO DO SAPUCAI'; 
update cidade set cod_tom = '7075' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO BERNARDO DO CAMPO'; 
update cidade set cod_tom = '7077' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO CAETANO DO SUL'; 
update cidade set cod_tom = '7079' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO CARLOS'; 
update cidade set cod_tom = '7081' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO'; 
update cidade set cod_tom = '7083' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO JOAO DA BOA VISTA'; 
update cidade set cod_tom = '7085' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO JOAO DAS DUAS PONTES'; 
update cidade set cod_tom = '2941' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO JOAO DE IRACEMA'; 
update cidade set cod_tom = '7087' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO JOAO DO PAU D`ALHO'; 
update cidade set cod_tom = '7089' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO JOAQUIM DA BARRA'; 
update cidade set cod_tom = '7091' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO JOSE DA BELA VISTA'; 
update cidade set cod_tom = '7093' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO JOSE DO BARREIRO'; 
update cidade set cod_tom = '7095' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO JOSE DO RIO PARDO'; 
update cidade set cod_tom = '7097' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO JOSE DO RIO PRETO'; 
update cidade set cod_tom = '7099' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO JOSE DOS CAMPOS'; 
update cidade set cod_tom = '5447' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO LOURENCO DA SERRA'; 
update cidade set cod_tom = '7101' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO LUIS DO PARAITINGA'; 
update cidade set cod_tom = '7103' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO MANUEL'; 
update cidade set cod_tom = '7105' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO MIGUEL ARCANJO'; 
update cidade set cod_tom = '7107' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO PAULO'; 
update cidade set cod_tom = '7109' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO PEDRO'; 
update cidade set cod_tom = '7111' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO PEDRO DO TURVO'; 
update cidade set cod_tom = '7113' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO ROQUE'; 
update cidade set cod_tom = '7115' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO'; 
update cidade set cod_tom = '7117' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO DA GRAMA'; 
update cidade set cod_tom = '7119' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO SIMAO'; 
update cidade set cod_tom = '7121' where uf = 26 and upper(trim(unaccent(nome))) like 'SAO VICENTE'; 
update cidade set cod_tom = '7123' where uf = 26 and upper(trim(unaccent(nome))) like 'SARAPUI'; 
update cidade set cod_tom = '7125' where uf = 26 and upper(trim(unaccent(nome))) like 'SARUTAIA'; 
update cidade set cod_tom = '7127' where uf = 26 and upper(trim(unaccent(nome))) like 'SEBASTIANOPOLIS DO SUL'; 
update cidade set cod_tom = '7129' where uf = 26 and upper(trim(unaccent(nome))) like 'SERRA AZUL'; 
update cidade set cod_tom = '7133' where uf = 26 and upper(trim(unaccent(nome))) like 'SERRA NEGRA'; 
update cidade set cod_tom = '7131' where uf = 26 and upper(trim(unaccent(nome))) like 'SERRANA'; 
update cidade set cod_tom = '7135' where uf = 26 and upper(trim(unaccent(nome))) like 'SERTAOZINHO'; 
update cidade set cod_tom = '7137' where uf = 26 and upper(trim(unaccent(nome))) like 'SETE BARRAS'; 
update cidade set cod_tom = '7139' where uf = 26 and upper(trim(unaccent(nome))) like 'SEVERINIA'; 
update cidade set cod_tom = '7141' where uf = 26 and upper(trim(unaccent(nome))) like 'SILVEIRAS'; 
update cidade set cod_tom = '7143' where uf = 26 and upper(trim(unaccent(nome))) like 'SOCORRO'; 
update cidade set cod_tom = '7145' where uf = 26 and upper(trim(unaccent(nome))) like 'SOROCABA'; 
update cidade set cod_tom = '7147' where uf = 26 and upper(trim(unaccent(nome))) like 'SUD MENNUCCI'; 
update cidade set cod_tom = '7149' where uf = 26 and upper(trim(unaccent(nome))) like 'SUMARE'; 
update cidade set cod_tom = '2945' where uf = 26 and upper(trim(unaccent(nome))) like 'SUZANAPOLIS'; 
update cidade set cod_tom = '7151' where uf = 26 and upper(trim(unaccent(nome))) like 'SUZANO'; 
update cidade set cod_tom = '7153' where uf = 26 and upper(trim(unaccent(nome))) like 'TABAPUA'; 
update cidade set cod_tom = '7155' where uf = 26 and upper(trim(unaccent(nome))) like 'TABATINGA'; 
update cidade set cod_tom = '7157' where uf = 26 and upper(trim(unaccent(nome))) like 'TABOAO DA SERRA'; 
update cidade set cod_tom = '7159' where uf = 26 and upper(trim(unaccent(nome))) like 'TACIBA'; 
update cidade set cod_tom = '7161' where uf = 26 and upper(trim(unaccent(nome))) like 'TAGUAI'; 
update cidade set cod_tom = '7163' where uf = 26 and upper(trim(unaccent(nome))) like 'TAIACU'; 
update cidade set cod_tom = '7165' where uf = 26 and upper(trim(unaccent(nome))) like 'TAIUVA'; 
update cidade set cod_tom = '7167' where uf = 26 and upper(trim(unaccent(nome))) like 'TAMBAU'; 
update cidade set cod_tom = '7169' where uf = 26 and upper(trim(unaccent(nome))) like 'TANABI'; 
update cidade set cod_tom = '7171' where uf = 26 and upper(trim(unaccent(nome))) like 'TAPIRAI'; 
update cidade set cod_tom = '7173' where uf = 26 and upper(trim(unaccent(nome))) like 'TAPIRATIBA'; 
update cidade set cod_tom = '0824' where uf = 26 and upper(trim(unaccent(nome))) like 'TAQUARAL'; 
update cidade set cod_tom = '7175' where uf = 26 and upper(trim(unaccent(nome))) like 'TAQUARITINGA'; 
update cidade set cod_tom = '7177' where uf = 26 and upper(trim(unaccent(nome))) like 'TAQUARITUBA'; 
update cidade set cod_tom = '3063' where uf = 26 and upper(trim(unaccent(nome))) like 'TAQUARIVAI'; 
update cidade set cod_tom = '7179' where uf = 26 and upper(trim(unaccent(nome))) like 'TARABAI'; 
update cidade set cod_tom = '7267' where uf = 26 and upper(trim(unaccent(nome))) like 'TARUMA'; 
update cidade set cod_tom = '7181' where uf = 26 and upper(trim(unaccent(nome))) like 'TATUI'; 
update cidade set cod_tom = '7183' where uf = 26 and upper(trim(unaccent(nome))) like 'TAUBATE'; 
update cidade set cod_tom = '7185' where uf = 26 and upper(trim(unaccent(nome))) like 'TEJUPA'; 
update cidade set cod_tom = '7187' where uf = 26 and upper(trim(unaccent(nome))) like 'TEODORO SAMPAIO'; 
update cidade set cod_tom = '7189' where uf = 26 and upper(trim(unaccent(nome))) like 'TERRA ROXA'; 
update cidade set cod_tom = '7191' where uf = 26 and upper(trim(unaccent(nome))) like 'TIETE'; 
update cidade set cod_tom = '7193' where uf = 26 and upper(trim(unaccent(nome))) like 'TIMBURI'; 
update cidade set cod_tom = '3227' where uf = 26 and upper(trim(unaccent(nome))) like 'TORRE DE PEDRA'; 
update cidade set cod_tom = '7195' where uf = 26 and upper(trim(unaccent(nome))) like 'TORRINHA'; 
update cidade set cod_tom = '0826' where uf = 26 and upper(trim(unaccent(nome))) like 'TRABIJU'; 
update cidade set cod_tom = '7197' where uf = 26 and upper(trim(unaccent(nome))) like 'TREMEMBE'; 
update cidade set cod_tom = '7199' where uf = 26 and upper(trim(unaccent(nome))) like 'TRES FRONTEIRAS'; 
update cidade set cod_tom = '2955' where uf = 26 and upper(trim(unaccent(nome))) like 'TUIUTI'; 
update cidade set cod_tom = '7201' where uf = 26 and upper(trim(unaccent(nome))) like 'TUPA'; 
update cidade set cod_tom = '7203' where uf = 26 and upper(trim(unaccent(nome))) like 'TUPI PAULISTA'; 
update cidade set cod_tom = '7205' where uf = 26 and upper(trim(unaccent(nome))) like 'TURIUBA'; 
update cidade set cod_tom = '7207' where uf = 26 and upper(trim(unaccent(nome))) like 'TURMALINA'; 
update cidade set cod_tom = '2971' where uf = 26 and upper(trim(unaccent(nome))) like 'UBARANA'; 
update cidade set cod_tom = '7209' where uf = 26 and upper(trim(unaccent(nome))) like 'UBATUBA'; 
update cidade set cod_tom = '7211' where uf = 26 and upper(trim(unaccent(nome))) like 'UBIRAJARA'; 
update cidade set cod_tom = '7213' where uf = 26 and upper(trim(unaccent(nome))) like 'UCHOA'; 
update cidade set cod_tom = '7215' where uf = 26 and upper(trim(unaccent(nome))) like 'UNIAO PAULISTA'; 
update cidade set cod_tom = '7217' where uf = 26 and upper(trim(unaccent(nome))) like 'URANIA'; 
update cidade set cod_tom = '7219' where uf = 26 and upper(trim(unaccent(nome))) like 'URU'; 
update cidade set cod_tom = '7221' where uf = 26 and upper(trim(unaccent(nome))) like 'URUPES'; 
update cidade set cod_tom = '7223' where uf = 26 and upper(trim(unaccent(nome))) like 'VALENTIM GENTIL'; 
update cidade set cod_tom = '7225' where uf = 26 and upper(trim(unaccent(nome))) like 'VALINHOS'; 
update cidade set cod_tom = '7227' where uf = 26 and upper(trim(unaccent(nome))) like 'VALPARAISO'; 
update cidade set cod_tom = '2957' where uf = 26 and upper(trim(unaccent(nome))) like 'VARGEM'; 
update cidade set cod_tom = '7231' where uf = 26 and upper(trim(unaccent(nome))) like 'VARGEM GRANDE DO SUL'; 
update cidade set cod_tom = '7273' where uf = 26 and upper(trim(unaccent(nome))) like 'VARGEM GRANDE PAULISTA'; 
update cidade set cod_tom = '7233' where uf = 26 and upper(trim(unaccent(nome))) like 'VARZEA PAULISTA'; 
update cidade set cod_tom = '7235' where uf = 26 and upper(trim(unaccent(nome))) like 'VERA CRUZ'; 
update cidade set cod_tom = '7237' where uf = 26 and upper(trim(unaccent(nome))) like 'VINHEDO'; 
update cidade set cod_tom = '7239' where uf = 26 and upper(trim(unaccent(nome))) like 'VIRADOURO'; 
update cidade set cod_tom = '7241' where uf = 26 and upper(trim(unaccent(nome))) like 'VISTA ALEGRE DO ALTO'; 
update cidade set cod_tom = '0828' where uf = 26 and upper(trim(unaccent(nome))) like 'VITORIA BRASIL'; 
update cidade set cod_tom = '7243' where uf = 26 and upper(trim(unaccent(nome))) like 'VOTORANTIM'; 
update cidade set cod_tom = '7245' where uf = 26 and upper(trim(unaccent(nome))) like 'VOTUPORANGA'; 
update cidade set cod_tom = '2973' where uf = 26 and upper(trim(unaccent(nome))) like 'ZACARIAS';