update cidade set cod_tom = '3365' where uf =  5 and upper(trim(unaccent(nome))) like 'BARRO PRETO%';
update cidade set cod_tom = '3365' where uf =  5 and upper(trim(unaccent(nome))) like 'BARRO PRETO%';
update cidade set cod_tom = '3291' where uf =  5 and upper(trim(unaccent(nome))) like 'LAJEDO DO TABOCAL';
update cidade set cod_tom = '3005' where uf =  5 and upper(trim(unaccent(nome))) like 'MUQUEM DE%';
update cidade set cod_tom = '0867' where uf = 10 and upper(trim(unaccent(nome))) like 'PINDARE-MIRIM';
update cidade set cod_tom = '4049' where uf = 11 and upper(trim(unaccent(nome))) like 'AMPARO DO SERRA';
update cidade set cod_tom = '4457' where uf = 11 and upper(trim(unaccent(nome))) like 'DONA EUSEBIA';
update cidade set cod_tom = '4551' where uf = 11 and upper(trim(unaccent(nome))) like 'GOUVEIA';
update cidade set cod_tom = '4955' where uf = 11 and upper(trim(unaccent(nome))) like 'PASSA-VINTE';
update cidade set cod_tom = '0688' where uf = 11 and upper(trim(unaccent(nome))) like 'PINGO-D`AGUA';
update cidade set cod_tom = '5303' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO THOME DAS LETRAS';
update cidade set cod_tom = '0688' where uf = 11 and upper(trim(unaccent(nome))) like 'PINGO-D`AGUA';
update cidade set cod_tom = '0123' where uf = 13 and upper(trim(unaccent(nome))) like 'SANTA CARMEM';
update cidade set cod_tom = '0834' where uf = 18 and upper(trim(unaccent(nome))) like 'BELA VISTA DA CAROBA';
update cidade set cod_tom = '5495' where uf = 18 and upper(trim(unaccent(nome))) like 'PINHAL DE SAO BENTO';
update cidade set cod_tom = '7843' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTA CRUZ DE MONTE CASTELO';
update cidade set cod_tom = '0770' where uf = 19 and upper(trim(unaccent(nome))) like 'ARMACAO DOS BUZIOS';
update cidade set cod_tom = '1603' where uf = 20 and upper(trim(unaccent(nome))) like 'ACU';
--update cidade set cod_tom = '0' where uf = 20 and upper(trim(unaccent(nome))) like 'AUGUSTO SEVERO';
update cidade set cod_tom = '1653' where uf = 20 and upper(trim(unaccent(nome))) like 'CERRO CORA';
--update cidade set cod_tom = '0' where uf = 20 and upper(trim(unaccent(nome))) like 'JANUARIO CICCO';
update cidade set cod_tom = '1767' where uf = 20 and upper(trim(unaccent(nome))) like 'OLHO D`AGUA DO BORGES';
--update cidade set cod_tom = '0' where uf = 20 and upper(trim(unaccent(nome))) like 'PRESIDENTE JUSCELINO';
update cidade set cod_tom = '8419' where uf = 23 and upper(trim(unaccent(nome))) like 'ENTRE-IJUIS';
update cidade set cod_tom = '8251' where uf = 24 and upper(trim(unaccent(nome))) like 'BALNEARIO PICARRAS';
update cidade set cod_tom = '5739' where uf = 24 and upper(trim(unaccent(nome))) like 'LAJEADO GRANDE';
update cidade set cod_tom = '8333' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO LOURENCO DO OESTE';
update cidade set cod_tom = '8339' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO MIGUEL DO OESTE';
update cidade set cod_tom = '3151' where uf = 25 and upper(trim(unaccent(nome))) like 'GRACHO CARDOSO';
update cidade set cod_tom = '6423' where uf = 26 and upper(trim(unaccent(nome))) like 'FLORINIA';
update cidade set cod_tom = '6715' where uf = 26 and upper(trim(unaccent(nome))) like 'MOGI GUACU';
update cidade set cod_tom = '6717' where uf = 26 and upper(trim(unaccent(nome))) like 'MOGI MIRIM';