update cidade set cod_tom = '3301' where uf = 5 and upper(trim(unaccent(nome))) like 'ABAIRA'; 
update cidade set cod_tom = '3303' where uf = 5 and upper(trim(unaccent(nome))) like 'ABARE'; 
update cidade set cod_tom = '3305' where uf = 5 and upper(trim(unaccent(nome))) like 'ACAJUTIBA'; 
update cidade set cod_tom = '3253' where uf = 5 and upper(trim(unaccent(nome))) like 'ADUSTINA'; 
update cidade set cod_tom = '3307' where uf = 5 and upper(trim(unaccent(nome))) like 'AGUA FRIA'; 
update cidade set cod_tom = '3311' where uf = 5 and upper(trim(unaccent(nome))) like 'AIQUARA'; 
update cidade set cod_tom = '3313' where uf = 5 and upper(trim(unaccent(nome))) like 'ALAGOINHAS'; 
update cidade set cod_tom = '3315' where uf = 5 and upper(trim(unaccent(nome))) like 'ALCOBACA'; 
update cidade set cod_tom = '3317' where uf = 5 and upper(trim(unaccent(nome))) like 'ALMADINA'; 
update cidade set cod_tom = '3319' where uf = 5 and upper(trim(unaccent(nome))) like 'AMARGOSA'; 
update cidade set cod_tom = '3321' where uf = 5 and upper(trim(unaccent(nome))) like 'AMELIA RODRIGUES'; 
update cidade set cod_tom = '3071' where uf = 5 and upper(trim(unaccent(nome))) like 'AMERICA DOURADA'; 
update cidade set cod_tom = '3323' where uf = 5 and upper(trim(unaccent(nome))) like 'ANAGE'; 
update cidade set cod_tom = '3325' where uf = 5 and upper(trim(unaccent(nome))) like 'ANDARAI'; 
update cidade set cod_tom = '3255' where uf = 5 and upper(trim(unaccent(nome))) like 'ANDORINHA'; 
update cidade set cod_tom = '3327' where uf = 5 and upper(trim(unaccent(nome))) like 'ANGICAL'; 
update cidade set cod_tom = '3329' where uf = 5 and upper(trim(unaccent(nome))) like 'ANGUERA'; 
update cidade set cod_tom = '3331' where uf = 5 and upper(trim(unaccent(nome))) like 'ANTAS'; 
update cidade set cod_tom = '3333' where uf = 5 and upper(trim(unaccent(nome))) like 'ANTONIO CARDOSO'; 
update cidade set cod_tom = '3335' where uf = 5 and upper(trim(unaccent(nome))) like 'ANTONIO GONCALVES'; 
update cidade set cod_tom = '3337' where uf = 5 and upper(trim(unaccent(nome))) like 'APORA'; 
update cidade set cod_tom = '3257' where uf = 5 and upper(trim(unaccent(nome))) like 'APUAREMA'; 
update cidade set cod_tom = '3259' where uf = 5 and upper(trim(unaccent(nome))) like 'ARACAS'; 
update cidade set cod_tom = '3339' where uf = 5 and upper(trim(unaccent(nome))) like 'ARACATU'; 
update cidade set cod_tom = '3341' where uf = 5 and upper(trim(unaccent(nome))) like 'ARACI'; 
update cidade set cod_tom = '3343' where uf = 5 and upper(trim(unaccent(nome))) like 'ARAMARI'; 
update cidade set cod_tom = '3073' where uf = 5 and upper(trim(unaccent(nome))) like 'ARATACA'; 
update cidade set cod_tom = '3345' where uf = 5 and upper(trim(unaccent(nome))) like 'ARATUIPE'; 
update cidade set cod_tom = '3347' where uf = 5 and upper(trim(unaccent(nome))) like 'AURELINO LEAL'; 
update cidade set cod_tom = '3349' where uf = 5 and upper(trim(unaccent(nome))) like 'BAIANOPOLIS'; 
update cidade set cod_tom = '3351' where uf = 5 and upper(trim(unaccent(nome))) like 'BAIXA GRANDE'; 
update cidade set cod_tom = '3261' where uf = 5 and upper(trim(unaccent(nome))) like 'BANZAE'; 
update cidade set cod_tom = '3353' where uf = 5 and upper(trim(unaccent(nome))) like 'BARRA'; 
update cidade set cod_tom = '3355' where uf = 5 and upper(trim(unaccent(nome))) like 'BARRA DA ESTIVA'; 
update cidade set cod_tom = '3357' where uf = 5 and upper(trim(unaccent(nome))) like 'BARRA DO CHOCA'; 
update cidade set cod_tom = '3359' where uf = 5 and upper(trim(unaccent(nome))) like 'BARRA DO MENDES'; 
update cidade set cod_tom = '3361' where uf = 5 and upper(trim(unaccent(nome))) like 'BARRA DO ROCHA'; 
update cidade set cod_tom = '3363' where uf = 5 and upper(trim(unaccent(nome))) like 'BARREIRAS'; 
update cidade set cod_tom = '3075' where uf = 5 and upper(trim(unaccent(nome))) like 'BARRO ALTO'; 
update cidade set cod_tom = '3365' where uf = 5 and upper(trim(unaccent(nome))) like 'BARRO PRETO'; 
update cidade set cod_tom = '1110' where uf = 5 and upper(trim(unaccent(nome))) like 'BARROCAS'; 
update cidade set cod_tom = '3367' where uf = 5 and upper(trim(unaccent(nome))) like 'BELMONTE'; 
update cidade set cod_tom = '3369' where uf = 5 and upper(trim(unaccent(nome))) like 'BELO CAMPO'; 
update cidade set cod_tom = '3371' where uf = 5 and upper(trim(unaccent(nome))) like 'BIRITINGA'; 
update cidade set cod_tom = '3373' where uf = 5 and upper(trim(unaccent(nome))) like 'BOA NOVA'; 
update cidade set cod_tom = '3375' where uf = 5 and upper(trim(unaccent(nome))) like 'BOA VISTA DO TUPIM'; 
update cidade set cod_tom = '3377' where uf = 5 and upper(trim(unaccent(nome))) like 'BOM JESUS DA LAPA'; 
update cidade set cod_tom = '3263' where uf = 5 and upper(trim(unaccent(nome))) like 'BOM JESUS DA SERRA'; 
update cidade set cod_tom = '3379' where uf = 5 and upper(trim(unaccent(nome))) like 'BONINAL'; 
update cidade set cod_tom = '3265' where uf = 5 and upper(trim(unaccent(nome))) like 'BONITO'; 
update cidade set cod_tom = '3381' where uf = 5 and upper(trim(unaccent(nome))) like 'BOQUIRA'; 
update cidade set cod_tom = '3383' where uf = 5 and upper(trim(unaccent(nome))) like 'BOTUPORA'; 
update cidade set cod_tom = '3385' where uf = 5 and upper(trim(unaccent(nome))) like 'BREJOES'; 
update cidade set cod_tom = '3387' where uf = 5 and upper(trim(unaccent(nome))) like 'BREJOLANDIA'; 
update cidade set cod_tom = '3389' where uf = 5 and upper(trim(unaccent(nome))) like 'BROTAS DE MACAUBAS'; 
update cidade set cod_tom = '3391' where uf = 5 and upper(trim(unaccent(nome))) like 'BRUMADO'; 
update cidade set cod_tom = '3393' where uf = 5 and upper(trim(unaccent(nome))) like 'BUERAREMA'; 
update cidade set cod_tom = '3079' where uf = 5 and upper(trim(unaccent(nome))) like 'BURITIRAMA'; 
update cidade set cod_tom = '3395' where uf = 5 and upper(trim(unaccent(nome))) like 'CAATIBA'; 
update cidade set cod_tom = '3267' where uf = 5 and upper(trim(unaccent(nome))) like 'CABACEIRAS DO PARAGUACU'; 
update cidade set cod_tom = '3397' where uf = 5 and upper(trim(unaccent(nome))) like 'CACHOEIRA'; 
update cidade set cod_tom = '3399' where uf = 5 and upper(trim(unaccent(nome))) like 'CACULE'; 
update cidade set cod_tom = '3401' where uf = 5 and upper(trim(unaccent(nome))) like 'CAEM'; 
update cidade set cod_tom = '3269' where uf = 5 and upper(trim(unaccent(nome))) like 'CAETANOS'; 
update cidade set cod_tom = '3403' where uf = 5 and upper(trim(unaccent(nome))) like 'CAETITE'; 
update cidade set cod_tom = '3405' where uf = 5 and upper(trim(unaccent(nome))) like 'CAFARNAUM'; 
update cidade set cod_tom = '3407' where uf = 5 and upper(trim(unaccent(nome))) like 'CAIRU'; 
update cidade set cod_tom = '3409' where uf = 5 and upper(trim(unaccent(nome))) like 'CALDEIRAO GRANDE'; 
update cidade set cod_tom = '3411' where uf = 5 and upper(trim(unaccent(nome))) like 'CAMACAN'; 
update cidade set cod_tom = '3413' where uf = 5 and upper(trim(unaccent(nome))) like 'CAMACARI'; 
update cidade set cod_tom = '3415' where uf = 5 and upper(trim(unaccent(nome))) like 'CAMAMU'; 
update cidade set cod_tom = '3417' where uf = 5 and upper(trim(unaccent(nome))) like 'CAMPO ALEGRE DE LOURDES'; 
update cidade set cod_tom = '3419' where uf = 5 and upper(trim(unaccent(nome))) like 'CAMPO FORMOSO'; 
update cidade set cod_tom = '3421' where uf = 5 and upper(trim(unaccent(nome))) like 'CANAPOLIS'; 
update cidade set cod_tom = '3423' where uf = 5 and upper(trim(unaccent(nome))) like 'CANARANA'; 
update cidade set cod_tom = '3425' where uf = 5 and upper(trim(unaccent(nome))) like 'CANAVIEIRAS'; 
update cidade set cod_tom = '3427' where uf = 5 and upper(trim(unaccent(nome))) like 'CANDEAL'; 
update cidade set cod_tom = '3429' where uf = 5 and upper(trim(unaccent(nome))) like 'CANDEIAS'; 
update cidade set cod_tom = '3431' where uf = 5 and upper(trim(unaccent(nome))) like 'CANDIBA'; 
update cidade set cod_tom = '3433' where uf = 5 and upper(trim(unaccent(nome))) like 'CANDIDO SALES'; 
update cidade set cod_tom = '3435' where uf = 5 and upper(trim(unaccent(nome))) like 'CANSANCAO'; 
update cidade set cod_tom = '3085' where uf = 5 and upper(trim(unaccent(nome))) like 'CANUDOS'; 
update cidade set cod_tom = '3081' where uf = 5 and upper(trim(unaccent(nome))) like 'CAPELA DO ALTO ALEGRE'; 
update cidade set cod_tom = '3083' where uf = 5 and upper(trim(unaccent(nome))) like 'CAPIM GROSSO'; 
update cidade set cod_tom = '3271' where uf = 5 and upper(trim(unaccent(nome))) like 'CARAIBAS'; 
update cidade set cod_tom = '3437' where uf = 5 and upper(trim(unaccent(nome))) like 'CARAVELAS'; 
update cidade set cod_tom = '3439' where uf = 5 and upper(trim(unaccent(nome))) like 'CARDEAL DA SILVA'; 
update cidade set cod_tom = '3441' where uf = 5 and upper(trim(unaccent(nome))) like 'CARINHANHA'; 
update cidade set cod_tom = '3443' where uf = 5 and upper(trim(unaccent(nome))) like 'CASA NOVA'; 
update cidade set cod_tom = '3445' where uf = 5 and upper(trim(unaccent(nome))) like 'CASTRO ALVES'; 
update cidade set cod_tom = '3447' where uf = 5 and upper(trim(unaccent(nome))) like 'CATOLANDIA'; 
update cidade set cod_tom = '3449' where uf = 5 and upper(trim(unaccent(nome))) like 'CATU'; 
update cidade set cod_tom = '3273' where uf = 5 and upper(trim(unaccent(nome))) like 'CATURAMA'; 
update cidade set cod_tom = '3451' where uf = 5 and upper(trim(unaccent(nome))) like 'CENTRAL'; 
update cidade set cod_tom = '3453' where uf = 5 and upper(trim(unaccent(nome))) like 'CHORROCHO'; 
update cidade set cod_tom = '3455' where uf = 5 and upper(trim(unaccent(nome))) like 'CICERO DANTAS'; 
update cidade set cod_tom = '3457' where uf = 5 and upper(trim(unaccent(nome))) like 'CIPO'; 
update cidade set cod_tom = '3459' where uf = 5 and upper(trim(unaccent(nome))) like 'COARACI'; 
update cidade set cod_tom = '3461' where uf = 5 and upper(trim(unaccent(nome))) like 'COCOS'; 
update cidade set cod_tom = '3463' where uf = 5 and upper(trim(unaccent(nome))) like 'CONCEICAO DA FEIRA'; 
update cidade set cod_tom = '3465' where uf = 5 and upper(trim(unaccent(nome))) like 'CONCEICAO DO ALMEIDA'; 
update cidade set cod_tom = '3467' where uf = 5 and upper(trim(unaccent(nome))) like 'CONCEICAO DO COITE'; 
update cidade set cod_tom = '3469' where uf = 5 and upper(trim(unaccent(nome))) like 'CONCEICAO DO JACUIPE'; 
update cidade set cod_tom = '3471' where uf = 5 and upper(trim(unaccent(nome))) like 'CONDE'; 
update cidade set cod_tom = '3473' where uf = 5 and upper(trim(unaccent(nome))) like 'CONDEUBA'; 
update cidade set cod_tom = '3475' where uf = 5 and upper(trim(unaccent(nome))) like 'CONTENDAS DO SINCORA'; 
update cidade set cod_tom = '3477' where uf = 5 and upper(trim(unaccent(nome))) like 'CORACAO DE MARIA'; 
update cidade set cod_tom = '3479' where uf = 5 and upper(trim(unaccent(nome))) like 'CORDEIROS'; 
update cidade set cod_tom = '3481' where uf = 5 and upper(trim(unaccent(nome))) like 'CORIBE'; 
update cidade set cod_tom = '3483' where uf = 5 and upper(trim(unaccent(nome))) like 'CORONEL JOAO SA'; 
update cidade set cod_tom = '3485' where uf = 5 and upper(trim(unaccent(nome))) like 'CORRENTINA'; 
update cidade set cod_tom = '3487' where uf = 5 and upper(trim(unaccent(nome))) like 'COTEGIPE'; 
update cidade set cod_tom = '3489' where uf = 5 and upper(trim(unaccent(nome))) like 'CRAVOLANDIA'; 
update cidade set cod_tom = '3491' where uf = 5 and upper(trim(unaccent(nome))) like 'CRISOPOLIS'; 
update cidade set cod_tom = '3493' where uf = 5 and upper(trim(unaccent(nome))) like 'CRISTOPOLIS'; 
update cidade set cod_tom = '3495' where uf = 5 and upper(trim(unaccent(nome))) like 'CRUZ DAS ALMAS'; 
update cidade set cod_tom = '3497' where uf = 5 and upper(trim(unaccent(nome))) like 'CURACA'; 
update cidade set cod_tom = '3499' where uf = 5 and upper(trim(unaccent(nome))) like 'DARIO MEIRA'; 
update cidade set cod_tom = '3087' where uf = 5 and upper(trim(unaccent(nome))) like 'DIAS D`AVILA'; 
update cidade set cod_tom = '3501' where uf = 5 and upper(trim(unaccent(nome))) like 'DOM BASILIO'; 
update cidade set cod_tom = '3503' where uf = 5 and upper(trim(unaccent(nome))) like 'DOM MACEDO COSTA'; 
update cidade set cod_tom = '3505' where uf = 5 and upper(trim(unaccent(nome))) like 'ELISIO MEDRADO'; 
update cidade set cod_tom = '3507' where uf = 5 and upper(trim(unaccent(nome))) like 'ENCRUZILHADA'; 
update cidade set cod_tom = '3509' where uf = 5 and upper(trim(unaccent(nome))) like 'ENTRE RIOS'; 
update cidade set cod_tom = '3309' where uf = 5 and upper(trim(unaccent(nome))) like 'ERICO CARDOSO'; 
update cidade set cod_tom = '3511' where uf = 5 and upper(trim(unaccent(nome))) like 'ESPLANADA'; 
update cidade set cod_tom = '3513' where uf = 5 and upper(trim(unaccent(nome))) like 'EUCLIDES DA CUNHA'; 
update cidade set cod_tom = '3117' where uf = 5 and upper(trim(unaccent(nome))) like 'EUNAPOLIS'; 
update cidade set cod_tom = '3089' where uf = 5 and upper(trim(unaccent(nome))) like 'FATIMA'; 
update cidade set cod_tom = '3275' where uf = 5 and upper(trim(unaccent(nome))) like 'FEIRA DA MATA'; 
update cidade set cod_tom = '3515' where uf = 5 and upper(trim(unaccent(nome))) like 'FEIRA DE SANTANA'; 
update cidade set cod_tom = '3091' where uf = 5 and upper(trim(unaccent(nome))) like 'FILADELFIA'; 
update cidade set cod_tom = '3517' where uf = 5 and upper(trim(unaccent(nome))) like 'FIRMINO ALVES'; 
update cidade set cod_tom = '3519' where uf = 5 and upper(trim(unaccent(nome))) like 'FLORESTA AZUL'; 
update cidade set cod_tom = '3521' where uf = 5 and upper(trim(unaccent(nome))) like 'FORMOSA DO RIO PRETO'; 
update cidade set cod_tom = '3523' where uf = 5 and upper(trim(unaccent(nome))) like 'GANDU'; 
update cidade set cod_tom = '3093' where uf = 5 and upper(trim(unaccent(nome))) like 'GAVIAO'; 
update cidade set cod_tom = '3525' where uf = 5 and upper(trim(unaccent(nome))) like 'GENTIO DO OURO'; 
update cidade set cod_tom = '3527' where uf = 5 and upper(trim(unaccent(nome))) like 'GLORIA'; 
update cidade set cod_tom = '3529' where uf = 5 and upper(trim(unaccent(nome))) like 'GONGOGI'; 
update cidade set cod_tom = '3531' where uf = 5 and upper(trim(unaccent(nome))) like 'GOVERNADOR MANGABEIRA'; 
update cidade set cod_tom = '3095' where uf = 5 and upper(trim(unaccent(nome))) like 'GUAJERU'; 
update cidade set cod_tom = '3533' where uf = 5 and upper(trim(unaccent(nome))) like 'GUANAMBI'; 
update cidade set cod_tom = '3535' where uf = 5 and upper(trim(unaccent(nome))) like 'GUARATINGA'; 
update cidade set cod_tom = '3097' where uf = 5 and upper(trim(unaccent(nome))) like 'HELIOPOLIS'; 
update cidade set cod_tom = '3537' where uf = 5 and upper(trim(unaccent(nome))) like 'IACU'; 
update cidade set cod_tom = '3539' where uf = 5 and upper(trim(unaccent(nome))) like 'IBIASSUCE'; 
update cidade set cod_tom = '3541' where uf = 5 and upper(trim(unaccent(nome))) like 'IBICARAI'; 
update cidade set cod_tom = '3543' where uf = 5 and upper(trim(unaccent(nome))) like 'IBICOARA'; 
update cidade set cod_tom = '3545' where uf = 5 and upper(trim(unaccent(nome))) like 'IBICUI'; 
update cidade set cod_tom = '3547' where uf = 5 and upper(trim(unaccent(nome))) like 'IBIPEBA'; 
update cidade set cod_tom = '3551' where uf = 5 and upper(trim(unaccent(nome))) like 'IBIPITANGA'; 
update cidade set cod_tom = '3553' where uf = 5 and upper(trim(unaccent(nome))) like 'IBIQUERA'; 
update cidade set cod_tom = '3555' where uf = 5 and upper(trim(unaccent(nome))) like 'IBIRAPITANGA'; 
update cidade set cod_tom = '3557' where uf = 5 and upper(trim(unaccent(nome))) like 'IBIRAPUA'; 
update cidade set cod_tom = '3559' where uf = 5 and upper(trim(unaccent(nome))) like 'IBIRATAIA'; 
update cidade set cod_tom = '3561' where uf = 5 and upper(trim(unaccent(nome))) like 'IBITIARA'; 
update cidade set cod_tom = '3563' where uf = 5 and upper(trim(unaccent(nome))) like 'IBITITA'; 
update cidade set cod_tom = '3565' where uf = 5 and upper(trim(unaccent(nome))) like 'IBOTIRAMA'; 
update cidade set cod_tom = '3567' where uf = 5 and upper(trim(unaccent(nome))) like 'ICHU'; 
update cidade set cod_tom = '3569' where uf = 5 and upper(trim(unaccent(nome))) like 'IGAPORA'; 
update cidade set cod_tom = '3277' where uf = 5 and upper(trim(unaccent(nome))) like 'IGRAPIUNA'; 
update cidade set cod_tom = '3571' where uf = 5 and upper(trim(unaccent(nome))) like 'IGUAI'; 
update cidade set cod_tom = '3573' where uf = 5 and upper(trim(unaccent(nome))) like 'ILHEUS'; 
update cidade set cod_tom = '0' where uf = 5 and upper(trim(unaccent(nome))) like 'IMBUI'; 
update cidade set cod_tom = '3575' where uf = 5 and upper(trim(unaccent(nome))) like 'INHAMBUPE'; 
update cidade set cod_tom = '3577' where uf = 5 and upper(trim(unaccent(nome))) like 'IPECAETA'; 
update cidade set cod_tom = '3579' where uf = 5 and upper(trim(unaccent(nome))) like 'IPIAU'; 
update cidade set cod_tom = '3581' where uf = 5 and upper(trim(unaccent(nome))) like 'IPIRA'; 
update cidade set cod_tom = '3583' where uf = 5 and upper(trim(unaccent(nome))) like 'IPUPIARA'; 
update cidade set cod_tom = '3585' where uf = 5 and upper(trim(unaccent(nome))) like 'IRAJUBA'; 
update cidade set cod_tom = '3587' where uf = 5 and upper(trim(unaccent(nome))) like 'IRAMAIA'; 
update cidade set cod_tom = '3589' where uf = 5 and upper(trim(unaccent(nome))) like 'IRAQUARA'; 
update cidade set cod_tom = '3591' where uf = 5 and upper(trim(unaccent(nome))) like 'IRARA'; 
update cidade set cod_tom = '3593' where uf = 5 and upper(trim(unaccent(nome))) like 'IRECE'; 
update cidade set cod_tom = '3279' where uf = 5 and upper(trim(unaccent(nome))) like 'ITABELA'; 
update cidade set cod_tom = '3595' where uf = 5 and upper(trim(unaccent(nome))) like 'ITABERABA'; 
update cidade set cod_tom = '3597' where uf = 5 and upper(trim(unaccent(nome))) like 'ITABUNA'; 
update cidade set cod_tom = '3599' where uf = 5 and upper(trim(unaccent(nome))) like 'ITACARE'; 
update cidade set cod_tom = '3601' where uf = 5 and upper(trim(unaccent(nome))) like 'ITAETE'; 
update cidade set cod_tom = '3603' where uf = 5 and upper(trim(unaccent(nome))) like 'ITAGI'; 
update cidade set cod_tom = '3605' where uf = 5 and upper(trim(unaccent(nome))) like 'ITAGIBA'; 
update cidade set cod_tom = '3607' where uf = 5 and upper(trim(unaccent(nome))) like 'ITAGIMIRIM'; 
update cidade set cod_tom = '3281' where uf = 5 and upper(trim(unaccent(nome))) like 'ITAGUACU DA BAHIA'; 
update cidade set cod_tom = '3609' where uf = 5 and upper(trim(unaccent(nome))) like 'ITAJU DO COLONIA'; 
update cidade set cod_tom = '3611' where uf = 5 and upper(trim(unaccent(nome))) like 'ITAJUIPE'; 
update cidade set cod_tom = '3613' where uf = 5 and upper(trim(unaccent(nome))) like 'ITAMARAJU'; 
update cidade set cod_tom = '3615' where uf = 5 and upper(trim(unaccent(nome))) like 'ITAMARI'; 
update cidade set cod_tom = '3617' where uf = 5 and upper(trim(unaccent(nome))) like 'ITAMBE'; 
update cidade set cod_tom = '3619' where uf = 5 and upper(trim(unaccent(nome))) like 'ITANAGRA'; 
update cidade set cod_tom = '3621' where uf = 5 and upper(trim(unaccent(nome))) like 'ITANHEM'; 
update cidade set cod_tom = '3623' where uf = 5 and upper(trim(unaccent(nome))) like 'ITAPARICA'; 
update cidade set cod_tom = '3625' where uf = 5 and upper(trim(unaccent(nome))) like 'ITAPE'; 
update cidade set cod_tom = '3627' where uf = 5 and upper(trim(unaccent(nome))) like 'ITAPEBI'; 
update cidade set cod_tom = '3629' where uf = 5 and upper(trim(unaccent(nome))) like 'ITAPETINGA'; 
update cidade set cod_tom = '3631' where uf = 5 and upper(trim(unaccent(nome))) like 'ITAPICURU'; 
update cidade set cod_tom = '3633' where uf = 5 and upper(trim(unaccent(nome))) like 'ITAPITANGA'; 
update cidade set cod_tom = '3635' where uf = 5 and upper(trim(unaccent(nome))) like 'ITAQUARA'; 
update cidade set cod_tom = '3637' where uf = 5 and upper(trim(unaccent(nome))) like 'ITARANTIM'; 
update cidade set cod_tom = '3283' where uf = 5 and upper(trim(unaccent(nome))) like 'ITATIM'; 
update cidade set cod_tom = '3639' where uf = 5 and upper(trim(unaccent(nome))) like 'ITIRUCU'; 
update cidade set cod_tom = '3641' where uf = 5 and upper(trim(unaccent(nome))) like 'ITIUBA'; 
update cidade set cod_tom = '3643' where uf = 5 and upper(trim(unaccent(nome))) like 'ITORORO'; 
update cidade set cod_tom = '3645' where uf = 5 and upper(trim(unaccent(nome))) like 'ITUACU'; 
update cidade set cod_tom = '3647' where uf = 5 and upper(trim(unaccent(nome))) like 'ITUBERA'; 
update cidade set cod_tom = '3285' where uf = 5 and upper(trim(unaccent(nome))) like 'IUIU'; 
update cidade set cod_tom = '9859' where uf = 5 and upper(trim(unaccent(nome))) like 'JABORANDI'; 
update cidade set cod_tom = '3649' where uf = 5 and upper(trim(unaccent(nome))) like 'JACARACI'; 
update cidade set cod_tom = '3651' where uf = 5 and upper(trim(unaccent(nome))) like 'JACOBINA'; 
update cidade set cod_tom = '3653' where uf = 5 and upper(trim(unaccent(nome))) like 'JAGUAQUARA'; 
update cidade set cod_tom = '3655' where uf = 5 and upper(trim(unaccent(nome))) like 'JAGUARARI'; 
update cidade set cod_tom = '3657' where uf = 5 and upper(trim(unaccent(nome))) like 'JAGUARIPE'; 
update cidade set cod_tom = '3659' where uf = 5 and upper(trim(unaccent(nome))) like 'JANDAIRA'; 
update cidade set cod_tom = '3661' where uf = 5 and upper(trim(unaccent(nome))) like 'JEQUIE'; 
update cidade set cod_tom = '3663' where uf = 5 and upper(trim(unaccent(nome))) like 'JEREMOABO'; 
update cidade set cod_tom = '3665' where uf = 5 and upper(trim(unaccent(nome))) like 'JIQUIRICA'; 
update cidade set cod_tom = '3667' where uf = 5 and upper(trim(unaccent(nome))) like 'JITAUNA'; 
update cidade set cod_tom = '3099' where uf = 5 and upper(trim(unaccent(nome))) like 'JOAO DOURADO'; 
update cidade set cod_tom = '3669' where uf = 5 and upper(trim(unaccent(nome))) like 'JUAZEIRO'; 
update cidade set cod_tom = '3287' where uf = 5 and upper(trim(unaccent(nome))) like 'JUCURUCU'; 
update cidade set cod_tom = '3671' where uf = 5 and upper(trim(unaccent(nome))) like 'JUSSARA'; 
update cidade set cod_tom = '3069' where uf = 5 and upper(trim(unaccent(nome))) like 'JUSSARI'; 
update cidade set cod_tom = '3673' where uf = 5 and upper(trim(unaccent(nome))) like 'JUSSIAPE'; 
update cidade set cod_tom = '3675' where uf = 5 and upper(trim(unaccent(nome))) like 'LAFAIETE COUTINHO'; 
update cidade set cod_tom = '3291' where uf = 5 and upper(trim(unaccent(nome))) like 'LAGEDO DO TABOCAL'; 
update cidade set cod_tom = '3289' where uf = 5 and upper(trim(unaccent(nome))) like 'LAGOA REAL'; 
update cidade set cod_tom = '3677' where uf = 5 and upper(trim(unaccent(nome))) like 'LAJE'; 
update cidade set cod_tom = '3679' where uf = 5 and upper(trim(unaccent(nome))) like 'LAJEDAO'; 
update cidade set cod_tom = '3681' where uf = 5 and upper(trim(unaccent(nome))) like 'LAJEDINHO'; 
update cidade set cod_tom = '3683' where uf = 5 and upper(trim(unaccent(nome))) like 'LAMARAO'; 
update cidade set cod_tom = '3973' where uf = 5 and upper(trim(unaccent(nome))) like 'LAPAO'; 
update cidade set cod_tom = '3685' where uf = 5 and upper(trim(unaccent(nome))) like 'LAURO DE FREITAS'; 
update cidade set cod_tom = '3687' where uf = 5 and upper(trim(unaccent(nome))) like 'LENCOIS'; 
update cidade set cod_tom = '3689' where uf = 5 and upper(trim(unaccent(nome))) like 'LICINIO DE ALMEIDA'; 
update cidade set cod_tom = '3691' where uf = 5 and upper(trim(unaccent(nome))) like 'LIVRAMENTO DE NOSSA SENHORA'; 
update cidade set cod_tom = '3691' where uf = 5 and upper(trim(unaccent(nome))) like 'LIVRAMENTO DO BRUMADO'; 
update cidade set cod_tom = '1112' where uf = 5 and upper(trim(unaccent(nome))) like 'LUIS EDUARDO MAGALHAES'; 
update cidade set cod_tom = '3693' where uf = 5 and upper(trim(unaccent(nome))) like 'MACAJUBA'; 
update cidade set cod_tom = '3695' where uf = 5 and upper(trim(unaccent(nome))) like 'MACARANI'; 
update cidade set cod_tom = '3697' where uf = 5 and upper(trim(unaccent(nome))) like 'MACAUBAS'; 
update cidade set cod_tom = '3699' where uf = 5 and upper(trim(unaccent(nome))) like 'MACURURE'; 
update cidade set cod_tom = '3293' where uf = 5 and upper(trim(unaccent(nome))) like 'MADRE DE DEUS'; 
update cidade set cod_tom = '3975' where uf = 5 and upper(trim(unaccent(nome))) like 'MAETINGA'; 
update cidade set cod_tom = '3701' where uf = 5 and upper(trim(unaccent(nome))) like 'MAIQUINIQUE'; 
update cidade set cod_tom = '3703' where uf = 5 and upper(trim(unaccent(nome))) like 'MAIRI'; 
update cidade set cod_tom = '3705' where uf = 5 and upper(trim(unaccent(nome))) like 'MALHADA'; 
update cidade set cod_tom = '3707' where uf = 5 and upper(trim(unaccent(nome))) like 'MALHADA DE PEDRAS'; 
update cidade set cod_tom = '3709' where uf = 5 and upper(trim(unaccent(nome))) like 'MANOEL VITORINO'; 
update cidade set cod_tom = '3977' where uf = 5 and upper(trim(unaccent(nome))) like 'MANSIDAO'; 
update cidade set cod_tom = '3711' where uf = 5 and upper(trim(unaccent(nome))) like 'MARACAS'; 
update cidade set cod_tom = '3713' where uf = 5 and upper(trim(unaccent(nome))) like 'MARAGOGIPE'; 
update cidade set cod_tom = '3715' where uf = 5 and upper(trim(unaccent(nome))) like 'MARAU'; 
update cidade set cod_tom = '3717' where uf = 5 and upper(trim(unaccent(nome))) like 'MARCIONILIO SOUZA'; 
update cidade set cod_tom = '3719' where uf = 5 and upper(trim(unaccent(nome))) like 'MASCOTE'; 
update cidade set cod_tom = '3721' where uf = 5 and upper(trim(unaccent(nome))) like 'MATA DE SAO JOAO'; 
update cidade set cod_tom = '3295' where uf = 5 and upper(trim(unaccent(nome))) like 'MATINA'; 
update cidade set cod_tom = '3723' where uf = 5 and upper(trim(unaccent(nome))) like 'MEDEIROS NETO'; 
update cidade set cod_tom = '3725' where uf = 5 and upper(trim(unaccent(nome))) like 'MIGUEL CALMON'; 
update cidade set cod_tom = '3727' where uf = 5 and upper(trim(unaccent(nome))) like 'MILAGRES'; 
update cidade set cod_tom = '3729' where uf = 5 and upper(trim(unaccent(nome))) like 'MIRANGABA'; 
update cidade set cod_tom = '3297' where uf = 5 and upper(trim(unaccent(nome))) like 'MIRANTE'; 
update cidade set cod_tom = '3731' where uf = 5 and upper(trim(unaccent(nome))) like 'MONTE SANTO'; 
update cidade set cod_tom = '3733' where uf = 5 and upper(trim(unaccent(nome))) like 'MORPARA'; 
update cidade set cod_tom = '3735' where uf = 5 and upper(trim(unaccent(nome))) like 'MORRO DO CHAPEU'; 
update cidade set cod_tom = '3737' where uf = 5 and upper(trim(unaccent(nome))) like 'MORTUGABA'; 
update cidade set cod_tom = '3739' where uf = 5 and upper(trim(unaccent(nome))) like 'MUCUGE'; 
update cidade set cod_tom = '3741' where uf = 5 and upper(trim(unaccent(nome))) like 'MUCURI'; 
update cidade set cod_tom = '3299' where uf = 5 and upper(trim(unaccent(nome))) like 'MULUNGU DO MORRO'; 
update cidade set cod_tom = '3743' where uf = 5 and upper(trim(unaccent(nome))) like 'MUNDO NOVO'; 
update cidade set cod_tom = '3745' where uf = 5 and upper(trim(unaccent(nome))) like 'MUNIZ FERREIRA'; 
update cidade set cod_tom = '3005' where uf = 5 and upper(trim(unaccent(nome))) like 'MUQUEM DO SAO FRANCISCO'; 
update cidade set cod_tom = '3747' where uf = 5 and upper(trim(unaccent(nome))) like 'MURITIBA'; 
update cidade set cod_tom = '3749' where uf = 5 and upper(trim(unaccent(nome))) like 'MUTUIPE'; 
update cidade set cod_tom = '3751' where uf = 5 and upper(trim(unaccent(nome))) like 'NAZARE'; 
update cidade set cod_tom = '3753' where uf = 5 and upper(trim(unaccent(nome))) like 'NILO PECANHA'; 
update cidade set cod_tom = '3979' where uf = 5 and upper(trim(unaccent(nome))) like 'NORDESTINA'; 
update cidade set cod_tom = '3755' where uf = 5 and upper(trim(unaccent(nome))) like 'NOVA CANAA'; 
update cidade set cod_tom = '3007' where uf = 5 and upper(trim(unaccent(nome))) like 'NOVA FATIMA'; 
update cidade set cod_tom = '3009' where uf = 5 and upper(trim(unaccent(nome))) like 'NOVA IBIA'; 
update cidade set cod_tom = '3757' where uf = 5 and upper(trim(unaccent(nome))) like 'NOVA ITARANA'; 
update cidade set cod_tom = '3011' where uf = 5 and upper(trim(unaccent(nome))) like 'NOVA REDENCAO'; 
update cidade set cod_tom = '3759' where uf = 5 and upper(trim(unaccent(nome))) like 'NOVA SOURE'; 
update cidade set cod_tom = '3761' where uf = 5 and upper(trim(unaccent(nome))) like 'NOVA VICOSA'; 
update cidade set cod_tom = '3013' where uf = 5 and upper(trim(unaccent(nome))) like 'NOVO HORIZONTE'; 
update cidade set cod_tom = '3015' where uf = 5 and upper(trim(unaccent(nome))) like 'NOVO TRIUNFO'; 
update cidade set cod_tom = '3763' where uf = 5 and upper(trim(unaccent(nome))) like 'OLINDINA'; 
update cidade set cod_tom = '3765' where uf = 5 and upper(trim(unaccent(nome))) like 'OLIVEIRA DOS BREJINHOS'; 
update cidade set cod_tom = '3767' where uf = 5 and upper(trim(unaccent(nome))) like 'OURICANGAS'; 
update cidade set cod_tom = '3017' where uf = 5 and upper(trim(unaccent(nome))) like 'OUROLANDIA'; 
update cidade set cod_tom = '3769' where uf = 5 and upper(trim(unaccent(nome))) like 'PALMAS DE MONTE ALTO'; 
update cidade set cod_tom = '3771' where uf = 5 and upper(trim(unaccent(nome))) like 'PALMEIRAS'; 
update cidade set cod_tom = '3773' where uf = 5 and upper(trim(unaccent(nome))) like 'PARAMIRIM'; 
update cidade set cod_tom = '3775' where uf = 5 and upper(trim(unaccent(nome))) like 'PARATINGA'; 
update cidade set cod_tom = '3777' where uf = 5 and upper(trim(unaccent(nome))) like 'PARIPIRANGA'; 
update cidade set cod_tom = '3779' where uf = 5 and upper(trim(unaccent(nome))) like 'PAU BRASIL'; 
update cidade set cod_tom = '3781' where uf = 5 and upper(trim(unaccent(nome))) like 'PAULO AFONSO'; 
update cidade set cod_tom = '3981' where uf = 5 and upper(trim(unaccent(nome))) like 'PE DE SERRA'; 
update cidade set cod_tom = '3783' where uf = 5 and upper(trim(unaccent(nome))) like 'PEDRAO'; 
update cidade set cod_tom = '3785' where uf = 5 and upper(trim(unaccent(nome))) like 'PEDRO ALEXANDRE'; 
update cidade set cod_tom = '3787' where uf = 5 and upper(trim(unaccent(nome))) like 'PIATA'; 
update cidade set cod_tom = '3789' where uf = 5 and upper(trim(unaccent(nome))) like 'PILAO ARCADO'; 
update cidade set cod_tom = '3791' where uf = 5 and upper(trim(unaccent(nome))) like 'PINDAI'; 
update cidade set cod_tom = '3793' where uf = 5 and upper(trim(unaccent(nome))) like 'PINDOBACU'; 
update cidade set cod_tom = '3983' where uf = 5 and upper(trim(unaccent(nome))) like 'PINTADAS'; 
update cidade set cod_tom = '3019' where uf = 5 and upper(trim(unaccent(nome))) like 'PIRAI DO NORTE'; 
update cidade set cod_tom = '3795' where uf = 5 and upper(trim(unaccent(nome))) like 'PIRIPA'; 
update cidade set cod_tom = '3797' where uf = 5 and upper(trim(unaccent(nome))) like 'PIRITIBA'; 
update cidade set cod_tom = '3799' where uf = 5 and upper(trim(unaccent(nome))) like 'PLANALTINO'; 
update cidade set cod_tom = '3801' where uf = 5 and upper(trim(unaccent(nome))) like 'PLANALTO'; 
update cidade set cod_tom = '3803' where uf = 5 and upper(trim(unaccent(nome))) like 'POCOES'; 
update cidade set cod_tom = '3805' where uf = 5 and upper(trim(unaccent(nome))) like 'POJUCA'; 
update cidade set cod_tom = '3021' where uf = 5 and upper(trim(unaccent(nome))) like 'PONTO NOVO'; 
update cidade set cod_tom = '3807' where uf = 5 and upper(trim(unaccent(nome))) like 'PORTO SEGURO'; 
update cidade set cod_tom = '3809' where uf = 5 and upper(trim(unaccent(nome))) like 'POTIRAGUA'; 
update cidade set cod_tom = '3811' where uf = 5 and upper(trim(unaccent(nome))) like 'PRADO'; 
update cidade set cod_tom = '3813' where uf = 5 and upper(trim(unaccent(nome))) like 'PRESIDENTE DUTRA'; 
update cidade set cod_tom = '3815' where uf = 5 and upper(trim(unaccent(nome))) like 'PRESIDENTE JANIO QUADROS'; 
update cidade set cod_tom = '3023' where uf = 5 and upper(trim(unaccent(nome))) like 'PRESIDENTE TANCREDO NEVES'; 
update cidade set cod_tom = '3817' where uf = 5 and upper(trim(unaccent(nome))) like 'QUEIMADAS'; 
update cidade set cod_tom = '3819' where uf = 5 and upper(trim(unaccent(nome))) like 'QUIJINGUE'; 
update cidade set cod_tom = '3025' where uf = 5 and upper(trim(unaccent(nome))) like 'QUIXABEIRA'; 
update cidade set cod_tom = '3985' where uf = 5 and upper(trim(unaccent(nome))) like 'RAFAEL JAMBEIRO'; 
update cidade set cod_tom = '3821' where uf = 5 and upper(trim(unaccent(nome))) like 'REMANSO'; 
update cidade set cod_tom = '3823' where uf = 5 and upper(trim(unaccent(nome))) like 'RETIROLANDIA'; 
update cidade set cod_tom = '3825' where uf = 5 and upper(trim(unaccent(nome))) like 'RIACHAO DAS NEVES'; 
update cidade set cod_tom = '3827' where uf = 5 and upper(trim(unaccent(nome))) like 'RIACHAO DO JACUIPE'; 
update cidade set cod_tom = '3829' where uf = 5 and upper(trim(unaccent(nome))) like 'RIACHO DE SANTANA'; 
update cidade set cod_tom = '3831' where uf = 5 and upper(trim(unaccent(nome))) like 'RIBEIRA DO AMPARO'; 
update cidade set cod_tom = '3833' where uf = 5 and upper(trim(unaccent(nome))) like 'RIBEIRA DO POMBAL'; 
update cidade set cod_tom = '3027' where uf = 5 and upper(trim(unaccent(nome))) like 'RIBEIRAO DO LARGO'; 
update cidade set cod_tom = '3835' where uf = 5 and upper(trim(unaccent(nome))) like 'RIO DE CONTAS'; 
update cidade set cod_tom = '3837' where uf = 5 and upper(trim(unaccent(nome))) like 'RIO DO ANTONIO'; 
update cidade set cod_tom = '3839' where uf = 5 and upper(trim(unaccent(nome))) like 'RIO DO PIRES'; 
update cidade set cod_tom = '3841' where uf = 5 and upper(trim(unaccent(nome))) like 'RIO REAL'; 
update cidade set cod_tom = '3843' where uf = 5 and upper(trim(unaccent(nome))) like 'RODELAS'; 
update cidade set cod_tom = '3845' where uf = 5 and upper(trim(unaccent(nome))) like 'RUY BARBOSA'; 
update cidade set cod_tom = '3847' where uf = 5 and upper(trim(unaccent(nome))) like 'SALINAS DA MARGARIDA'; 
update cidade set cod_tom = '3849' where uf = 5 and upper(trim(unaccent(nome))) like 'SALVADOR'; 
update cidade set cod_tom = '3851' where uf = 5 and upper(trim(unaccent(nome))) like 'SANTA BARBARA'; 
update cidade set cod_tom = '3853' where uf = 5 and upper(trim(unaccent(nome))) like 'SANTA BRIGIDA'; 
update cidade set cod_tom = '3855' where uf = 5 and upper(trim(unaccent(nome))) like 'SANTA CRUZ CABRALIA'; 
update cidade set cod_tom = '3857' where uf = 5 and upper(trim(unaccent(nome))) like 'SANTA CRUZ DA VITORIA'; 
update cidade set cod_tom = '3859' where uf = 5 and upper(trim(unaccent(nome))) like 'SANTA INES'; 
update cidade set cod_tom = '3987' where uf = 5 and upper(trim(unaccent(nome))) like 'SANTA LUZIA'; 
update cidade set cod_tom = '3863' where uf = 5 and upper(trim(unaccent(nome))) like 'SANTA MARIA DA VITORIA'; 
update cidade set cod_tom = '3549' where uf = 5 and upper(trim(unaccent(nome))) like 'SANTA RITA DE CASSIA'; 
update cidade set cod_tom = '3869' where uf = 5 and upper(trim(unaccent(nome))) like 'SANTA TERESINHA'; 
update cidade set cod_tom = '3861' where uf = 5 and upper(trim(unaccent(nome))) like 'SANTALUZ'; 
update cidade set cod_tom = '3865' where uf = 5 and upper(trim(unaccent(nome))) like 'SANTANA'; 
update cidade set cod_tom = '3867' where uf = 5 and upper(trim(unaccent(nome))) like 'SANTANOPOLIS'; 
update cidade set cod_tom = '3871' where uf = 5 and upper(trim(unaccent(nome))) like 'SANTO AMARO'; 
update cidade set cod_tom = '3873' where uf = 5 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DE JESUS'; 
update cidade set cod_tom = '3875' where uf = 5 and upper(trim(unaccent(nome))) like 'SANTO ESTEVAO'; 
update cidade set cod_tom = '3877' where uf = 5 and upper(trim(unaccent(nome))) like 'SAO DESIDERIO'; 
update cidade set cod_tom = '3029' where uf = 5 and upper(trim(unaccent(nome))) like 'SAO DOMINGOS'; 
update cidade set cod_tom = '3881' where uf = 5 and upper(trim(unaccent(nome))) like 'SAO FELIPE'; 
update cidade set cod_tom = '3879' where uf = 5 and upper(trim(unaccent(nome))) like 'SAO FELIX'; 
update cidade set cod_tom = '3031' where uf = 5 and upper(trim(unaccent(nome))) like 'SAO FELIX DO CORIBE'; 
update cidade set cod_tom = '3883' where uf = 5 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO DO CONDE'; 
update cidade set cod_tom = '3989' where uf = 5 and upper(trim(unaccent(nome))) like 'SAO GABRIEL'; 
update cidade set cod_tom = '3885' where uf = 5 and upper(trim(unaccent(nome))) like 'SAO GONCALO DOS CAMPOS'; 
update cidade set cod_tom = '3035' where uf = 5 and upper(trim(unaccent(nome))) like 'SAO JOSE DA VITORIA'; 
update cidade set cod_tom = '3033' where uf = 5 and upper(trim(unaccent(nome))) like 'SAO JOSE DO JACUIPE'; 
update cidade set cod_tom = '3887' where uf = 5 and upper(trim(unaccent(nome))) like 'SAO MIGUEL DAS MATAS'; 
update cidade set cod_tom = '3889' where uf = 5 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO DO PASSE'; 
update cidade set cod_tom = '3891' where uf = 5 and upper(trim(unaccent(nome))) like 'SAPEACU'; 
update cidade set cod_tom = '3893' where uf = 5 and upper(trim(unaccent(nome))) like 'SATIRO DIAS'; 
update cidade set cod_tom = '3037' where uf = 5 and upper(trim(unaccent(nome))) like 'SAUBARA'; 
update cidade set cod_tom = '3895' where uf = 5 and upper(trim(unaccent(nome))) like 'SAUDE'; 
update cidade set cod_tom = '3897' where uf = 5 and upper(trim(unaccent(nome))) like 'SEABRA'; 
update cidade set cod_tom = '3899' where uf = 5 and upper(trim(unaccent(nome))) like 'SEBASTIAO LARANJEIRAS'; 
update cidade set cod_tom = '3901' where uf = 5 and upper(trim(unaccent(nome))) like 'SENHOR DO BONFIM'; 
update cidade set cod_tom = '3903' where uf = 5 and upper(trim(unaccent(nome))) like 'SENTO SE'; 
update cidade set cod_tom = '3039' where uf = 5 and upper(trim(unaccent(nome))) like 'SERRA DO RAMALHO'; 
update cidade set cod_tom = '3905' where uf = 5 and upper(trim(unaccent(nome))) like 'SERRA DOURADA'; 
update cidade set cod_tom = '3907' where uf = 5 and upper(trim(unaccent(nome))) like 'SERRA PRETA'; 
update cidade set cod_tom = '3909' where uf = 5 and upper(trim(unaccent(nome))) like 'SERRINHA'; 
update cidade set cod_tom = '3911' where uf = 5 and upper(trim(unaccent(nome))) like 'SERROLANDIA'; 
update cidade set cod_tom = '3913' where uf = 5 and upper(trim(unaccent(nome))) like 'SIMOES FILHO'; 
update cidade set cod_tom = '3041' where uf = 5 and upper(trim(unaccent(nome))) like 'SITIO DO MATO'; 
update cidade set cod_tom = '3043' where uf = 5 and upper(trim(unaccent(nome))) like 'SITIO DO QUINTO'; 
update cidade set cod_tom = '3045' where uf = 5 and upper(trim(unaccent(nome))) like 'SOBRADINHO'; 
update cidade set cod_tom = '3915' where uf = 5 and upper(trim(unaccent(nome))) like 'SOUTO SOARES'; 
update cidade set cod_tom = '3917' where uf = 5 and upper(trim(unaccent(nome))) like 'TABOCAS DO BREJO VELHO'; 
update cidade set cod_tom = '3919' where uf = 5 and upper(trim(unaccent(nome))) like 'TANHACU'; 
update cidade set cod_tom = '3991' where uf = 5 and upper(trim(unaccent(nome))) like 'TANQUE NOVO'; 
update cidade set cod_tom = '3921' where uf = 5 and upper(trim(unaccent(nome))) like 'TANQUINHO'; 
update cidade set cod_tom = '3923' where uf = 5 and upper(trim(unaccent(nome))) like 'TAPEROA'; 
update cidade set cod_tom = '3925' where uf = 5 and upper(trim(unaccent(nome))) like 'TAPIRAMUTA'; 
update cidade set cod_tom = '3993' where uf = 5 and upper(trim(unaccent(nome))) like 'TEIXEIRA DE FREITAS'; 
update cidade set cod_tom = '3927' where uf = 5 and upper(trim(unaccent(nome))) like 'TEODORO SAMPAIO'; 
update cidade set cod_tom = '3929' where uf = 5 and upper(trim(unaccent(nome))) like 'TEOFILANDIA'; 
update cidade set cod_tom = '3931' where uf = 5 and upper(trim(unaccent(nome))) like 'TEOLANDIA'; 
update cidade set cod_tom = '3933' where uf = 5 and upper(trim(unaccent(nome))) like 'TERRA NOVA'; 
update cidade set cod_tom = '3935' where uf = 5 and upper(trim(unaccent(nome))) like 'TREMEDAL'; 
update cidade set cod_tom = '3937' where uf = 5 and upper(trim(unaccent(nome))) like 'TUCANO'; 
update cidade set cod_tom = '3939' where uf = 5 and upper(trim(unaccent(nome))) like 'UAUA'; 
update cidade set cod_tom = '3941' where uf = 5 and upper(trim(unaccent(nome))) like 'UBAIRA'; 
update cidade set cod_tom = '3943' where uf = 5 and upper(trim(unaccent(nome))) like 'UBAITABA'; 
update cidade set cod_tom = '3945' where uf = 5 and upper(trim(unaccent(nome))) like 'UBATA'; 
update cidade set cod_tom = '3947' where uf = 5 and upper(trim(unaccent(nome))) like 'UIBAI'; 
update cidade set cod_tom = '3047' where uf = 5 and upper(trim(unaccent(nome))) like 'UMBURANAS'; 
update cidade set cod_tom = '3949' where uf = 5 and upper(trim(unaccent(nome))) like 'UNA'; 
update cidade set cod_tom = '3951' where uf = 5 and upper(trim(unaccent(nome))) like 'URANDI'; 
update cidade set cod_tom = '3953' where uf = 5 and upper(trim(unaccent(nome))) like 'URUCUCA'; 
update cidade set cod_tom = '3955' where uf = 5 and upper(trim(unaccent(nome))) like 'UTINGA'; 
update cidade set cod_tom = '3957' where uf = 5 and upper(trim(unaccent(nome))) like 'VALENCA'; 
update cidade set cod_tom = '3959' where uf = 5 and upper(trim(unaccent(nome))) like 'VALENTE'; 
update cidade set cod_tom = '3997' where uf = 5 and upper(trim(unaccent(nome))) like 'VARZEA DA ROCA'; 
update cidade set cod_tom = '3961' where uf = 5 and upper(trim(unaccent(nome))) like 'VARZEA DO POCO'; 
update cidade set cod_tom = '3995' where uf = 5 and upper(trim(unaccent(nome))) like 'VARZEA NOVA'; 
update cidade set cod_tom = '3049' where uf = 5 and upper(trim(unaccent(nome))) like 'VARZEDO'; 
update cidade set cod_tom = '3963' where uf = 5 and upper(trim(unaccent(nome))) like 'VERA CRUZ'; 
update cidade set cod_tom = '3051' where uf = 5 and upper(trim(unaccent(nome))) like 'VEREDA'; 
update cidade set cod_tom = '3965' where uf = 5 and upper(trim(unaccent(nome))) like 'VITORIA DA CONQUISTA'; 
update cidade set cod_tom = '3967' where uf = 5 and upper(trim(unaccent(nome))) like 'WAGNER'; 
update cidade set cod_tom = '3999' where uf = 5 and upper(trim(unaccent(nome))) like 'WANDERLEY'; 
update cidade set cod_tom = '3969' where uf = 5 and upper(trim(unaccent(nome))) like 'WENCESLAU GUIMARAES'; 
update cidade set cod_tom = '3971' where uf = 5 and upper(trim(unaccent(nome))) like 'XIQUE-XIQUE';