update cidade set cod_tom = '1118' where uf = 23 and upper(trim(unaccent(nome))) like 'ACEGUA'; 
update cidade set cod_tom = '8499' where uf = 23 and upper(trim(unaccent(nome))) like 'AGUA SANTA'; 
update cidade set cod_tom = '8501' where uf = 23 and upper(trim(unaccent(nome))) like 'AGUDO'; 
update cidade set cod_tom = '8503' where uf = 23 and upper(trim(unaccent(nome))) like 'AJURICABA'; 
update cidade set cod_tom = '8505' where uf = 23 and upper(trim(unaccent(nome))) like 'ALECRIM'; 
update cidade set cod_tom = '8507' where uf = 23 and upper(trim(unaccent(nome))) like 'ALEGRETE'; 
update cidade set cod_tom = '8497' where uf = 23 and upper(trim(unaccent(nome))) like 'ALEGRIA'; 
update cidade set cod_tom = '1120' where uf = 23 and upper(trim(unaccent(nome))) like 'ALMIRANTE TAMANDARE DO SUL'; 
update cidade set cod_tom = '8509' where uf = 23 and upper(trim(unaccent(nome))) like 'ALPESTRE'; 
update cidade set cod_tom = '8495' where uf = 23 and upper(trim(unaccent(nome))) like 'ALTO ALEGRE'; 
update cidade set cod_tom = '6045' where uf = 23 and upper(trim(unaccent(nome))) like 'ALTO FELIZ'; 
update cidade set cod_tom = '8511' where uf = 23 and upper(trim(unaccent(nome))) like 'ALVORADA'; 
update cidade set cod_tom = '8493' where uf = 23 and upper(trim(unaccent(nome))) like 'AMARAL FERRADOR'; 
update cidade set cod_tom = '5969' where uf = 23 and upper(trim(unaccent(nome))) like 'AMETISTA DO SUL'; 
update cidade set cod_tom = '8491' where uf = 23 and upper(trim(unaccent(nome))) like 'ANDRE DA ROCHA'; 
update cidade set cod_tom = '8513' where uf = 23 and upper(trim(unaccent(nome))) like 'ANTA GORDA'; 
update cidade set cod_tom = '8515' where uf = 23 and upper(trim(unaccent(nome))) like 'ANTONIO PRADO'; 
update cidade set cod_tom = '5779' where uf = 23 and upper(trim(unaccent(nome))) like 'ARAMBARE'; 
update cidade set cod_tom = '0952' where uf = 23 and upper(trim(unaccent(nome))) like 'ARARICA'; 
update cidade set cod_tom = '8517' where uf = 23 and upper(trim(unaccent(nome))) like 'ARATIBA'; 
update cidade set cod_tom = '8519' where uf = 23 and upper(trim(unaccent(nome))) like 'ARROIO DO MEIO'; 
update cidade set cod_tom = '1122' where uf = 23 and upper(trim(unaccent(nome))) like 'ARROIO DO PADRE'; 
update cidade set cod_tom = '8489' where uf = 23 and upper(trim(unaccent(nome))) like 'ARROIO DO SAL'; 
update cidade set cod_tom = '8523' where uf = 23 and upper(trim(unaccent(nome))) like 'ARROIO DO TIGRE'; 
update cidade set cod_tom = '8521' where uf = 23 and upper(trim(unaccent(nome))) like 'ARROIO DOS RATOS'; 
update cidade set cod_tom = '8525' where uf = 23 and upper(trim(unaccent(nome))) like 'ARROIO GRANDE'; 
update cidade set cod_tom = '8527' where uf = 23 and upper(trim(unaccent(nome))) like 'ARVOREZINHA'; 
update cidade set cod_tom = '8529' where uf = 23 and upper(trim(unaccent(nome))) like 'AUGUSTO PESTANA'; 
update cidade set cod_tom = '8487' where uf = 23 and upper(trim(unaccent(nome))) like 'AUREA'; 
update cidade set cod_tom = '8531' where uf = 23 and upper(trim(unaccent(nome))) like 'BAGE'; 
update cidade set cod_tom = '0954' where uf = 23 and upper(trim(unaccent(nome))) like 'BALNEARIO PINHAL'; 
update cidade set cod_tom = '8485' where uf = 23 and upper(trim(unaccent(nome))) like 'BARAO'; 
update cidade set cod_tom = '8533' where uf = 23 and upper(trim(unaccent(nome))) like 'BARAO DE COTEGIPE'; 
update cidade set cod_tom = '5771' where uf = 23 and upper(trim(unaccent(nome))) like 'BARAO DO TRIUNFO'; 
update cidade set cod_tom = '6069' where uf = 23 and upper(trim(unaccent(nome))) like 'BARRA DO GUARITA'; 
update cidade set cod_tom = '0956' where uf = 23 and upper(trim(unaccent(nome))) like 'BARRA DO QUARAI'; 
update cidade set cod_tom = '8537' where uf = 23 and upper(trim(unaccent(nome))) like 'BARRA DO RIBEIRO'; 
update cidade set cod_tom = '5959' where uf = 23 and upper(trim(unaccent(nome))) like 'BARRA DO RIO AZUL'; 
update cidade set cod_tom = '5943' where uf = 23 and upper(trim(unaccent(nome))) like 'BARRA FUNDA'; 
update cidade set cod_tom = '8535' where uf = 23 and upper(trim(unaccent(nome))) like 'BARRACAO'; 
update cidade set cod_tom = '8539' where uf = 23 and upper(trim(unaccent(nome))) like 'BARROS CASSAL'; 
update cidade set cod_tom = '0958' where uf = 23 and upper(trim(unaccent(nome))) like 'BENJAMIN CONSTANT DO SUL'; 
update cidade set cod_tom = '8541' where uf = 23 and upper(trim(unaccent(nome))) like 'BENTO GONCALVES'; 
update cidade set cod_tom = '5981' where uf = 23 and upper(trim(unaccent(nome))) like 'BOA VISTA DAS MISSOES'; 
update cidade set cod_tom = '8543' where uf = 23 and upper(trim(unaccent(nome))) like 'BOA VISTA DO BURICA'; 
update cidade set cod_tom = '1124' where uf = 23 and upper(trim(unaccent(nome))) like 'BOA VISTA DO CADEADO'; 
update cidade set cod_tom = '1126' where uf = 23 and upper(trim(unaccent(nome))) like 'BOA VISTA DO INCRA'; 
update cidade set cod_tom = '0960' where uf = 23 and upper(trim(unaccent(nome))) like 'BOA VISTA DO SUL'; 
update cidade set cod_tom = '8545' where uf = 23 and upper(trim(unaccent(nome))) like 'BOM JESUS'; 
update cidade set cod_tom = '9823' where uf = 23 and upper(trim(unaccent(nome))) like 'BOM PRINCIPIO'; 
update cidade set cod_tom = '6071' where uf = 23 and upper(trim(unaccent(nome))) like 'BOM PROGRESSO'; 
update cidade set cod_tom = '8547' where uf = 23 and upper(trim(unaccent(nome))) like 'BOM RETIRO DO SUL'; 
update cidade set cod_tom = '8483' where uf = 23 and upper(trim(unaccent(nome))) like 'BOQUEIRAO DO LEAO'; 
update cidade set cod_tom = '8549' where uf = 23 and upper(trim(unaccent(nome))) like 'BOSSOROCA'; 
update cidade set cod_tom = '1128' where uf = 23 and upper(trim(unaccent(nome))) like 'BOZANO'; 
update cidade set cod_tom = '8551' where uf = 23 and upper(trim(unaccent(nome))) like 'BRAGA'; 
update cidade set cod_tom = '8449' where uf = 23 and upper(trim(unaccent(nome))) like 'BROCHIER'; 
update cidade set cod_tom = '0' where uf = 23 and upper(trim(unaccent(nome))) like 'BROCHIER DO MARATA'; 
update cidade set cod_tom = '8553' where uf = 23 and upper(trim(unaccent(nome))) like 'BUTIA'; 
update cidade set cod_tom = '8555' where uf = 23 and upper(trim(unaccent(nome))) like 'CACAPAVA DO SUL'; 
update cidade set cod_tom = '8557' where uf = 23 and upper(trim(unaccent(nome))) like 'CACEQUI'; 
update cidade set cod_tom = '8559' where uf = 23 and upper(trim(unaccent(nome))) like 'CACHOEIRA DO SUL'; 
update cidade set cod_tom = '8561' where uf = 23 and upper(trim(unaccent(nome))) like 'CACHOEIRINHA'; 
update cidade set cod_tom = '8563' where uf = 23 and upper(trim(unaccent(nome))) like 'CACIQUE DOBLE'; 
update cidade set cod_tom = '8565' where uf = 23 and upper(trim(unaccent(nome))) like 'CAIBATE'; 
update cidade set cod_tom = '8567' where uf = 23 and upper(trim(unaccent(nome))) like 'CAICARA'; 
update cidade set cod_tom = '8569' where uf = 23 and upper(trim(unaccent(nome))) like 'CAMAQUA'; 
update cidade set cod_tom = '8447' where uf = 23 and upper(trim(unaccent(nome))) like 'CAMARGO'; 
update cidade set cod_tom = '8571' where uf = 23 and upper(trim(unaccent(nome))) like 'CAMBARA DO SUL'; 
update cidade set cod_tom = '6013' where uf = 23 and upper(trim(unaccent(nome))) like 'CAMPESTRE DA SERRA'; 
update cidade set cod_tom = '8573' where uf = 23 and upper(trim(unaccent(nome))) like 'CAMPINA DAS MISSOES'; 
update cidade set cod_tom = '8575' where uf = 23 and upper(trim(unaccent(nome))) like 'CAMPINAS DO SUL'; 
update cidade set cod_tom = '8577' where uf = 23 and upper(trim(unaccent(nome))) like 'CAMPO BOM'; 
update cidade set cod_tom = '8579' where uf = 23 and upper(trim(unaccent(nome))) like 'CAMPO NOVO'; 
update cidade set cod_tom = '8445' where uf = 23 and upper(trim(unaccent(nome))) like 'CAMPOS BORGES'; 
update cidade set cod_tom = '8581' where uf = 23 and upper(trim(unaccent(nome))) like 'CANDELARIA'; 
update cidade set cod_tom = '8583' where uf = 23 and upper(trim(unaccent(nome))) like 'CANDIDO GODOI'; 
update cidade set cod_tom = '6083' where uf = 23 and upper(trim(unaccent(nome))) like 'CANDIOTA'; 
update cidade set cod_tom = '8585' where uf = 23 and upper(trim(unaccent(nome))) like 'CANELA'; 
update cidade set cod_tom = '8587' where uf = 23 and upper(trim(unaccent(nome))) like 'CANGUCU'; 
update cidade set cod_tom = '8589' where uf = 23 and upper(trim(unaccent(nome))) like 'CANOAS'; 
update cidade set cod_tom = '1130' where uf = 23 and upper(trim(unaccent(nome))) like 'CANUDOS DO VALE'; 
update cidade set cod_tom = '1132' where uf = 23 and upper(trim(unaccent(nome))) like 'CAPAO BONITO DO SUL'; 
update cidade set cod_tom = '8915' where uf = 23 and upper(trim(unaccent(nome))) like 'CAPAO DA CANOA'; 
update cidade set cod_tom = '1134' where uf = 23 and upper(trim(unaccent(nome))) like 'CAPAO DO CIPO'; 
update cidade set cod_tom = '8973' where uf = 23 and upper(trim(unaccent(nome))) like 'CAPAO DO LEAO'; 
update cidade set cod_tom = '8443' where uf = 23 and upper(trim(unaccent(nome))) like 'CAPELA DE SANTANA'; 
update cidade set cod_tom = '6025' where uf = 23 and upper(trim(unaccent(nome))) like 'CAPITAO'; 
update cidade set cod_tom = '0962' where uf = 23 and upper(trim(unaccent(nome))) like 'CAPIVARI DO SUL'; 
update cidade set cod_tom = '0964' where uf = 23 and upper(trim(unaccent(nome))) like 'CARAA'; 
update cidade set cod_tom = '8591' where uf = 23 and upper(trim(unaccent(nome))) like 'CARAZINHO'; 
update cidade set cod_tom = '8593' where uf = 23 and upper(trim(unaccent(nome))) like 'CARLOS BARBOSA'; 
update cidade set cod_tom = '5961' where uf = 23 and upper(trim(unaccent(nome))) like 'CARLOS GOMES'; 
update cidade set cod_tom = '8595' where uf = 23 and upper(trim(unaccent(nome))) like 'CASCA'; 
update cidade set cod_tom = '8441' where uf = 23 and upper(trim(unaccent(nome))) like 'CASEIROS'; 
update cidade set cod_tom = '8597' where uf = 23 and upper(trim(unaccent(nome))) like 'CATUIPE'; 
update cidade set cod_tom = '8599' where uf = 23 and upper(trim(unaccent(nome))) like 'CAXIAS DO SUL'; 
update cidade set cod_tom = '5963' where uf = 23 and upper(trim(unaccent(nome))) like 'CENTENARIO'; 
update cidade set cod_tom = '0966' where uf = 23 and upper(trim(unaccent(nome))) like 'CERRITO'; 
update cidade set cod_tom = '8439' where uf = 23 and upper(trim(unaccent(nome))) like 'CERRO BRANCO'; 
update cidade set cod_tom = '8437' where uf = 23 and upper(trim(unaccent(nome))) like 'CERRO GRANDE'; 
update cidade set cod_tom = '8435' where uf = 23 and upper(trim(unaccent(nome))) like 'CERRO GRANDE DO SUL'; 
update cidade set cod_tom = '8601' where uf = 23 and upper(trim(unaccent(nome))) like 'CERRO LARGO'; 
update cidade set cod_tom = '8603' where uf = 23 and upper(trim(unaccent(nome))) like 'CHAPADA'; 
update cidade set cod_tom = '8693' where uf = 23 and upper(trim(unaccent(nome))) like 'CHARQUEADAS'; 
update cidade set cod_tom = '5965' where uf = 23 and upper(trim(unaccent(nome))) like 'CHARRUA'; 
update cidade set cod_tom = '8605' where uf = 23 and upper(trim(unaccent(nome))) like 'CHIAPETTA'; 
update cidade set cod_tom = '0968' where uf = 23 and upper(trim(unaccent(nome))) like 'CHUI'; 
update cidade set cod_tom = '0970' where uf = 23 and upper(trim(unaccent(nome))) like 'CHUVISCA'; 
update cidade set cod_tom = '8433' where uf = 23 and upper(trim(unaccent(nome))) like 'CIDREIRA'; 
update cidade set cod_tom = '8607' where uf = 23 and upper(trim(unaccent(nome))) like 'CIRIACO'; 
update cidade set cod_tom = '6029' where uf = 23 and upper(trim(unaccent(nome))) like 'COLINAS'; 
update cidade set cod_tom = '8609' where uf = 23 and upper(trim(unaccent(nome))) like 'COLORADO'; 
update cidade set cod_tom = '8611' where uf = 23 and upper(trim(unaccent(nome))) like 'CONDOR'; 
update cidade set cod_tom = '8613' where uf = 23 and upper(trim(unaccent(nome))) like 'CONSTANTINA'; 
update cidade set cod_tom = '1136' where uf = 23 and upper(trim(unaccent(nome))) like 'COQUEIRO BAIXO'; 
update cidade set cod_tom = '5945' where uf = 23 and upper(trim(unaccent(nome))) like 'COQUEIROS DO SUL'; 
update cidade set cod_tom = '6055' where uf = 23 and upper(trim(unaccent(nome))) like 'CORONEL BARROS'; 
update cidade set cod_tom = '8615' where uf = 23 and upper(trim(unaccent(nome))) like 'CORONEL BICACO'; 
update cidade set cod_tom = '1138' where uf = 23 and upper(trim(unaccent(nome))) like 'CORONEL PILAR'; 
update cidade set cod_tom = '8977' where uf = 23 and upper(trim(unaccent(nome))) like 'COTIPORA'; 
update cidade set cod_tom = '5797' where uf = 23 and upper(trim(unaccent(nome))) like 'COXILHA'; 
update cidade set cod_tom = '8617' where uf = 23 and upper(trim(unaccent(nome))) like 'CRISSIUMAL'; 
update cidade set cod_tom = '8431' where uf = 23 and upper(trim(unaccent(nome))) like 'CRISTAL'; 
update cidade set cod_tom = '0972' where uf = 23 and upper(trim(unaccent(nome))) like 'CRISTAL DO SUL'; 
update cidade set cod_tom = '8619' where uf = 23 and upper(trim(unaccent(nome))) like 'CRUZ ALTA'; 
update cidade set cod_tom = '1140' where uf = 23 and upper(trim(unaccent(nome))) like 'CRUZALTENSE'; 
update cidade set cod_tom = '8621' where uf = 23 and upper(trim(unaccent(nome))) like 'CRUZEIRO DO SUL'; 
update cidade set cod_tom = '8623' where uf = 23 and upper(trim(unaccent(nome))) like 'DAVID CANABARRO'; 
update cidade set cod_tom = '6073' where uf = 23 and upper(trim(unaccent(nome))) like 'DERRUBADAS'; 
update cidade set cod_tom = '8429' where uf = 23 and upper(trim(unaccent(nome))) like 'DEZESSEIS DE NOVEMBRO'; 
update cidade set cod_tom = '0974' where uf = 23 and upper(trim(unaccent(nome))) like 'DILERMANDO DE AGUIAR'; 
update cidade set cod_tom = '8625' where uf = 23 and upper(trim(unaccent(nome))) like 'DOIS IRMAOS'; 
update cidade set cod_tom = '5971' where uf = 23 and upper(trim(unaccent(nome))) like 'DOIS IRMAOS DAS MISSOES'; 
update cidade set cod_tom = '8427' where uf = 23 and upper(trim(unaccent(nome))) like 'DOIS LAJEADOS'; 
update cidade set cod_tom = '8627' where uf = 23 and upper(trim(unaccent(nome))) like 'DOM FELICIANO'; 
update cidade set cod_tom = '8629' where uf = 23 and upper(trim(unaccent(nome))) like 'DOM PEDRITO'; 
update cidade set cod_tom = '0976' where uf = 23 and upper(trim(unaccent(nome))) like 'DOM PEDRO DE ALCANTARA'; 
update cidade set cod_tom = '8631' where uf = 23 and upper(trim(unaccent(nome))) like 'DONA FRANCISCA'; 
update cidade set cod_tom = '8425' where uf = 23 and upper(trim(unaccent(nome))) like 'DOUTOR MAURICIO CARDOSO'; 
update cidade set cod_tom = '0978' where uf = 23 and upper(trim(unaccent(nome))) like 'DOUTOR RICARDO'; 
update cidade set cod_tom = '8423' where uf = 23 and upper(trim(unaccent(nome))) like 'ELDORADO DO SUL'; 
update cidade set cod_tom = '8633' where uf = 23 and upper(trim(unaccent(nome))) like 'ENCANTADO'; 
update cidade set cod_tom = '8635' where uf = 23 and upper(trim(unaccent(nome))) like 'ENCRUZILHADA DO SUL'; 
update cidade set cod_tom = '5947' where uf = 23 and upper(trim(unaccent(nome))) like 'ENGENHO VELHO'; 
update cidade set cod_tom = '8419' where uf = 23 and upper(trim(unaccent(nome))) like 'ENTRE IJUIS'; 
update cidade set cod_tom = '8421' where uf = 23 and upper(trim(unaccent(nome))) like 'ENTRE RIOS DO SUL'; 
update cidade set cod_tom = '8417' where uf = 23 and upper(trim(unaccent(nome))) like 'EREBANGO'; 
update cidade set cod_tom = '8637' where uf = 23 and upper(trim(unaccent(nome))) like 'ERECHIM'; 
update cidade set cod_tom = '8415' where uf = 23 and upper(trim(unaccent(nome))) like 'ERNESTINA'; 
update cidade set cod_tom = '8641' where uf = 23 and upper(trim(unaccent(nome))) like 'ERVAL GRANDE'; 
update cidade set cod_tom = '8643' where uf = 23 and upper(trim(unaccent(nome))) like 'ERVAL SECO'; 
update cidade set cod_tom = '8645' where uf = 23 and upper(trim(unaccent(nome))) like 'ESMERALDA'; 
update cidade set cod_tom = '0980' where uf = 23 and upper(trim(unaccent(nome))) like 'ESPERANCA DO SUL'; 
update cidade set cod_tom = '8647' where uf = 23 and upper(trim(unaccent(nome))) like 'ESPUMOSO'; 
update cidade set cod_tom = '7301' where uf = 23 and upper(trim(unaccent(nome))) like 'ESTACAO'; 
update cidade set cod_tom = '8649' where uf = 23 and upper(trim(unaccent(nome))) like 'ESTANCIA VELHA'; 
update cidade set cod_tom = '8651' where uf = 23 and upper(trim(unaccent(nome))) like 'ESTEIO'; 
update cidade set cod_tom = '8653' where uf = 23 and upper(trim(unaccent(nome))) like 'ESTRELA'; 
update cidade set cod_tom = '0982' where uf = 23 and upper(trim(unaccent(nome))) like 'ESTRELA VELHA'; 
update cidade set cod_tom = '8413' where uf = 23 and upper(trim(unaccent(nome))) like 'EUGENIO DE CASTRO'; 
update cidade set cod_tom = '8411' where uf = 23 and upper(trim(unaccent(nome))) like 'FAGUNDES VARELA'; 
update cidade set cod_tom = '8655' where uf = 23 and upper(trim(unaccent(nome))) like 'FARROUPILHA'; 
update cidade set cod_tom = '8657' where uf = 23 and upper(trim(unaccent(nome))) like 'FAXINAL DO SOTURNO'; 
update cidade set cod_tom = '8409' where uf = 23 and upper(trim(unaccent(nome))) like 'FAXINALZINHO'; 
update cidade set cod_tom = '0984' where uf = 23 and upper(trim(unaccent(nome))) like 'FAZENDA VILANOVA'; 
update cidade set cod_tom = '8659' where uf = 23 and upper(trim(unaccent(nome))) like 'FELIZ'; 
update cidade set cod_tom = '8661' where uf = 23 and upper(trim(unaccent(nome))) like 'FLORES DA CUNHA'; 
update cidade set cod_tom = '0986' where uf = 23 and upper(trim(unaccent(nome))) like 'FLORIANO PEIXOTO'; 
update cidade set cod_tom = '8663' where uf = 23 and upper(trim(unaccent(nome))) like 'FONTOURA XAVIER'; 
update cidade set cod_tom = '8665' where uf = 23 and upper(trim(unaccent(nome))) like 'FORMIGUEIRO'; 
update cidade set cod_tom = '1142' where uf = 23 and upper(trim(unaccent(nome))) like 'FORQUETINHA'; 
update cidade set cod_tom = '9827' where uf = 23 and upper(trim(unaccent(nome))) like 'FORTALEZA DOS VALOS'; 
update cidade set cod_tom = '8667' where uf = 23 and upper(trim(unaccent(nome))) like 'FREDERICO WESTPHALEN'; 
update cidade set cod_tom = '8669' where uf = 23 and upper(trim(unaccent(nome))) like 'GARIBALDI'; 
update cidade set cod_tom = '6081' where uf = 23 and upper(trim(unaccent(nome))) like 'GARRUCHOS'; 
update cidade set cod_tom = '8671' where uf = 23 and upper(trim(unaccent(nome))) like 'GAURAMA'; 
update cidade set cod_tom = '8673' where uf = 23 and upper(trim(unaccent(nome))) like 'GENERAL CAMARA'; 
update cidade set cod_tom = '5799' where uf = 23 and upper(trim(unaccent(nome))) like 'GENTIL'; 
update cidade set cod_tom = '8677' where uf = 23 and upper(trim(unaccent(nome))) like 'GETULIO VARGAS'; 
update cidade set cod_tom = '8679' where uf = 23 and upper(trim(unaccent(nome))) like 'GIRUA'; 
update cidade set cod_tom = '8407' where uf = 23 and upper(trim(unaccent(nome))) like 'GLORINHA'; 
update cidade set cod_tom = '8681' where uf = 23 and upper(trim(unaccent(nome))) like 'GRAMADO'; 
update cidade set cod_tom = '5949' where uf = 23 and upper(trim(unaccent(nome))) like 'GRAMADO DOS LOUREIROS'; 
update cidade set cod_tom = '5763' where uf = 23 and upper(trim(unaccent(nome))) like 'GRAMADO XAVIER'; 
update cidade set cod_tom = '8683' where uf = 23 and upper(trim(unaccent(nome))) like 'GRAVATAI'; 
update cidade set cod_tom = '8405' where uf = 23 and upper(trim(unaccent(nome))) like 'GUABIJU'; 
update cidade set cod_tom = '8685' where uf = 23 and upper(trim(unaccent(nome))) like 'GUAIBA'; 
update cidade set cod_tom = '8687' where uf = 23 and upper(trim(unaccent(nome))) like 'GUAPORE'; 
update cidade set cod_tom = '8689' where uf = 23 and upper(trim(unaccent(nome))) like 'GUARANI DAS MISSOES'; 
update cidade set cod_tom = '8403' where uf = 23 and upper(trim(unaccent(nome))) like 'HARMONIA'; 
update cidade set cod_tom = '8639' where uf = 23 and upper(trim(unaccent(nome))) like 'HERVAL'; 
update cidade set cod_tom = '0988' where uf = 23 and upper(trim(unaccent(nome))) like 'HERVEIRAS'; 
update cidade set cod_tom = '8691' where uf = 23 and upper(trim(unaccent(nome))) like 'HORIZONTINA'; 
update cidade set cod_tom = '6085' where uf = 23 and upper(trim(unaccent(nome))) like 'HULHA NEGRA'; 
update cidade set cod_tom = '8695' where uf = 23 and upper(trim(unaccent(nome))) like 'HUMAITA'; 
update cidade set cod_tom = '8401' where uf = 23 and upper(trim(unaccent(nome))) like 'IBARAMA'; 
update cidade set cod_tom = '8697' where uf = 23 and upper(trim(unaccent(nome))) like 'IBIACA'; 
update cidade set cod_tom = '8699' where uf = 23 and upper(trim(unaccent(nome))) like 'IBIRAIARAS'; 
update cidade set cod_tom = '7299' where uf = 23 and upper(trim(unaccent(nome))) like 'IBIRAPUITA'; 
update cidade set cod_tom = '8701' where uf = 23 and upper(trim(unaccent(nome))) like 'IBIRUBA'; 
update cidade set cod_tom = '8703' where uf = 23 and upper(trim(unaccent(nome))) like 'IGREJINHA'; 
update cidade set cod_tom = '8705' where uf = 23 and upper(trim(unaccent(nome))) like 'IJUI'; 
update cidade set cod_tom = '8707' where uf = 23 and upper(trim(unaccent(nome))) like 'ILOPOLIS'; 
update cidade set cod_tom = '7297' where uf = 23 and upper(trim(unaccent(nome))) like 'IMBE'; 
update cidade set cod_tom = '7295' where uf = 23 and upper(trim(unaccent(nome))) like 'IMIGRANTE'; 
update cidade set cod_tom = '8709' where uf = 23 and upper(trim(unaccent(nome))) like 'INDEPENDENCIA'; 
update cidade set cod_tom = '6051' where uf = 23 and upper(trim(unaccent(nome))) like 'INHACORA'; 
update cidade set cod_tom = '8399' where uf = 23 and upper(trim(unaccent(nome))) like 'IPE'; 
update cidade set cod_tom = '7399' where uf = 23 and upper(trim(unaccent(nome))) like 'IPIRANGA DO SUL'; 
update cidade set cod_tom = '8711' where uf = 23 and upper(trim(unaccent(nome))) like 'IRAI'; 
update cidade set cod_tom = '0990' where uf = 23 and upper(trim(unaccent(nome))) like 'ITAARA'; 
update cidade set cod_tom = '7397' where uf = 23 and upper(trim(unaccent(nome))) like 'ITACURUBI'; 
update cidade set cod_tom = '6027' where uf = 23 and upper(trim(unaccent(nome))) like 'ITAPUCA'; 
update cidade set cod_tom = '8713' where uf = 23 and upper(trim(unaccent(nome))) like 'ITAQUI'; 
update cidade set cod_tom = '1144' where uf = 23 and upper(trim(unaccent(nome))) like 'ITATI'; 
update cidade set cod_tom = '8715' where uf = 23 and upper(trim(unaccent(nome))) like 'ITATIBA DO SUL'; 
update cidade set cod_tom = '7395' where uf = 23 and upper(trim(unaccent(nome))) like 'IVORA'; 
update cidade set cod_tom = '8717' where uf = 23 and upper(trim(unaccent(nome))) like 'IVOTI'; 
update cidade set cod_tom = '7393' where uf = 23 and upper(trim(unaccent(nome))) like 'JABOTICABA'; 
update cidade set cod_tom = '1146' where uf = 23 and upper(trim(unaccent(nome))) like 'JACUIZINHO'; 
update cidade set cod_tom = '8719' where uf = 23 and upper(trim(unaccent(nome))) like 'JACUTINGA'; 
update cidade set cod_tom = '8721' where uf = 23 and upper(trim(unaccent(nome))) like 'JAGUARAO'; 
update cidade set cod_tom = '8723' where uf = 23 and upper(trim(unaccent(nome))) like 'JAGUARI'; 
update cidade set cod_tom = '7391' where uf = 23 and upper(trim(unaccent(nome))) like 'JAQUIRANA'; 
update cidade set cod_tom = '0992' where uf = 23 and upper(trim(unaccent(nome))) like 'JARI'; 
update cidade set cod_tom = '9829' where uf = 23 and upper(trim(unaccent(nome))) like 'JOIA'; 
update cidade set cod_tom = '8725' where uf = 23 and upper(trim(unaccent(nome))) like 'JULIO DE CASTILHOS'; 
update cidade set cod_tom = '1148' where uf = 23 and upper(trim(unaccent(nome))) like 'LAGOA BONITA DO SUL'; 
update cidade set cod_tom = '5951' where uf = 23 and upper(trim(unaccent(nome))) like 'LAGOA DOS TRES CANTOS'; 
update cidade set cod_tom = '8727' where uf = 23 and upper(trim(unaccent(nome))) like 'LAGOA VERMELHA'; 
update cidade set cod_tom = '7389' where uf = 23 and upper(trim(unaccent(nome))) like 'LAGOAO'; 
update cidade set cod_tom = '8729' where uf = 23 and upper(trim(unaccent(nome))) like 'LAJEADO'; 
update cidade set cod_tom = '5983' where uf = 23 and upper(trim(unaccent(nome))) like 'LAJEADO DO BUGRE'; 
update cidade set cod_tom = '8731' where uf = 23 and upper(trim(unaccent(nome))) like 'LAVRAS DO SUL'; 
update cidade set cod_tom = '8733' where uf = 23 and upper(trim(unaccent(nome))) like 'LIBERATO SALZANO'; 
update cidade set cod_tom = '6017' where uf = 23 and upper(trim(unaccent(nome))) like 'LINDOLFO COLLOR'; 
update cidade set cod_tom = '6047' where uf = 23 and upper(trim(unaccent(nome))) like 'LINHA NOVA'; 
update cidade set cod_tom = '0994' where uf = 23 and upper(trim(unaccent(nome))) like 'MACAMBARA'; 
update cidade set cod_tom = '8735' where uf = 23 and upper(trim(unaccent(nome))) like 'MACHADINHO'; 
update cidade set cod_tom = '0996' where uf = 23 and upper(trim(unaccent(nome))) like 'MAMPITUBA'; 
update cidade set cod_tom = '6079' where uf = 23 and upper(trim(unaccent(nome))) like 'MANOEL VIANA'; 
update cidade set cod_tom = '5783' where uf = 23 and upper(trim(unaccent(nome))) like 'MAQUINE'; 
update cidade set cod_tom = '6039' where uf = 23 and upper(trim(unaccent(nome))) like 'MARATA'; 
update cidade set cod_tom = '8737' where uf = 23 and upper(trim(unaccent(nome))) like 'MARAU'; 
update cidade set cod_tom = '8739' where uf = 23 and upper(trim(unaccent(nome))) like 'MARCELINO RAMOS'; 
update cidade set cod_tom = '5759' where uf = 23 and upper(trim(unaccent(nome))) like 'MARIANA PIMENTEL'; 
update cidade set cod_tom = '8741' where uf = 23 and upper(trim(unaccent(nome))) like 'MARIANO MORO'; 
update cidade set cod_tom = '0998' where uf = 23 and upper(trim(unaccent(nome))) like 'MARQUES DE SOUZA'; 
update cidade set cod_tom = '8743' where uf = 23 and upper(trim(unaccent(nome))) like 'MATA'; 
update cidade set cod_tom = '5931' where uf = 23 and upper(trim(unaccent(nome))) like 'MATO CASTELHANO'; 
update cidade set cod_tom = '6031' where uf = 23 and upper(trim(unaccent(nome))) like 'MATO LEITAO'; 
update cidade set cod_tom = '1150' where uf = 23 and upper(trim(unaccent(nome))) like 'MATO QUEIMADO'; 
update cidade set cod_tom = '8745' where uf = 23 and upper(trim(unaccent(nome))) like 'MAXIMILIANO DE ALMEIDA'; 
update cidade set cod_tom = '5773' where uf = 23 and upper(trim(unaccent(nome))) like 'MINAS DO LEAO'; 
update cidade set cod_tom = '8747' where uf = 23 and upper(trim(unaccent(nome))) like 'MIRAGUAI'; 
update cidade set cod_tom = '7387' where uf = 23 and upper(trim(unaccent(nome))) like 'MONTAURI'; 
update cidade set cod_tom = '1000' where uf = 23 and upper(trim(unaccent(nome))) like 'MONTE ALEGRE DOS CAMPOS'; 
update cidade set cod_tom = '5993' where uf = 23 and upper(trim(unaccent(nome))) like 'MONTE BELO DO SUL'; 
update cidade set cod_tom = '8749' where uf = 23 and upper(trim(unaccent(nome))) like 'MONTENEGRO'; 
update cidade set cod_tom = '5933' where uf = 23 and upper(trim(unaccent(nome))) like 'MORMACO'; 
update cidade set cod_tom = '5775' where uf = 23 and upper(trim(unaccent(nome))) like 'MORRINHOS DO SUL'; 
update cidade set cod_tom = '7385' where uf = 23 and upper(trim(unaccent(nome))) like 'MORRO REDONDO'; 
update cidade set cod_tom = '6019' where uf = 23 and upper(trim(unaccent(nome))) like 'MORRO REUTER'; 
update cidade set cod_tom = '8751' where uf = 23 and upper(trim(unaccent(nome))) like 'MOSTARDAS'; 
update cidade set cod_tom = '8753' where uf = 23 and upper(trim(unaccent(nome))) like 'MUCUM'; 
update cidade set cod_tom = '1002' where uf = 23 and upper(trim(unaccent(nome))) like 'MUITOS CAPOES'; 
update cidade set cod_tom = '5935' where uf = 23 and upper(trim(unaccent(nome))) like 'MULITERNO'; 
update cidade set cod_tom = '8755' where uf = 23 and upper(trim(unaccent(nome))) like 'NAO-ME-TOQUE'; 
update cidade set cod_tom = '5937' where uf = 23 and upper(trim(unaccent(nome))) like 'NICOLAU VERGUEIRO'; 
update cidade set cod_tom = '8757' where uf = 23 and upper(trim(unaccent(nome))) like 'NONOAI'; 
update cidade set cod_tom = '7383' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVA ALVORADA'; 
update cidade set cod_tom = '8759' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVA ARACA'; 
update cidade set cod_tom = '8761' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVA BASSANO'; 
update cidade set cod_tom = '5953' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVA BOA VISTA'; 
update cidade set cod_tom = '8763' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVA BRESCIA'; 
update cidade set cod_tom = '1004' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVA CANDELARIA'; 
update cidade set cod_tom = '7381' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVA ESPERANCA DO SUL'; 
update cidade set cod_tom = '7379' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVA HARTZ'; 
update cidade set cod_tom = '5991' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVA PADUA'; 
update cidade set cod_tom = '8765' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVA PALMA'; 
update cidade set cod_tom = '8767' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVA PETROPOLIS'; 
update cidade set cod_tom = '8769' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVA PRATA'; 
update cidade set cod_tom = '1006' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVA RAMADA'; 
update cidade set cod_tom = '7377' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVA ROMA DO SUL'; 
update cidade set cod_tom = '5757' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVA SANTA RITA'; 
update cidade set cod_tom = '5985' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVO BARREIRO'; 
update cidade set cod_tom = '1008' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVO CABRAIS'; 
update cidade set cod_tom = '8771' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVO HAMBURGO'; 
update cidade set cod_tom = '6057' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVO MACHADO'; 
update cidade set cod_tom = '5973' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVO TIRADENTES'; 
update cidade set cod_tom = '1152' where uf = 23 and upper(trim(unaccent(nome))) like 'NOVO XINGU'; 
update cidade set cod_tom = '8773' where uf = 23 and upper(trim(unaccent(nome))) like 'OSORIO'; 
update cidade set cod_tom = '8775' where uf = 23 and upper(trim(unaccent(nome))) like 'PAIM FILHO'; 
update cidade set cod_tom = '8967' where uf = 23 and upper(trim(unaccent(nome))) like 'PALMARES DO SUL'; 
update cidade set cod_tom = '8777' where uf = 23 and upper(trim(unaccent(nome))) like 'PALMEIRA DAS MISSOES'; 
update cidade set cod_tom = '8779' where uf = 23 and upper(trim(unaccent(nome))) like 'PALMITINHO'; 
update cidade set cod_tom = '8781' where uf = 23 and upper(trim(unaccent(nome))) like 'PANAMBI'; 
update cidade set cod_tom = '7375' where uf = 23 and upper(trim(unaccent(nome))) like 'PANTANO GRANDE'; 
update cidade set cod_tom = '8783' where uf = 23 and upper(trim(unaccent(nome))) like 'PARAI'; 
update cidade set cod_tom = '7373' where uf = 23 and upper(trim(unaccent(nome))) like 'PARAISO DO SUL'; 
update cidade set cod_tom = '6041' where uf = 23 and upper(trim(unaccent(nome))) like 'PARECI NOVO'; 
update cidade set cod_tom = '9825' where uf = 23 and upper(trim(unaccent(nome))) like 'PAROBE'; 
update cidade set cod_tom = '1010' where uf = 23 and upper(trim(unaccent(nome))) like 'PASSA SETE'; 
update cidade set cod_tom = '5765' where uf = 23 and upper(trim(unaccent(nome))) like 'PASSO DO SOBRADO'; 
update cidade set cod_tom = '8785' where uf = 23 and upper(trim(unaccent(nome))) like 'PASSO FUNDO'; 
update cidade set cod_tom = '1154' where uf = 23 and upper(trim(unaccent(nome))) like 'PAULO BENTO'; 
update cidade set cod_tom = '7371' where uf = 23 and upper(trim(unaccent(nome))) like 'PAVERAMA'; 
update cidade set cod_tom = '1156' where uf = 23 and upper(trim(unaccent(nome))) like 'PEDRAS ALTAS'; 
update cidade set cod_tom = '8787' where uf = 23 and upper(trim(unaccent(nome))) like 'PEDRO OSORIO'; 
update cidade set cod_tom = '8789' where uf = 23 and upper(trim(unaccent(nome))) like 'PEJUCARA'; 
update cidade set cod_tom = '8791' where uf = 23 and upper(trim(unaccent(nome))) like 'PELOTAS'; 
update cidade set cod_tom = '6021' where uf = 23 and upper(trim(unaccent(nome))) like 'PICADA CAFE'; 
update cidade set cod_tom = '7369' where uf = 23 and upper(trim(unaccent(nome))) like 'PINHAL'; 
update cidade set cod_tom = '1158' where uf = 23 and upper(trim(unaccent(nome))) like 'PINHAL DA SERRA'; 
update cidade set cod_tom = '5787' where uf = 23 and upper(trim(unaccent(nome))) like 'PINHAL GRANDE'; 
update cidade set cod_tom = '5975' where uf = 23 and upper(trim(unaccent(nome))) like 'PINHEIRINHO DO VALE'; 
update cidade set cod_tom = '8793' where uf = 23 and upper(trim(unaccent(nome))) like 'PINHEIRO MACHADO'; 
update cidade set cod_tom = '1160' where uf = 23 and upper(trim(unaccent(nome))) like 'PINTO BANDEIRA'; 
update cidade set cod_tom = '7367' where uf = 23 and upper(trim(unaccent(nome))) like 'PIRAPO'; 
update cidade set cod_tom = '8795' where uf = 23 and upper(trim(unaccent(nome))) like 'PIRATINI'; 
update cidade set cod_tom = '8797' where uf = 23 and upper(trim(unaccent(nome))) like 'PLANALTO'; 
update cidade set cod_tom = '7365' where uf = 23 and upper(trim(unaccent(nome))) like 'POCO DAS ANTAS'; 
update cidade set cod_tom = '5939' where uf = 23 and upper(trim(unaccent(nome))) like 'PONTAO'; 
update cidade set cod_tom = '5967' where uf = 23 and upper(trim(unaccent(nome))) like 'PONTE PRETA'; 
update cidade set cod_tom = '8799' where uf = 23 and upper(trim(unaccent(nome))) like 'PORTAO'; 
update cidade set cod_tom = '8801' where uf = 23 and upper(trim(unaccent(nome))) like 'PORTO ALEGRE'; 
update cidade set cod_tom = '8803' where uf = 23 and upper(trim(unaccent(nome))) like 'PORTO LUCENA'; 
update cidade set cod_tom = '6065' where uf = 23 and upper(trim(unaccent(nome))) like 'PORTO MAUA'; 
update cidade set cod_tom = '6067' where uf = 23 and upper(trim(unaccent(nome))) like 'PORTO VERA CRUZ'; 
update cidade set cod_tom = '8805' where uf = 23 and upper(trim(unaccent(nome))) like 'PORTO XAVIER'; 
update cidade set cod_tom = '7363' where uf = 23 and upper(trim(unaccent(nome))) like 'POUSO NOVO'; 
update cidade set cod_tom = '6023' where uf = 23 and upper(trim(unaccent(nome))) like 'PRESIDENTE LUCENA'; 
update cidade set cod_tom = '7361' where uf = 23 and upper(trim(unaccent(nome))) like 'PROGRESSO'; 
update cidade set cod_tom = '7359' where uf = 23 and upper(trim(unaccent(nome))) like 'PROTASIO ALVES'; 
update cidade set cod_tom = '8807' where uf = 23 and upper(trim(unaccent(nome))) like 'PUTINGA'; 
update cidade set cod_tom = '8809' where uf = 23 and upper(trim(unaccent(nome))) like 'QUARAI'; 
update cidade set cod_tom = '1162' where uf = 23 and upper(trim(unaccent(nome))) like 'QUATRO IRMAOS'; 
update cidade set cod_tom = '5789' where uf = 23 and upper(trim(unaccent(nome))) like 'QUEVEDOS'; 
update cidade set cod_tom = '7357' where uf = 23 and upper(trim(unaccent(nome))) like 'QUINZE DE NOVEMBRO'; 
update cidade set cod_tom = '8811' where uf = 23 and upper(trim(unaccent(nome))) like 'REDENTORA'; 
update cidade set cod_tom = '7355' where uf = 23 and upper(trim(unaccent(nome))) like 'RELVADO'; 
update cidade set cod_tom = '8813' where uf = 23 and upper(trim(unaccent(nome))) like 'RESTINGA SECA'; 
update cidade set cod_tom = '5955' where uf = 23 and upper(trim(unaccent(nome))) like 'RIO DOS INDIOS'; 
update cidade set cod_tom = '8815' where uf = 23 and upper(trim(unaccent(nome))) like 'RIO GRANDE'; 
update cidade set cod_tom = '8817' where uf = 23 and upper(trim(unaccent(nome))) like 'RIO PARDO'; 
update cidade set cod_tom = '7353' where uf = 23 and upper(trim(unaccent(nome))) like 'RIOZINHO'; 
update cidade set cod_tom = '8819' where uf = 23 and upper(trim(unaccent(nome))) like 'ROCA SALES'; 
update cidade set cod_tom = '8821' where uf = 23 and upper(trim(unaccent(nome))) like 'RODEIO BONITO'; 
update cidade set cod_tom = '1164' where uf = 23 and upper(trim(unaccent(nome))) like 'ROLADOR'; 
update cidade set cod_tom = '8823' where uf = 23 and upper(trim(unaccent(nome))) like 'ROLANTE'; 
update cidade set cod_tom = '8825' where uf = 23 and upper(trim(unaccent(nome))) like 'RONDA ALTA'; 
update cidade set cod_tom = '8827' where uf = 23 and upper(trim(unaccent(nome))) like 'RONDINHA'; 
update cidade set cod_tom = '8829' where uf = 23 and upper(trim(unaccent(nome))) like 'ROQUE GONZALES'; 
update cidade set cod_tom = '8831' where uf = 23 and upper(trim(unaccent(nome))) like 'ROSARIO DO SUL'; 
update cidade set cod_tom = '5987' where uf = 23 and upper(trim(unaccent(nome))) like 'SAGRADA FAMILIA'; 
update cidade set cod_tom = '7339' where uf = 23 and upper(trim(unaccent(nome))) like 'SALDANHA MARINHO'; 
update cidade set cod_tom = '8975' where uf = 23 and upper(trim(unaccent(nome))) like 'SALTO DO JACUI'; 
update cidade set cod_tom = '6061' where uf = 23 and upper(trim(unaccent(nome))) like 'SALVADOR DAS MISSOES'; 
update cidade set cod_tom = '8833' where uf = 23 and upper(trim(unaccent(nome))) like 'SALVADOR DO SUL'; 
update cidade set cod_tom = '8835' where uf = 23 and upper(trim(unaccent(nome))) like 'SANANDUVA'; 
update cidade set cod_tom = '8837' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTA BARBARA DO SUL'; 
update cidade set cod_tom = '1166' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTA CECILIA DO SUL'; 
update cidade set cod_tom = '6033' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTA CLARA DO SUL'; 
update cidade set cod_tom = '8839' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTA CRUZ DO SUL'; 
update cidade set cod_tom = '1168' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTA MARGARIDA DO SUL'; 
update cidade set cod_tom = '8841' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTA MARIA'; 
update cidade set cod_tom = '7337' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTA MARIA DO HERVAL'; 
update cidade set cod_tom = '8847' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTA ROSA'; 
update cidade set cod_tom = '5995' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTA TEREZA'; 
update cidade set cod_tom = '8849' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTA VITORIA DO PALMAR'; 
update cidade set cod_tom = '8843' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTANA DA BOA VISTA'; 
update cidade set cod_tom = '8845' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTANA DO LIVRAMENTO'; 
update cidade set cod_tom = '8851' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTIAGO'; 
update cidade set cod_tom = '8853' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTO ANGELO'; 
update cidade set cod_tom = '8855' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DA PATRULHA'; 
update cidade set cod_tom = '8857' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DAS MISSOES'; 
update cidade set cod_tom = '5941' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO PALMA'; 
update cidade set cod_tom = '5957' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO PLANALTO'; 
update cidade set cod_tom = '8859' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTO AUGUSTO'; 
update cidade set cod_tom = '8861' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTO CRISTO'; 
update cidade set cod_tom = '5977' where uf = 23 and upper(trim(unaccent(nome))) like 'SANTO EXPEDITO DO SUL'; 
update cidade set cod_tom = '8863' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO BORJA'; 
update cidade set cod_tom = '7351' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO DOMINGOS DO SUL'; 
update cidade set cod_tom = '8865' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO DE ASSIS'; 
update cidade set cod_tom = '8867' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO DE PAULA'; 
update cidade set cod_tom = '8869' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO GABRIEL'; 
update cidade set cod_tom = '8871' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO JERONIMO'; 
update cidade set cod_tom = '7349' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO JOAO DA URTIGA'; 
update cidade set cod_tom = '5791' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO JOAO DO POLESINE'; 
update cidade set cod_tom = '7347' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO JORGE'; 
update cidade set cod_tom = '5989' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO JOSE DAS MISSOES'; 
update cidade set cod_tom = '7345' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO JOSE DO HERVAL'; 
update cidade set cod_tom = '7343' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO JOSE DO HORTENCIO'; 
update cidade set cod_tom = '6059' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO JOSE DO INHACORA'; 
update cidade set cod_tom = '8873' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO JOSE DO NORTE'; 
update cidade set cod_tom = '8875' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO JOSE DO OURO'; 
update cidade set cod_tom = '1170' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO JOSE DO SUL'; 
update cidade set cod_tom = '6015' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO JOSE DOS AUSENTES'; 
update cidade set cod_tom = '8877' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO LEOPOLDO'; 
update cidade set cod_tom = '8879' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO LOURENCO DO SUL'; 
update cidade set cod_tom = '8881' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO LUIZ GONZAGA'; 
update cidade set cod_tom = '8883' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO MARCOS'; 
update cidade set cod_tom = '8885' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO MARTINHO'; 
update cidade set cod_tom = '5793' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO MARTINHO DA SERRA'; 
update cidade set cod_tom = '7341' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO MIGUEL DAS MISSOES'; 
update cidade set cod_tom = '8887' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO NICOLAU'; 
update cidade set cod_tom = '8889' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO PAULO DAS MISSOES'; 
update cidade set cod_tom = '6043' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO PEDRO DA SERRA'; 
update cidade set cod_tom = '1172' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO PEDRO DAS MISSOES'; 
update cidade set cod_tom = '6063' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO PEDRO DO BUTIA'; 
update cidade set cod_tom = '8891' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO PEDRO DO SUL'; 
update cidade set cod_tom = '8893' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO DO CAI'; 
update cidade set cod_tom = '8895' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO SEPE'; 
update cidade set cod_tom = '8897' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO VALENTIM'; 
update cidade set cod_tom = '5997' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO VALENTIM DO SUL'; 
update cidade set cod_tom = '6075' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO VALERIO DO SUL'; 
update cidade set cod_tom = '7293' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO VENDELINO'; 
update cidade set cod_tom = '8675' where uf = 23 and upper(trim(unaccent(nome))) like 'SAO VICENTE DO SUL'; 
update cidade set cod_tom = '8899' where uf = 23 and upper(trim(unaccent(nome))) like 'SAPIRANGA'; 
update cidade set cod_tom = '8901' where uf = 23 and upper(trim(unaccent(nome))) like 'SAPUCAIA DO SUL'; 
update cidade set cod_tom = '8903' where uf = 23 and upper(trim(unaccent(nome))) like 'SARANDI'; 
update cidade set cod_tom = '8905' where uf = 23 and upper(trim(unaccent(nome))) like 'SEBERI'; 
update cidade set cod_tom = '7335' where uf = 23 and upper(trim(unaccent(nome))) like 'SEDE NOVA'; 
update cidade set cod_tom = '7317' where uf = 23 and upper(trim(unaccent(nome))) like 'SEGREDO'; 
update cidade set cod_tom = '8907' where uf = 23 and upper(trim(unaccent(nome))) like 'SELBACH'; 
update cidade set cod_tom = '1012' where uf = 23 and upper(trim(unaccent(nome))) like 'SENADOR SALGADO FILHO'; 
update cidade set cod_tom = '5781' where uf = 23 and upper(trim(unaccent(nome))) like 'SENTINELA DO SUL'; 
update cidade set cod_tom = '8909' where uf = 23 and upper(trim(unaccent(nome))) like 'SERAFINA CORREA'; 
update cidade set cod_tom = '6035' where uf = 23 and upper(trim(unaccent(nome))) like 'SERIO'; 
update cidade set cod_tom = '8911' where uf = 23 and upper(trim(unaccent(nome))) like 'SERTAO'; 
update cidade set cod_tom = '5761' where uf = 23 and upper(trim(unaccent(nome))) like 'SERTAO SANTANA'; 
update cidade set cod_tom = '1014' where uf = 23 and upper(trim(unaccent(nome))) like 'SETE DE SETEMBRO'; 
update cidade set cod_tom = '8913' where uf = 23 and upper(trim(unaccent(nome))) like 'SEVERIANO DE ALMEIDA'; 
update cidade set cod_tom = '7315' where uf = 23 and upper(trim(unaccent(nome))) like 'SILVEIRA MARTINS'; 
update cidade set cod_tom = '5767' where uf = 23 and upper(trim(unaccent(nome))) like 'SINIMBU'; 
update cidade set cod_tom = '8917' where uf = 23 and upper(trim(unaccent(nome))) like 'SOBRADINHO'; 
update cidade set cod_tom = '8919' where uf = 23 and upper(trim(unaccent(nome))) like 'SOLEDADE'; 
update cidade set cod_tom = '1016' where uf = 23 and upper(trim(unaccent(nome))) like 'TABAI'; 
update cidade set cod_tom = '8921' where uf = 23 and upper(trim(unaccent(nome))) like 'TAPEJARA'; 
update cidade set cod_tom = '8923' where uf = 23 and upper(trim(unaccent(nome))) like 'TAPERA'; 
update cidade set cod_tom = '8925' where uf = 23 and upper(trim(unaccent(nome))) like 'TAPES'; 
update cidade set cod_tom = '8927' where uf = 23 and upper(trim(unaccent(nome))) like 'TAQUARA'; 
update cidade set cod_tom = '8929' where uf = 23 and upper(trim(unaccent(nome))) like 'TAQUARI'; 
update cidade set cod_tom = '7313' where uf = 23 and upper(trim(unaccent(nome))) like 'TAQUARUCU DO SUL'; 
update cidade set cod_tom = '8971' where uf = 23 and upper(trim(unaccent(nome))) like 'TAVARES'; 
update cidade set cod_tom = '0' where uf = 23 and upper(trim(unaccent(nome))) like 'TEINAS'; 
update cidade set cod_tom = '8931' where uf = 23 and upper(trim(unaccent(nome))) like 'TENENTE PORTELA'; 
update cidade set cod_tom = '7333' where uf = 23 and upper(trim(unaccent(nome))) like 'TERRA DE AREIA'; 
update cidade set cod_tom = '9821' where uf = 23 and upper(trim(unaccent(nome))) like 'TEUTONIA'; 
update cidade set cod_tom = '1174' where uf = 23 and upper(trim(unaccent(nome))) like 'TIO HUGO'; 
update cidade set cod_tom = '6077' where uf = 23 and upper(trim(unaccent(nome))) like 'TIRADENTES DO SUL'; 
update cidade set cod_tom = '1018' where uf = 23 and upper(trim(unaccent(nome))) like 'TOROPI'; 
update cidade set cod_tom = '8933' where uf = 23 and upper(trim(unaccent(nome))) like 'TORRES'; 
update cidade set cod_tom = '8935' where uf = 23 and upper(trim(unaccent(nome))) like 'TRAMANDAI'; 
update cidade set cod_tom = '6037' where uf = 23 and upper(trim(unaccent(nome))) like 'TRAVESSEIRO'; 
update cidade set cod_tom = '7331' where uf = 23 and upper(trim(unaccent(nome))) like 'TRES ARROIOS'; 
update cidade set cod_tom = '7329' where uf = 23 and upper(trim(unaccent(nome))) like 'TRES CACHOEIRAS'; 
update cidade set cod_tom = '8937' where uf = 23 and upper(trim(unaccent(nome))) like 'TRES COROAS'; 
update cidade set cod_tom = '8939' where uf = 23 and upper(trim(unaccent(nome))) like 'TRES DE MAIO'; 
update cidade set cod_tom = '5777' where uf = 23 and upper(trim(unaccent(nome))) like 'TRES FORQUILHAS'; 
update cidade set cod_tom = '7327' where uf = 23 and upper(trim(unaccent(nome))) like 'TRES PALMEIRAS'; 
update cidade set cod_tom = '8941' where uf = 23 and upper(trim(unaccent(nome))) like 'TRES PASSOS'; 
update cidade set cod_tom = '7325' where uf = 23 and upper(trim(unaccent(nome))) like 'TRINDADE DO SUL'; 
update cidade set cod_tom = '8943' where uf = 23 and upper(trim(unaccent(nome))) like 'TRIUNFO'; 
update cidade set cod_tom = '8945' where uf = 23 and upper(trim(unaccent(nome))) like 'TUCUNDUVA'; 
update cidade set cod_tom = '7323' where uf = 23 and upper(trim(unaccent(nome))) like 'TUNAS'; 
update cidade set cod_tom = '5979' where uf = 23 and upper(trim(unaccent(nome))) like 'TUPANCI DO SUL'; 
update cidade set cod_tom = '8947' where uf = 23 and upper(trim(unaccent(nome))) like 'TUPANCIRETA'; 
update cidade set cod_tom = '7321' where uf = 23 and upper(trim(unaccent(nome))) like 'TUPANDI'; 
update cidade set cod_tom = '8949' where uf = 23 and upper(trim(unaccent(nome))) like 'TUPARENDI'; 
update cidade set cod_tom = '1020' where uf = 23 and upper(trim(unaccent(nome))) like 'TURUCU'; 
update cidade set cod_tom = '1022' where uf = 23 and upper(trim(unaccent(nome))) like 'UBIRETAMA'; 
update cidade set cod_tom = '5999' where uf = 23 and upper(trim(unaccent(nome))) like 'UNIAO DA SERRA'; 
update cidade set cod_tom = '1024' where uf = 23 and upper(trim(unaccent(nome))) like 'UNISTALDA'; 
update cidade set cod_tom = '8951' where uf = 23 and upper(trim(unaccent(nome))) like 'URUGUAIANA'; 
update cidade set cod_tom = '8953' where uf = 23 and upper(trim(unaccent(nome))) like 'VACARIA'; 
update cidade set cod_tom = '5769' where uf = 23 and upper(trim(unaccent(nome))) like 'VALE DO SOL'; 
update cidade set cod_tom = '6049' where uf = 23 and upper(trim(unaccent(nome))) like 'VALE REAL'; 
update cidade set cod_tom = '1026' where uf = 23 and upper(trim(unaccent(nome))) like 'VALE VERDE'; 
update cidade set cod_tom = '7319' where uf = 23 and upper(trim(unaccent(nome))) like 'VANINI'; 
update cidade set cod_tom = '8955' where uf = 23 and upper(trim(unaccent(nome))) like 'VENANCIO AIRES'; 
update cidade set cod_tom = '8957' where uf = 23 and upper(trim(unaccent(nome))) like 'VERA CRUZ'; 
update cidade set cod_tom = '8959' where uf = 23 and upper(trim(unaccent(nome))) like 'VERANOPOLIS'; 
update cidade set cod_tom = '1028' where uf = 23 and upper(trim(unaccent(nome))) like 'VESPASIANO CORREA'; 
update cidade set cod_tom = '8961' where uf = 23 and upper(trim(unaccent(nome))) like 'VIADUTOS'; 
update cidade set cod_tom = '8963' where uf = 23 and upper(trim(unaccent(nome))) like 'VIAMAO'; 
update cidade set cod_tom = '8965' where uf = 23 and upper(trim(unaccent(nome))) like 'VICENTE DUTRA'; 
update cidade set cod_tom = '8969' where uf = 23 and upper(trim(unaccent(nome))) like 'VICTOR GRAEFF'; 
update cidade set cod_tom = '7311' where uf = 23 and upper(trim(unaccent(nome))) like 'VILA FLORES'; 
update cidade set cod_tom = '1030' where uf = 23 and upper(trim(unaccent(nome))) like 'VILA LANGARO'; 
update cidade set cod_tom = '7309' where uf = 23 and upper(trim(unaccent(nome))) like 'VILA MARIA'; 
update cidade set cod_tom = '5795' where uf = 23 and upper(trim(unaccent(nome))) like 'VILA NOVA DO SUL'; 
update cidade set cod_tom = '7307' where uf = 23 and upper(trim(unaccent(nome))) like 'VISTA ALEGRE'; 
update cidade set cod_tom = '7305' where uf = 23 and upper(trim(unaccent(nome))) like 'VISTA ALEGRE DO PRATA'; 
update cidade set cod_tom = '7303' where uf = 23 and upper(trim(unaccent(nome))) like 'VISTA GAUCHA'; 
update cidade set cod_tom = '6053' where uf = 23 and upper(trim(unaccent(nome))) like 'VITORIA DAS MISSOES'; 
update cidade set cod_tom = '1176' where uf = 23 and upper(trim(unaccent(nome))) like 'WESTFALIA'; 
update cidade set cod_tom = '5785' where uf = 23 and upper(trim(unaccent(nome))) like 'XANGRI-LA';