update cidade set cod_tom = '0643' where uf = 1 and upper(trim(unaccent(nome))) like 'ACRELANDIA'; 
update cidade set cod_tom = '0157' where uf = 1 and upper(trim(unaccent(nome))) like 'ASSIS BRASIL'; 
update cidade set cod_tom = '0105' where uf = 1 and upper(trim(unaccent(nome))) like 'BRASILEIA'; 
update cidade set cod_tom = '0645' where uf = 1 and upper(trim(unaccent(nome))) like 'BUJARI'; 
update cidade set cod_tom = '0647' where uf = 1 and upper(trim(unaccent(nome))) like 'CAPIXABA'; 
update cidade set cod_tom = '0107' where uf = 1 and upper(trim(unaccent(nome))) like 'CRUZEIRO DO SUL'; 
update cidade set cod_tom = '0651' where uf = 1 and upper(trim(unaccent(nome))) like 'EPITACIOLANDIA'; 
update cidade set cod_tom = '0113' where uf = 1 and upper(trim(unaccent(nome))) like 'FEIJO'; 
update cidade set cod_tom = '0653' where uf = 1 and upper(trim(unaccent(nome))) like 'JORDAO'; 
update cidade set cod_tom = '0109' where uf = 1 and upper(trim(unaccent(nome))) like 'MANCIO LIMA'; 
update cidade set cod_tom = '0155' where uf = 1 and upper(trim(unaccent(nome))) like 'MANOEL URBANO'; 
update cidade set cod_tom = '0655' where uf = 1 and upper(trim(unaccent(nome))) like 'MARECHAL THAUMATURGO'; 
update cidade set cod_tom = '0151' where uf = 1 and upper(trim(unaccent(nome))) like 'PLACIDO DE CASTRO'; 
update cidade set cod_tom = '0649' where uf = 1 and upper(trim(unaccent(nome))) like 'PORTO ACRE'; 
update cidade set cod_tom = '0657' where uf = 1 and upper(trim(unaccent(nome))) like 'PORTO WALTER'; 
update cidade set cod_tom = '0139' where uf = 1 and upper(trim(unaccent(nome))) like 'RIO BRANCO'; 
update cidade set cod_tom = '0659' where uf = 1 and upper(trim(unaccent(nome))) like 'RODRIGUES ALVES'; 
update cidade set cod_tom = '0661' where uf = 1 and upper(trim(unaccent(nome))) like 'SANTA ROSA DO PURUS'; 
update cidade set cod_tom = '0145' where uf = 1 and upper(trim(unaccent(nome))) like 'SENA MADUREIRA'; 
update cidade set cod_tom = '0153' where uf = 1 and upper(trim(unaccent(nome))) like 'SENADOR GUIOMARD'; 
update cidade set cod_tom = '0147' where uf = 1 and upper(trim(unaccent(nome))) like 'TARAUACA'; 
update cidade set cod_tom = '0149' where uf = 1 and upper(trim(unaccent(nome))) like 'XAPURI'; 
