update cidade set cod_tom = '5801' where uf = 19 and upper(trim(unaccent(nome))) like 'ANGRA DOS REIS'; 
update cidade set cod_tom = '2919' where uf = 19 and upper(trim(unaccent(nome))) like 'APERIBE'; 
update cidade set cod_tom = '5803' where uf = 19 and upper(trim(unaccent(nome))) like 'ARARUAMA'; 
update cidade set cod_tom = '2925' where uf = 19 and upper(trim(unaccent(nome))) like 'AREAL'; 
update cidade set cod_tom = '0770' where uf = 19 and upper(trim(unaccent(nome))) like 'ARMACAO DE BUZIOS'; 
update cidade set cod_tom = '5927' where uf = 19 and upper(trim(unaccent(nome))) like 'ARRAIAL DO CABO'; 
update cidade set cod_tom = '5805' where uf = 19 and upper(trim(unaccent(nome))) like 'BARRA DO PIRAI'; 
update cidade set cod_tom = '5807' where uf = 19 and upper(trim(unaccent(nome))) like 'BARRA MANSA'; 
update cidade set cod_tom = '2909' where uf = 19 and upper(trim(unaccent(nome))) like 'BELFORD ROXO'; 
update cidade set cod_tom = '5809' where uf = 19 and upper(trim(unaccent(nome))) like 'BOM JARDIM'; 
update cidade set cod_tom = '5811' where uf = 19 and upper(trim(unaccent(nome))) like 'BOM JESUS DO ITABAPOANA'; 
update cidade set cod_tom = '5813' where uf = 19 and upper(trim(unaccent(nome))) like 'CABO FRIO'; 
update cidade set cod_tom = '5815' where uf = 19 and upper(trim(unaccent(nome))) like 'CACHOEIRAS DE MACACU'; 
update cidade set cod_tom = '5817' where uf = 19 and upper(trim(unaccent(nome))) like 'CAMBUCI'; 
update cidade set cod_tom = '5819' where uf = 19 and upper(trim(unaccent(nome))) like 'CAMPOS DOS GOYTACAZES'; 
update cidade set cod_tom = '5821' where uf = 19 and upper(trim(unaccent(nome))) like 'CANTAGALO'; 
update cidade set cod_tom = '0772' where uf = 19 and upper(trim(unaccent(nome))) like 'CARAPEBUS'; 
update cidade set cod_tom = '2915' where uf = 19 and upper(trim(unaccent(nome))) like 'CARDOSO MOREIRA'; 
update cidade set cod_tom = '5823' where uf = 19 and upper(trim(unaccent(nome))) like 'CARMO'; 
update cidade set cod_tom = '5825' where uf = 19 and upper(trim(unaccent(nome))) like 'CASIMIRO DE ABREU'; 
update cidade set cod_tom = '2927' where uf = 19 and upper(trim(unaccent(nome))) like 'COMENDADOR LEVY GASPARIAN'; 
update cidade set cod_tom = '5827' where uf = 19 and upper(trim(unaccent(nome))) like 'CONCEICAO DE MACABU'; 
update cidade set cod_tom = '5829' where uf = 19 and upper(trim(unaccent(nome))) like 'CORDEIRO'; 
update cidade set cod_tom = '5831' where uf = 19 and upper(trim(unaccent(nome))) like 'DUAS BARRAS'; 
update cidade set cod_tom = '5833' where uf = 19 and upper(trim(unaccent(nome))) like 'DUQUE DE CAXIAS'; 
update cidade set cod_tom = '5835' where uf = 19 and upper(trim(unaccent(nome))) like 'ENGENHEIRO PAULO DE FRONTIN'; 
update cidade set cod_tom = '2907' where uf = 19 and upper(trim(unaccent(nome))) like 'GUAPIMIRIM'; 
update cidade set cod_tom = '0774' where uf = 19 and upper(trim(unaccent(nome))) like 'IGUABA GRANDE'; 
update cidade set cod_tom = '5837' where uf = 19 and upper(trim(unaccent(nome))) like 'ITABORAI'; 
update cidade set cod_tom = '5839' where uf = 19 and upper(trim(unaccent(nome))) like 'ITAGUAI'; 
update cidade set cod_tom = '5929' where uf = 19 and upper(trim(unaccent(nome))) like 'ITALVA'; 
update cidade set cod_tom = '5841' where uf = 19 and upper(trim(unaccent(nome))) like 'ITAOCARA'; 
update cidade set cod_tom = '5843' where uf = 19 and upper(trim(unaccent(nome))) like 'ITAPERUNA'; 
update cidade set cod_tom = '6003' where uf = 19 and upper(trim(unaccent(nome))) like 'ITATIAIA'; 
update cidade set cod_tom = '2913' where uf = 19 and upper(trim(unaccent(nome))) like 'JAPERI'; 
update cidade set cod_tom = '5845' where uf = 19 and upper(trim(unaccent(nome))) like 'LAJE DO MURIAE'; 
update cidade set cod_tom = '5847' where uf = 19 and upper(trim(unaccent(nome))) like 'MACAE'; 
update cidade set cod_tom = '0776' where uf = 19 and upper(trim(unaccent(nome))) like 'MACUCO'; 
update cidade set cod_tom = '5849' where uf = 19 and upper(trim(unaccent(nome))) like 'MAGE'; 
update cidade set cod_tom = '5851' where uf = 19 and upper(trim(unaccent(nome))) like 'MANGARATIBA'; 
update cidade set cod_tom = '5853' where uf = 19 and upper(trim(unaccent(nome))) like 'MARICA'; 
update cidade set cod_tom = '5855' where uf = 19 and upper(trim(unaccent(nome))) like 'MENDES'; 
update cidade set cod_tom = '1116' where uf = 19 and upper(trim(unaccent(nome))) like 'MESQUITA'; 
update cidade set cod_tom = '5857' where uf = 19 and upper(trim(unaccent(nome))) like 'MIGUEL PEREIRA'; 
update cidade set cod_tom = '5859' where uf = 19 and upper(trim(unaccent(nome))) like 'MIRACEMA'; 
update cidade set cod_tom = '5861' where uf = 19 and upper(trim(unaccent(nome))) like 'NATIVIDADE'; 
update cidade set cod_tom = '5863' where uf = 19 and upper(trim(unaccent(nome))) like 'NILOPOLIS'; 
update cidade set cod_tom = '5865' where uf = 19 and upper(trim(unaccent(nome))) like 'NITEROI'; 
update cidade set cod_tom = '5867' where uf = 19 and upper(trim(unaccent(nome))) like 'NOVA FRIBURGO'; 
update cidade set cod_tom = '5869' where uf = 19 and upper(trim(unaccent(nome))) like 'NOVA IGUACU'; 
update cidade set cod_tom = '5871' where uf = 19 and upper(trim(unaccent(nome))) like 'PARACAMBI'; 
update cidade set cod_tom = '5873' where uf = 19 and upper(trim(unaccent(nome))) like 'PARAIBA DO SUL'; 
update cidade set cod_tom = '5875' where uf = 19 and upper(trim(unaccent(nome))) like 'PARATI'; 
update cidade set cod_tom = '6005' where uf = 19 and upper(trim(unaccent(nome))) like 'PATY DO ALFERES'; 
update cidade set cod_tom = '0' where uf = 19 and upper(trim(unaccent(nome))) like 'PELINCA'; 
update cidade set cod_tom = '5877' where uf = 19 and upper(trim(unaccent(nome))) like 'PETROPOLIS'; 
update cidade set cod_tom = '0778' where uf = 19 and upper(trim(unaccent(nome))) like 'PINHEIRAL'; 
update cidade set cod_tom = '0778' where uf = 19 and upper(trim(unaccent(nome))) like 'PINHEIRAL'; 
update cidade set cod_tom = '5879' where uf = 19 and upper(trim(unaccent(nome))) like 'PIRAI'; 
update cidade set cod_tom = '5881' where uf = 19 and upper(trim(unaccent(nome))) like 'PORCIUNCULA'; 
update cidade set cod_tom = '0780' where uf = 19 and upper(trim(unaccent(nome))) like 'PORTO REAL'; 
update cidade set cod_tom = '2923' where uf = 19 and upper(trim(unaccent(nome))) like 'QUATIS'; 
update cidade set cod_tom = '2911' where uf = 19 and upper(trim(unaccent(nome))) like 'QUEIMADOS'; 
update cidade set cod_tom = '6007' where uf = 19 and upper(trim(unaccent(nome))) like 'QUISSAMA'; 
update cidade set cod_tom = '5883' where uf = 19 and upper(trim(unaccent(nome))) like 'RESENDE'; 
update cidade set cod_tom = '5885' where uf = 19 and upper(trim(unaccent(nome))) like 'RIO BONITO'; 
update cidade set cod_tom = '5887' where uf = 19 and upper(trim(unaccent(nome))) like 'RIO CLARO'; 
update cidade set cod_tom = '5889' where uf = 19 and upper(trim(unaccent(nome))) like 'RIO DAS FLORES'; 
update cidade set cod_tom = '2921' where uf = 19 and upper(trim(unaccent(nome))) like 'RIO DAS OSTRAS'; 
update cidade set cod_tom = '6001' where uf = 19 and upper(trim(unaccent(nome))) like 'RIO DE JANEIRO'; 
update cidade set cod_tom = '5891' where uf = 19 and upper(trim(unaccent(nome))) like 'SANTA MARIA MADALENA'; 
update cidade set cod_tom = '5893' where uf = 19 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DE PADUA'; 
update cidade set cod_tom = '5895' where uf = 19 and upper(trim(unaccent(nome))) like 'SAO FIDELIS'; 
update cidade set cod_tom = '0782' where uf = 19 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO DE ITABAPOANA'; 
update cidade set cod_tom = '5897' where uf = 19 and upper(trim(unaccent(nome))) like 'SAO GONCALO'; 
update cidade set cod_tom = '5899' where uf = 19 and upper(trim(unaccent(nome))) like 'SAO JOAO DA BARRA'; 
update cidade set cod_tom = '5901' where uf = 19 and upper(trim(unaccent(nome))) like 'SAO JOAO DE MERITI'; 
update cidade set cod_tom = '0784' where uf = 19 and upper(trim(unaccent(nome))) like 'SAO JOSE DE UBA'; 
update cidade set cod_tom = '6009' where uf = 19 and upper(trim(unaccent(nome))) like 'SAO JOSE DO VALE DO RIO PRETO'; 
update cidade set cod_tom = '5903' where uf = 19 and upper(trim(unaccent(nome))) like 'SAO PEDRO DA ALDEIA'; 
update cidade set cod_tom = '5905' where uf = 19 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO DO ALTO'; 
update cidade set cod_tom = '5907' where uf = 19 and upper(trim(unaccent(nome))) like 'SAPUCAIA'; 
update cidade set cod_tom = '5909' where uf = 19 and upper(trim(unaccent(nome))) like 'SAQUAREMA'; 
update cidade set cod_tom = '0786' where uf = 19 and upper(trim(unaccent(nome))) like 'SEROPEDICA'; 
update cidade set cod_tom = '5911' where uf = 19 and upper(trim(unaccent(nome))) like 'SILVA JARDIM'; 
update cidade set cod_tom = '5913' where uf = 19 and upper(trim(unaccent(nome))) like 'SUMIDOURO'; 
update cidade set cod_tom = '0788' where uf = 19 and upper(trim(unaccent(nome))) like 'TANGUA'; 
update cidade set cod_tom = '5915' where uf = 19 and upper(trim(unaccent(nome))) like 'TERESOPOLIS'; 
update cidade set cod_tom = '5917' where uf = 19 and upper(trim(unaccent(nome))) like 'TRAJANO DE MORAIS'; 
update cidade set cod_tom = '5919' where uf = 19 and upper(trim(unaccent(nome))) like 'TRES RIOS'; 
update cidade set cod_tom = '5921' where uf = 19 and upper(trim(unaccent(nome))) like 'VALENCA'; 
update cidade set cod_tom = '2917' where uf = 19 and upper(trim(unaccent(nome))) like 'VARRE-SAI'; 
update cidade set cod_tom = '5923' where uf = 19 and upper(trim(unaccent(nome))) like 'VASSOURAS'; 
update cidade set cod_tom = '5925' where uf = 19 and upper(trim(unaccent(nome))) like 'VOLTA REDONDA';