update cidade set cod_tom = '0266' where uf = 17 and upper(trim(unaccent(nome))) like 'ACAUA'; 
update cidade set cod_tom = '1001' where uf = 17 and upper(trim(unaccent(nome))) like 'AGRICOLANDIA'; 
update cidade set cod_tom = '1003' where uf = 17 and upper(trim(unaccent(nome))) like 'AGUA BRANCA'; 
update cidade set cod_tom = '9767' where uf = 17 and upper(trim(unaccent(nome))) like 'ALAGOINHA DO PIAUI'; 
update cidade set cod_tom = '2269' where uf = 17 and upper(trim(unaccent(nome))) like 'ALEGRETE DO PIAUI'; 
update cidade set cod_tom = '1005' where uf = 17 and upper(trim(unaccent(nome))) like 'ALTO LONGA'; 
update cidade set cod_tom = '1007' where uf = 17 and upper(trim(unaccent(nome))) like 'ALTOS'; 
update cidade set cod_tom = '0268' where uf = 17 and upper(trim(unaccent(nome))) like 'ALVORADA DO GURGUEIA'; 
update cidade set cod_tom = '1009' where uf = 17 and upper(trim(unaccent(nome))) like 'AMARANTE'; 
update cidade set cod_tom = '1011' where uf = 17 and upper(trim(unaccent(nome))) like 'ANGICAL DO PIAUI'; 
update cidade set cod_tom = '1013' where uf = 17 and upper(trim(unaccent(nome))) like 'ANISIO DE ABREU'; 
update cidade set cod_tom = '1015' where uf = 17 and upper(trim(unaccent(nome))) like 'ANTONIO ALMEIDA'; 
update cidade set cod_tom = '1017' where uf = 17 and upper(trim(unaccent(nome))) like 'AROAZES'; 
update cidade set cod_tom = '1188' where uf = 17 and upper(trim(unaccent(nome))) like 'AROEIRAS DO ITAIM'; 
update cidade set cod_tom = '1019' where uf = 17 and upper(trim(unaccent(nome))) like 'ARRAIAL'; 
update cidade set cod_tom = '0270' where uf = 17 and upper(trim(unaccent(nome))) like 'ASSUNCAO DO PIAUI'; 
update cidade set cod_tom = '1021' where uf = 17 and upper(trim(unaccent(nome))) like 'AVELINO LOPES'; 
update cidade set cod_tom = '2245' where uf = 17 and upper(trim(unaccent(nome))) like 'BAIXA GRANDE DO RIBEIRO'; 
update cidade set cod_tom = '0272' where uf = 17 and upper(trim(unaccent(nome))) like 'BARRA D`ALCANTARA'; 
update cidade set cod_tom = '1023' where uf = 17 and upper(trim(unaccent(nome))) like 'BARRAS'; 
update cidade set cod_tom = '1025' where uf = 17 and upper(trim(unaccent(nome))) like 'BARREIRAS DO PIAUI'; 
update cidade set cod_tom = '1027' where uf = 17 and upper(trim(unaccent(nome))) like 'BARRO DURO'; 
update cidade set cod_tom = '1029' where uf = 17 and upper(trim(unaccent(nome))) like 'BATALHA'; 
update cidade set cod_tom = '0274' where uf = 17 and upper(trim(unaccent(nome))) like 'BELA VISTA DO PIAUI'; 
update cidade set cod_tom = '0276' where uf = 17 and upper(trim(unaccent(nome))) like 'BELEM DO PIAUI'; 
update cidade set cod_tom = '1031' where uf = 17 and upper(trim(unaccent(nome))) like 'BENEDITINOS'; 
update cidade set cod_tom = '1033' where uf = 17 and upper(trim(unaccent(nome))) like 'BERTOLINIA'; 
update cidade set cod_tom = '0278' where uf = 17 and upper(trim(unaccent(nome))) like 'BETANIA DO PIAUI'; 
update cidade set cod_tom = '0280' where uf = 17 and upper(trim(unaccent(nome))) like 'BOA HORA'; 
update cidade set cod_tom = '1035' where uf = 17 and upper(trim(unaccent(nome))) like 'BOCAINA'; 
update cidade set cod_tom = '1037' where uf = 17 and upper(trim(unaccent(nome))) like 'BOM JESUS'; 
update cidade set cod_tom = '2287' where uf = 17 and upper(trim(unaccent(nome))) like 'BOM PRINCIPIO DO PIAUI'; 
update cidade set cod_tom = '2251' where uf = 17 and upper(trim(unaccent(nome))) like 'BONFIM DO PIAUI'; 
update cidade set cod_tom = '0282' where uf = 17 and upper(trim(unaccent(nome))) like 'BOQUEIRAO DO PIAUI'; 
update cidade set cod_tom = '2283' where uf = 17 and upper(trim(unaccent(nome))) like 'BRASILEIRA'; 
update cidade set cod_tom = '0284' where uf = 17 and upper(trim(unaccent(nome))) like 'BREJO DO PIAUI'; 
update cidade set cod_tom = '1039' where uf = 17 and upper(trim(unaccent(nome))) like 'BURITI DOS LOPES'; 
update cidade set cod_tom = '1297' where uf = 17 and upper(trim(unaccent(nome))) like 'BURITI DOS MONTES'; 
update cidade set cod_tom = '1299' where uf = 17 and upper(trim(unaccent(nome))) like 'CABECEIRAS DO PIAUI'; 
update cidade set cod_tom = '0286' where uf = 17 and upper(trim(unaccent(nome))) like 'CAJAZEIRAS DO PIAUI'; 
update cidade set cod_tom = '0288' where uf = 17 and upper(trim(unaccent(nome))) like 'CAJUEIRO DA PRAIA'; 
update cidade set cod_tom = '2271' where uf = 17 and upper(trim(unaccent(nome))) like 'CALDEIRAO GRANDE DO PIAUI'; 
update cidade set cod_tom = '1041' where uf = 17 and upper(trim(unaccent(nome))) like 'CAMPINAS DO PIAUI'; 
update cidade set cod_tom = '0290' where uf = 17 and upper(trim(unaccent(nome))) like 'CAMPO ALEGRE DO FIDALGO'; 
update cidade set cod_tom = '0' where uf = 17 and upper(trim(unaccent(nome))) like 'CAMPO ALEGRE DO PIAUI'; 
update cidade set cod_tom = '0292' where uf = 17 and upper(trim(unaccent(nome))) like 'CAMPO GRANDE DO PIAUI'; 
update cidade set cod_tom = '0294' where uf = 17 and upper(trim(unaccent(nome))) like 'CAMPO LARGO DO PIAUI'; 
update cidade set cod_tom = '1043' where uf = 17 and upper(trim(unaccent(nome))) like 'CAMPO MAIOR'; 
update cidade set cod_tom = '2247' where uf = 17 and upper(trim(unaccent(nome))) like 'CANAVIEIRA'; 
update cidade set cod_tom = '1045' where uf = 17 and upper(trim(unaccent(nome))) like 'CANTO DO BURITI'; 
update cidade set cod_tom = '1047' where uf = 17 and upper(trim(unaccent(nome))) like 'CAPITAO DE CAMPOS'; 
update cidade set cod_tom = '0296' where uf = 17 and upper(trim(unaccent(nome))) like 'CAPITAO GERVASIO OLIVEIRA'; 
update cidade set cod_tom = '1049' where uf = 17 and upper(trim(unaccent(nome))) like 'CARACOL'; 
update cidade set cod_tom = '0298' where uf = 17 and upper(trim(unaccent(nome))) like 'CARAUBAS DO PIAUI'; 
update cidade set cod_tom = '0300' where uf = 17 and upper(trim(unaccent(nome))) like 'CARIDADE DO PIAUI'; 
update cidade set cod_tom = '1051' where uf = 17 and upper(trim(unaccent(nome))) like 'CASTELO DO PIAUI'; 
update cidade set cod_tom = '0302' where uf = 17 and upper(trim(unaccent(nome))) like 'CAXINGO'; 
update cidade set cod_tom = '1053' where uf = 17 and upper(trim(unaccent(nome))) like 'COCAL'; 
update cidade set cod_tom = '0304' where uf = 17 and upper(trim(unaccent(nome))) like 'COCAL DE TELHA'; 
update cidade set cod_tom = '0306' where uf = 17 and upper(trim(unaccent(nome))) like 'COCAL DOS ALVES'; 
update cidade set cod_tom = '0995' where uf = 17 and upper(trim(unaccent(nome))) like 'COIVARAS'; 
update cidade set cod_tom = '2249' where uf = 17 and upper(trim(unaccent(nome))) like 'COLONIA DO GURGUEIA'; 
update cidade set cod_tom = '2253' where uf = 17 and upper(trim(unaccent(nome))) like 'COLONIA DO PIAUI'; 
update cidade set cod_tom = '1055' where uf = 17 and upper(trim(unaccent(nome))) like 'CONCEICAO DO CANINDE'; 
update cidade set cod_tom = '2255' where uf = 17 and upper(trim(unaccent(nome))) like 'CORONEL JOSE DIAS'; 
update cidade set cod_tom = '1057' where uf = 17 and upper(trim(unaccent(nome))) like 'CORRENTE'; 
update cidade set cod_tom = '1059' where uf = 17 and upper(trim(unaccent(nome))) like 'CRISTALANDIA DO PIAUI'; 
update cidade set cod_tom = '1061' where uf = 17 and upper(trim(unaccent(nome))) like 'CRISTINO CASTRO'; 
update cidade set cod_tom = '1063' where uf = 17 and upper(trim(unaccent(nome))) like 'CURIMATA'; 
update cidade set cod_tom = '0308' where uf = 17 and upper(trim(unaccent(nome))) like 'CURRAIS'; 
update cidade set cod_tom = '0312' where uf = 17 and upper(trim(unaccent(nome))) like 'CURRAL NOVO DO PIAUI'; 
update cidade set cod_tom = '0310' where uf = 17 and upper(trim(unaccent(nome))) like 'CURRALINHOS'; 
update cidade set cod_tom = '1065' where uf = 17 and upper(trim(unaccent(nome))) like 'DEMERVAL LOBAO'; 
update cidade set cod_tom = '1229' where uf = 17 and upper(trim(unaccent(nome))) like 'DIRCEU ARCOVERDE'; 
update cidade set cod_tom = '1067' where uf = 17 and upper(trim(unaccent(nome))) like 'DOM EXPEDITO LOPES'; 
update cidade set cod_tom = '1289' where uf = 17 and upper(trim(unaccent(nome))) like 'DOM INOCENCIO'; 
update cidade set cod_tom = '1141' where uf = 17 and upper(trim(unaccent(nome))) like 'DOMINGOS MOURAO'; 
update cidade set cod_tom = '1069' where uf = 17 and upper(trim(unaccent(nome))) like 'ELESBAO VELOSO'; 
update cidade set cod_tom = '1071' where uf = 17 and upper(trim(unaccent(nome))) like 'ELISEU MARTINS'; 
update cidade set cod_tom = '1073' where uf = 17 and upper(trim(unaccent(nome))) like 'ESPERANTINA'; 
update cidade set cod_tom = '2257' where uf = 17 and upper(trim(unaccent(nome))) like 'FARTURA DO PIAUI'; 
update cidade set cod_tom = '1075' where uf = 17 and upper(trim(unaccent(nome))) like 'FLORES DO PIAUI'; 
update cidade set cod_tom = '0314' where uf = 17 and upper(trim(unaccent(nome))) like 'FLORESTA DO PIAUI'; 
update cidade set cod_tom = '1077' where uf = 17 and upper(trim(unaccent(nome))) like 'FLORIANO'; 
update cidade set cod_tom = '1079' where uf = 17 and upper(trim(unaccent(nome))) like 'FRANCINOPOLIS'; 
update cidade set cod_tom = '1081' where uf = 17 and upper(trim(unaccent(nome))) like 'FRANCISCO AYRES'; 
update cidade set cod_tom = '0316' where uf = 17 and upper(trim(unaccent(nome))) like 'FRANCISCO MACEDO'; 
update cidade set cod_tom = '1083' where uf = 17 and upper(trim(unaccent(nome))) like 'FRANCISCO SANTOS'; 
update cidade set cod_tom = '1085' where uf = 17 and upper(trim(unaccent(nome))) like 'FRONTEIRAS'; 
update cidade set cod_tom = '0318' where uf = 17 and upper(trim(unaccent(nome))) like 'GEMINIANO'; 
update cidade set cod_tom = '1087' where uf = 17 and upper(trim(unaccent(nome))) like 'GILBUES'; 
update cidade set cod_tom = '1089' where uf = 17 and upper(trim(unaccent(nome))) like 'GUADALUPE'; 
update cidade set cod_tom = '0320' where uf = 17 and upper(trim(unaccent(nome))) like 'GUARIBAS'; 
update cidade set cod_tom = '1091' where uf = 17 and upper(trim(unaccent(nome))) like 'HUGO NAPOLEAO'; 
update cidade set cod_tom = '0322' where uf = 17 and upper(trim(unaccent(nome))) like 'ILHA GRANDE'; 
update cidade set cod_tom = '1093' where uf = 17 and upper(trim(unaccent(nome))) like 'INHUMA'; 
update cidade set cod_tom = '1095' where uf = 17 and upper(trim(unaccent(nome))) like 'IPIRANGA DO PIAUI'; 
update cidade set cod_tom = '1097' where uf = 17 and upper(trim(unaccent(nome))) like 'ISAIAS COELHO'; 
update cidade set cod_tom = '1099' where uf = 17 and upper(trim(unaccent(nome))) like 'ITAINOPOLIS'; 
update cidade set cod_tom = '1101' where uf = 17 and upper(trim(unaccent(nome))) like 'ITAUEIRA'; 
update cidade set cod_tom = '2273' where uf = 17 and upper(trim(unaccent(nome))) like 'JACOBINA DO PIAUI'; 
update cidade set cod_tom = '1103' where uf = 17 and upper(trim(unaccent(nome))) like 'JAICOS'; 
update cidade set cod_tom = '0997' where uf = 17 and upper(trim(unaccent(nome))) like 'JARDIM DO MULATO'; 
update cidade set cod_tom = '0324' where uf = 17 and upper(trim(unaccent(nome))) like 'JATOBA DO PIAUI'; 
update cidade set cod_tom = '1105' where uf = 17 and upper(trim(unaccent(nome))) like 'JERUMENHA'; 
update cidade set cod_tom = '0326' where uf = 17 and upper(trim(unaccent(nome))) like 'JOAO COSTA'; 
update cidade set cod_tom = '1107' where uf = 17 and upper(trim(unaccent(nome))) like 'JOAQUIM PIRES'; 
update cidade set cod_tom = '0328' where uf = 17 and upper(trim(unaccent(nome))) like 'JOCA MARQUES'; 
update cidade set cod_tom = '1109' where uf = 17 and upper(trim(unaccent(nome))) like 'JOSE DE FREITAS'; 
update cidade set cod_tom = '0330' where uf = 17 and upper(trim(unaccent(nome))) like 'JUAZEIRO DO PIAUI'; 
update cidade set cod_tom = '0332' where uf = 17 and upper(trim(unaccent(nome))) like 'JULIO BORGES'; 
update cidade set cod_tom = '0334' where uf = 17 and upper(trim(unaccent(nome))) like 'JUREMA'; 
update cidade set cod_tom = '0999' where uf = 17 and upper(trim(unaccent(nome))) like 'LAGOA ALEGRE'; 
update cidade set cod_tom = '0338' where uf = 17 and upper(trim(unaccent(nome))) like 'LAGOA DE SAO FRANCISCO'; 
update cidade set cod_tom = '2259' where uf = 17 and upper(trim(unaccent(nome))) like 'LAGOA DO BARRO DO PIAUI'; 
update cidade set cod_tom = '0340' where uf = 17 and upper(trim(unaccent(nome))) like 'LAGOA DO PIAUI'; 
update cidade set cod_tom = '0342' where uf = 17 and upper(trim(unaccent(nome))) like 'LAGOA DO SITIO'; 
update cidade set cod_tom = '0336' where uf = 17 and upper(trim(unaccent(nome))) like 'LAGOINHA DO PIAUI'; 
update cidade set cod_tom = '1111' where uf = 17 and upper(trim(unaccent(nome))) like 'LANDRI SALES'; 
update cidade set cod_tom = '1113' where uf = 17 and upper(trim(unaccent(nome))) like 'LUIS CORREIA'; 
update cidade set cod_tom = '1115' where uf = 17 and upper(trim(unaccent(nome))) like 'LUZILANDIA'; 
update cidade set cod_tom = '0344' where uf = 17 and upper(trim(unaccent(nome))) like 'MADEIRO'; 
update cidade set cod_tom = '1117' where uf = 17 and upper(trim(unaccent(nome))) like 'MANOEL EMIDIO'; 
update cidade set cod_tom = '2275' where uf = 17 and upper(trim(unaccent(nome))) like 'MARCOLANDIA'; 
update cidade set cod_tom = '1119' where uf = 17 and upper(trim(unaccent(nome))) like 'MARCOS PARENTE'; 
update cidade set cod_tom = '0346' where uf = 17 and upper(trim(unaccent(nome))) like 'MASSAPE DO PIAUI'; 
update cidade set cod_tom = '1121' where uf = 17 and upper(trim(unaccent(nome))) like 'MATIAS OLIMPIO'; 
update cidade set cod_tom = '1123' where uf = 17 and upper(trim(unaccent(nome))) like 'MIGUEL ALVES'; 
update cidade set cod_tom = '1125' where uf = 17 and upper(trim(unaccent(nome))) like 'MIGUEL LEAO'; 
update cidade set cod_tom = '0348' where uf = 17 and upper(trim(unaccent(nome))) like 'MILTON BRANDAO'; 
update cidade set cod_tom = '1127' where uf = 17 and upper(trim(unaccent(nome))) like 'MONSENHOR GIL'; 
update cidade set cod_tom = '1129' where uf = 17 and upper(trim(unaccent(nome))) like 'MONSENHOR HIPOLITO'; 
update cidade set cod_tom = '1131' where uf = 17 and upper(trim(unaccent(nome))) like 'MONTE ALEGRE DO PIAUI'; 
update cidade set cod_tom = '0350' where uf = 17 and upper(trim(unaccent(nome))) like 'MORRO CABECA NO TEMPO'; 
update cidade set cod_tom = '0352' where uf = 17 and upper(trim(unaccent(nome))) like 'MORRO DO CHAPEU DO PIAUI'; 
update cidade set cod_tom = '0354' where uf = 17 and upper(trim(unaccent(nome))) like 'MURICI DOS PORTELAS'; 
update cidade set cod_tom = '1133' where uf = 17 and upper(trim(unaccent(nome))) like 'NAZARE DO PIAUI'; 
update cidade set cod_tom = '0356' where uf = 17 and upper(trim(unaccent(nome))) like 'NOSSA SENHORA DE NAZARE'; 
update cidade set cod_tom = '1135' where uf = 17 and upper(trim(unaccent(nome))) like 'NOSSA SENHORA DOS REMEDIOS'; 
update cidade set cod_tom = '0370' where uf = 17 and upper(trim(unaccent(nome))) like 'NOVA SANTA RITA'; 
update cidade set cod_tom = '1137' where uf = 17 and upper(trim(unaccent(nome))) like 'NOVO ORIENTE DO PIAUI'; 
update cidade set cod_tom = '0358' where uf = 17 and upper(trim(unaccent(nome))) like 'NOVO SANTO ANTONIO'; 
update cidade set cod_tom = '1139' where uf = 17 and upper(trim(unaccent(nome))) like 'OEIRAS'; 
update cidade set cod_tom = '0360' where uf = 17 and upper(trim(unaccent(nome))) like 'OLHO D`AGUA DO PIAUI'; 
update cidade set cod_tom = '1143' where uf = 17 and upper(trim(unaccent(nome))) like 'PADRE MARCOS'; 
update cidade set cod_tom = '1145' where uf = 17 and upper(trim(unaccent(nome))) like 'PAES LANDIM'; 
update cidade set cod_tom = '0362' where uf = 17 and upper(trim(unaccent(nome))) like 'PAJEU DO PIAUI'; 
update cidade set cod_tom = '1147' where uf = 17 and upper(trim(unaccent(nome))) like 'PALMEIRA DO PIAUI'; 
update cidade set cod_tom = '1149' where uf = 17 and upper(trim(unaccent(nome))) like 'PALMEIRAIS'; 
update cidade set cod_tom = '0364' where uf = 17 and upper(trim(unaccent(nome))) like 'PAQUETA'; 
update cidade set cod_tom = '1151' where uf = 17 and upper(trim(unaccent(nome))) like 'PARNAGUA'; 
update cidade set cod_tom = '1153' where uf = 17 and upper(trim(unaccent(nome))) like 'PARNAIBA'; 
update cidade set cod_tom = '1293' where uf = 17 and upper(trim(unaccent(nome))) like 'PASSAGEM FRANCA DO PIAUI'; 
update cidade set cod_tom = '2277' where uf = 17 and upper(trim(unaccent(nome))) like 'PATOS DO PIAUI'; 
update cidade set cod_tom = '1104' where uf = 17 and upper(trim(unaccent(nome))) like 'PAU D`ARCO DO PIAUI'; 
update cidade set cod_tom = '1155' where uf = 17 and upper(trim(unaccent(nome))) like 'PAULISTANA'; 
update cidade set cod_tom = '0366' where uf = 17 and upper(trim(unaccent(nome))) like 'PAVUSSU'; 
update cidade set cod_tom = '1157' where uf = 17 and upper(trim(unaccent(nome))) like 'PEDRO II'; 
update cidade set cod_tom = '0368' where uf = 17 and upper(trim(unaccent(nome))) like 'PEDRO LAURENTINO'; 
update cidade set cod_tom = '0' where uf = 17 and upper(trim(unaccent(nome))) like 'PETRONIO PORTELA'; 
update cidade set cod_tom = '1159' where uf = 17 and upper(trim(unaccent(nome))) like 'PICOS'; 
update cidade set cod_tom = '1161' where uf = 17 and upper(trim(unaccent(nome))) like 'PIMENTEIRAS'; 
update cidade set cod_tom = '1163' where uf = 17 and upper(trim(unaccent(nome))) like 'PIO IX'; 
update cidade set cod_tom = '1165' where uf = 17 and upper(trim(unaccent(nome))) like 'PIRACURUCA'; 
update cidade set cod_tom = '1167' where uf = 17 and upper(trim(unaccent(nome))) like 'PIRIPIRI'; 
update cidade set cod_tom = '1169' where uf = 17 and upper(trim(unaccent(nome))) like 'PORTO'; 
update cidade set cod_tom = '0372' where uf = 17 and upper(trim(unaccent(nome))) like 'PORTO ALEGRE DO PIAUI'; 
update cidade set cod_tom = '1171' where uf = 17 and upper(trim(unaccent(nome))) like 'PRATA DO PIAUI'; 
update cidade set cod_tom = '2279' where uf = 17 and upper(trim(unaccent(nome))) like 'QUEIMADA NOVA'; 
update cidade set cod_tom = '1173' where uf = 17 and upper(trim(unaccent(nome))) like 'REDENCAO DO GURGUEIA'; 
update cidade set cod_tom = '1175' where uf = 17 and upper(trim(unaccent(nome))) like 'REGENERACAO'; 
update cidade set cod_tom = '0374' where uf = 17 and upper(trim(unaccent(nome))) like 'RIACHO FRIO'; 
update cidade set cod_tom = '0376' where uf = 17 and upper(trim(unaccent(nome))) like 'RIBEIRA DO PIAUI'; 
update cidade set cod_tom = '1177' where uf = 17 and upper(trim(unaccent(nome))) like 'RIBEIRO GONCALVES'; 
update cidade set cod_tom = '1179' where uf = 17 and upper(trim(unaccent(nome))) like 'RIO GRANDE DO PIAUI'; 
update cidade set cod_tom = '1181' where uf = 17 and upper(trim(unaccent(nome))) like 'SANTA CRUZ DO PIAUI'; 
update cidade set cod_tom = '1295' where uf = 17 and upper(trim(unaccent(nome))) like 'SANTA CRUZ DOS MILAGRES'; 
update cidade set cod_tom = '1183' where uf = 17 and upper(trim(unaccent(nome))) like 'SANTA FILOMENA'; 
update cidade set cod_tom = '1185' where uf = 17 and upper(trim(unaccent(nome))) like 'SANTA LUZ'; 
update cidade set cod_tom = '2261' where uf = 17 and upper(trim(unaccent(nome))) like 'SANTA ROSA DO PIAUI'; 
update cidade set cod_tom = '2281' where uf = 17 and upper(trim(unaccent(nome))) like 'SANTANA DO PIAUI'; 
update cidade set cod_tom = '1187' where uf = 17 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DE LISBOA'; 
update cidade set cod_tom = '0378' where uf = 17 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DOS MILAGRES'; 
update cidade set cod_tom = '1189' where uf = 17 and upper(trim(unaccent(nome))) like 'SANTO INACIO DO PIAUI'; 
update cidade set cod_tom = '2263' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO BRAZ DO PIAUI'; 
update cidade set cod_tom = '1191' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO FELIX DO PIAUI'; 
update cidade set cod_tom = '0380' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO DE ASSIS DO PIAUI'; 
update cidade set cod_tom = '1193' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO DO PIAUI'; 
update cidade set cod_tom = '0382' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO GONCALO DO GURGUEIA'; 
update cidade set cod_tom = '1195' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO GONCALO DO PIAUI'; 
update cidade set cod_tom = '1291' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO JOAO DA CANABRAVA'; 
update cidade set cod_tom = '0384' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO JOAO DA FRONTEIRA'; 
update cidade set cod_tom = '1197' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO JOAO DA SERRA'; 
update cidade set cod_tom = '0386' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO JOAO DA VARJOTA'; 
update cidade set cod_tom = '0388' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO JOAO DO ARRAIAL'; 
update cidade set cod_tom = '1199' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO JOAO DO PIAUI'; 
update cidade set cod_tom = '2285' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO JOSE DO DIVINO'; 
update cidade set cod_tom = '1201' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO JOSE DO PEIXE'; 
update cidade set cod_tom = '1203' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO JOSE DO PIAUI'; 
update cidade set cod_tom = '1205' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO JULIAO'; 
update cidade set cod_tom = '2265' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO LOURENCO DO PIAUI'; 
update cidade set cod_tom = '0390' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO LUIS DO PIAUI'; 
update cidade set cod_tom = '0392' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO MIGUEL DA BAIXA GRANDE'; 
update cidade set cod_tom = '0394' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO MIGUEL DO FIDALGO'; 
update cidade set cod_tom = '1207' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO MIGUEL DO TAPUIO'; 
update cidade set cod_tom = '1209' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO PEDRO DO PIAUI'; 
update cidade set cod_tom = '1211' where uf = 17 and upper(trim(unaccent(nome))) like 'SAO RAIMUNDO NONATO'; 
update cidade set cod_tom = '0396' where uf = 17 and upper(trim(unaccent(nome))) like 'SEBASTIAO BARROS'; 
update cidade set cod_tom = '0398' where uf = 17 and upper(trim(unaccent(nome))) like 'SEBASTIAO LEAL'; 
update cidade set cod_tom = '1379' where uf = 17 and upper(trim(unaccent(nome))) like 'SIGEFREDO PACHECO'; 
update cidade set cod_tom = '1213' where uf = 17 and upper(trim(unaccent(nome))) like 'SIMOES'; 
update cidade set cod_tom = '1215' where uf = 17 and upper(trim(unaccent(nome))) like 'SIMPLICIO MENDES'; 
update cidade set cod_tom = '1217' where uf = 17 and upper(trim(unaccent(nome))) like 'SOCORRO DO PIAUI'; 
update cidade set cod_tom = '0400' where uf = 17 and upper(trim(unaccent(nome))) like 'SUSSUAPARA'; 
update cidade set cod_tom = '0402' where uf = 17 and upper(trim(unaccent(nome))) like 'TAMBORIL DO PIAUI'; 
update cidade set cod_tom = '0404' where uf = 17 and upper(trim(unaccent(nome))) like 'TANQUE DO PIAUI'; 
update cidade set cod_tom = '1219' where uf = 17 and upper(trim(unaccent(nome))) like 'TERESINA'; 
update cidade set cod_tom = '1221' where uf = 17 and upper(trim(unaccent(nome))) like 'UNIAO'; 
update cidade set cod_tom = '1223' where uf = 17 and upper(trim(unaccent(nome))) like 'URUCUI'; 
update cidade set cod_tom = '1225' where uf = 17 and upper(trim(unaccent(nome))) like 'VALENCA DO PIAUI'; 
update cidade set cod_tom = '2267' where uf = 17 and upper(trim(unaccent(nome))) like 'VARZEA BRANCA'; 
update cidade set cod_tom = '1227' where uf = 17 and upper(trim(unaccent(nome))) like 'VARZEA GRANDE'; 
update cidade set cod_tom = '0406' where uf = 17 and upper(trim(unaccent(nome))) like 'VERA MENDES'; 
update cidade set cod_tom = '0408' where uf = 17 and upper(trim(unaccent(nome))) like 'VILA NOVA DO PIAUI'; 
update cidade set cod_tom = '0410' where uf = 17 and upper(trim(unaccent(nome))) like 'WALL FERRAZ';