update cidade set cod_tom = '1601' where uf = 20 and upper(trim(unaccent(nome))) like 'ACARI'; 
update cidade set cod_tom = '1605' where uf = 20 and upper(trim(unaccent(nome))) like 'AFONSO BEZERRA'; 
update cidade set cod_tom = '1607' where uf = 20 and upper(trim(unaccent(nome))) like 'AGUA NOVA'; 
update cidade set cod_tom = '1609' where uf = 20 and upper(trim(unaccent(nome))) like 'ALEXANDRIA'; 
update cidade set cod_tom = '1611' where uf = 20 and upper(trim(unaccent(nome))) like 'ALMINO AFONSO'; 
update cidade set cod_tom = '1613' where uf = 20 and upper(trim(unaccent(nome))) like 'ALTO DO RODRIGUES'; 
update cidade set cod_tom = '1615' where uf = 20 and upper(trim(unaccent(nome))) like 'ANGICOS'; 
update cidade set cod_tom = '1617' where uf = 20 and upper(trim(unaccent(nome))) like 'ANTONIO MARTINS'; 
update cidade set cod_tom = '1619' where uf = 20 and upper(trim(unaccent(nome))) like 'APODI'; 
update cidade set cod_tom = '1621' where uf = 20 and upper(trim(unaccent(nome))) like 'AREIA BRANCA'; 
update cidade set cod_tom = '1623' where uf = 20 and upper(trim(unaccent(nome))) like 'ARES'; 
update cidade set cod_tom = '1603' where uf = 20 and upper(trim(unaccent(nome))) like 'ASSU'; 
update cidade set cod_tom = '0' where uf = 20 and upper(trim(unaccent(nome))) like 'AUGUSTO SEVERO'; 
update cidade set cod_tom = '1627' where uf = 20 and upper(trim(unaccent(nome))) like 'BAIA FORMOSA'; 
update cidade set cod_tom = '3003' where uf = 20 and upper(trim(unaccent(nome))) like 'BARAUNA'; 
update cidade set cod_tom = '1629' where uf = 20 and upper(trim(unaccent(nome))) like 'BARCELONA'; 
update cidade set cod_tom = '1631' where uf = 20 and upper(trim(unaccent(nome))) like 'BENTO FERNANDES'; 
update cidade set cod_tom = '1703' where uf = 20 and upper(trim(unaccent(nome))) like 'BOA SAUDE'; 
update cidade set cod_tom = '0412' where uf = 20 and upper(trim(unaccent(nome))) like 'BODO'; 
update cidade set cod_tom = '1633' where uf = 20 and upper(trim(unaccent(nome))) like 'BOM JESUS'; 
update cidade set cod_tom = '1635' where uf = 20 and upper(trim(unaccent(nome))) like 'BREJINHO'; 
update cidade set cod_tom = '0414' where uf = 20 and upper(trim(unaccent(nome))) like 'CAICARA DO NORTE'; 
update cidade set cod_tom = '1637' where uf = 20 and upper(trim(unaccent(nome))) like 'CAICARA DO RIO DO VENTO'; 
update cidade set cod_tom = '1639' where uf = 20 and upper(trim(unaccent(nome))) like 'CAICO'; 
update cidade set cod_tom = '1625' where uf = 20 and upper(trim(unaccent(nome))) like 'CAMPO GRANDE'; 
update cidade set cod_tom = '1641' where uf = 20 and upper(trim(unaccent(nome))) like 'CAMPO REDONDO'; 
update cidade set cod_tom = '1643' where uf = 20 and upper(trim(unaccent(nome))) like 'CANGUARETAMA'; 
update cidade set cod_tom = '1645' where uf = 20 and upper(trim(unaccent(nome))) like 'CARAUBAS'; 
update cidade set cod_tom = '1647' where uf = 20 and upper(trim(unaccent(nome))) like 'CARNAUBA DOS DANTAS'; 
update cidade set cod_tom = '1649' where uf = 20 and upper(trim(unaccent(nome))) like 'CARNAUBAIS'; 
update cidade set cod_tom = '1651' where uf = 20 and upper(trim(unaccent(nome))) like 'CEARA-MIRIM'; 
update cidade set cod_tom = '1653' where uf = 20 and upper(trim(unaccent(nome))) like 'CERRO-CORA'; 
update cidade set cod_tom = '1655' where uf = 20 and upper(trim(unaccent(nome))) like 'CORONEL EZEQUIEL'; 
update cidade set cod_tom = '1657' where uf = 20 and upper(trim(unaccent(nome))) like 'CORONEL JOAO PESSOA'; 
update cidade set cod_tom = '1659' where uf = 20 and upper(trim(unaccent(nome))) like 'CRUZETA'; 
update cidade set cod_tom = '1661' where uf = 20 and upper(trim(unaccent(nome))) like 'CURRAIS NOVOS'; 
update cidade set cod_tom = '1663' where uf = 20 and upper(trim(unaccent(nome))) like 'DOUTOR SEVERIANO'; 
update cidade set cod_tom = '1665' where uf = 20 and upper(trim(unaccent(nome))) like 'ENCANTO'; 
update cidade set cod_tom = '1667' where uf = 20 and upper(trim(unaccent(nome))) like 'EQUADOR'; 
update cidade set cod_tom = '1669' where uf = 20 and upper(trim(unaccent(nome))) like 'ESPIRITO SANTO'; 
update cidade set cod_tom = '1773' where uf = 20 and upper(trim(unaccent(nome))) like 'ESPIRITO SANTO DO OESTE'; 
update cidade set cod_tom = '1671' where uf = 20 and upper(trim(unaccent(nome))) like 'EXTREMOZ'; 
update cidade set cod_tom = '1673' where uf = 20 and upper(trim(unaccent(nome))) like 'FELIPE GUERRA'; 
update cidade set cod_tom = '0416' where uf = 20 and upper(trim(unaccent(nome))) like 'FERNANDO PEDROZA'; 
update cidade set cod_tom = '1675' where uf = 20 and upper(trim(unaccent(nome))) like 'FLORANIA'; 
update cidade set cod_tom = '1677' where uf = 20 and upper(trim(unaccent(nome))) like 'FRANCISCO DANTAS'; 
update cidade set cod_tom = '1751' where uf = 20 and upper(trim(unaccent(nome))) like 'FRUTUOSO GOMES'; 
update cidade set cod_tom = '1679' where uf = 20 and upper(trim(unaccent(nome))) like 'GALINHOS'; 
update cidade set cod_tom = '1681' where uf = 20 and upper(trim(unaccent(nome))) like 'GOIANINHA'; 
update cidade set cod_tom = '1683' where uf = 20 and upper(trim(unaccent(nome))) like 'GOVERNADOR DIX-SEPT ROSADO'; 
update cidade set cod_tom = '1685' where uf = 20 and upper(trim(unaccent(nome))) like 'GROSSOS'; 
update cidade set cod_tom = '1687' where uf = 20 and upper(trim(unaccent(nome))) like 'GUAMARE'; 
update cidade set cod_tom = '1689' where uf = 20 and upper(trim(unaccent(nome))) like 'IELMO MARINHO'; 
update cidade set cod_tom = '1691' where uf = 20 and upper(trim(unaccent(nome))) like 'IPANGUACU'; 
update cidade set cod_tom = '1693' where uf = 20 and upper(trim(unaccent(nome))) like 'IPUEIRA'; 
update cidade set cod_tom = '0418' where uf = 20 and upper(trim(unaccent(nome))) like 'ITAJA'; 
update cidade set cod_tom = '1695' where uf = 20 and upper(trim(unaccent(nome))) like 'ITAU'; 
update cidade set cod_tom = '1697' where uf = 20 and upper(trim(unaccent(nome))) like 'JACANA'; 
update cidade set cod_tom = '1699' where uf = 20 and upper(trim(unaccent(nome))) like 'JANDAIRA'; 
update cidade set cod_tom = '1701' where uf = 20 and upper(trim(unaccent(nome))) like 'JANDUIS'; 
update cidade set cod_tom = '0' where uf = 20 and upper(trim(unaccent(nome))) like 'JANUARIO CICCO'; 
update cidade set cod_tom = '1705' where uf = 20 and upper(trim(unaccent(nome))) like 'JAPI'; 
update cidade set cod_tom = '1707' where uf = 20 and upper(trim(unaccent(nome))) like 'JARDIM DE ANGICOS'; 
update cidade set cod_tom = '1709' where uf = 20 and upper(trim(unaccent(nome))) like 'JARDIM DE PIRANHAS'; 
update cidade set cod_tom = '1711' where uf = 20 and upper(trim(unaccent(nome))) like 'JARDIM DO SERIDO'; 
update cidade set cod_tom = '1713' where uf = 20 and upper(trim(unaccent(nome))) like 'JOAO CAMARA'; 
update cidade set cod_tom = '1715' where uf = 20 and upper(trim(unaccent(nome))) like 'JOAO DIAS'; 
update cidade set cod_tom = '1717' where uf = 20 and upper(trim(unaccent(nome))) like 'JOSE DA PENHA'; 
update cidade set cod_tom = '1719' where uf = 20 and upper(trim(unaccent(nome))) like 'JUCURUTU'; 
update cidade set cod_tom = '1108' where uf = 20 and upper(trim(unaccent(nome))) like 'JUNDIA'; 
update cidade set cod_tom = '1723' where uf = 20 and upper(trim(unaccent(nome))) like 'LAGOA D`ANTA'; 
update cidade set cod_tom = '1725' where uf = 20 and upper(trim(unaccent(nome))) like 'LAGOA DE PEDRAS'; 
update cidade set cod_tom = '1727' where uf = 20 and upper(trim(unaccent(nome))) like 'LAGOA DE VELHOS'; 
update cidade set cod_tom = '1729' where uf = 20 and upper(trim(unaccent(nome))) like 'LAGOA NOVA'; 
update cidade set cod_tom = '1731' where uf = 20 and upper(trim(unaccent(nome))) like 'LAGOA SALGADA'; 
update cidade set cod_tom = '1733' where uf = 20 and upper(trim(unaccent(nome))) like 'LAJES'; 
update cidade set cod_tom = '1735' where uf = 20 and upper(trim(unaccent(nome))) like 'LAJES PINTADAS'; 
update cidade set cod_tom = '1737' where uf = 20 and upper(trim(unaccent(nome))) like 'LUCRECIA'; 
update cidade set cod_tom = '1739' where uf = 20 and upper(trim(unaccent(nome))) like 'LUIS GOMES'; 
update cidade set cod_tom = '1741' where uf = 20 and upper(trim(unaccent(nome))) like 'MACAIBA'; 
update cidade set cod_tom = '1743' where uf = 20 and upper(trim(unaccent(nome))) like 'MACAU'; 
update cidade set cod_tom = '0420' where uf = 20 and upper(trim(unaccent(nome))) like 'MAJOR SALES'; 
update cidade set cod_tom = '1745' where uf = 20 and upper(trim(unaccent(nome))) like 'MARCELINO VIEIRA'; 
update cidade set cod_tom = '1747' where uf = 20 and upper(trim(unaccent(nome))) like 'MARTINS'; 
update cidade set cod_tom = '1749' where uf = 20 and upper(trim(unaccent(nome))) like 'MAXARANGUAPE'; 
update cidade set cod_tom = '1721' where uf = 20 and upper(trim(unaccent(nome))) like 'MESSIAS TARGINO'; 
update cidade set cod_tom = '1753' where uf = 20 and upper(trim(unaccent(nome))) like 'MONTANHAS'; 
update cidade set cod_tom = '1755' where uf = 20 and upper(trim(unaccent(nome))) like 'MONTE ALEGRE'; 
update cidade set cod_tom = '1757' where uf = 20 and upper(trim(unaccent(nome))) like 'MONTE DAS GAMELEIRAS'; 
update cidade set cod_tom = '1759' where uf = 20 and upper(trim(unaccent(nome))) like 'MOSSORO'; 
update cidade set cod_tom = '1761' where uf = 20 and upper(trim(unaccent(nome))) like 'NATAL'; 
update cidade set cod_tom = '1763' where uf = 20 and upper(trim(unaccent(nome))) like 'NISIA FLORESTA'; 
update cidade set cod_tom = '1765' where uf = 20 and upper(trim(unaccent(nome))) like 'NOVA CRUZ'; 
update cidade set cod_tom = '1767' where uf = 20 and upper(trim(unaccent(nome))) like 'OLHO D`AGUA DO BORGES'; 
update cidade set cod_tom = '1769' where uf = 20 and upper(trim(unaccent(nome))) like 'OURO BRANCO'; 
update cidade set cod_tom = '1771' where uf = 20 and upper(trim(unaccent(nome))) like 'PARANA'; 
update cidade set cod_tom = '1773' where uf = 20 and upper(trim(unaccent(nome))) like 'PARAU'; 
update cidade set cod_tom = '1775' where uf = 20 and upper(trim(unaccent(nome))) like 'PARAZINHO'; 
update cidade set cod_tom = '1777' where uf = 20 and upper(trim(unaccent(nome))) like 'PARELHAS'; 
update cidade set cod_tom = '1779' where uf = 20 and upper(trim(unaccent(nome))) like 'PARNAMIRIM'; 
update cidade set cod_tom = '1781' where uf = 20 and upper(trim(unaccent(nome))) like 'PASSA E FICA'; 
update cidade set cod_tom = '1783' where uf = 20 and upper(trim(unaccent(nome))) like 'PASSAGEM'; 
update cidade set cod_tom = '1785' where uf = 20 and upper(trim(unaccent(nome))) like 'PATU'; 
update cidade set cod_tom = '1787' where uf = 20 and upper(trim(unaccent(nome))) like 'PAU DOS FERROS'; 
update cidade set cod_tom = '1789' where uf = 20 and upper(trim(unaccent(nome))) like 'PEDRA GRANDE'; 
update cidade set cod_tom = '1791' where uf = 20 and upper(trim(unaccent(nome))) like 'PEDRA PRETA'; 
update cidade set cod_tom = '1793' where uf = 20 and upper(trim(unaccent(nome))) like 'PEDRO AVELINO'; 
update cidade set cod_tom = '1795' where uf = 20 and upper(trim(unaccent(nome))) like 'PEDRO VELHO'; 
update cidade set cod_tom = '1797' where uf = 20 and upper(trim(unaccent(nome))) like 'PENDENCIAS'; 
update cidade set cod_tom = '1799' where uf = 20 and upper(trim(unaccent(nome))) like 'PILOES'; 
update cidade set cod_tom = '1801' where uf = 20 and upper(trim(unaccent(nome))) like 'POCO BRANCO'; 
update cidade set cod_tom = '1803' where uf = 20 and upper(trim(unaccent(nome))) like 'PORTALEGRE'; 
update cidade set cod_tom = '0426' where uf = 20 and upper(trim(unaccent(nome))) like 'PORTO DO MANGUE'; 
update cidade set cod_tom = '0' where uf = 20 and upper(trim(unaccent(nome))) like 'PRESIDENTE JUSCELINO'; 
update cidade set cod_tom = '1807' where uf = 20 and upper(trim(unaccent(nome))) like 'PUREZA'; 
update cidade set cod_tom = '1809' where uf = 20 and upper(trim(unaccent(nome))) like 'RAFAEL FERNANDES'; 
update cidade set cod_tom = '1893' where uf = 20 and upper(trim(unaccent(nome))) like 'RAFAEL GODEIRO'; 
update cidade set cod_tom = '1811' where uf = 20 and upper(trim(unaccent(nome))) like 'RIACHO DA CRUZ'; 
update cidade set cod_tom = '1813' where uf = 20 and upper(trim(unaccent(nome))) like 'RIACHO DE SANTANA'; 
update cidade set cod_tom = '1815' where uf = 20 and upper(trim(unaccent(nome))) like 'RIACHUELO'; 
update cidade set cod_tom = '0422' where uf = 20 and upper(trim(unaccent(nome))) like 'RIO DO FOGO'; 
update cidade set cod_tom = '1817' where uf = 20 and upper(trim(unaccent(nome))) like 'RODOLFO FERNANDES'; 
update cidade set cod_tom = '1819' where uf = 20 and upper(trim(unaccent(nome))) like 'RUY BARBOSA'; 
update cidade set cod_tom = '1823' where uf = 20 and upper(trim(unaccent(nome))) like 'SANTA CRUZ'; 
update cidade set cod_tom = '0424' where uf = 20 and upper(trim(unaccent(nome))) like 'SANTA MARIA'; 
update cidade set cod_tom = '1827' where uf = 20 and upper(trim(unaccent(nome))) like 'SANTANA DO MATOS'; 
update cidade set cod_tom = '1825' where uf = 20 and upper(trim(unaccent(nome))) like 'SANTANA DO SERIDO'; 
update cidade set cod_tom = '1829' where uf = 20 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO'; 
update cidade set cod_tom = '1831' where uf = 20 and upper(trim(unaccent(nome))) like 'SAO BENTO DO NORTE'; 
update cidade set cod_tom = '1833' where uf = 20 and upper(trim(unaccent(nome))) like 'SAO BENTO DO TRAIRI'; 
update cidade set cod_tom = '1835' where uf = 20 and upper(trim(unaccent(nome))) like 'SAO FERNANDO'; 
update cidade set cod_tom = '1821' where uf = 20 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO DO OESTE'; 
update cidade set cod_tom = '1837' where uf = 20 and upper(trim(unaccent(nome))) like 'SAO GONCALO DO AMARANTE'; 
update cidade set cod_tom = '1839' where uf = 20 and upper(trim(unaccent(nome))) like 'SAO JOAO DO SABUGI'; 
update cidade set cod_tom = '1841' where uf = 20 and upper(trim(unaccent(nome))) like 'SAO JOSE DE MIPIBU'; 
update cidade set cod_tom = '1843' where uf = 20 and upper(trim(unaccent(nome))) like 'SAO JOSE DO CAMPESTRE'; 
update cidade set cod_tom = '1845' where uf = 20 and upper(trim(unaccent(nome))) like 'SAO JOSE DO SERIDO'; 
update cidade set cod_tom = '1847' where uf = 20 and upper(trim(unaccent(nome))) like 'SAO MIGUEL'; 
update cidade set cod_tom = '0430' where uf = 20 and upper(trim(unaccent(nome))) like 'SAO MIGUEL DO GOSTOSO'; 
update cidade set cod_tom = '1849' where uf = 20 and upper(trim(unaccent(nome))) like 'SAO PAULO DO POTENGI'; 
update cidade set cod_tom = '1851' where uf = 20 and upper(trim(unaccent(nome))) like 'SAO PEDRO'; 
update cidade set cod_tom = '1853' where uf = 20 and upper(trim(unaccent(nome))) like 'SAO RAFAEL'; 
update cidade set cod_tom = '1855' where uf = 20 and upper(trim(unaccent(nome))) like 'SAO TOME'; 
update cidade set cod_tom = '1857' where uf = 20 and upper(trim(unaccent(nome))) like 'SAO VICENTE'; 
update cidade set cod_tom = '1859' where uf = 20 and upper(trim(unaccent(nome))) like 'SENADOR ELOI DE SOUZA'; 
update cidade set cod_tom = '1861' where uf = 20 and upper(trim(unaccent(nome))) like 'SENADOR GEORGINO AVELINO'; 
update cidade set cod_tom = '1805' where uf = 20 and upper(trim(unaccent(nome))) like 'SERRA CAIADA'; 
update cidade set cod_tom = '1863' where uf = 20 and upper(trim(unaccent(nome))) like 'SERRA DE SAO BENTO'; 
update cidade set cod_tom = '1927' where uf = 20 and upper(trim(unaccent(nome))) like 'SERRA DO MEL'; 
update cidade set cod_tom = '1865' where uf = 20 and upper(trim(unaccent(nome))) like 'SERRA NEGRA DO NORTE'; 
update cidade set cod_tom = '1867' where uf = 20 and upper(trim(unaccent(nome))) like 'SERRINHA'; 
update cidade set cod_tom = '0432' where uf = 20 and upper(trim(unaccent(nome))) like 'SERRINHA DOS PINTOS'; 
update cidade set cod_tom = '1869' where uf = 20 and upper(trim(unaccent(nome))) like 'SEVERIANO MELO'; 
update cidade set cod_tom = '1871' where uf = 20 and upper(trim(unaccent(nome))) like 'SITIO NOVO'; 
update cidade set cod_tom = '1873' where uf = 20 and upper(trim(unaccent(nome))) like 'TABOLEIRO GRANDE'; 
update cidade set cod_tom = '1875' where uf = 20 and upper(trim(unaccent(nome))) like 'TAIPU'; 
update cidade set cod_tom = '1877' where uf = 20 and upper(trim(unaccent(nome))) like 'TANGARA'; 
update cidade set cod_tom = '1879' where uf = 20 and upper(trim(unaccent(nome))) like 'TENENTE ANANIAS'; 
update cidade set cod_tom = '0434' where uf = 20 and upper(trim(unaccent(nome))) like 'TENENTE LAURENTINO CRUZ'; 
update cidade set cod_tom = '0428' where uf = 20 and upper(trim(unaccent(nome))) like 'TIBAU'; 
update cidade set cod_tom = '1881' where uf = 20 and upper(trim(unaccent(nome))) like 'TIBAU DO SUL'; 
update cidade set cod_tom = '1883' where uf = 20 and upper(trim(unaccent(nome))) like 'TIMBAUBA DOS BATISTAS'; 
update cidade set cod_tom = '1885' where uf = 20 and upper(trim(unaccent(nome))) like 'TOUROS'; 
update cidade set cod_tom = '0436' where uf = 20 and upper(trim(unaccent(nome))) like 'TRIUNFO POTIGUAR'; 
update cidade set cod_tom = '1887' where uf = 20 and upper(trim(unaccent(nome))) like 'UMARIZAL'; 
update cidade set cod_tom = '1889' where uf = 20 and upper(trim(unaccent(nome))) like 'UPANEMA'; 
update cidade set cod_tom = '1891' where uf = 20 and upper(trim(unaccent(nome))) like 'VARZEA'; 
update cidade set cod_tom = '0438' where uf = 20 and upper(trim(unaccent(nome))) like 'VENHA-VER'; 
update cidade set cod_tom = '1895' where uf = 20 and upper(trim(unaccent(nome))) like 'VERA CRUZ'; 
update cidade set cod_tom = '1897' where uf = 20 and upper(trim(unaccent(nome))) like 'VICOSA'; 
update cidade set cod_tom = '1899' where uf = 20 and upper(trim(unaccent(nome))) like 'VILA FLOR';