update cidade set cod_tom = '4001' where uf = 11 and upper(trim(unaccent(nome))) like 'ABADIA DOS DOURADOS'; 
update cidade set cod_tom = '4003' where uf = 11 and upper(trim(unaccent(nome))) like 'ABAETE'; 
update cidade set cod_tom = '4005' where uf = 11 and upper(trim(unaccent(nome))) like 'ABRE CAMPO'; 
update cidade set cod_tom = '4007' where uf = 11 and upper(trim(unaccent(nome))) like 'ACAIACA'; 
update cidade set cod_tom = '4009' where uf = 11 and upper(trim(unaccent(nome))) like 'ACUCENA'; 
update cidade set cod_tom = '4011' where uf = 11 and upper(trim(unaccent(nome))) like 'AGUA BOA'; 
update cidade set cod_tom = '4013' where uf = 11 and upper(trim(unaccent(nome))) like 'AGUA COMPRIDA'; 
update cidade set cod_tom = '4015' where uf = 11 and upper(trim(unaccent(nome))) like 'AGUANIL'; 
update cidade set cod_tom = '4017' where uf = 11 and upper(trim(unaccent(nome))) like 'AGUAS FORMOSAS'; 
update cidade set cod_tom = '4019' where uf = 11 and upper(trim(unaccent(nome))) like 'AGUAS VERMELHAS'; 
update cidade set cod_tom = '4021' where uf = 11 and upper(trim(unaccent(nome))) like 'AIMORES'; 
update cidade set cod_tom = '4023' where uf = 11 and upper(trim(unaccent(nome))) like 'AIURUOCA'; 
update cidade set cod_tom = '4025' where uf = 11 and upper(trim(unaccent(nome))) like 'ALAGOA'; 
update cidade set cod_tom = '4027' where uf = 11 and upper(trim(unaccent(nome))) like 'ALBERTINA'; 
update cidade set cod_tom = '4029' where uf = 11 and upper(trim(unaccent(nome))) like 'ALEM PARAIBA'; 
update cidade set cod_tom = '4031' where uf = 11 and upper(trim(unaccent(nome))) like 'ALFENAS'; 
update cidade set cod_tom = '2681' where uf = 11 and upper(trim(unaccent(nome))) like 'ALFREDO VASCONCELOS'; 
update cidade set cod_tom = '4033' where uf = 11 and upper(trim(unaccent(nome))) like 'ALMENARA'; 
update cidade set cod_tom = '4035' where uf = 11 and upper(trim(unaccent(nome))) like 'ALPERCATA'; 
update cidade set cod_tom = '4037' where uf = 11 and upper(trim(unaccent(nome))) like 'ALPINOPOLIS'; 
update cidade set cod_tom = '4039' where uf = 11 and upper(trim(unaccent(nome))) like 'ALTEROSA'; 
update cidade set cod_tom = '0564' where uf = 11 and upper(trim(unaccent(nome))) like 'ALTO CAPARAO'; 
update cidade set cod_tom = '5069' where uf = 11 and upper(trim(unaccent(nome))) like 'ALTO JEQUITIBA'; 
update cidade set cod_tom = '4041' where uf = 11 and upper(trim(unaccent(nome))) like 'ALTO RIO DOCE'; 
update cidade set cod_tom = '4043' where uf = 11 and upper(trim(unaccent(nome))) like 'ALVARENGA'; 
update cidade set cod_tom = '4045' where uf = 11 and upper(trim(unaccent(nome))) like 'ALVINOPOLIS'; 
update cidade set cod_tom = '4047' where uf = 11 and upper(trim(unaccent(nome))) like 'ALVORADA DE MINAS'; 
update cidade set cod_tom = '4049' where uf = 11 and upper(trim(unaccent(nome))) like 'AMPARO DA SERRA'; 
update cidade set cod_tom = '4051' where uf = 11 and upper(trim(unaccent(nome))) like 'ANDRADAS'; 
update cidade set cod_tom = '4055' where uf = 11 and upper(trim(unaccent(nome))) like 'ANDRELANDIA'; 
update cidade set cod_tom = '0566' where uf = 11 and upper(trim(unaccent(nome))) like 'ANGELANDIA'; 
update cidade set cod_tom = '4057' where uf = 11 and upper(trim(unaccent(nome))) like 'ANTONIO CARLOS'; 
update cidade set cod_tom = '4059' where uf = 11 and upper(trim(unaccent(nome))) like 'ANTONIO DIAS'; 
update cidade set cod_tom = '4061' where uf = 11 and upper(trim(unaccent(nome))) like 'ANTONIO PRADO DE MINAS'; 
update cidade set cod_tom = '4063' where uf = 11 and upper(trim(unaccent(nome))) like 'ARACAI'; 
update cidade set cod_tom = '4065' where uf = 11 and upper(trim(unaccent(nome))) like 'ARACITABA'; 
update cidade set cod_tom = '4067' where uf = 11 and upper(trim(unaccent(nome))) like 'ARACUAI'; 
update cidade set cod_tom = '4069' where uf = 11 and upper(trim(unaccent(nome))) like 'ARAGUARI'; 
update cidade set cod_tom = '4071' where uf = 11 and upper(trim(unaccent(nome))) like 'ARANTINA'; 
update cidade set cod_tom = '4073' where uf = 11 and upper(trim(unaccent(nome))) like 'ARAPONGA'; 
update cidade set cod_tom = '2903' where uf = 11 and upper(trim(unaccent(nome))) like 'ARAPORA'; 
update cidade set cod_tom = '4075' where uf = 11 and upper(trim(unaccent(nome))) like 'ARAPUA'; 
update cidade set cod_tom = '4077' where uf = 11 and upper(trim(unaccent(nome))) like 'ARAUJOS'; 
update cidade set cod_tom = '4079' where uf = 11 and upper(trim(unaccent(nome))) like 'ARAXA'; 
update cidade set cod_tom = '4081' where uf = 11 and upper(trim(unaccent(nome))) like 'ARCEBURGO'; 
update cidade set cod_tom = '4083' where uf = 11 and upper(trim(unaccent(nome))) like 'ARCOS'; 
update cidade set cod_tom = '4085' where uf = 11 and upper(trim(unaccent(nome))) like 'AREADO'; 
update cidade set cod_tom = '4087' where uf = 11 and upper(trim(unaccent(nome))) like 'ARGIRITA'; 
update cidade set cod_tom = '0568' where uf = 11 and upper(trim(unaccent(nome))) like 'ARICANDUVA'; 
update cidade set cod_tom = '4089' where uf = 11 and upper(trim(unaccent(nome))) like 'ARINOS'; 
update cidade set cod_tom = '4091' where uf = 11 and upper(trim(unaccent(nome))) like 'ASTOLFO DUTRA'; 
update cidade set cod_tom = '4093' where uf = 11 and upper(trim(unaccent(nome))) like 'ATALEIA'; 
update cidade set cod_tom = '4095' where uf = 11 and upper(trim(unaccent(nome))) like 'AUGUSTO DE LIMA'; 
update cidade set cod_tom = '4097' where uf = 11 and upper(trim(unaccent(nome))) like 'BAEPENDI'; 
update cidade set cod_tom = '4099' where uf = 11 and upper(trim(unaccent(nome))) like 'BALDIM'; 
update cidade set cod_tom = '4101' where uf = 11 and upper(trim(unaccent(nome))) like 'BAMBUI'; 
update cidade set cod_tom = '4103' where uf = 11 and upper(trim(unaccent(nome))) like 'BANDEIRA'; 
update cidade set cod_tom = '4105' where uf = 11 and upper(trim(unaccent(nome))) like 'BANDEIRA DO SUL'; 
update cidade set cod_tom = '4107' where uf = 11 and upper(trim(unaccent(nome))) like 'BARAO DE COCAIS'; 
update cidade set cod_tom = '4109' where uf = 11 and upper(trim(unaccent(nome))) like 'BARAO DE MONTE ALTO'; 
update cidade set cod_tom = '4111' where uf = 11 and upper(trim(unaccent(nome))) like 'BARBACENA'; 
update cidade set cod_tom = '4113' where uf = 11 and upper(trim(unaccent(nome))) like 'BARRA LONGA'; 
update cidade set cod_tom = '4117' where uf = 11 and upper(trim(unaccent(nome))) like 'BARROSO'; 
update cidade set cod_tom = '4119' where uf = 11 and upper(trim(unaccent(nome))) like 'BELA VISTA DE MINAS'; 
update cidade set cod_tom = '4121' where uf = 11 and upper(trim(unaccent(nome))) like 'BELMIRO BRAGA'; 
update cidade set cod_tom = '4123' where uf = 11 and upper(trim(unaccent(nome))) like 'BELO HORIZONTE'; 
update cidade set cod_tom = '4125' where uf = 11 and upper(trim(unaccent(nome))) like 'BELO ORIENTE'; 
update cidade set cod_tom = '4127' where uf = 11 and upper(trim(unaccent(nome))) like 'BELO VALE'; 
update cidade set cod_tom = '4129' where uf = 11 and upper(trim(unaccent(nome))) like 'BERILO'; 
update cidade set cod_tom = '0570' where uf = 11 and upper(trim(unaccent(nome))) like 'BERIZAL'; 
update cidade set cod_tom = '4131' where uf = 11 and upper(trim(unaccent(nome))) like 'BERTOPOLIS'; 
update cidade set cod_tom = '4133' where uf = 11 and upper(trim(unaccent(nome))) like 'BETIM'; 
update cidade set cod_tom = '4135' where uf = 11 and upper(trim(unaccent(nome))) like 'BIAS FORTES'; 
update cidade set cod_tom = '4137' where uf = 11 and upper(trim(unaccent(nome))) like 'BICAS'; 
update cidade set cod_tom = '4139' where uf = 11 and upper(trim(unaccent(nome))) like 'BIQUINHAS'; 
update cidade set cod_tom = '4141' where uf = 11 and upper(trim(unaccent(nome))) like 'BOA ESPERANCA'; 
update cidade set cod_tom = '4143' where uf = 11 and upper(trim(unaccent(nome))) like 'BOCAINA DE MINAS'; 
update cidade set cod_tom = '4145' where uf = 11 and upper(trim(unaccent(nome))) like 'BOCAIUVA'; 
update cidade set cod_tom = '4147' where uf = 11 and upper(trim(unaccent(nome))) like 'BOM DESPACHO'; 
update cidade set cod_tom = '4149' where uf = 11 and upper(trim(unaccent(nome))) like 'BOM JARDIM DE MINAS'; 
update cidade set cod_tom = '4151' where uf = 11 and upper(trim(unaccent(nome))) like 'BOM JESUS DA PENHA'; 
update cidade set cod_tom = '4153' where uf = 11 and upper(trim(unaccent(nome))) like 'BOM JESUS DO AMPARO'; 
update cidade set cod_tom = '4155' where uf = 11 and upper(trim(unaccent(nome))) like 'BOM JESUS DO GALHO'; 
update cidade set cod_tom = '4157' where uf = 11 and upper(trim(unaccent(nome))) like 'BOM REPOUSO'; 
update cidade set cod_tom = '4159' where uf = 11 and upper(trim(unaccent(nome))) like 'BOM SUCESSO'; 
update cidade set cod_tom = '4161' where uf = 11 and upper(trim(unaccent(nome))) like 'BONFIM'; 
update cidade set cod_tom = '4163' where uf = 11 and upper(trim(unaccent(nome))) like 'BONFINOPOLIS DE MINAS'; 
update cidade set cod_tom = '0572' where uf = 11 and upper(trim(unaccent(nome))) like 'BONITO DE MINAS'; 
update cidade set cod_tom = '4165' where uf = 11 and upper(trim(unaccent(nome))) like 'BORDA DA MATA'; 
update cidade set cod_tom = '4167' where uf = 11 and upper(trim(unaccent(nome))) like 'BOTELHOS'; 
update cidade set cod_tom = '4169' where uf = 11 and upper(trim(unaccent(nome))) like 'BOTUMIRIM'; 
update cidade set cod_tom = '4173' where uf = 11 and upper(trim(unaccent(nome))) like 'BRAS PIRES'; 
update cidade set cod_tom = '0574' where uf = 11 and upper(trim(unaccent(nome))) like 'BRASILANDIA DE MINAS'; 
update cidade set cod_tom = '4171' where uf = 11 and upper(trim(unaccent(nome))) like 'BRASILIA DE MINAS'; 
update cidade set cod_tom = '4177' where uf = 11 and upper(trim(unaccent(nome))) like 'BRASOPOLIS'; 
update cidade set cod_tom = '4175' where uf = 11 and upper(trim(unaccent(nome))) like 'BRAUNAS'; 
update cidade set cod_tom = '4179' where uf = 11 and upper(trim(unaccent(nome))) like 'BRUMADINHO'; 
update cidade set cod_tom = '4181' where uf = 11 and upper(trim(unaccent(nome))) like 'BUENO BRANDAO'; 
update cidade set cod_tom = '4183' where uf = 11 and upper(trim(unaccent(nome))) like 'BUENOPOLIS'; 
update cidade set cod_tom = '0576' where uf = 11 and upper(trim(unaccent(nome))) like 'BUGRE'; 
update cidade set cod_tom = '4185' where uf = 11 and upper(trim(unaccent(nome))) like 'BURITIS'; 
update cidade set cod_tom = '4187' where uf = 11 and upper(trim(unaccent(nome))) like 'BURITIZEIRO'; 
update cidade set cod_tom = '0578' where uf = 11 and upper(trim(unaccent(nome))) like 'CABECEIRA GRANDE'; 
update cidade set cod_tom = '4189' where uf = 11 and upper(trim(unaccent(nome))) like 'CABO VERDE'; 
update cidade set cod_tom = '4191' where uf = 11 and upper(trim(unaccent(nome))) like 'CACHOEIRA DA PRATA'; 
update cidade set cod_tom = '4193' where uf = 11 and upper(trim(unaccent(nome))) like 'CACHOEIRA DE MINAS'; 
update cidade set cod_tom = '4053' where uf = 11 and upper(trim(unaccent(nome))) like 'CACHOEIRA DE PAJEU'; 
update cidade set cod_tom = '4195' where uf = 11 and upper(trim(unaccent(nome))) like 'CACHOEIRA DOURADA'; 
update cidade set cod_tom = '4197' where uf = 11 and upper(trim(unaccent(nome))) like 'CAETANOPOLIS'; 
update cidade set cod_tom = '4199' where uf = 11 and upper(trim(unaccent(nome))) like 'CAETE'; 
update cidade set cod_tom = '4201' where uf = 11 and upper(trim(unaccent(nome))) like 'CAIANA'; 
update cidade set cod_tom = '4203' where uf = 11 and upper(trim(unaccent(nome))) like 'CAJURI'; 
update cidade set cod_tom = '4205' where uf = 11 and upper(trim(unaccent(nome))) like 'CALDAS'; 
update cidade set cod_tom = '4207' where uf = 11 and upper(trim(unaccent(nome))) like 'CAMACHO'; 
update cidade set cod_tom = '4209' where uf = 11 and upper(trim(unaccent(nome))) like 'CAMANDUCAIA'; 
update cidade set cod_tom = '4211' where uf = 11 and upper(trim(unaccent(nome))) like 'CAMBUI'; 
update cidade set cod_tom = '4213' where uf = 11 and upper(trim(unaccent(nome))) like 'CAMBUQUIRA'; 
update cidade set cod_tom = '4215' where uf = 11 and upper(trim(unaccent(nome))) like 'CAMPANARIO'; 
update cidade set cod_tom = '4217' where uf = 11 and upper(trim(unaccent(nome))) like 'CAMPANHA'; 
update cidade set cod_tom = '4219' where uf = 11 and upper(trim(unaccent(nome))) like 'CAMPESTRE'; 
update cidade set cod_tom = '4221' where uf = 11 and upper(trim(unaccent(nome))) like 'CAMPINA VERDE'; 
update cidade set cod_tom = '0580' where uf = 11 and upper(trim(unaccent(nome))) like 'CAMPO AZUL'; 
update cidade set cod_tom = '4223' where uf = 11 and upper(trim(unaccent(nome))) like 'CAMPO BELO'; 
update cidade set cod_tom = '4225' where uf = 11 and upper(trim(unaccent(nome))) like 'CAMPO DO MEIO'; 
update cidade set cod_tom = '4227' where uf = 11 and upper(trim(unaccent(nome))) like 'CAMPO FLORIDO'; 
update cidade set cod_tom = '4229' where uf = 11 and upper(trim(unaccent(nome))) like 'CAMPOS ALTOS'; 
update cidade set cod_tom = '4231' where uf = 11 and upper(trim(unaccent(nome))) like 'CAMPOS GERAIS'; 
update cidade set cod_tom = '4237' where uf = 11 and upper(trim(unaccent(nome))) like 'CANA VERDE'; 
update cidade set cod_tom = '4233' where uf = 11 and upper(trim(unaccent(nome))) like 'CANAA'; 
update cidade set cod_tom = '4235' where uf = 11 and upper(trim(unaccent(nome))) like 'CANAPOLIS'; 
update cidade set cod_tom = '4239' where uf = 11 and upper(trim(unaccent(nome))) like 'CANDEIAS'; 
update cidade set cod_tom = '0582' where uf = 11 and upper(trim(unaccent(nome))) like 'CANTAGALO'; 
update cidade set cod_tom = '4241' where uf = 11 and upper(trim(unaccent(nome))) like 'CAPARAO'; 
update cidade set cod_tom = '4243' where uf = 11 and upper(trim(unaccent(nome))) like 'CAPELA NOVA'; 
update cidade set cod_tom = '4245' where uf = 11 and upper(trim(unaccent(nome))) like 'CAPELINHA'; 
update cidade set cod_tom = '4247' where uf = 11 and upper(trim(unaccent(nome))) like 'CAPETINGA'; 
update cidade set cod_tom = '4249' where uf = 11 and upper(trim(unaccent(nome))) like 'CAPIM BRANCO'; 
update cidade set cod_tom = '4251' where uf = 11 and upper(trim(unaccent(nome))) like 'CAPINOPOLIS'; 
update cidade set cod_tom = '2651' where uf = 11 and upper(trim(unaccent(nome))) like 'CAPITAO ANDRADE'; 
update cidade set cod_tom = '4253' where uf = 11 and upper(trim(unaccent(nome))) like 'CAPITAO ENEAS'; 
update cidade set cod_tom = '4255' where uf = 11 and upper(trim(unaccent(nome))) like 'CAPITOLIO'; 
update cidade set cod_tom = '4257' where uf = 11 and upper(trim(unaccent(nome))) like 'CAPUTIRA'; 
update cidade set cod_tom = '4259' where uf = 11 and upper(trim(unaccent(nome))) like 'CARAI'; 
update cidade set cod_tom = '4261' where uf = 11 and upper(trim(unaccent(nome))) like 'CARANAIBA'; 
update cidade set cod_tom = '4263' where uf = 11 and upper(trim(unaccent(nome))) like 'CARANDAI'; 
update cidade set cod_tom = '4265' where uf = 11 and upper(trim(unaccent(nome))) like 'CARANGOLA'; 
update cidade set cod_tom = '4267' where uf = 11 and upper(trim(unaccent(nome))) like 'CARATINGA'; 
update cidade set cod_tom = '4269' where uf = 11 and upper(trim(unaccent(nome))) like 'CARBONITA'; 
update cidade set cod_tom = '4271' where uf = 11 and upper(trim(unaccent(nome))) like 'CAREACU'; 
update cidade set cod_tom = '4273' where uf = 11 and upper(trim(unaccent(nome))) like 'CARLOS CHAGAS'; 
update cidade set cod_tom = '4275' where uf = 11 and upper(trim(unaccent(nome))) like 'CARMESIA'; 
update cidade set cod_tom = '4277' where uf = 11 and upper(trim(unaccent(nome))) like 'CARMO DA CACHOEIRA'; 
update cidade set cod_tom = '4279' where uf = 11 and upper(trim(unaccent(nome))) like 'CARMO DA MATA'; 
update cidade set cod_tom = '4281' where uf = 11 and upper(trim(unaccent(nome))) like 'CARMO DE MINAS'; 
update cidade set cod_tom = '4283' where uf = 11 and upper(trim(unaccent(nome))) like 'CARMO DO CAJURU'; 
update cidade set cod_tom = '4285' where uf = 11 and upper(trim(unaccent(nome))) like 'CARMO DO PARANAIBA'; 
update cidade set cod_tom = '4287' where uf = 11 and upper(trim(unaccent(nome))) like 'CARMO DO RIO CLARO'; 
update cidade set cod_tom = '4289' where uf = 11 and upper(trim(unaccent(nome))) like 'CARMOPOLIS DE MINAS'; 
update cidade set cod_tom = '2685' where uf = 11 and upper(trim(unaccent(nome))) like 'CARNEIRINHO'; 
update cidade set cod_tom = '4291' where uf = 11 and upper(trim(unaccent(nome))) like 'CARRANCAS'; 
update cidade set cod_tom = '4293' where uf = 11 and upper(trim(unaccent(nome))) like 'CARVALHOPOLIS'; 
update cidade set cod_tom = '4295' where uf = 11 and upper(trim(unaccent(nome))) like 'CARVALHOS'; 
update cidade set cod_tom = '4297' where uf = 11 and upper(trim(unaccent(nome))) like 'CASA GRANDE'; 
update cidade set cod_tom = '4299' where uf = 11 and upper(trim(unaccent(nome))) like 'CASCALHO RICO'; 
update cidade set cod_tom = '4301' where uf = 11 and upper(trim(unaccent(nome))) like 'CASSIA'; 
update cidade set cod_tom = '4305' where uf = 11 and upper(trim(unaccent(nome))) like 'CATAGUASES'; 
update cidade set cod_tom = '0584' where uf = 11 and upper(trim(unaccent(nome))) like 'CATAS ALTAS'; 
update cidade set cod_tom = '4307' where uf = 11 and upper(trim(unaccent(nome))) like 'CATAS ALTAS DA NORUEGA'; 
update cidade set cod_tom = '2653' where uf = 11 and upper(trim(unaccent(nome))) like 'CATUJI'; 
update cidade set cod_tom = '0586' where uf = 11 and upper(trim(unaccent(nome))) like 'CATUTI'; 
update cidade set cod_tom = '4309' where uf = 11 and upper(trim(unaccent(nome))) like 'CAXAMBU'; 
update cidade set cod_tom = '4311' where uf = 11 and upper(trim(unaccent(nome))) like 'CEDRO DO ABAETE'; 
update cidade set cod_tom = '4313' where uf = 11 and upper(trim(unaccent(nome))) like 'CENTRAL DE MINAS'; 
update cidade set cod_tom = '4315' where uf = 11 and upper(trim(unaccent(nome))) like 'CENTRALINA'; 
update cidade set cod_tom = '4317' where uf = 11 and upper(trim(unaccent(nome))) like 'CHACARA'; 
update cidade set cod_tom = '4319' where uf = 11 and upper(trim(unaccent(nome))) like 'CHALE'; 
update cidade set cod_tom = '4321' where uf = 11 and upper(trim(unaccent(nome))) like 'CHAPADA DO NORTE'; 
update cidade set cod_tom = '0588' where uf = 11 and upper(trim(unaccent(nome))) like 'CHAPADA GAUCHA'; 
update cidade set cod_tom = '4323' where uf = 11 and upper(trim(unaccent(nome))) like 'CHIADOR'; 
update cidade set cod_tom = '4325' where uf = 11 and upper(trim(unaccent(nome))) like 'CIPOTANEA'; 
update cidade set cod_tom = '4327' where uf = 11 and upper(trim(unaccent(nome))) like 'CLARAVAL'; 
update cidade set cod_tom = '4329' where uf = 11 and upper(trim(unaccent(nome))) like 'CLARO DOS POCOES'; 
update cidade set cod_tom = '4331' where uf = 11 and upper(trim(unaccent(nome))) like 'CLAUDIO'; 
update cidade set cod_tom = '4333' where uf = 11 and upper(trim(unaccent(nome))) like 'COIMBRA'; 
update cidade set cod_tom = '4335' where uf = 11 and upper(trim(unaccent(nome))) like 'COLUNA'; 
update cidade set cod_tom = '4337' where uf = 11 and upper(trim(unaccent(nome))) like 'COMENDADOR GOMES'; 
update cidade set cod_tom = '4339' where uf = 11 and upper(trim(unaccent(nome))) like 'COMERCINHO'; 
update cidade set cod_tom = '4341' where uf = 11 and upper(trim(unaccent(nome))) like 'CONCEICAO DA APARECIDA'; 
update cidade set cod_tom = '4303' where uf = 11 and upper(trim(unaccent(nome))) like 'CONCEICAO DA BARRA DE MINAS'; 
update cidade set cod_tom = '4345' where uf = 11 and upper(trim(unaccent(nome))) like 'CONCEICAO DAS ALAGOAS'; 
update cidade set cod_tom = '4343' where uf = 11 and upper(trim(unaccent(nome))) like 'CONCEICAO DAS PEDRAS'; 
update cidade set cod_tom = '4347' where uf = 11 and upper(trim(unaccent(nome))) like 'CONCEICAO DE IPANEMA'; 
update cidade set cod_tom = '4349' where uf = 11 and upper(trim(unaccent(nome))) like 'CONCEICAO DO MATO DENTRO'; 
update cidade set cod_tom = '4351' where uf = 11 and upper(trim(unaccent(nome))) like 'CONCEICAO DO PARA'; 
update cidade set cod_tom = '4353' where uf = 11 and upper(trim(unaccent(nome))) like 'CONCEICAO DO RIO VERDE'; 
update cidade set cod_tom = '4355' where uf = 11 and upper(trim(unaccent(nome))) like 'CONCEICAO DOS OUROS'; 
update cidade set cod_tom = '0590' where uf = 11 and upper(trim(unaccent(nome))) like 'CONEGO MARINHO'; 
update cidade set cod_tom = '0592' where uf = 11 and upper(trim(unaccent(nome))) like 'CONFINS'; 
update cidade set cod_tom = '4357' where uf = 11 and upper(trim(unaccent(nome))) like 'CONGONHAL'; 
update cidade set cod_tom = '4359' where uf = 11 and upper(trim(unaccent(nome))) like 'CONGONHAS'; 
update cidade set cod_tom = '4361' where uf = 11 and upper(trim(unaccent(nome))) like 'CONGONHAS DO NORTE'; 
update cidade set cod_tom = '4363' where uf = 11 and upper(trim(unaccent(nome))) like 'CONQUISTA'; 
update cidade set cod_tom = '4365' where uf = 11 and upper(trim(unaccent(nome))) like 'CONSELHEIRO LAFAIETE'; 
update cidade set cod_tom = '4367' where uf = 11 and upper(trim(unaccent(nome))) like 'CONSELHEIRO PENA'; 
update cidade set cod_tom = '4369' where uf = 11 and upper(trim(unaccent(nome))) like 'CONSOLACAO'; 
update cidade set cod_tom = '4371' where uf = 11 and upper(trim(unaccent(nome))) like 'CONTAGEM'; 
update cidade set cod_tom = '4373' where uf = 11 and upper(trim(unaccent(nome))) like 'COQUEIRAL'; 
update cidade set cod_tom = '4375' where uf = 11 and upper(trim(unaccent(nome))) like 'CORACAO DE JESUS'; 
update cidade set cod_tom = '4377' where uf = 11 and upper(trim(unaccent(nome))) like 'CORDISBURGO'; 
update cidade set cod_tom = '4379' where uf = 11 and upper(trim(unaccent(nome))) like 'CORDISLANDIA'; 
update cidade set cod_tom = '4381' where uf = 11 and upper(trim(unaccent(nome))) like 'CORINTO'; 
update cidade set cod_tom = '4383' where uf = 11 and upper(trim(unaccent(nome))) like 'COROACI'; 
update cidade set cod_tom = '4385' where uf = 11 and upper(trim(unaccent(nome))) like 'COROMANDEL'; 
update cidade set cod_tom = '4387' where uf = 11 and upper(trim(unaccent(nome))) like 'CORONEL FABRICIANO'; 
update cidade set cod_tom = '4389' where uf = 11 and upper(trim(unaccent(nome))) like 'CORONEL MURTA'; 
update cidade set cod_tom = '4391' where uf = 11 and upper(trim(unaccent(nome))) like 'CORONEL PACHECO'; 
update cidade set cod_tom = '4393' where uf = 11 and upper(trim(unaccent(nome))) like 'CORONEL XAVIER CHAVES'; 
update cidade set cod_tom = '4395' where uf = 11 and upper(trim(unaccent(nome))) like 'CORREGO DANTA'; 
update cidade set cod_tom = '4397' where uf = 11 and upper(trim(unaccent(nome))) like 'CORREGO DO BOM JESUS'; 
update cidade set cod_tom = '0594' where uf = 11 and upper(trim(unaccent(nome))) like 'CORREGO FUNDO'; 
update cidade set cod_tom = '4399' where uf = 11 and upper(trim(unaccent(nome))) like 'CORREGO NOVO'; 
update cidade set cod_tom = '4401' where uf = 11 and upper(trim(unaccent(nome))) like 'COUTO DE MAGALHAES DE MINAS'; 
update cidade set cod_tom = '0596' where uf = 11 and upper(trim(unaccent(nome))) like 'CRISOLITA'; 
update cidade set cod_tom = '4403' where uf = 11 and upper(trim(unaccent(nome))) like 'CRISTAIS'; 
update cidade set cod_tom = '4405' where uf = 11 and upper(trim(unaccent(nome))) like 'CRISTALIA'; 
update cidade set cod_tom = '4407' where uf = 11 and upper(trim(unaccent(nome))) like 'CRISTIANO OTONI'; 
update cidade set cod_tom = '4409' where uf = 11 and upper(trim(unaccent(nome))) like 'CRISTINA'; 
update cidade set cod_tom = '4411' where uf = 11 and upper(trim(unaccent(nome))) like 'CRUCILANDIA'; 
update cidade set cod_tom = '4413' where uf = 11 and upper(trim(unaccent(nome))) like 'CRUZEIRO DA FORTALEZA'; 
update cidade set cod_tom = '4415' where uf = 11 and upper(trim(unaccent(nome))) like 'CRUZILIA'; 
update cidade set cod_tom = '0598' where uf = 11 and upper(trim(unaccent(nome))) like 'CUPARAQUE'; 
update cidade set cod_tom = '0600' where uf = 11 and upper(trim(unaccent(nome))) like 'CURRAL DE DENTRO'; 
update cidade set cod_tom = '4417' where uf = 11 and upper(trim(unaccent(nome))) like 'CURVELO'; 
update cidade set cod_tom = '4419' where uf = 11 and upper(trim(unaccent(nome))) like 'DATAS'; 
update cidade set cod_tom = '4421' where uf = 11 and upper(trim(unaccent(nome))) like 'DELFIM MOREIRA'; 
update cidade set cod_tom = '4423' where uf = 11 and upper(trim(unaccent(nome))) like 'DELFINOPOLIS'; 
update cidade set cod_tom = '0602' where uf = 11 and upper(trim(unaccent(nome))) like 'DELTA'; 
update cidade set cod_tom = '4425' where uf = 11 and upper(trim(unaccent(nome))) like 'DESCOBERTO'; 
update cidade set cod_tom = '4427' where uf = 11 and upper(trim(unaccent(nome))) like 'DESTERRO DE ENTRE RIOS'; 
update cidade set cod_tom = '4429' where uf = 11 and upper(trim(unaccent(nome))) like 'DESTERRO DO MELO'; 
update cidade set cod_tom = '4431' where uf = 11 and upper(trim(unaccent(nome))) like 'DIAMANTINA'; 
update cidade set cod_tom = '4433' where uf = 11 and upper(trim(unaccent(nome))) like 'DIOGO DE VASCONCELOS'; 
update cidade set cod_tom = '4435' where uf = 11 and upper(trim(unaccent(nome))) like 'DIONISIO'; 
update cidade set cod_tom = '4437' where uf = 11 and upper(trim(unaccent(nome))) like 'DIVINESIA'; 
update cidade set cod_tom = '4439' where uf = 11 and upper(trim(unaccent(nome))) like 'DIVINO'; 
update cidade set cod_tom = '4441' where uf = 11 and upper(trim(unaccent(nome))) like 'DIVINO DAS LARANJEIRAS'; 
update cidade set cod_tom = '4443' where uf = 11 and upper(trim(unaccent(nome))) like 'DIVINOLANDIA DE MINAS'; 
update cidade set cod_tom = '4445' where uf = 11 and upper(trim(unaccent(nome))) like 'DIVINOPOLIS'; 
update cidade set cod_tom = '0604' where uf = 11 and upper(trim(unaccent(nome))) like 'DIVISA ALEGRE'; 
update cidade set cod_tom = '4447' where uf = 11 and upper(trim(unaccent(nome))) like 'DIVISA NOVA'; 
update cidade set cod_tom = '2657' where uf = 11 and upper(trim(unaccent(nome))) like 'DIVISOPOLIS'; 
update cidade set cod_tom = '0606' where uf = 11 and upper(trim(unaccent(nome))) like 'DOM BOSCO'; 
update cidade set cod_tom = '4449' where uf = 11 and upper(trim(unaccent(nome))) like 'DOM CAVATI'; 
update cidade set cod_tom = '4451' where uf = 11 and upper(trim(unaccent(nome))) like 'DOM JOAQUIM'; 
update cidade set cod_tom = '4453' where uf = 11 and upper(trim(unaccent(nome))) like 'DOM SILVERIO'; 
update cidade set cod_tom = '4455' where uf = 11 and upper(trim(unaccent(nome))) like 'DOM VICOSO'; 
update cidade set cod_tom = '4457' where uf = 11 and upper(trim(unaccent(nome))) like 'DONA EUZEBIA'; 
update cidade set cod_tom = '4459' where uf = 11 and upper(trim(unaccent(nome))) like 'DORES DE CAMPOS'; 
update cidade set cod_tom = '4461' where uf = 11 and upper(trim(unaccent(nome))) like 'DORES DE GUANHAES'; 
update cidade set cod_tom = '4463' where uf = 11 and upper(trim(unaccent(nome))) like 'DORES DO INDAIA'; 
update cidade set cod_tom = '4465' where uf = 11 and upper(trim(unaccent(nome))) like 'DORES DO TURVO'; 
update cidade set cod_tom = '4467' where uf = 11 and upper(trim(unaccent(nome))) like 'DORESOPOLIS'; 
update cidade set cod_tom = '4469' where uf = 11 and upper(trim(unaccent(nome))) like 'DOURADOQUARA'; 
update cidade set cod_tom = '2675' where uf = 11 and upper(trim(unaccent(nome))) like 'DURANDE'; 
update cidade set cod_tom = '4471' where uf = 11 and upper(trim(unaccent(nome))) like 'ELOI MENDES'; 
update cidade set cod_tom = '4473' where uf = 11 and upper(trim(unaccent(nome))) like 'ENGENHEIRO CALDAS'; 
update cidade set cod_tom = '4475' where uf = 11 and upper(trim(unaccent(nome))) like 'ENGENHEIRO NAVARRO'; 
update cidade set cod_tom = '2663' where uf = 11 and upper(trim(unaccent(nome))) like 'ENTRE FOLHAS'; 
update cidade set cod_tom = '4477' where uf = 11 and upper(trim(unaccent(nome))) like 'ENTRE RIOS DE MINAS'; 
update cidade set cod_tom = '4479' where uf = 11 and upper(trim(unaccent(nome))) like 'ERVALIA'; 
update cidade set cod_tom = '4481' where uf = 11 and upper(trim(unaccent(nome))) like 'ESMERALDAS'; 
update cidade set cod_tom = '4483' where uf = 11 and upper(trim(unaccent(nome))) like 'ESPERA FELIZ'; 
update cidade set cod_tom = '4485' where uf = 11 and upper(trim(unaccent(nome))) like 'ESPINOSA'; 
update cidade set cod_tom = '4487' where uf = 11 and upper(trim(unaccent(nome))) like 'ESPIRITO SANTO DO DOURADO'; 
update cidade set cod_tom = '4489' where uf = 11 and upper(trim(unaccent(nome))) like 'ESTIVA'; 
update cidade set cod_tom = '4491' where uf = 11 and upper(trim(unaccent(nome))) like 'ESTRELA DALVA'; 
update cidade set cod_tom = '4493' where uf = 11 and upper(trim(unaccent(nome))) like 'ESTRELA DO INDAIA'; 
update cidade set cod_tom = '4495' where uf = 11 and upper(trim(unaccent(nome))) like 'ESTRELA DO SUL'; 
update cidade set cod_tom = '4497' where uf = 11 and upper(trim(unaccent(nome))) like 'EUGENOPOLIS'; 
update cidade set cod_tom = '4499' where uf = 11 and upper(trim(unaccent(nome))) like 'EWBANK DA CAMARA'; 
update cidade set cod_tom = '4501' where uf = 11 and upper(trim(unaccent(nome))) like 'EXTREMA'; 
update cidade set cod_tom = '4503' where uf = 11 and upper(trim(unaccent(nome))) like 'FAMA'; 
update cidade set cod_tom = '4505' where uf = 11 and upper(trim(unaccent(nome))) like 'FARIA LEMOS'; 
update cidade set cod_tom = '4507' where uf = 11 and upper(trim(unaccent(nome))) like 'FELICIO DOS SANTOS'; 
update cidade set cod_tom = '4511' where uf = 11 and upper(trim(unaccent(nome))) like 'FELISBURGO'; 
update cidade set cod_tom = '4513' where uf = 11 and upper(trim(unaccent(nome))) like 'FELIXLANDIA'; 
update cidade set cod_tom = '4515' where uf = 11 and upper(trim(unaccent(nome))) like 'FERNANDES TOURINHO'; 
update cidade set cod_tom = '4517' where uf = 11 and upper(trim(unaccent(nome))) like 'FERROS'; 
update cidade set cod_tom = '2683' where uf = 11 and upper(trim(unaccent(nome))) like 'FERVEDOURO'; 
update cidade set cod_tom = '4519' where uf = 11 and upper(trim(unaccent(nome))) like 'FLORESTAL'; 
update cidade set cod_tom = '4521' where uf = 11 and upper(trim(unaccent(nome))) like 'FORMIGA'; 
update cidade set cod_tom = '4523' where uf = 11 and upper(trim(unaccent(nome))) like 'FORMOSO'; 
update cidade set cod_tom = '4525' where uf = 11 and upper(trim(unaccent(nome))) like 'FORTALEZA DE MINAS'; 
update cidade set cod_tom = '4527' where uf = 11 and upper(trim(unaccent(nome))) like 'FORTUNA DE MINAS'; 
update cidade set cod_tom = '4529' where uf = 11 and upper(trim(unaccent(nome))) like 'FRANCISCO BADARO'; 
update cidade set cod_tom = '4531' where uf = 11 and upper(trim(unaccent(nome))) like 'FRANCISCO DUMONT'; 
update cidade set cod_tom = '4533' where uf = 11 and upper(trim(unaccent(nome))) like 'FRANCISCO SA'; 
update cidade set cod_tom = '0608' where uf = 11 and upper(trim(unaccent(nome))) like 'FRANCISCOPOLIS'; 
update cidade set cod_tom = '4535' where uf = 11 and upper(trim(unaccent(nome))) like 'FREI GASPAR'; 
update cidade set cod_tom = '4537' where uf = 11 and upper(trim(unaccent(nome))) like 'FREI INOCENCIO'; 
update cidade set cod_tom = '0610' where uf = 11 and upper(trim(unaccent(nome))) like 'FREI LAGONEGRO'; 
update cidade set cod_tom = '4539' where uf = 11 and upper(trim(unaccent(nome))) like 'FRONTEIRA'; 
update cidade set cod_tom = '4935' where uf = 11 and upper(trim(unaccent(nome))) like 'FRONTEIRA DOS VALES'; 
update cidade set cod_tom = '0612' where uf = 11 and upper(trim(unaccent(nome))) like 'FRUTA DE LEITE'; 
update cidade set cod_tom = '4541' where uf = 11 and upper(trim(unaccent(nome))) like 'FRUTAL'; 
update cidade set cod_tom = '4543' where uf = 11 and upper(trim(unaccent(nome))) like 'FUNILANDIA'; 
update cidade set cod_tom = '4545' where uf = 11 and upper(trim(unaccent(nome))) like 'GALILEIA'; 
update cidade set cod_tom = '0614' where uf = 11 and upper(trim(unaccent(nome))) like 'GAMELEIRAS'; 
update cidade set cod_tom = '0616' where uf = 11 and upper(trim(unaccent(nome))) like 'GLAUCILANDIA'; 
update cidade set cod_tom = '0618' where uf = 11 and upper(trim(unaccent(nome))) like 'GOIABEIRA'; 
update cidade set cod_tom = '0620' where uf = 11 and upper(trim(unaccent(nome))) like 'GOIANA'; 
update cidade set cod_tom = '4547' where uf = 11 and upper(trim(unaccent(nome))) like 'GONCALVES'; 
update cidade set cod_tom = '4549' where uf = 11 and upper(trim(unaccent(nome))) like 'GONZAGA'; 
update cidade set cod_tom = '4551' where uf = 11 and upper(trim(unaccent(nome))) like 'GOUVEA'; 
update cidade set cod_tom = '4553' where uf = 11 and upper(trim(unaccent(nome))) like 'GOVERNADOR VALADARES'; 
update cidade set cod_tom = '4555' where uf = 11 and upper(trim(unaccent(nome))) like 'GRAO MOGOL'; 
update cidade set cod_tom = '4557' where uf = 11 and upper(trim(unaccent(nome))) like 'GRUPIARA'; 
update cidade set cod_tom = '4559' where uf = 11 and upper(trim(unaccent(nome))) like 'GUANHAES'; 
update cidade set cod_tom = '4561' where uf = 11 and upper(trim(unaccent(nome))) like 'GUAPE'; 
update cidade set cod_tom = '4563' where uf = 11 and upper(trim(unaccent(nome))) like 'GUARACIABA'; 
update cidade set cod_tom = '0622' where uf = 11 and upper(trim(unaccent(nome))) like 'GUARACIAMA'; 
update cidade set cod_tom = '4565' where uf = 11 and upper(trim(unaccent(nome))) like 'GUARANESIA'; 
update cidade set cod_tom = '4567' where uf = 11 and upper(trim(unaccent(nome))) like 'GUARANI'; 
update cidade set cod_tom = '4569' where uf = 11 and upper(trim(unaccent(nome))) like 'GUARARA'; 
update cidade set cod_tom = '4571' where uf = 11 and upper(trim(unaccent(nome))) like 'GUARDA-MOR'; 
update cidade set cod_tom = '4573' where uf = 11 and upper(trim(unaccent(nome))) like 'GUAXUPE'; 
update cidade set cod_tom = '4575' where uf = 11 and upper(trim(unaccent(nome))) like 'GUIDOVAL'; 
update cidade set cod_tom = '4577' where uf = 11 and upper(trim(unaccent(nome))) like 'GUIMARANIA'; 
update cidade set cod_tom = '4579' where uf = 11 and upper(trim(unaccent(nome))) like 'GUIRICEMA'; 
update cidade set cod_tom = '4581' where uf = 11 and upper(trim(unaccent(nome))) like 'GURINHATA'; 
update cidade set cod_tom = '4583' where uf = 11 and upper(trim(unaccent(nome))) like 'HELIODORA'; 
update cidade set cod_tom = '4585' where uf = 11 and upper(trim(unaccent(nome))) like 'IAPU'; 
update cidade set cod_tom = '4587' where uf = 11 and upper(trim(unaccent(nome))) like 'IBERTIOGA'; 
update cidade set cod_tom = '4589' where uf = 11 and upper(trim(unaccent(nome))) like 'IBIA'; 
update cidade set cod_tom = '4591' where uf = 11 and upper(trim(unaccent(nome))) like 'IBIAI'; 
update cidade set cod_tom = '0624' where uf = 11 and upper(trim(unaccent(nome))) like 'IBIRACATU'; 
update cidade set cod_tom = '4593' where uf = 11 and upper(trim(unaccent(nome))) like 'IBIRACI'; 
update cidade set cod_tom = '4595' where uf = 11 and upper(trim(unaccent(nome))) like 'IBIRITE'; 
update cidade set cod_tom = '4597' where uf = 11 and upper(trim(unaccent(nome))) like 'IBITIURA DE MINAS'; 
update cidade set cod_tom = '4599' where uf = 11 and upper(trim(unaccent(nome))) like 'IBITURUNA'; 
update cidade set cod_tom = '2693' where uf = 11 and upper(trim(unaccent(nome))) like 'ICARAI DE MINAS'; 
update cidade set cod_tom = '4601' where uf = 11 and upper(trim(unaccent(nome))) like 'IGARAPE'; 
update cidade set cod_tom = '4603' where uf = 11 and upper(trim(unaccent(nome))) like 'IGARATINGA'; 
update cidade set cod_tom = '4605' where uf = 11 and upper(trim(unaccent(nome))) like 'IGUATAMA'; 
update cidade set cod_tom = '4607' where uf = 11 and upper(trim(unaccent(nome))) like 'IJACI'; 
update cidade set cod_tom = '4609' where uf = 11 and upper(trim(unaccent(nome))) like 'ILICINEA'; 
update cidade set cod_tom = '0626' where uf = 11 and upper(trim(unaccent(nome))) like 'IMBE DE MINAS'; 
update cidade set cod_tom = '4611' where uf = 11 and upper(trim(unaccent(nome))) like 'INCONFIDENTES'; 
update cidade set cod_tom = '0628' where uf = 11 and upper(trim(unaccent(nome))) like 'INDAIABIRA'; 
update cidade set cod_tom = '4613' where uf = 11 and upper(trim(unaccent(nome))) like 'INDIANOPOLIS'; 
update cidade set cod_tom = '4615' where uf = 11 and upper(trim(unaccent(nome))) like 'INGAI'; 
update cidade set cod_tom = '4617' where uf = 11 and upper(trim(unaccent(nome))) like 'INHAPIM'; 
update cidade set cod_tom = '4619' where uf = 11 and upper(trim(unaccent(nome))) like 'INHAUMA'; 
update cidade set cod_tom = '4621' where uf = 11 and upper(trim(unaccent(nome))) like 'INIMUTABA'; 
update cidade set cod_tom = '2665' where uf = 11 and upper(trim(unaccent(nome))) like 'IPABA'; 
update cidade set cod_tom = '4623' where uf = 11 and upper(trim(unaccent(nome))) like 'IPANEMA'; 
update cidade set cod_tom = '4625' where uf = 11 and upper(trim(unaccent(nome))) like 'IPATINGA'; 
update cidade set cod_tom = '4627' where uf = 11 and upper(trim(unaccent(nome))) like 'IPIACU'; 
update cidade set cod_tom = '4629' where uf = 11 and upper(trim(unaccent(nome))) like 'IPUIUNA'; 
update cidade set cod_tom = '4631' where uf = 11 and upper(trim(unaccent(nome))) like 'IRAI DE MINAS'; 
update cidade set cod_tom = '4633' where uf = 11 and upper(trim(unaccent(nome))) like 'ITABIRA'; 
update cidade set cod_tom = '4635' where uf = 11 and upper(trim(unaccent(nome))) like 'ITABIRINHA'; 
update cidade set cod_tom = '4637' where uf = 11 and upper(trim(unaccent(nome))) like 'ITABIRITO'; 
update cidade set cod_tom = '4639' where uf = 11 and upper(trim(unaccent(nome))) like 'ITACAMBIRA'; 
update cidade set cod_tom = '4641' where uf = 11 and upper(trim(unaccent(nome))) like 'ITACARAMBI'; 
update cidade set cod_tom = '4643' where uf = 11 and upper(trim(unaccent(nome))) like 'ITAGUARA'; 
update cidade set cod_tom = '4645' where uf = 11 and upper(trim(unaccent(nome))) like 'ITAIPE'; 
update cidade set cod_tom = '4647' where uf = 11 and upper(trim(unaccent(nome))) like 'ITAJUBA'; 
update cidade set cod_tom = '4649' where uf = 11 and upper(trim(unaccent(nome))) like 'ITAMARANDIBA'; 
update cidade set cod_tom = '4651' where uf = 11 and upper(trim(unaccent(nome))) like 'ITAMARATI DE MINAS'; 
update cidade set cod_tom = '4653' where uf = 11 and upper(trim(unaccent(nome))) like 'ITAMBACURI'; 
update cidade set cod_tom = '4655' where uf = 11 and upper(trim(unaccent(nome))) like 'ITAMBE DO MATO DENTRO'; 
update cidade set cod_tom = '4657' where uf = 11 and upper(trim(unaccent(nome))) like 'ITAMOGI'; 
update cidade set cod_tom = '4659' where uf = 11 and upper(trim(unaccent(nome))) like 'ITAMONTE'; 
update cidade set cod_tom = '4661' where uf = 11 and upper(trim(unaccent(nome))) like 'ITANHANDU'; 
update cidade set cod_tom = '4663' where uf = 11 and upper(trim(unaccent(nome))) like 'ITANHOMI'; 
update cidade set cod_tom = '4665' where uf = 11 and upper(trim(unaccent(nome))) like 'ITAOBIM'; 
update cidade set cod_tom = '4667' where uf = 11 and upper(trim(unaccent(nome))) like 'ITAPAGIPE'; 
update cidade set cod_tom = '4669' where uf = 11 and upper(trim(unaccent(nome))) like 'ITAPECERICA'; 
update cidade set cod_tom = '4671' where uf = 11 and upper(trim(unaccent(nome))) like 'ITAPEVA'; 
update cidade set cod_tom = '4673' where uf = 11 and upper(trim(unaccent(nome))) like 'ITATIAIUCU'; 
update cidade set cod_tom = '5731' where uf = 11 and upper(trim(unaccent(nome))) like 'ITAU DE MINAS'; 
update cidade set cod_tom = '4675' where uf = 11 and upper(trim(unaccent(nome))) like 'ITAUNA'; 
update cidade set cod_tom = '4677' where uf = 11 and upper(trim(unaccent(nome))) like 'ITAVERAVA'; 
update cidade set cod_tom = '4679' where uf = 11 and upper(trim(unaccent(nome))) like 'ITINGA'; 
update cidade set cod_tom = '4681' where uf = 11 and upper(trim(unaccent(nome))) like 'ITUETA'; 
update cidade set cod_tom = '4683' where uf = 11 and upper(trim(unaccent(nome))) like 'ITUIUTABA'; 
update cidade set cod_tom = '4685' where uf = 11 and upper(trim(unaccent(nome))) like 'ITUMIRIM'; 
update cidade set cod_tom = '4687' where uf = 11 and upper(trim(unaccent(nome))) like 'ITURAMA'; 
update cidade set cod_tom = '4689' where uf = 11 and upper(trim(unaccent(nome))) like 'ITUTINGA'; 
update cidade set cod_tom = '4691' where uf = 11 and upper(trim(unaccent(nome))) like 'JABOTICATUBAS'; 
update cidade set cod_tom = '4693' where uf = 11 and upper(trim(unaccent(nome))) like 'JACINTO'; 
update cidade set cod_tom = '4695' where uf = 11 and upper(trim(unaccent(nome))) like 'JACUI'; 
update cidade set cod_tom = '4697' where uf = 11 and upper(trim(unaccent(nome))) like 'JACUTINGA'; 
update cidade set cod_tom = '4699' where uf = 11 and upper(trim(unaccent(nome))) like 'JAGUARACU'; 
update cidade set cod_tom = '2893' where uf = 11 and upper(trim(unaccent(nome))) like 'JAIBA'; 
update cidade set cod_tom = '2655' where uf = 11 and upper(trim(unaccent(nome))) like 'JAMPRUCA'; 
update cidade set cod_tom = '4701' where uf = 11 and upper(trim(unaccent(nome))) like 'JANAUBA'; 
update cidade set cod_tom = '4703' where uf = 11 and upper(trim(unaccent(nome))) like 'JANUARIA'; 
update cidade set cod_tom = '4705' where uf = 11 and upper(trim(unaccent(nome))) like 'JAPARAIBA'; 
update cidade set cod_tom = '0630' where uf = 11 and upper(trim(unaccent(nome))) like 'JAPONVAR'; 
update cidade set cod_tom = '4707' where uf = 11 and upper(trim(unaccent(nome))) like 'JECEABA'; 
update cidade set cod_tom = '0632' where uf = 11 and upper(trim(unaccent(nome))) like 'JENIPAPO DE MINAS'; 
update cidade set cod_tom = '4709' where uf = 11 and upper(trim(unaccent(nome))) like 'JEQUERI'; 
update cidade set cod_tom = '4711' where uf = 11 and upper(trim(unaccent(nome))) like 'JEQUITAI'; 
update cidade set cod_tom = '4713' where uf = 11 and upper(trim(unaccent(nome))) like 'JEQUITIBA'; 
update cidade set cod_tom = '4715' where uf = 11 and upper(trim(unaccent(nome))) like 'JEQUITINHONHA'; 
update cidade set cod_tom = '4717' where uf = 11 and upper(trim(unaccent(nome))) like 'JESUANIA'; 
update cidade set cod_tom = '4719' where uf = 11 and upper(trim(unaccent(nome))) like 'JOAIMA'; 
update cidade set cod_tom = '4721' where uf = 11 and upper(trim(unaccent(nome))) like 'JOANESIA'; 
update cidade set cod_tom = '4723' where uf = 11 and upper(trim(unaccent(nome))) like 'JOAO MONLEVADE'; 
update cidade set cod_tom = '4725' where uf = 11 and upper(trim(unaccent(nome))) like 'JOAO PINHEIRO'; 
update cidade set cod_tom = '4727' where uf = 11 and upper(trim(unaccent(nome))) like 'JOAQUIM FELICIO'; 
update cidade set cod_tom = '4729' where uf = 11 and upper(trim(unaccent(nome))) like 'JORDANIA'; 
update cidade set cod_tom = '0634' where uf = 11 and upper(trim(unaccent(nome))) like 'JOSE GONCALVES DE MINAS'; 
update cidade set cod_tom = '0636' where uf = 11 and upper(trim(unaccent(nome))) like 'JOSE RAYDAN'; 
update cidade set cod_tom = '0638' where uf = 11 and upper(trim(unaccent(nome))) like 'JOSENOPOLIS'; 
update cidade set cod_tom = '2691' where uf = 11 and upper(trim(unaccent(nome))) like 'JUATUBA'; 
update cidade set cod_tom = '4733' where uf = 11 and upper(trim(unaccent(nome))) like 'JUIZ DE FORA'; 
update cidade set cod_tom = '4735' where uf = 11 and upper(trim(unaccent(nome))) like 'JURAMENTO'; 
update cidade set cod_tom = '4737' where uf = 11 and upper(trim(unaccent(nome))) like 'JURUAIA'; 
update cidade set cod_tom = '0640' where uf = 11 and upper(trim(unaccent(nome))) like 'JUVENILIA'; 
update cidade set cod_tom = '4739' where uf = 11 and upper(trim(unaccent(nome))) like 'LADAINHA'; 
update cidade set cod_tom = '4741' where uf = 11 and upper(trim(unaccent(nome))) like 'LAGAMAR'; 
update cidade set cod_tom = '4743' where uf = 11 and upper(trim(unaccent(nome))) like 'LAGOA DA PRATA'; 
update cidade set cod_tom = '4745' where uf = 11 and upper(trim(unaccent(nome))) like 'LAGOA DOS PATOS'; 
update cidade set cod_tom = '4747' where uf = 11 and upper(trim(unaccent(nome))) like 'LAGOA DOURADA'; 
update cidade set cod_tom = '4749' where uf = 11 and upper(trim(unaccent(nome))) like 'LAGOA FORMOSA'; 
update cidade set cod_tom = '2905' where uf = 11 and upper(trim(unaccent(nome))) like 'LAGOA GRANDE'; 
update cidade set cod_tom = '4751' where uf = 11 and upper(trim(unaccent(nome))) like 'LAGOA SANTA'; 
update cidade set cod_tom = '4753' where uf = 11 and upper(trim(unaccent(nome))) like 'LAJINHA'; 
update cidade set cod_tom = '4755' where uf = 11 and upper(trim(unaccent(nome))) like 'LAMBARI'; 
update cidade set cod_tom = '4757' where uf = 11 and upper(trim(unaccent(nome))) like 'LAMIM'; 
update cidade set cod_tom = '4759' where uf = 11 and upper(trim(unaccent(nome))) like 'LARANJAL'; 
update cidade set cod_tom = '4761' where uf = 11 and upper(trim(unaccent(nome))) like 'LASSANCE'; 
update cidade set cod_tom = '4763' where uf = 11 and upper(trim(unaccent(nome))) like 'LAVRAS'; 
update cidade set cod_tom = '4765' where uf = 11 and upper(trim(unaccent(nome))) like 'LEANDRO FERREIRA'; 
update cidade set cod_tom = '0642' where uf = 11 and upper(trim(unaccent(nome))) like 'LEME DO PRADO'; 
update cidade set cod_tom = '4767' where uf = 11 and upper(trim(unaccent(nome))) like 'LEOPOLDINA'; 
update cidade set cod_tom = '4769' where uf = 11 and upper(trim(unaccent(nome))) like 'LIBERDADE'; 
update cidade set cod_tom = '4771' where uf = 11 and upper(trim(unaccent(nome))) like 'LIMA DUARTE'; 
update cidade set cod_tom = '2687' where uf = 11 and upper(trim(unaccent(nome))) like 'LIMEIRA DO OESTE'; 
update cidade set cod_tom = '2695' where uf = 11 and upper(trim(unaccent(nome))) like 'LONTRA'; 
update cidade set cod_tom = '0644' where uf = 11 and upper(trim(unaccent(nome))) like 'LUISBURGO'; 
update cidade set cod_tom = '0646' where uf = 11 and upper(trim(unaccent(nome))) like 'LUISLANDIA'; 
update cidade set cod_tom = '4773' where uf = 11 and upper(trim(unaccent(nome))) like 'LUMINARIAS'; 
update cidade set cod_tom = '4775' where uf = 11 and upper(trim(unaccent(nome))) like 'LUZ'; 
update cidade set cod_tom = '4777' where uf = 11 and upper(trim(unaccent(nome))) like 'MACHACALIS'; 
update cidade set cod_tom = '4779' where uf = 11 and upper(trim(unaccent(nome))) like 'MACHADO'; 
update cidade set cod_tom = '4781' where uf = 11 and upper(trim(unaccent(nome))) like 'MADRE DE DEUS DE MINAS'; 
update cidade set cod_tom = '4783' where uf = 11 and upper(trim(unaccent(nome))) like 'MALACACHETA'; 
update cidade set cod_tom = '2895' where uf = 11 and upper(trim(unaccent(nome))) like 'MAMONAS'; 
update cidade set cod_tom = '4785' where uf = 11 and upper(trim(unaccent(nome))) like 'MANGA'; 
update cidade set cod_tom = '4787' where uf = 11 and upper(trim(unaccent(nome))) like 'MANHUACU'; 
update cidade set cod_tom = '4789' where uf = 11 and upper(trim(unaccent(nome))) like 'MANHUMIRIM'; 
update cidade set cod_tom = '4791' where uf = 11 and upper(trim(unaccent(nome))) like 'MANTENA'; 
update cidade set cod_tom = '4795' where uf = 11 and upper(trim(unaccent(nome))) like 'MAR DE ESPANHA'; 
update cidade set cod_tom = '4793' where uf = 11 and upper(trim(unaccent(nome))) like 'MARAVILHAS'; 
update cidade set cod_tom = '4797' where uf = 11 and upper(trim(unaccent(nome))) like 'MARIA DA FE'; 
update cidade set cod_tom = '4799' where uf = 11 and upper(trim(unaccent(nome))) like 'MARIANA'; 
update cidade set cod_tom = '4801' where uf = 11 and upper(trim(unaccent(nome))) like 'MARILAC'; 
update cidade set cod_tom = '0648' where uf = 11 and upper(trim(unaccent(nome))) like 'MARIO CAMPOS'; 
update cidade set cod_tom = '4803' where uf = 11 and upper(trim(unaccent(nome))) like 'MARIPA DE MINAS'; 
update cidade set cod_tom = '4805' where uf = 11 and upper(trim(unaccent(nome))) like 'MARLIERIA'; 
update cidade set cod_tom = '4807' where uf = 11 and upper(trim(unaccent(nome))) like 'MARMELOPOLIS'; 
update cidade set cod_tom = '4809' where uf = 11 and upper(trim(unaccent(nome))) like 'MARTINHO CAMPOS'; 
update cidade set cod_tom = '0650' where uf = 11 and upper(trim(unaccent(nome))) like 'MARTINS SOARES'; 
update cidade set cod_tom = '2659' where uf = 11 and upper(trim(unaccent(nome))) like 'MATA VERDE'; 
update cidade set cod_tom = '4811' where uf = 11 and upper(trim(unaccent(nome))) like 'MATERLANDIA'; 
update cidade set cod_tom = '4813' where uf = 11 and upper(trim(unaccent(nome))) like 'MATEUS LEME'; 
update cidade set cod_tom = '5431' where uf = 11 and upper(trim(unaccent(nome))) like 'MATHIAS LOBATO'; 
update cidade set cod_tom = '4815' where uf = 11 and upper(trim(unaccent(nome))) like 'MATIAS BARBOSA'; 
update cidade set cod_tom = '2897' where uf = 11 and upper(trim(unaccent(nome))) like 'MATIAS CARDOSO'; 
update cidade set cod_tom = '4817' where uf = 11 and upper(trim(unaccent(nome))) like 'MATIPO'; 
update cidade set cod_tom = '4819' where uf = 11 and upper(trim(unaccent(nome))) like 'MATO VERDE'; 
update cidade set cod_tom = '4821' where uf = 11 and upper(trim(unaccent(nome))) like 'MATOZINHOS'; 
update cidade set cod_tom = '4823' where uf = 11 and upper(trim(unaccent(nome))) like 'MATUTINA'; 
update cidade set cod_tom = '4825' where uf = 11 and upper(trim(unaccent(nome))) like 'MEDEIROS'; 
update cidade set cod_tom = '4827' where uf = 11 and upper(trim(unaccent(nome))) like 'MEDINA'; 
update cidade set cod_tom = '4829' where uf = 11 and upper(trim(unaccent(nome))) like 'MENDES PIMENTEL'; 
update cidade set cod_tom = '4831' where uf = 11 and upper(trim(unaccent(nome))) like 'MERCES'; 
update cidade set cod_tom = '4833' where uf = 11 and upper(trim(unaccent(nome))) like 'MESQUITA'; 
update cidade set cod_tom = '4835' where uf = 11 and upper(trim(unaccent(nome))) like 'MINAS NOVAS'; 
update cidade set cod_tom = '4837' where uf = 11 and upper(trim(unaccent(nome))) like 'MINDURI'; 
update cidade set cod_tom = '4839' where uf = 11 and upper(trim(unaccent(nome))) like 'MIRABELA'; 
update cidade set cod_tom = '4841' where uf = 11 and upper(trim(unaccent(nome))) like 'MIRADOURO'; 
update cidade set cod_tom = '4843' where uf = 11 and upper(trim(unaccent(nome))) like 'MIRAI'; 
update cidade set cod_tom = '0652' where uf = 11 and upper(trim(unaccent(nome))) like 'MIRAVANIA'; 
update cidade set cod_tom = '4845' where uf = 11 and upper(trim(unaccent(nome))) like 'MOEDA'; 
update cidade set cod_tom = '4847' where uf = 11 and upper(trim(unaccent(nome))) like 'MOEMA'; 
update cidade set cod_tom = '4849' where uf = 11 and upper(trim(unaccent(nome))) like 'MONJOLOS'; 
update cidade set cod_tom = '4851' where uf = 11 and upper(trim(unaccent(nome))) like 'MONSENHOR PAULO'; 
update cidade set cod_tom = '4853' where uf = 11 and upper(trim(unaccent(nome))) like 'MONTALVANIA'; 
update cidade set cod_tom = '4855' where uf = 11 and upper(trim(unaccent(nome))) like 'MONTE ALEGRE DE MINAS'; 
update cidade set cod_tom = '4857' where uf = 11 and upper(trim(unaccent(nome))) like 'MONTE AZUL'; 
update cidade set cod_tom = '4859' where uf = 11 and upper(trim(unaccent(nome))) like 'MONTE BELO'; 
update cidade set cod_tom = '4861' where uf = 11 and upper(trim(unaccent(nome))) like 'MONTE CARMELO'; 
update cidade set cod_tom = '0654' where uf = 11 and upper(trim(unaccent(nome))) like 'MONTE FORMOSO'; 
update cidade set cod_tom = '4863' where uf = 11 and upper(trim(unaccent(nome))) like 'MONTE SANTO DE MINAS'; 
update cidade set cod_tom = '4867' where uf = 11 and upper(trim(unaccent(nome))) like 'MONTE SIAO'; 
update cidade set cod_tom = '4865' where uf = 11 and upper(trim(unaccent(nome))) like 'MONTES CLAROS'; 
update cidade set cod_tom = '2697' where uf = 11 and upper(trim(unaccent(nome))) like 'MONTEZUMA'; 
update cidade set cod_tom = '4869' where uf = 11 and upper(trim(unaccent(nome))) like 'MORADA NOVA DE MINAS'; 
update cidade set cod_tom = '4871' where uf = 11 and upper(trim(unaccent(nome))) like 'MORRO DA GARCA'; 
update cidade set cod_tom = '4873' where uf = 11 and upper(trim(unaccent(nome))) like 'MORRO DO PILAR'; 
update cidade set cod_tom = '4875' where uf = 11 and upper(trim(unaccent(nome))) like 'MUNHOZ'; 
update cidade set cod_tom = '4877' where uf = 11 and upper(trim(unaccent(nome))) like 'MURIAE'; 
update cidade set cod_tom = '4879' where uf = 11 and upper(trim(unaccent(nome))) like 'MUTUM'; 
update cidade set cod_tom = '4881' where uf = 11 and upper(trim(unaccent(nome))) like 'MUZAMBINHO'; 
update cidade set cod_tom = '4883' where uf = 11 and upper(trim(unaccent(nome))) like 'NACIP RAYDAN'; 
update cidade set cod_tom = '4885' where uf = 11 and upper(trim(unaccent(nome))) like 'NANUQUE'; 
update cidade set cod_tom = '0656' where uf = 11 and upper(trim(unaccent(nome))) like 'NAQUE'; 
update cidade set cod_tom = '0658' where uf = 11 and upper(trim(unaccent(nome))) like 'NATALANDIA'; 
update cidade set cod_tom = '4887' where uf = 11 and upper(trim(unaccent(nome))) like 'NATERCIA'; 
update cidade set cod_tom = '4889' where uf = 11 and upper(trim(unaccent(nome))) like 'NAZARENO'; 
update cidade set cod_tom = '4891' where uf = 11 and upper(trim(unaccent(nome))) like 'NEPOMUCENO'; 
update cidade set cod_tom = '0660' where uf = 11 and upper(trim(unaccent(nome))) like 'NINHEIRA'; 
update cidade set cod_tom = '0662' where uf = 11 and upper(trim(unaccent(nome))) like 'NOVA BELEM'; 
update cidade set cod_tom = '4893' where uf = 11 and upper(trim(unaccent(nome))) like 'NOVA ERA'; 
update cidade set cod_tom = '4895' where uf = 11 and upper(trim(unaccent(nome))) like 'NOVA LIMA'; 
update cidade set cod_tom = '4897' where uf = 11 and upper(trim(unaccent(nome))) like 'NOVA MODICA'; 
update cidade set cod_tom = '4899' where uf = 11 and upper(trim(unaccent(nome))) like 'NOVA PONTE'; 
update cidade set cod_tom = '0664' where uf = 11 and upper(trim(unaccent(nome))) like 'NOVA PORTEIRINHA'; 
update cidade set cod_tom = '4901' where uf = 11 and upper(trim(unaccent(nome))) like 'NOVA RESENDE'; 
update cidade set cod_tom = '4903' where uf = 11 and upper(trim(unaccent(nome))) like 'NOVA SERRANA'; 
update cidade set cod_tom = '4731' where uf = 11 and upper(trim(unaccent(nome))) like 'NOVA UNIAO'; 
update cidade set cod_tom = '4905' where uf = 11 and upper(trim(unaccent(nome))) like 'NOVO CRUZEIRO'; 
update cidade set cod_tom = '0666' where uf = 11 and upper(trim(unaccent(nome))) like 'NOVO ORIENTE DE MINAS'; 
update cidade set cod_tom = '0668' where uf = 11 and upper(trim(unaccent(nome))) like 'NOVORIZONTE'; 
update cidade set cod_tom = '4907' where uf = 11 and upper(trim(unaccent(nome))) like 'OLARIA'; 
update cidade set cod_tom = '0670' where uf = 11 and upper(trim(unaccent(nome))) like 'OLHOS-D`AGUA'; 
update cidade set cod_tom = '4909' where uf = 11 and upper(trim(unaccent(nome))) like 'OLIMPIO NORONHA'; 
update cidade set cod_tom = '4911' where uf = 11 and upper(trim(unaccent(nome))) like 'OLIVEIRA'; 
update cidade set cod_tom = '4913' where uf = 11 and upper(trim(unaccent(nome))) like 'OLIVEIRA FORTES'; 
update cidade set cod_tom = '4915' where uf = 11 and upper(trim(unaccent(nome))) like 'ONCA DE PITANGUI'; 
update cidade set cod_tom = '0672' where uf = 11 and upper(trim(unaccent(nome))) like 'ORATORIOS'; 
update cidade set cod_tom = '0674' where uf = 11 and upper(trim(unaccent(nome))) like 'ORIZANIA'; 
update cidade set cod_tom = '4917' where uf = 11 and upper(trim(unaccent(nome))) like 'OURO BRANCO'; 
update cidade set cod_tom = '4919' where uf = 11 and upper(trim(unaccent(nome))) like 'OURO FINO'; 
update cidade set cod_tom = '4921' where uf = 11 and upper(trim(unaccent(nome))) like 'OURO PRETO'; 
update cidade set cod_tom = '4923' where uf = 11 and upper(trim(unaccent(nome))) like 'OURO VERDE DE MINAS'; 
update cidade set cod_tom = '0676' where uf = 11 and upper(trim(unaccent(nome))) like 'PADRE CARVALHO'; 
update cidade set cod_tom = '4925' where uf = 11 and upper(trim(unaccent(nome))) like 'PADRE PARAISO'; 
update cidade set cod_tom = '0678' where uf = 11 and upper(trim(unaccent(nome))) like 'PAI PEDRO'; 
update cidade set cod_tom = '4927' where uf = 11 and upper(trim(unaccent(nome))) like 'PAINEIRAS'; 
update cidade set cod_tom = '4929' where uf = 11 and upper(trim(unaccent(nome))) like 'PAINS'; 
update cidade set cod_tom = '4931' where uf = 11 and upper(trim(unaccent(nome))) like 'PAIVA'; 
update cidade set cod_tom = '4933' where uf = 11 and upper(trim(unaccent(nome))) like 'PALMA'; 
update cidade set cod_tom = '2661' where uf = 11 and upper(trim(unaccent(nome))) like 'PALMOPOLIS'; 
update cidade set cod_tom = '4937' where uf = 11 and upper(trim(unaccent(nome))) like 'PAPAGAIOS'; 
update cidade set cod_tom = '4941' where uf = 11 and upper(trim(unaccent(nome))) like 'PARA DE MINAS'; 
update cidade set cod_tom = '4939' where uf = 11 and upper(trim(unaccent(nome))) like 'PARACATU'; 
update cidade set cod_tom = '4943' where uf = 11 and upper(trim(unaccent(nome))) like 'PARAGUACU'; 
update cidade set cod_tom = '4945' where uf = 11 and upper(trim(unaccent(nome))) like 'PARAISOPOLIS'; 
update cidade set cod_tom = '4947' where uf = 11 and upper(trim(unaccent(nome))) like 'PARAOPEBA'; 
update cidade set cod_tom = '4951' where uf = 11 and upper(trim(unaccent(nome))) like 'PASSA QUATRO'; 
update cidade set cod_tom = '4953' where uf = 11 and upper(trim(unaccent(nome))) like 'PASSA TEMPO'; 
update cidade set cod_tom = '4955' where uf = 11 and upper(trim(unaccent(nome))) like 'PASSA VINTE'; 
update cidade set cod_tom = '4949' where uf = 11 and upper(trim(unaccent(nome))) like 'PASSABEM'; 
update cidade set cod_tom = '4957' where uf = 11 and upper(trim(unaccent(nome))) like 'PASSOS'; 
update cidade set cod_tom = '0680' where uf = 11 and upper(trim(unaccent(nome))) like 'PATIS'; 
update cidade set cod_tom = '4959' where uf = 11 and upper(trim(unaccent(nome))) like 'PATOS DE MINAS'; 
update cidade set cod_tom = '4961' where uf = 11 and upper(trim(unaccent(nome))) like 'PATROCINIO'; 
update cidade set cod_tom = '4963' where uf = 11 and upper(trim(unaccent(nome))) like 'PATROCINIO DO MURIAE'; 
update cidade set cod_tom = '4965' where uf = 11 and upper(trim(unaccent(nome))) like 'PAULA CANDIDO'; 
update cidade set cod_tom = '4967' where uf = 11 and upper(trim(unaccent(nome))) like 'PAULISTAS'; 
update cidade set cod_tom = '4969' where uf = 11 and upper(trim(unaccent(nome))) like 'PAVAO'; 
update cidade set cod_tom = '4971' where uf = 11 and upper(trim(unaccent(nome))) like 'PECANHA'; 
update cidade set cod_tom = '4973' where uf = 11 and upper(trim(unaccent(nome))) like 'PEDRA AZUL'; 
update cidade set cod_tom = '0682' where uf = 11 and upper(trim(unaccent(nome))) like 'PEDRA BONITA'; 
update cidade set cod_tom = '4975' where uf = 11 and upper(trim(unaccent(nome))) like 'PEDRA DO ANTA'; 
update cidade set cod_tom = '4977' where uf = 11 and upper(trim(unaccent(nome))) like 'PEDRA DO INDAIA'; 
update cidade set cod_tom = '4979' where uf = 11 and upper(trim(unaccent(nome))) like 'PEDRA DOURADA'; 
update cidade set cod_tom = '4981' where uf = 11 and upper(trim(unaccent(nome))) like 'PEDRALVA'; 
update cidade set cod_tom = '2899' where uf = 11 and upper(trim(unaccent(nome))) like 'PEDRAS DE MARIA DA CRUZ'; 
update cidade set cod_tom = '4983' where uf = 11 and upper(trim(unaccent(nome))) like 'PEDRINOPOLIS'; 
update cidade set cod_tom = '4985' where uf = 11 and upper(trim(unaccent(nome))) like 'PEDRO LEOPOLDO'; 
update cidade set cod_tom = '4987' where uf = 11 and upper(trim(unaccent(nome))) like 'PEDRO TEIXEIRA'; 
update cidade set cod_tom = '4989' where uf = 11 and upper(trim(unaccent(nome))) like 'PEQUERI'; 
update cidade set cod_tom = '4991' where uf = 11 and upper(trim(unaccent(nome))) like 'PEQUI'; 
update cidade set cod_tom = '4993' where uf = 11 and upper(trim(unaccent(nome))) like 'PERDIGAO'; 
update cidade set cod_tom = '4995' where uf = 11 and upper(trim(unaccent(nome))) like 'PERDIZES'; 
update cidade set cod_tom = '4997' where uf = 11 and upper(trim(unaccent(nome))) like 'PERDOES'; 
update cidade set cod_tom = '0684' where uf = 11 and upper(trim(unaccent(nome))) like 'PERIQUITO'; 
update cidade set cod_tom = '4999' where uf = 11 and upper(trim(unaccent(nome))) like 'PESCADOR'; 
update cidade set cod_tom = '5001' where uf = 11 and upper(trim(unaccent(nome))) like 'PIAU'; 
update cidade set cod_tom = '0686' where uf = 11 and upper(trim(unaccent(nome))) like 'PIEDADE DE CARATINGA'; 
update cidade set cod_tom = '5003' where uf = 11 and upper(trim(unaccent(nome))) like 'PIEDADE DE PONTE NOVA'; 
update cidade set cod_tom = '5005' where uf = 11 and upper(trim(unaccent(nome))) like 'PIEDADE DO RIO GRANDE'; 
update cidade set cod_tom = '5007' where uf = 11 and upper(trim(unaccent(nome))) like 'PIEDADE DOS GERAIS'; 
update cidade set cod_tom = '5009' where uf = 11 and upper(trim(unaccent(nome))) like 'PIMENTA'; 
update cidade set cod_tom = '0688' where uf = 11 and upper(trim(unaccent(nome))) like 'PINGO D`AGUA'; 
update cidade set cod_tom = '0690' where uf = 11 and upper(trim(unaccent(nome))) like 'PINTOPOLIS'; 
update cidade set cod_tom = '5011' where uf = 11 and upper(trim(unaccent(nome))) like 'PIRACEMA'; 
update cidade set cod_tom = '5013' where uf = 11 and upper(trim(unaccent(nome))) like 'PIRAJUBA'; 
update cidade set cod_tom = '5015' where uf = 11 and upper(trim(unaccent(nome))) like 'PIRANGA'; 
update cidade set cod_tom = '5017' where uf = 11 and upper(trim(unaccent(nome))) like 'PIRANGUCU'; 
update cidade set cod_tom = '5019' where uf = 11 and upper(trim(unaccent(nome))) like 'PIRANGUINHO'; 
update cidade set cod_tom = '5021' where uf = 11 and upper(trim(unaccent(nome))) like 'PIRAPETINGA'; 
update cidade set cod_tom = '5023' where uf = 11 and upper(trim(unaccent(nome))) like 'PIRAPORA'; 
update cidade set cod_tom = '5025' where uf = 11 and upper(trim(unaccent(nome))) like 'PIRAUBA'; 
update cidade set cod_tom = '5027' where uf = 11 and upper(trim(unaccent(nome))) like 'PITANGUI'; 
update cidade set cod_tom = '5029' where uf = 11 and upper(trim(unaccent(nome))) like 'PIUMHI'; 
update cidade set cod_tom = '5031' where uf = 11 and upper(trim(unaccent(nome))) like 'PLANURA'; 
update cidade set cod_tom = '5033' where uf = 11 and upper(trim(unaccent(nome))) like 'POCO FUNDO'; 
update cidade set cod_tom = '5035' where uf = 11 and upper(trim(unaccent(nome))) like 'POCOS DE CALDAS'; 
update cidade set cod_tom = '5037' where uf = 11 and upper(trim(unaccent(nome))) like 'POCRANE'; 
update cidade set cod_tom = '5039' where uf = 11 and upper(trim(unaccent(nome))) like 'POMPEU'; 
update cidade set cod_tom = '5041' where uf = 11 and upper(trim(unaccent(nome))) like 'PONTE NOVA'; 
update cidade set cod_tom = '0692' where uf = 11 and upper(trim(unaccent(nome))) like 'PONTO CHIQUE'; 
update cidade set cod_tom = '0694' where uf = 11 and upper(trim(unaccent(nome))) like 'PONTO DOS VOLANTES'; 
update cidade set cod_tom = '5043' where uf = 11 and upper(trim(unaccent(nome))) like 'PORTEIRINHA'; 
update cidade set cod_tom = '5045' where uf = 11 and upper(trim(unaccent(nome))) like 'PORTO FIRME'; 
update cidade set cod_tom = '5047' where uf = 11 and upper(trim(unaccent(nome))) like 'POTE'; 
update cidade set cod_tom = '5049' where uf = 11 and upper(trim(unaccent(nome))) like 'POUSO ALEGRE'; 
update cidade set cod_tom = '5051' where uf = 11 and upper(trim(unaccent(nome))) like 'POUSO ALTO'; 
update cidade set cod_tom = '5053' where uf = 11 and upper(trim(unaccent(nome))) like 'PRADOS'; 
update cidade set cod_tom = '5055' where uf = 11 and upper(trim(unaccent(nome))) like 'PRATA'; 
update cidade set cod_tom = '5057' where uf = 11 and upper(trim(unaccent(nome))) like 'PRATAPOLIS'; 
update cidade set cod_tom = '5059' where uf = 11 and upper(trim(unaccent(nome))) like 'PRATINHA'; 
update cidade set cod_tom = '5061' where uf = 11 and upper(trim(unaccent(nome))) like 'PRESIDENTE BERNARDES'; 
update cidade set cod_tom = '5063' where uf = 11 and upper(trim(unaccent(nome))) like 'PRESIDENTE JUSCELINO'; 
update cidade set cod_tom = '5065' where uf = 11 and upper(trim(unaccent(nome))) like 'PRESIDENTE KUBITSCHEK'; 
update cidade set cod_tom = '5067' where uf = 11 and upper(trim(unaccent(nome))) like 'PRESIDENTE OLEGARIO'; 
update cidade set cod_tom = '5071' where uf = 11 and upper(trim(unaccent(nome))) like 'PRUDENTE DE MORAIS'; 
update cidade set cod_tom = '5073' where uf = 11 and upper(trim(unaccent(nome))) like 'QUARTEL GERAL'; 
update cidade set cod_tom = '5075' where uf = 11 and upper(trim(unaccent(nome))) like 'QUELUZITO'; 
update cidade set cod_tom = '5077' where uf = 11 and upper(trim(unaccent(nome))) like 'RAPOSOS'; 
update cidade set cod_tom = '5079' where uf = 11 and upper(trim(unaccent(nome))) like 'RAUL SOARES'; 
update cidade set cod_tom = '5081' where uf = 11 and upper(trim(unaccent(nome))) like 'RECREIO'; 
update cidade set cod_tom = '0696' where uf = 11 and upper(trim(unaccent(nome))) like 'REDUTO'; 
update cidade set cod_tom = '5083' where uf = 11 and upper(trim(unaccent(nome))) like 'RESENDE COSTA'; 
update cidade set cod_tom = '5085' where uf = 11 and upper(trim(unaccent(nome))) like 'RESPLENDOR'; 
update cidade set cod_tom = '5087' where uf = 11 and upper(trim(unaccent(nome))) like 'RESSAQUINHA'; 
update cidade set cod_tom = '2901' where uf = 11 and upper(trim(unaccent(nome))) like 'RIACHINHO'; 
update cidade set cod_tom = '5089' where uf = 11 and upper(trim(unaccent(nome))) like 'RIACHO DOS MACHADOS'; 
update cidade set cod_tom = '5091' where uf = 11 and upper(trim(unaccent(nome))) like 'RIBEIRAO DAS NEVES'; 
update cidade set cod_tom = '5093' where uf = 11 and upper(trim(unaccent(nome))) like 'RIBEIRAO VERMELHO'; 
update cidade set cod_tom = '5095' where uf = 11 and upper(trim(unaccent(nome))) like 'RIO ACIMA'; 
update cidade set cod_tom = '5097' where uf = 11 and upper(trim(unaccent(nome))) like 'RIO CASCA'; 
update cidade set cod_tom = '5101' where uf = 11 and upper(trim(unaccent(nome))) like 'RIO DO PRADO'; 
update cidade set cod_tom = '5099' where uf = 11 and upper(trim(unaccent(nome))) like 'RIO DOCE'; 
update cidade set cod_tom = '5103' where uf = 11 and upper(trim(unaccent(nome))) like 'RIO ESPERA'; 
update cidade set cod_tom = '5105' where uf = 11 and upper(trim(unaccent(nome))) like 'RIO MANSO'; 
update cidade set cod_tom = '5107' where uf = 11 and upper(trim(unaccent(nome))) like 'RIO NOVO'; 
update cidade set cod_tom = '5109' where uf = 11 and upper(trim(unaccent(nome))) like 'RIO PARANAIBA'; 
update cidade set cod_tom = '5111' where uf = 11 and upper(trim(unaccent(nome))) like 'RIO PARDO DE MINAS'; 
update cidade set cod_tom = '5113' where uf = 11 and upper(trim(unaccent(nome))) like 'RIO PIRACICABA'; 
update cidade set cod_tom = '5115' where uf = 11 and upper(trim(unaccent(nome))) like 'RIO POMBA'; 
update cidade set cod_tom = '5117' where uf = 11 and upper(trim(unaccent(nome))) like 'RIO PRETO'; 
update cidade set cod_tom = '5119' where uf = 11 and upper(trim(unaccent(nome))) like 'RIO VERMELHO'; 
update cidade set cod_tom = '5121' where uf = 11 and upper(trim(unaccent(nome))) like 'RITAPOLIS'; 
update cidade set cod_tom = '5123' where uf = 11 and upper(trim(unaccent(nome))) like 'ROCHEDO DE MINAS'; 
update cidade set cod_tom = '5125' where uf = 11 and upper(trim(unaccent(nome))) like 'RODEIRO'; 
update cidade set cod_tom = '5127' where uf = 11 and upper(trim(unaccent(nome))) like 'ROMARIA'; 
update cidade set cod_tom = '0698' where uf = 11 and upper(trim(unaccent(nome))) like 'ROSARIO DA LIMEIRA'; 
update cidade set cod_tom = '5129' where uf = 11 and upper(trim(unaccent(nome))) like 'RUBELITA'; 
update cidade set cod_tom = '5131' where uf = 11 and upper(trim(unaccent(nome))) like 'RUBIM'; 
update cidade set cod_tom = '5133' where uf = 11 and upper(trim(unaccent(nome))) like 'SABARA'; 
update cidade set cod_tom = '5135' where uf = 11 and upper(trim(unaccent(nome))) like 'SABINOPOLIS'; 
update cidade set cod_tom = '5137' where uf = 11 and upper(trim(unaccent(nome))) like 'SACRAMENTO'; 
update cidade set cod_tom = '5139' where uf = 11 and upper(trim(unaccent(nome))) like 'SALINAS'; 
update cidade set cod_tom = '5141' where uf = 11 and upper(trim(unaccent(nome))) like 'SALTO DA DIVISA'; 
update cidade set cod_tom = '5143' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA BARBARA'; 
update cidade set cod_tom = '2667' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA BARBARA DO LESTE'; 
update cidade set cod_tom = '0700' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA BARBARA DO MONTE VERDE'; 
update cidade set cod_tom = '5145' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA BARBARA DO TUGURIO'; 
update cidade set cod_tom = '0702' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA CRUZ DE MINAS'; 
update cidade set cod_tom = '0704' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA CRUZ DE SALINAS'; 
update cidade set cod_tom = '5147' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA CRUZ DO ESCALVADO'; 
update cidade set cod_tom = '5149' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA EFIGENIA DE MINAS'; 
update cidade set cod_tom = '5151' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA FE DE MINAS'; 
update cidade set cod_tom = '0706' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA HELENA DE MINAS'; 
update cidade set cod_tom = '5153' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA JULIANA'; 
update cidade set cod_tom = '5155' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA LUZIA'; 
update cidade set cod_tom = '5157' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA MARGARIDA'; 
update cidade set cod_tom = '5159' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA MARIA DE ITABIRA'; 
update cidade set cod_tom = '5161' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA MARIA DO SALTO'; 
update cidade set cod_tom = '5163' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA MARIA DO SUACUI'; 
update cidade set cod_tom = '5183' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA RITA DE CALDAS'; 
update cidade set cod_tom = '5187' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA RITA DE IBITIPOCA'; 
update cidade set cod_tom = '5185' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA RITA DE JACUTINGA'; 
update cidade set cod_tom = '2669' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA RITA DE MINAS'; 
update cidade set cod_tom = '5189' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA RITA DO ITUETO'; 
update cidade set cod_tom = '5191' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA RITA DO SAPUCAI'; 
update cidade set cod_tom = '5193' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA ROSA DA SERRA'; 
update cidade set cod_tom = '5195' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTA VITORIA'; 
update cidade set cod_tom = '5165' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTANA DA VARGEM'; 
update cidade set cod_tom = '5167' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTANA DE CATAGUASES'; 
update cidade set cod_tom = '5169' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTANA DE PIRAPAMA'; 
update cidade set cod_tom = '5171' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTANA DO DESERTO'; 
update cidade set cod_tom = '5173' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTANA DO GARAMBEU'; 
update cidade set cod_tom = '5175' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTANA DO JACARE'; 
update cidade set cod_tom = '5177' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTANA DO MANHUACU'; 
update cidade set cod_tom = '2673' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTANA DO PARAISO'; 
update cidade set cod_tom = '5179' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTANA DO RIACHO'; 
update cidade set cod_tom = '5181' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTANA DOS MONTES'; 
update cidade set cod_tom = '5197' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO AMPARO'; 
update cidade set cod_tom = '5199' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO AVENTUREIRO'; 
update cidade set cod_tom = '5201' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO GRAMA'; 
update cidade set cod_tom = '5203' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO ITAMBE'; 
update cidade set cod_tom = '5205' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO JACINTO'; 
update cidade set cod_tom = '5207' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO MONTE'; 
update cidade set cod_tom = '0708' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO RETIRO'; 
update cidade set cod_tom = '5209' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO RIO ABAIXO'; 
update cidade set cod_tom = '5211' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTO HIPOLITO'; 
update cidade set cod_tom = '5213' where uf = 11 and upper(trim(unaccent(nome))) like 'SANTOS DUMONT'; 
update cidade set cod_tom = '5215' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO BENTO ABADE'; 
update cidade set cod_tom = '5217' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO BRAS DO SUACUI'; 
update cidade set cod_tom = '0710' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO DOMINGOS DAS DORES'; 
update cidade set cod_tom = '5219' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO DOMINGOS DO PRATA'; 
update cidade set cod_tom = '0712' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO FELIX DE MINAS'; 
update cidade set cod_tom = '5221' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO'; 
update cidade set cod_tom = '5223' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO DE PAULA'; 
update cidade set cod_tom = '5225' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO DE SALES'; 
update cidade set cod_tom = '5227' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO DO GLORIA'; 
update cidade set cod_tom = '5229' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO GERALDO'; 
update cidade set cod_tom = '5231' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO GERALDO DA PIEDADE'; 
update cidade set cod_tom = '0714' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO GERALDO DO BAIXIO'; 
update cidade set cod_tom = '5233' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO GONCALO DO ABAETE'; 
update cidade set cod_tom = '5235' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO GONCALO DO PARA'; 
update cidade set cod_tom = '5237' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO GONCALO DO RIO ABAIXO'; 
update cidade set cod_tom = '4509' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO GONCALO DO RIO PRETO'; 
update cidade set cod_tom = '5239' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO GONCALO DO SAPUCAI'; 
update cidade set cod_tom = '5241' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO GOTARDO'; 
update cidade set cod_tom = '5243' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOAO BATISTA DO GLORIA'; 
update cidade set cod_tom = '0716' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOAO DA LAGOA'; 
update cidade set cod_tom = '5245' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOAO DA MATA'; 
update cidade set cod_tom = '5247' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOAO DA PONTE'; 
update cidade set cod_tom = '0718' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOAO DAS MISSOES'; 
update cidade set cod_tom = '5249' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOAO DEL REI'; 
update cidade set cod_tom = '2677' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOAO DO MANHUACU'; 
update cidade set cod_tom = '2679' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOAO DO MANTENINHA'; 
update cidade set cod_tom = '5251' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOAO DO ORIENTE'; 
update cidade set cod_tom = '0720' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOAO DO PACUI'; 
update cidade set cod_tom = '5253' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOAO DO PARAISO'; 
update cidade set cod_tom = '5255' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOAO EVANGELISTA'; 
update cidade set cod_tom = '5257' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOAO NEPOMUCENO'; 
update cidade set cod_tom = '0722' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOAQUIM DE BICAS'; 
update cidade set cod_tom = '0724' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOSE DA BARRA'; 
update cidade set cod_tom = '2649' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOSE DA LAPA'; 
update cidade set cod_tom = '5259' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOSE DA SAFIRA'; 
update cidade set cod_tom = '5261' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOSE DA VARGINHA'; 
update cidade set cod_tom = '5263' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOSE DO ALEGRE'; 
update cidade set cod_tom = '5265' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOSE DO DIVINO'; 
update cidade set cod_tom = '5267' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOSE DO GOIABAL'; 
update cidade set cod_tom = '5269' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOSE DO JACURI'; 
update cidade set cod_tom = '5271' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO JOSE DO MANTIMENTO'; 
update cidade set cod_tom = '5273' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO LOURENCO'; 
update cidade set cod_tom = '5275' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO MIGUEL DO ANTA'; 
update cidade set cod_tom = '5277' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO PEDRO DA UNIAO'; 
update cidade set cod_tom = '5281' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO PEDRO DO SUACUI'; 
update cidade set cod_tom = '5279' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO PEDRO DOS FERROS'; 
update cidade set cod_tom = '5283' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO ROMAO'; 
update cidade set cod_tom = '5285' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO ROQUE DE MINAS'; 
update cidade set cod_tom = '5287' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO DA BELA VISTA'; 
update cidade set cod_tom = '0726' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO DA VARGEM ALEGRE'; 
update cidade set cod_tom = '0728' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO DO ANTA'; 
update cidade set cod_tom = '5289' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO DO MARANHAO'; 
update cidade set cod_tom = '5291' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO DO OESTE'; 
update cidade set cod_tom = '5293' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO DO PARAISO'; 
update cidade set cod_tom = '5295' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO DO RIO PRETO'; 
update cidade set cod_tom = '5297' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO DO RIO VERDE'; 
update cidade set cod_tom = '5299' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO TIAGO'; 
update cidade set cod_tom = '5301' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO TOMAS DE AQUINO'; 
update cidade set cod_tom = '5303' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO TOME DAS LETRAS'; 
update cidade set cod_tom = '5305' where uf = 11 and upper(trim(unaccent(nome))) like 'SAO VICENTE DE MINAS'; 
update cidade set cod_tom = '5307' where uf = 11 and upper(trim(unaccent(nome))) like 'SAPUCAI-MIRIM'; 
update cidade set cod_tom = '5309' where uf = 11 and upper(trim(unaccent(nome))) like 'SARDOA'; 
update cidade set cod_tom = '0730' where uf = 11 and upper(trim(unaccent(nome))) like 'SARZEDO'; 
update cidade set cod_tom = '0734' where uf = 11 and upper(trim(unaccent(nome))) like 'SEM-PEIXE'; 
update cidade set cod_tom = '2689' where uf = 11 and upper(trim(unaccent(nome))) like 'SENADOR AMARAL'; 
update cidade set cod_tom = '5311' where uf = 11 and upper(trim(unaccent(nome))) like 'SENADOR CORTES'; 
update cidade set cod_tom = '5313' where uf = 11 and upper(trim(unaccent(nome))) like 'SENADOR FIRMINO'; 
update cidade set cod_tom = '5315' where uf = 11 and upper(trim(unaccent(nome))) like 'SENADOR JOSE BENTO'; 
update cidade set cod_tom = '5317' where uf = 11 and upper(trim(unaccent(nome))) like 'SENADOR MODESTINO GONCALVES'; 
update cidade set cod_tom = '5319' where uf = 11 and upper(trim(unaccent(nome))) like 'SENHORA DE OLIVEIRA'; 
update cidade set cod_tom = '5321' where uf = 11 and upper(trim(unaccent(nome))) like 'SENHORA DO PORTO'; 
update cidade set cod_tom = '5323' where uf = 11 and upper(trim(unaccent(nome))) like 'SENHORA DOS REMEDIOS'; 
update cidade set cod_tom = '5325' where uf = 11 and upper(trim(unaccent(nome))) like 'SERICITA'; 
update cidade set cod_tom = '5327' where uf = 11 and upper(trim(unaccent(nome))) like 'SERITINGA'; 
update cidade set cod_tom = '5329' where uf = 11 and upper(trim(unaccent(nome))) like 'SERRA AZUL DE MINAS'; 
update cidade set cod_tom = '5331' where uf = 11 and upper(trim(unaccent(nome))) like 'SERRA DA SAUDADE'; 
update cidade set cod_tom = '5335' where uf = 11 and upper(trim(unaccent(nome))) like 'SERRA DO SALITRE'; 
update cidade set cod_tom = '5333' where uf = 11 and upper(trim(unaccent(nome))) like 'SERRA DOS AIMORES'; 
update cidade set cod_tom = '5337' where uf = 11 and upper(trim(unaccent(nome))) like 'SERRANIA'; 
update cidade set cod_tom = '0736' where uf = 11 and upper(trim(unaccent(nome))) like 'SERRANOPOLIS DE MINAS'; 
update cidade set cod_tom = '5339' where uf = 11 and upper(trim(unaccent(nome))) like 'SERRANOS'; 
update cidade set cod_tom = '5341' where uf = 11 and upper(trim(unaccent(nome))) like 'SERRO'; 
update cidade set cod_tom = '5343' where uf = 11 and upper(trim(unaccent(nome))) like 'SETE LAGOAS'; 
update cidade set cod_tom = '0732' where uf = 11 and upper(trim(unaccent(nome))) like 'SETUBINHA'; 
update cidade set cod_tom = '5345' where uf = 11 and upper(trim(unaccent(nome))) like 'SILVEIRANIA'; 
update cidade set cod_tom = '5347' where uf = 11 and upper(trim(unaccent(nome))) like 'SILVIANOPOLIS'; 
update cidade set cod_tom = '5349' where uf = 11 and upper(trim(unaccent(nome))) like 'SIMAO PEREIRA'; 
update cidade set cod_tom = '5351' where uf = 11 and upper(trim(unaccent(nome))) like 'SIMONESIA'; 
update cidade set cod_tom = '5353' where uf = 11 and upper(trim(unaccent(nome))) like 'SOBRALIA'; 
update cidade set cod_tom = '5355' where uf = 11 and upper(trim(unaccent(nome))) like 'SOLEDADE DE MINAS'; 
update cidade set cod_tom = '5357' where uf = 11 and upper(trim(unaccent(nome))) like 'TABULEIRO'; 
update cidade set cod_tom = '5359' where uf = 11 and upper(trim(unaccent(nome))) like 'TAIOBEIRAS'; 
update cidade set cod_tom = '0738' where uf = 11 and upper(trim(unaccent(nome))) like 'TAPARUBA'; 
update cidade set cod_tom = '5361' where uf = 11 and upper(trim(unaccent(nome))) like 'TAPIRA'; 
update cidade set cod_tom = '5363' where uf = 11 and upper(trim(unaccent(nome))) like 'TAPIRAI'; 
update cidade set cod_tom = '5365' where uf = 11 and upper(trim(unaccent(nome))) like 'TAQUARACU DE MINAS'; 
update cidade set cod_tom = '5367' where uf = 11 and upper(trim(unaccent(nome))) like 'TARUMIRIM'; 
update cidade set cod_tom = '5369' where uf = 11 and upper(trim(unaccent(nome))) like 'TEIXEIRAS'; 
update cidade set cod_tom = '5371' where uf = 11 and upper(trim(unaccent(nome))) like 'TEOFILO OTONI'; 
update cidade set cod_tom = '5373' where uf = 11 and upper(trim(unaccent(nome))) like 'TIMOTEO'; 
update cidade set cod_tom = '5375' where uf = 11 and upper(trim(unaccent(nome))) like 'TIRADENTES'; 
update cidade set cod_tom = '5377' where uf = 11 and upper(trim(unaccent(nome))) like 'TIROS'; 
update cidade set cod_tom = '5379' where uf = 11 and upper(trim(unaccent(nome))) like 'TOCANTINS'; 
update cidade set cod_tom = '0740' where uf = 11 and upper(trim(unaccent(nome))) like 'TOCOS DO MOJI'; 
update cidade set cod_tom = '5381' where uf = 11 and upper(trim(unaccent(nome))) like 'TOLEDO'; 
update cidade set cod_tom = '5383' where uf = 11 and upper(trim(unaccent(nome))) like 'TOMBOS'; 
update cidade set cod_tom = '5385' where uf = 11 and upper(trim(unaccent(nome))) like 'TRES CORACOES'; 
update cidade set cod_tom = '4115' where uf = 11 and upper(trim(unaccent(nome))) like 'TRES MARIAS'; 
update cidade set cod_tom = '5387' where uf = 11 and upper(trim(unaccent(nome))) like 'TRES PONTAS'; 
update cidade set cod_tom = '5389' where uf = 11 and upper(trim(unaccent(nome))) like 'TUMIRITINGA'; 
update cidade set cod_tom = '5391' where uf = 11 and upper(trim(unaccent(nome))) like 'TUPACIGUARA'; 
update cidade set cod_tom = '5393' where uf = 11 and upper(trim(unaccent(nome))) like 'TURMALINA'; 
update cidade set cod_tom = '5395' where uf = 11 and upper(trim(unaccent(nome))) like 'TURVOLANDIA'; 
update cidade set cod_tom = '5397' where uf = 11 and upper(trim(unaccent(nome))) like 'UBA'; 
update cidade set cod_tom = '5399' where uf = 11 and upper(trim(unaccent(nome))) like 'UBAI'; 
update cidade set cod_tom = '2671' where uf = 11 and upper(trim(unaccent(nome))) like 'UBAPORANGA'; 
update cidade set cod_tom = '5401' where uf = 11 and upper(trim(unaccent(nome))) like 'UBERABA'; 
update cidade set cod_tom = '5403' where uf = 11 and upper(trim(unaccent(nome))) like 'UBERLANDIA'; 
update cidade set cod_tom = '5405' where uf = 11 and upper(trim(unaccent(nome))) like 'UMBURATIBA'; 
update cidade set cod_tom = '5407' where uf = 11 and upper(trim(unaccent(nome))) like 'UNAI'; 
update cidade set cod_tom = '0742' where uf = 11 and upper(trim(unaccent(nome))) like 'UNIAO DE MINAS'; 
update cidade set cod_tom = '0744' where uf = 11 and upper(trim(unaccent(nome))) like 'URUANA DE MINAS'; 
update cidade set cod_tom = '5409' where uf = 11 and upper(trim(unaccent(nome))) like 'URUCANIA'; 
update cidade set cod_tom = '2699' where uf = 11 and upper(trim(unaccent(nome))) like 'URUCUIA'; 
update cidade set cod_tom = '0746' where uf = 11 and upper(trim(unaccent(nome))) like 'VARGEM ALEGRE'; 
update cidade set cod_tom = '5411' where uf = 11 and upper(trim(unaccent(nome))) like 'VARGEM BONITA'; 
update cidade set cod_tom = '0748' where uf = 11 and upper(trim(unaccent(nome))) like 'VARGEM GRANDE DO RIO PARDO'; 
update cidade set cod_tom = '5413' where uf = 11 and upper(trim(unaccent(nome))) like 'VARGINHA'; 
update cidade set cod_tom = '0750' where uf = 11 and upper(trim(unaccent(nome))) like 'VARJAO DE MINAS'; 
update cidade set cod_tom = '5415' where uf = 11 and upper(trim(unaccent(nome))) like 'VARZEA DA PALMA'; 
update cidade set cod_tom = '5417' where uf = 11 and upper(trim(unaccent(nome))) like 'VARZELANDIA'; 
update cidade set cod_tom = '5419' where uf = 11 and upper(trim(unaccent(nome))) like 'VAZANTE'; 
update cidade set cod_tom = '0752' where uf = 11 and upper(trim(unaccent(nome))) like 'VERDELANDIA'; 
update cidade set cod_tom = '0754' where uf = 11 and upper(trim(unaccent(nome))) like 'VEREDINHA'; 
update cidade set cod_tom = '5423' where uf = 11 and upper(trim(unaccent(nome))) like 'VERISSIMO'; 
update cidade set cod_tom = '0756' where uf = 11 and upper(trim(unaccent(nome))) like 'VERMELHO NOVO'; 
update cidade set cod_tom = '5425' where uf = 11 and upper(trim(unaccent(nome))) like 'VESPASIANO'; 
update cidade set cod_tom = '5427' where uf = 11 and upper(trim(unaccent(nome))) like 'VICOSA'; 
update cidade set cod_tom = '5429' where uf = 11 and upper(trim(unaccent(nome))) like 'VIEIRAS'; 
update cidade set cod_tom = '5433' where uf = 11 and upper(trim(unaccent(nome))) like 'VIRGEM DA LAPA'; 
update cidade set cod_tom = '5435' where uf = 11 and upper(trim(unaccent(nome))) like 'VIRGINIA'; 
update cidade set cod_tom = '5437' where uf = 11 and upper(trim(unaccent(nome))) like 'VIRGINOPOLIS'; 
update cidade set cod_tom = '5439' where uf = 11 and upper(trim(unaccent(nome))) like 'VIRGOLANDIA'; 
update cidade set cod_tom = '5441' where uf = 11 and upper(trim(unaccent(nome))) like 'VISCONDE DO RIO BRANCO'; 
update cidade set cod_tom = '5443' where uf = 11 and upper(trim(unaccent(nome))) like 'VOLTA GRANDE'; 
update cidade set cod_tom = '5421' where uf = 11 and upper(trim(unaccent(nome))) like 'WENCESLAU BRAZ';