update cidade set cod_tom = '2701' where uf = 2 and upper(trim(unaccent(nome))) like 'AGUA BRANCA'; 
update cidade set cod_tom = '2703' where uf = 2 and upper(trim(unaccent(nome))) like 'ANADIA'; 
update cidade set cod_tom = '2705' where uf = 2 and upper(trim(unaccent(nome))) like 'ARAPIRACA'; 
update cidade set cod_tom = '2707' where uf = 2 and upper(trim(unaccent(nome))) like 'ATALAIA'; 
update cidade set cod_tom = '2709' where uf = 2 and upper(trim(unaccent(nome))) like 'BARRA DE SANTO ANTONIO'; 
update cidade set cod_tom = '2711' where uf = 2 and upper(trim(unaccent(nome))) like 'BARRA DE SAO MIGUEL'; 
update cidade set cod_tom = '2713' where uf = 2 and upper(trim(unaccent(nome))) like 'BATALHA'; 
update cidade set cod_tom = '2715' where uf = 2 and upper(trim(unaccent(nome))) like 'BELEM'; 
update cidade set cod_tom = '2717' where uf = 2 and upper(trim(unaccent(nome))) like 'BELO MONTE'; 
update cidade set cod_tom = '2719' where uf = 2 and upper(trim(unaccent(nome))) like 'BOCA DA MATA'; 
update cidade set cod_tom = '2721' where uf = 2 and upper(trim(unaccent(nome))) like 'BRANQUINHA'; 
update cidade set cod_tom = '2723' where uf = 2 and upper(trim(unaccent(nome))) like 'CACIMBINHAS'; 
update cidade set cod_tom = '2725' where uf = 2 and upper(trim(unaccent(nome))) like 'CAJUEIRO'; 
update cidade set cod_tom = '0560' where uf = 2 and upper(trim(unaccent(nome))) like 'CAMPESTRE'; 
update cidade set cod_tom = '2727' where uf = 2 and upper(trim(unaccent(nome))) like 'CAMPO ALEGRE'; 
update cidade set cod_tom = '2729' where uf = 2 and upper(trim(unaccent(nome))) like 'CAMPO GRANDE'; 
update cidade set cod_tom = '2731' where uf = 2 and upper(trim(unaccent(nome))) like 'CANAPI'; 
update cidade set cod_tom = '2733' where uf = 2 and upper(trim(unaccent(nome))) like 'CAPELA'; 
update cidade set cod_tom = '2735' where uf = 2 and upper(trim(unaccent(nome))) like 'CARNEIROS'; 
update cidade set cod_tom = '2737' where uf = 2 and upper(trim(unaccent(nome))) like 'CHA PRETA'; 
update cidade set cod_tom = '2739' where uf = 2 and upper(trim(unaccent(nome))) like 'COITE DO NOIA'; 
update cidade set cod_tom = '2741' where uf = 2 and upper(trim(unaccent(nome))) like 'COLONIA LEOPOLDINA'; 
update cidade set cod_tom = '2743' where uf = 2 and upper(trim(unaccent(nome))) like 'COQUEIRO SECO'; 
update cidade set cod_tom = '2745' where uf = 2 and upper(trim(unaccent(nome))) like 'CORURIPE'; 
update cidade set cod_tom = '2889' where uf = 2 and upper(trim(unaccent(nome))) like 'CRAIBAS'; 
update cidade set cod_tom = '2747' where uf = 2 and upper(trim(unaccent(nome))) like 'DELMIRO GOUVEIA'; 
update cidade set cod_tom = '2749' where uf = 2 and upper(trim(unaccent(nome))) like 'DOIS RIACHOS'; 
update cidade set cod_tom = '2643' where uf = 2 and upper(trim(unaccent(nome))) like 'ESTRELA DE ALAGOAS'; 
update cidade set cod_tom = '2751' where uf = 2 and upper(trim(unaccent(nome))) like 'FEIRA GRANDE'; 
update cidade set cod_tom = '2753' where uf = 2 and upper(trim(unaccent(nome))) like 'FELIZ DESERTO'; 
update cidade set cod_tom = '2755' where uf = 2 and upper(trim(unaccent(nome))) like 'FLEXEIRAS'; 
update cidade set cod_tom = '2757' where uf = 2 and upper(trim(unaccent(nome))) like 'GIRAU DO PONCIANO'; 
update cidade set cod_tom = '2759' where uf = 2 and upper(trim(unaccent(nome))) like 'IBATEGUARA'; 
update cidade set cod_tom = '2761' where uf = 2 and upper(trim(unaccent(nome))) like 'IGACI'; 
update cidade set cod_tom = '2763' where uf = 2 and upper(trim(unaccent(nome))) like 'IGREJA NOVA'; 
update cidade set cod_tom = '2765' where uf = 2 and upper(trim(unaccent(nome))) like 'INHAPI'; 
update cidade set cod_tom = '2767' where uf = 2 and upper(trim(unaccent(nome))) like 'JACARE DOS HOMENS'; 
update cidade set cod_tom = '2769' where uf = 2 and upper(trim(unaccent(nome))) like 'JACUIPE'; 
update cidade set cod_tom = '2771' where uf = 2 and upper(trim(unaccent(nome))) like 'JAPARATINGA'; 
update cidade set cod_tom = '2773' where uf = 2 and upper(trim(unaccent(nome))) like 'JARAMATAIA'; 
update cidade set cod_tom = '0562' where uf = 2 and upper(trim(unaccent(nome))) like 'JEQUIA DA PRAIA'; 
update cidade set cod_tom = '2775' where uf = 2 and upper(trim(unaccent(nome))) like 'JOAQUIM GOMES'; 
update cidade set cod_tom = '2777' where uf = 2 and upper(trim(unaccent(nome))) like 'JUNDIA'; 
update cidade set cod_tom = '2779' where uf = 2 and upper(trim(unaccent(nome))) like 'JUNQUEIRO'; 
update cidade set cod_tom = '2781' where uf = 2 and upper(trim(unaccent(nome))) like 'LAGOA DA CANOA'; 
update cidade set cod_tom = '2783' where uf = 2 and upper(trim(unaccent(nome))) like 'LIMOEIRO DE ANADIA'; 
update cidade set cod_tom = '2785' where uf = 2 and upper(trim(unaccent(nome))) like 'MACEIO'; 
update cidade set cod_tom = '2787' where uf = 2 and upper(trim(unaccent(nome))) like 'MAJOR ISIDORO'; 
update cidade set cod_tom = '2797' where uf = 2 and upper(trim(unaccent(nome))) like 'MAR VERMELHO'; 
update cidade set cod_tom = '2789' where uf = 2 and upper(trim(unaccent(nome))) like 'MARAGOGI'; 
update cidade set cod_tom = '2791' where uf = 2 and upper(trim(unaccent(nome))) like 'MARAVILHA'; 
update cidade set cod_tom = '2793' where uf = 2 and upper(trim(unaccent(nome))) like 'MARECHAL DEODORO'; 
update cidade set cod_tom = '2795' where uf = 2 and upper(trim(unaccent(nome))) like 'MARIBONDO'; 
update cidade set cod_tom = '2799' where uf = 2 and upper(trim(unaccent(nome))) like 'MATA GRANDE'; 
update cidade set cod_tom = '2801' where uf = 2 and upper(trim(unaccent(nome))) like 'MATRIZ DE CAMARAGIBE'; 
update cidade set cod_tom = '2803' where uf = 2 and upper(trim(unaccent(nome))) like 'MESSIAS'; 
update cidade set cod_tom = '2805' where uf = 2 and upper(trim(unaccent(nome))) like 'MINADOR DO NEGRAO'; 
update cidade set cod_tom = '2807' where uf = 2 and upper(trim(unaccent(nome))) like 'MONTEIROPOLIS'; 
update cidade set cod_tom = '2809' where uf = 2 and upper(trim(unaccent(nome))) like 'MURICI'; 
update cidade set cod_tom = '2811' where uf = 2 and upper(trim(unaccent(nome))) like 'NOVO LINO'; 
update cidade set cod_tom = '2813' where uf = 2 and upper(trim(unaccent(nome))) like 'OLHO D`AGUA DAS FLORES'; 
update cidade set cod_tom = '2815' where uf = 2 and upper(trim(unaccent(nome))) like 'OLHO D`AGUA DO CASADO'; 
update cidade set cod_tom = '2817' where uf = 2 and upper(trim(unaccent(nome))) like 'OLHO D`AGUA GRANDE'; 
update cidade set cod_tom = '2819' where uf = 2 and upper(trim(unaccent(nome))) like 'OLIVENCA'; 
update cidade set cod_tom = '2821' where uf = 2 and upper(trim(unaccent(nome))) like 'OURO BRANCO'; 
update cidade set cod_tom = '2823' where uf = 2 and upper(trim(unaccent(nome))) like 'PALESTINA'; 
update cidade set cod_tom = '2825' where uf = 2 and upper(trim(unaccent(nome))) like 'PALMEIRA DOS INDIOS'; 
update cidade set cod_tom = '2827' where uf = 2 and upper(trim(unaccent(nome))) like 'PAO DE ACUCAR'; 
update cidade set cod_tom = '2645' where uf = 2 and upper(trim(unaccent(nome))) like 'PARICONHA'; 
update cidade set cod_tom = '2641' where uf = 2 and upper(trim(unaccent(nome))) like 'PARIPUEIRA'; 
update cidade set cod_tom = '2829' where uf = 2 and upper(trim(unaccent(nome))) like 'PASSO DE CAMARAGIBE'; 
update cidade set cod_tom = '2831' where uf = 2 and upper(trim(unaccent(nome))) like 'PAULO JACINTO'; 
update cidade set cod_tom = '2833' where uf = 2 and upper(trim(unaccent(nome))) like 'PENEDO'; 
update cidade set cod_tom = '2835' where uf = 2 and upper(trim(unaccent(nome))) like 'PIACABUCU'; 
update cidade set cod_tom = '2837' where uf = 2 and upper(trim(unaccent(nome))) like 'PILAR'; 
update cidade set cod_tom = '2839' where uf = 2 and upper(trim(unaccent(nome))) like 'PINDOBA'; 
update cidade set cod_tom = '2841' where uf = 2 and upper(trim(unaccent(nome))) like 'PIRANHAS'; 
update cidade set cod_tom = '2843' where uf = 2 and upper(trim(unaccent(nome))) like 'POCO DAS TRINCHEIRAS'; 
update cidade set cod_tom = '2845' where uf = 2 and upper(trim(unaccent(nome))) like 'PORTO CALVO'; 
update cidade set cod_tom = '2847' where uf = 2 and upper(trim(unaccent(nome))) like 'PORTO DE PEDRAS'; 
update cidade set cod_tom = '2849' where uf = 2 and upper(trim(unaccent(nome))) like 'PORTO REAL DO COLEGIO'; 
update cidade set cod_tom = '2851' where uf = 2 and upper(trim(unaccent(nome))) like 'QUEBRANGULO'; 
update cidade set cod_tom = '2853' where uf = 2 and upper(trim(unaccent(nome))) like 'RIO LARGO'; 
update cidade set cod_tom = '2855' where uf = 2 and upper(trim(unaccent(nome))) like 'ROTEIRO'; 
update cidade set cod_tom = '2857' where uf = 2 and upper(trim(unaccent(nome))) like 'SANTA LUZIA DO NORTE'; 
update cidade set cod_tom = '2859' where uf = 2 and upper(trim(unaccent(nome))) like 'SANTANA DO IPANEMA'; 
update cidade set cod_tom = '2861' where uf = 2 and upper(trim(unaccent(nome))) like 'SANTANA DO MUNDAU'; 
update cidade set cod_tom = '2863' where uf = 2 and upper(trim(unaccent(nome))) like 'SAO BRAS'; 
update cidade set cod_tom = '2865' where uf = 2 and upper(trim(unaccent(nome))) like 'SAO JOSE DA LAJE'; 
update cidade set cod_tom = '2867' where uf = 2 and upper(trim(unaccent(nome))) like 'SAO JOSE DA TAPERA'; 
update cidade set cod_tom = '2869' where uf = 2 and upper(trim(unaccent(nome))) like 'SAO LUIS DO QUITUNDE'; 
update cidade set cod_tom = '2871' where uf = 2 and upper(trim(unaccent(nome))) like 'SAO MIGUEL DOS CAMPOS'; 
update cidade set cod_tom = '2873' where uf = 2 and upper(trim(unaccent(nome))) like 'SAO MIGUEL DOS MILAGRES'; 
update cidade set cod_tom = '2875' where uf = 2 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO'; 
update cidade set cod_tom = '2877' where uf = 2 and upper(trim(unaccent(nome))) like 'SATUBA'; 
update cidade set cod_tom = '2891' where uf = 2 and upper(trim(unaccent(nome))) like 'SENADOR RUI PALMEIRA'; 
update cidade set cod_tom = '2879' where uf = 2 and upper(trim(unaccent(nome))) like 'TANQUE D`ARCA'; 
update cidade set cod_tom = '2881' where uf = 2 and upper(trim(unaccent(nome))) like 'TAQUARANA'; 
update cidade set cod_tom = '0971' where uf = 2 and upper(trim(unaccent(nome))) like 'TEOTONIO VILELA'; 
update cidade set cod_tom = '2883' where uf = 2 and upper(trim(unaccent(nome))) like 'TRAIPU'; 
update cidade set cod_tom = '2885' where uf = 2 and upper(trim(unaccent(nome))) like 'UNIAO DOS PALMARES'; 
update cidade set cod_tom = '2887' where uf = 2 and upper(trim(unaccent(nome))) like 'VICOSA';