update cidade set cod_tom = '1050' where uf = 9 and upper(trim(unaccent(nome))) like 'ABADIA DE GOIAS'; 
update cidade set cod_tom = '9201' where uf = 9 and upper(trim(unaccent(nome))) like 'ABADIANIA'; 
update cidade set cod_tom = '9645' where uf = 9 and upper(trim(unaccent(nome))) like 'ACREUNA'; 
update cidade set cod_tom = '9769' where uf = 9 and upper(trim(unaccent(nome))) like 'ADELANDIA'; 
update cidade set cod_tom = '9771' where uf = 9 and upper(trim(unaccent(nome))) like 'AGUA FRIA DE GOIAS'; 
update cidade set cod_tom = '9203' where uf = 9 and upper(trim(unaccent(nome))) like 'AGUA LIMPA'; 
update cidade set cod_tom = '1052' where uf = 9 and upper(trim(unaccent(nome))) like 'AGUAS LINDAS DE GOIAS'; 
update cidade set cod_tom = '9205' where uf = 9 and upper(trim(unaccent(nome))) like 'ALEXANIA'; 
update cidade set cod_tom = '9209' where uf = 9 and upper(trim(unaccent(nome))) like 'ALOANDIA'; 
update cidade set cod_tom = '0085' where uf = 9 and upper(trim(unaccent(nome))) like 'ALTO HORIZONTE'; 
update cidade set cod_tom = '9211' where uf = 9 and upper(trim(unaccent(nome))) like 'ALTO PARAISO DE GOIAS'; 
update cidade set cod_tom = '9215' where uf = 9 and upper(trim(unaccent(nome))) like 'ALVORADA DO NORTE'; 
update cidade set cod_tom = '1054' where uf = 9 and upper(trim(unaccent(nome))) like 'AMARALINA'; 
update cidade set cod_tom = '9661' where uf = 9 and upper(trim(unaccent(nome))) like 'AMERICANO DO BRASIL'; 
update cidade set cod_tom = '9217' where uf = 9 and upper(trim(unaccent(nome))) like 'AMORINOPOLIS'; 
update cidade set cod_tom = '9221' where uf = 9 and upper(trim(unaccent(nome))) like 'ANAPOLIS'; 
update cidade set cod_tom = '9223' where uf = 9 and upper(trim(unaccent(nome))) like 'ANHANGUERA'; 
update cidade set cod_tom = '9225' where uf = 9 and upper(trim(unaccent(nome))) like 'ANICUNS'; 
update cidade set cod_tom = '9227' where uf = 9 and upper(trim(unaccent(nome))) like 'APARECIDA DE GOIANIA'; 
update cidade set cod_tom = '0071' where uf = 9 and upper(trim(unaccent(nome))) like 'APARECIDA DO RIO DOCE'; 
update cidade set cod_tom = '9229' where uf = 9 and upper(trim(unaccent(nome))) like 'APORE'; 
update cidade set cod_tom = '9231' where uf = 9 and upper(trim(unaccent(nome))) like 'ARACU'; 
update cidade set cod_tom = '9233' where uf = 9 and upper(trim(unaccent(nome))) like 'ARAGARCAS'; 
update cidade set cod_tom = '9235' where uf = 9 and upper(trim(unaccent(nome))) like 'ARAGOIANIA'; 
update cidade set cod_tom = '9669' where uf = 9 and upper(trim(unaccent(nome))) like 'ARAGUAPAZ'; 
update cidade set cod_tom = '9671' where uf = 9 and upper(trim(unaccent(nome))) like 'ARENOPOLIS'; 
update cidade set cod_tom = '9249' where uf = 9 and upper(trim(unaccent(nome))) like 'ARUANA'; 
update cidade set cod_tom = '9251' where uf = 9 and upper(trim(unaccent(nome))) like 'AURILANDIA'; 
update cidade set cod_tom = '9255' where uf = 9 and upper(trim(unaccent(nome))) like 'AVELINOPOLIS'; 
update cidade set cod_tom = '9261' where uf = 9 and upper(trim(unaccent(nome))) like 'BALIZA'; 
update cidade set cod_tom = '9263' where uf = 9 and upper(trim(unaccent(nome))) like 'BARRO ALTO'; 
update cidade set cod_tom = '9265' where uf = 9 and upper(trim(unaccent(nome))) like 'BELA VISTA DE GOIAS'; 
update cidade set cod_tom = '9267' where uf = 9 and upper(trim(unaccent(nome))) like 'BOM JARDIM DE GOIAS'; 
update cidade set cod_tom = '9269' where uf = 9 and upper(trim(unaccent(nome))) like 'BOM JESUS DE GOIAS'; 
update cidade set cod_tom = '9775' where uf = 9 and upper(trim(unaccent(nome))) like 'BONFINOPOLIS'; 
update cidade set cod_tom = '1056' where uf = 9 and upper(trim(unaccent(nome))) like 'BONOPOLIS'; 
update cidade set cod_tom = '9271' where uf = 9 and upper(trim(unaccent(nome))) like 'BRAZABRANTES'; 
update cidade set cod_tom = '9275' where uf = 9 and upper(trim(unaccent(nome))) like 'BRITANIA'; 
update cidade set cod_tom = '9277' where uf = 9 and upper(trim(unaccent(nome))) like 'BURITI ALEGRE'; 
update cidade set cod_tom = '0063' where uf = 9 and upper(trim(unaccent(nome))) like 'BURITI DE GOIAS'; 
update cidade set cod_tom = '0061' where uf = 9 and upper(trim(unaccent(nome))) like 'BURITINOPOLIS'; 
update cidade set cod_tom = '9279' where uf = 9 and upper(trim(unaccent(nome))) like 'CABECEIRAS'; 
update cidade set cod_tom = '9281' where uf = 9 and upper(trim(unaccent(nome))) like 'CACHOEIRA ALTA'; 
update cidade set cod_tom = '9283' where uf = 9 and upper(trim(unaccent(nome))) like 'CACHOEIRA DE GOIAS'; 
update cidade set cod_tom = '9673' where uf = 9 and upper(trim(unaccent(nome))) like 'CACHOEIRA DOURADA'; 
update cidade set cod_tom = '9285' where uf = 9 and upper(trim(unaccent(nome))) like 'CACU'; 
update cidade set cod_tom = '9287' where uf = 9 and upper(trim(unaccent(nome))) like 'CAIAPONIA'; 
update cidade set cod_tom = '9289' where uf = 9 and upper(trim(unaccent(nome))) like 'CALDAS NOVAS'; 
update cidade set cod_tom = '0031' where uf = 9 and upper(trim(unaccent(nome))) like 'CALDAZINHA'; 
update cidade set cod_tom = '9291' where uf = 9 and upper(trim(unaccent(nome))) like 'CAMPESTRE DE GOIAS'; 
update cidade set cod_tom = '9687' where uf = 9 and upper(trim(unaccent(nome))) like 'CAMPINACU'; 
update cidade set cod_tom = '9293' where uf = 9 and upper(trim(unaccent(nome))) like 'CAMPINORTE'; 
update cidade set cod_tom = '9295' where uf = 9 and upper(trim(unaccent(nome))) like 'CAMPO ALEGRE DE GOIAS'; 
update cidade set cod_tom = '1070' where uf = 9 and upper(trim(unaccent(nome))) like 'CAMPO LIMPO DE GOIAS'; 
update cidade set cod_tom = '9297' where uf = 9 and upper(trim(unaccent(nome))) like 'CAMPOS BELOS'; 
update cidade set cod_tom = '9781' where uf = 9 and upper(trim(unaccent(nome))) like 'CAMPOS VERDES'; 
update cidade set cod_tom = '9299' where uf = 9 and upper(trim(unaccent(nome))) like 'CARMO DO RIO VERDE'; 
update cidade set cod_tom = '0081' where uf = 9 and upper(trim(unaccent(nome))) like 'CASTELANDIA'; 
update cidade set cod_tom = '9301' where uf = 9 and upper(trim(unaccent(nome))) like 'CATALAO'; 
update cidade set cod_tom = '9303' where uf = 9 and upper(trim(unaccent(nome))) like 'CATURAI'; 
update cidade set cod_tom = '9305' where uf = 9 and upper(trim(unaccent(nome))) like 'CAVALCANTE'; 
update cidade set cod_tom = '9307' where uf = 9 and upper(trim(unaccent(nome))) like 'CERES'; 
update cidade set cod_tom = '9785' where uf = 9 and upper(trim(unaccent(nome))) like 'CEZARINA'; 
update cidade set cod_tom = '0073' where uf = 9 and upper(trim(unaccent(nome))) like 'CHAPADAO DO CEU'; 
update cidade set cod_tom = '0077' where uf = 9 and upper(trim(unaccent(nome))) like 'CIDADE OCIDENTAL'; 
update cidade set cod_tom = '0055' where uf = 9 and upper(trim(unaccent(nome))) like 'COCALZINHO DE GOIAS'; 
update cidade set cod_tom = '9791' where uf = 9 and upper(trim(unaccent(nome))) like 'COLINAS DO SUL'; 
update cidade set cod_tom = '9315' where uf = 9 and upper(trim(unaccent(nome))) like 'CORREGO DO OURO'; 
update cidade set cod_tom = '9317' where uf = 9 and upper(trim(unaccent(nome))) like 'CORUMBA DE GOIAS'; 
update cidade set cod_tom = '9319' where uf = 9 and upper(trim(unaccent(nome))) like 'CORUMBAIBA'; 
update cidade set cod_tom = '9325' where uf = 9 and upper(trim(unaccent(nome))) like 'CRISTALINA'; 
update cidade set cod_tom = '9327' where uf = 9 and upper(trim(unaccent(nome))) like 'CRISTIANOPOLIS'; 
update cidade set cod_tom = '9329' where uf = 9 and upper(trim(unaccent(nome))) like 'CRIXAS'; 
update cidade set cod_tom = '9331' where uf = 9 and upper(trim(unaccent(nome))) like 'CROMINIA'; 
update cidade set cod_tom = '9333' where uf = 9 and upper(trim(unaccent(nome))) like 'CUMARI'; 
update cidade set cod_tom = '9335' where uf = 9 and upper(trim(unaccent(nome))) like 'DAMIANOPOLIS'; 
update cidade set cod_tom = '9337' where uf = 9 and upper(trim(unaccent(nome))) like 'DAMOLANDIA'; 
update cidade set cod_tom = '9339' where uf = 9 and upper(trim(unaccent(nome))) like 'DAVINOPOLIS'; 
update cidade set cod_tom = '0' where uf = 9 and upper(trim(unaccent(nome))) like 'DIANOPOLIS'; 
update cidade set cod_tom = '9343' where uf = 9 and upper(trim(unaccent(nome))) like 'DIORAMA'; 
update cidade set cod_tom = '9309' where uf = 9 and upper(trim(unaccent(nome))) like 'DIVINOPOLIS DE GOIAS'; 
update cidade set cod_tom = '9675' where uf = 9 and upper(trim(unaccent(nome))) like 'DOVERLANDIA'; 
update cidade set cod_tom = '9795' where uf = 9 and upper(trim(unaccent(nome))) like 'EDEALINA'; 
update cidade set cod_tom = '9349' where uf = 9 and upper(trim(unaccent(nome))) like 'EDEIA'; 
update cidade set cod_tom = '9351' where uf = 9 and upper(trim(unaccent(nome))) like 'ESTRELA DO NORTE'; 
update cidade set cod_tom = '9797' where uf = 9 and upper(trim(unaccent(nome))) like 'FAINA'; 
update cidade set cod_tom = '9353' where uf = 9 and upper(trim(unaccent(nome))) like 'FAZENDA NOVA'; 
update cidade set cod_tom = '9357' where uf = 9 and upper(trim(unaccent(nome))) like 'FIRMINOPOLIS'; 
update cidade set cod_tom = '9359' where uf = 9 and upper(trim(unaccent(nome))) like 'FLORES DE GOIAS'; 
update cidade set cod_tom = '9361' where uf = 9 and upper(trim(unaccent(nome))) like 'FORMOSA'; 
update cidade set cod_tom = '9363' where uf = 9 and upper(trim(unaccent(nome))) like 'FORMOSO'; 
update cidade set cod_tom = '1072' where uf = 9 and upper(trim(unaccent(nome))) like 'GAMELEIRA DE GOIAS'; 
update cidade set cod_tom = '9367' where uf = 9 and upper(trim(unaccent(nome))) like 'GOIANAPOLIS'; 
update cidade set cod_tom = '9369' where uf = 9 and upper(trim(unaccent(nome))) like 'GOIANDIRA'; 
update cidade set cod_tom = '9371' where uf = 9 and upper(trim(unaccent(nome))) like 'GOIANESIA'; 
update cidade set cod_tom = '9373' where uf = 9 and upper(trim(unaccent(nome))) like 'GOIANIA'; 
update cidade set cod_tom = '9375' where uf = 9 and upper(trim(unaccent(nome))) like 'GOIANIRA'; 
update cidade set cod_tom = '9377' where uf = 9 and upper(trim(unaccent(nome))) like 'GOIAS'; 
update cidade set cod_tom = '9379' where uf = 9 and upper(trim(unaccent(nome))) like 'GOIATUBA'; 
update cidade set cod_tom = '9799' where uf = 9 and upper(trim(unaccent(nome))) like 'GOUVELANDIA'; 
update cidade set cod_tom = '9381' where uf = 9 and upper(trim(unaccent(nome))) like 'GUAPO'; 
update cidade set cod_tom = '0065' where uf = 9 and upper(trim(unaccent(nome))) like 'GUARAITA'; 
update cidade set cod_tom = '9383' where uf = 9 and upper(trim(unaccent(nome))) like 'GUARANI DE GOIAS'; 
update cidade set cod_tom = '9993' where uf = 9 and upper(trim(unaccent(nome))) like 'GUARINOS'; 
update cidade set cod_tom = '9387' where uf = 9 and upper(trim(unaccent(nome))) like 'HEITORAI'; 
update cidade set cod_tom = '9389' where uf = 9 and upper(trim(unaccent(nome))) like 'HIDROLANDIA'; 
update cidade set cod_tom = '9391' where uf = 9 and upper(trim(unaccent(nome))) like 'HIDROLINA'; 
update cidade set cod_tom = '9393' where uf = 9 and upper(trim(unaccent(nome))) like 'IACIARA'; 
update cidade set cod_tom = '0069' where uf = 9 and upper(trim(unaccent(nome))) like 'INACIOLANDIA'; 
update cidade set cod_tom = '9681' where uf = 9 and upper(trim(unaccent(nome))) like 'INDIARA'; 
update cidade set cod_tom = '9395' where uf = 9 and upper(trim(unaccent(nome))) like 'INHUMAS'; 
update cidade set cod_tom = '9397' where uf = 9 and upper(trim(unaccent(nome))) like 'IPAMERI'; 
update cidade set cod_tom = '1074' where uf = 9 and upper(trim(unaccent(nome))) like 'IPIRANGA DE GOIAS'; 
update cidade set cod_tom = '9399' where uf = 9 and upper(trim(unaccent(nome))) like 'IPORA'; 
update cidade set cod_tom = '9401' where uf = 9 and upper(trim(unaccent(nome))) like 'ISRAELANDIA'; 
update cidade set cod_tom = '9403' where uf = 9 and upper(trim(unaccent(nome))) like 'ITABERAI'; 
update cidade set cod_tom = '9919' where uf = 9 and upper(trim(unaccent(nome))) like 'ITAGUARI'; 
update cidade set cod_tom = '9407' where uf = 9 and upper(trim(unaccent(nome))) like 'ITAGUARU'; 
update cidade set cod_tom = '9411' where uf = 9 and upper(trim(unaccent(nome))) like 'ITAJA'; 
update cidade set cod_tom = '9413' where uf = 9 and upper(trim(unaccent(nome))) like 'ITAPACI'; 
update cidade set cod_tom = '9415' where uf = 9 and upper(trim(unaccent(nome))) like 'ITAPIRAPUA'; 
update cidade set cod_tom = '9419' where uf = 9 and upper(trim(unaccent(nome))) like 'ITAPURANGA'; 
update cidade set cod_tom = '9421' where uf = 9 and upper(trim(unaccent(nome))) like 'ITARUMA'; 
update cidade set cod_tom = '9423' where uf = 9 and upper(trim(unaccent(nome))) like 'ITAUCU'; 
update cidade set cod_tom = '9425' where uf = 9 and upper(trim(unaccent(nome))) like 'ITUMBIARA'; 
update cidade set cod_tom = '9427' where uf = 9 and upper(trim(unaccent(nome))) like 'IVOLANDIA'; 
update cidade set cod_tom = '9429' where uf = 9 and upper(trim(unaccent(nome))) like 'JANDAIA'; 
update cidade set cod_tom = '9431' where uf = 9 and upper(trim(unaccent(nome))) like 'JARAGUA'; 
update cidade set cod_tom = '9433' where uf = 9 and upper(trim(unaccent(nome))) like 'JATAI'; 
update cidade set cod_tom = '9435' where uf = 9 and upper(trim(unaccent(nome))) like 'JAUPACI'; 
update cidade set cod_tom = '0049' where uf = 9 and upper(trim(unaccent(nome))) like 'JESUPOLIS'; 
update cidade set cod_tom = '9437' where uf = 9 and upper(trim(unaccent(nome))) like 'JOVIANIA'; 
update cidade set cod_tom = '9439' where uf = 9 and upper(trim(unaccent(nome))) like 'JUSSARA'; 
update cidade set cod_tom = '1076' where uf = 9 and upper(trim(unaccent(nome))) like 'LAGOA SANTA'; 
update cidade set cod_tom = '9443' where uf = 9 and upper(trim(unaccent(nome))) like 'LEOPOLDO DE BULHOES'; 
update cidade set cod_tom = '9445' where uf = 9 and upper(trim(unaccent(nome))) like 'LUZIANIA'; 
update cidade set cod_tom = '9447' where uf = 9 and upper(trim(unaccent(nome))) like 'MAIRIPOTABA'; 
update cidade set cod_tom = '9449' where uf = 9 and upper(trim(unaccent(nome))) like 'MAMBAI'; 
update cidade set cod_tom = '9451' where uf = 9 and upper(trim(unaccent(nome))) like 'MARA ROSA'; 
update cidade set cod_tom = '9453' where uf = 9 and upper(trim(unaccent(nome))) like 'MARZAGAO'; 
update cidade set cod_tom = '9927' where uf = 9 and upper(trim(unaccent(nome))) like 'MATRINCHA'; 
update cidade set cod_tom = '9457' where uf = 9 and upper(trim(unaccent(nome))) like 'MAURILANDIA'; 
update cidade set cod_tom = '9931' where uf = 9 and upper(trim(unaccent(nome))) like 'MIMOSO DE GOIAS'; 
update cidade set cod_tom = '9647' where uf = 9 and upper(trim(unaccent(nome))) like 'MINACU'; 
update cidade set cod_tom = '9459' where uf = 9 and upper(trim(unaccent(nome))) like 'MINEIROS'; 
update cidade set cod_tom = '9465' where uf = 9 and upper(trim(unaccent(nome))) like 'MOIPORA'; 
update cidade set cod_tom = '9467' where uf = 9 and upper(trim(unaccent(nome))) like 'MONTE ALEGRE DE GOIAS'; 
update cidade set cod_tom = '9471' where uf = 9 and upper(trim(unaccent(nome))) like 'MONTES CLAROS DE GOIAS'; 
update cidade set cod_tom = '9933' where uf = 9 and upper(trim(unaccent(nome))) like 'MONTIVIDIU'; 
update cidade set cod_tom = '0079' where uf = 9 and upper(trim(unaccent(nome))) like 'MONTIVIDIU DO NORTE'; 
update cidade set cod_tom = '9473' where uf = 9 and upper(trim(unaccent(nome))) like 'MORRINHOS'; 
update cidade set cod_tom = '9935' where uf = 9 and upper(trim(unaccent(nome))) like 'MORRO AGUDO DE GOIAS'; 
update cidade set cod_tom = '9475' where uf = 9 and upper(trim(unaccent(nome))) like 'MOSSAMEDES'; 
update cidade set cod_tom = '9477' where uf = 9 and upper(trim(unaccent(nome))) like 'MOZARLANDIA'; 
update cidade set cod_tom = '9651' where uf = 9 and upper(trim(unaccent(nome))) like 'MUNDO NOVO'; 
update cidade set cod_tom = '9479' where uf = 9 and upper(trim(unaccent(nome))) like 'MUTUNOPOLIS'; 
update cidade set cod_tom = '9485' where uf = 9 and upper(trim(unaccent(nome))) like 'NAZARIO'; 
update cidade set cod_tom = '9487' where uf = 9 and upper(trim(unaccent(nome))) like 'NEROPOLIS'; 
update cidade set cod_tom = '9489' where uf = 9 and upper(trim(unaccent(nome))) like 'NIQUELANDIA'; 
update cidade set cod_tom = '9491' where uf = 9 and upper(trim(unaccent(nome))) like 'NOVA AMERICA'; 
update cidade set cod_tom = '9493' where uf = 9 and upper(trim(unaccent(nome))) like 'NOVA AURORA'; 
update cidade set cod_tom = '9653' where uf = 9 and upper(trim(unaccent(nome))) like 'NOVA CRIXAS'; 
update cidade set cod_tom = '9655' where uf = 9 and upper(trim(unaccent(nome))) like 'NOVA GLORIA'; 
update cidade set cod_tom = '0087' where uf = 9 and upper(trim(unaccent(nome))) like 'NOVA IGUACU DE GOIAS'; 
update cidade set cod_tom = '9495' where uf = 9 and upper(trim(unaccent(nome))) like 'NOVA ROMA'; 
update cidade set cod_tom = '9497' where uf = 9 and upper(trim(unaccent(nome))) like 'NOVA VENEZA'; 
update cidade set cod_tom = '9501' where uf = 9 and upper(trim(unaccent(nome))) like 'NOVO BRASIL'; 
update cidade set cod_tom = '1058' where uf = 9 and upper(trim(unaccent(nome))) like 'NOVO GAMA'; 
update cidade set cod_tom = '9735' where uf = 9 and upper(trim(unaccent(nome))) like 'NOVO PLANALTO'; 
update cidade set cod_tom = '9503' where uf = 9 and upper(trim(unaccent(nome))) like 'ORIZONA'; 
update cidade set cod_tom = '9505' where uf = 9 and upper(trim(unaccent(nome))) like 'OURO VERDE DE GOIAS'; 
update cidade set cod_tom = '9507' where uf = 9 and upper(trim(unaccent(nome))) like 'OUVIDOR'; 
update cidade set cod_tom = '9509' where uf = 9 and upper(trim(unaccent(nome))) like 'PADRE BERNARDO'; 
update cidade set cod_tom = '9737' where uf = 9 and upper(trim(unaccent(nome))) like 'PALESTINA DE GOIAS'; 
update cidade set cod_tom = '9511' where uf = 9 and upper(trim(unaccent(nome))) like 'PALMEIRAS DE GOIAS'; 
update cidade set cod_tom = '9513' where uf = 9 and upper(trim(unaccent(nome))) like 'PALMELO'; 
update cidade set cod_tom = '9515' where uf = 9 and upper(trim(unaccent(nome))) like 'PALMINOPOLIS'; 
update cidade set cod_tom = '9517' where uf = 9 and upper(trim(unaccent(nome))) like 'PANAMA'; 
update cidade set cod_tom = '9455' where uf = 9 and upper(trim(unaccent(nome))) like 'PARANAIGUARA'; 
update cidade set cod_tom = '9523' where uf = 9 and upper(trim(unaccent(nome))) like 'PARAUNA'; 
update cidade set cod_tom = '0075' where uf = 9 and upper(trim(unaccent(nome))) like 'PEROLANDIA'; 
update cidade set cod_tom = '9531' where uf = 9 and upper(trim(unaccent(nome))) like 'PETROLINA DE GOIAS'; 
update cidade set cod_tom = '9535' where uf = 9 and upper(trim(unaccent(nome))) like 'PILAR DE GOIAS'; 
update cidade set cod_tom = '9539' where uf = 9 and upper(trim(unaccent(nome))) like 'PIRACANJUBA'; 
update cidade set cod_tom = '9541' where uf = 9 and upper(trim(unaccent(nome))) like 'PIRANHAS'; 
update cidade set cod_tom = '9543' where uf = 9 and upper(trim(unaccent(nome))) like 'PIRENOPOLIS'; 
update cidade set cod_tom = '9545' where uf = 9 and upper(trim(unaccent(nome))) like 'PIRES DO RIO'; 
update cidade set cod_tom = '9595' where uf = 9 and upper(trim(unaccent(nome))) like 'PLANALTINA'; 
update cidade set cod_tom = '9549' where uf = 9 and upper(trim(unaccent(nome))) like 'PONTALINA'; 
update cidade set cod_tom = '9555' where uf = 9 and upper(trim(unaccent(nome))) like 'PORANGATU'; 
update cidade set cod_tom = '1060' where uf = 9 and upper(trim(unaccent(nome))) like 'PORTEIRAO'; 
update cidade set cod_tom = '9557' where uf = 9 and upper(trim(unaccent(nome))) like 'PORTELANDIA'; 
update cidade set cod_tom = '9561' where uf = 9 and upper(trim(unaccent(nome))) like 'POSSE'; 
update cidade set cod_tom = '0051' where uf = 9 and upper(trim(unaccent(nome))) like 'PROFESSOR JAMIL'; 
update cidade set cod_tom = '9563' where uf = 9 and upper(trim(unaccent(nome))) like 'QUIRINOPOLIS'; 
update cidade set cod_tom = '9565' where uf = 9 and upper(trim(unaccent(nome))) like 'RIALMA'; 
update cidade set cod_tom = '9567' where uf = 9 and upper(trim(unaccent(nome))) like 'RIANAPOLIS'; 
update cidade set cod_tom = '9995' where uf = 9 and upper(trim(unaccent(nome))) like 'RIO QUENTE'; 
update cidade set cod_tom = '9571' where uf = 9 and upper(trim(unaccent(nome))) like 'RIO VERDE'; 
update cidade set cod_tom = '9573' where uf = 9 and upper(trim(unaccent(nome))) like 'RUBIATABA'; 
update cidade set cod_tom = '9575' where uf = 9 and upper(trim(unaccent(nome))) like 'SANCLERLANDIA'; 
update cidade set cod_tom = '9577' where uf = 9 and upper(trim(unaccent(nome))) like 'SANTA BARBARA DE GOIAS'; 
update cidade set cod_tom = '9579' where uf = 9 and upper(trim(unaccent(nome))) like 'SANTA CRUZ DE GOIAS'; 
update cidade set cod_tom = '9743' where uf = 9 and upper(trim(unaccent(nome))) like 'SANTA FE DE GOIAS'; 
update cidade set cod_tom = '9581' where uf = 9 and upper(trim(unaccent(nome))) like 'SANTA HELENA DE GOIAS'; 
update cidade set cod_tom = '9689' where uf = 9 and upper(trim(unaccent(nome))) like 'SANTA ISABEL'; 
update cidade set cod_tom = '9583' where uf = 9 and upper(trim(unaccent(nome))) like 'SANTA RITA DO ARAGUAIA'; 
update cidade set cod_tom = '1062' where uf = 9 and upper(trim(unaccent(nome))) like 'SANTA RITA DO NOVO DESTINO'; 
update cidade set cod_tom = '9585' where uf = 9 and upper(trim(unaccent(nome))) like 'SANTA ROSA DE GOIAS'; 
update cidade set cod_tom = '9587' where uf = 9 and upper(trim(unaccent(nome))) like 'SANTA TEREZA DE GOIAS'; 
update cidade set cod_tom = '9589' where uf = 9 and upper(trim(unaccent(nome))) like 'SANTA TEREZINHA DE GOIAS'; 
update cidade set cod_tom = '0083' where uf = 9 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DA BARRA'; 
update cidade set cod_tom = '0053' where uf = 9 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DE GOIAS'; 
update cidade set cod_tom = '9677' where uf = 9 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO DESCOBERTO'; 
update cidade set cod_tom = '9591' where uf = 9 and upper(trim(unaccent(nome))) like 'SAO DOMINGOS'; 
update cidade set cod_tom = '9593' where uf = 9 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO DE GOIAS'; 
update cidade set cod_tom = '9747' where uf = 9 and upper(trim(unaccent(nome))) like 'SAO JOAO DA PARAUNA'; 
update cidade set cod_tom = '9597' where uf = 9 and upper(trim(unaccent(nome))) like 'SAO JOAO D`ALIANCA'; 
update cidade set cod_tom = '9599' where uf = 9 and upper(trim(unaccent(nome))) like 'SAO LUIS DE MONTES BELOS'; 
update cidade set cod_tom = '9749' where uf = 9 and upper(trim(unaccent(nome))) like 'SAO LUIZ DO NORTE'; 
update cidade set cod_tom = '9601' where uf = 9 and upper(trim(unaccent(nome))) like 'SAO MIGUEL DO ARAGUAIA'; 
update cidade set cod_tom = '9751' where uf = 9 and upper(trim(unaccent(nome))) like 'SAO MIGUEL DO PASSA QUATRO'; 
update cidade set cod_tom = '1064' where uf = 9 and upper(trim(unaccent(nome))) like 'SAO PATRICIO'; 
update cidade set cod_tom = '9605' where uf = 9 and upper(trim(unaccent(nome))) like 'SAO SIMAO'; 
update cidade set cod_tom = '9753' where uf = 9 and upper(trim(unaccent(nome))) like 'SENADOR CANEDO'; 
update cidade set cod_tom = '9607' where uf = 9 and upper(trim(unaccent(nome))) like 'SERRANOPOLIS'; 
update cidade set cod_tom = '9609' where uf = 9 and upper(trim(unaccent(nome))) like 'SILVANIA'; 
update cidade set cod_tom = '9755' where uf = 9 and upper(trim(unaccent(nome))) like 'SIMOLANDIA'; 
update cidade set cod_tom = '9611' where uf = 9 and upper(trim(unaccent(nome))) like 'SITIO D`ABADIA'; 
update cidade set cod_tom = '9617' where uf = 9 and upper(trim(unaccent(nome))) like 'TAQUARAL DE GOIAS'; 
update cidade set cod_tom = '9759' where uf = 9 and upper(trim(unaccent(nome))) like 'TERESINA DE GOIAS'; 
update cidade set cod_tom = '0057' where uf = 9 and upper(trim(unaccent(nome))) like 'TEREZOPOLIS DE GOIAS'; 
update cidade set cod_tom = '9623' where uf = 9 and upper(trim(unaccent(nome))) like 'TRES RANCHOS'; 
update cidade set cod_tom = '9625' where uf = 9 and upper(trim(unaccent(nome))) like 'TRINDADE'; 
update cidade set cod_tom = '9761' where uf = 9 and upper(trim(unaccent(nome))) like 'TROMBAS'; 
update cidade set cod_tom = '9631' where uf = 9 and upper(trim(unaccent(nome))) like 'TURVANIA'; 
update cidade set cod_tom = '9765' where uf = 9 and upper(trim(unaccent(nome))) like 'TURVELANDIA'; 
update cidade set cod_tom = '0059' where uf = 9 and upper(trim(unaccent(nome))) like 'UIRAPURU'; 
update cidade set cod_tom = '9633' where uf = 9 and upper(trim(unaccent(nome))) like 'URUACU'; 
update cidade set cod_tom = '9635' where uf = 9 and upper(trim(unaccent(nome))) like 'URUANA'; 
update cidade set cod_tom = '9637' where uf = 9 and upper(trim(unaccent(nome))) like 'URUTAI'; 
update cidade set cod_tom = '1066' where uf = 9 and upper(trim(unaccent(nome))) like 'VALPARAISO DE GOIAS'; 
update cidade set cod_tom = '9639' where uf = 9 and upper(trim(unaccent(nome))) like 'VARJAO'; 
update cidade set cod_tom = '9641' where uf = 9 and upper(trim(unaccent(nome))) like 'VIANOPOLIS'; 
update cidade set cod_tom = '9657' where uf = 9 and upper(trim(unaccent(nome))) like 'VICENTINOPOLIS'; 
update cidade set cod_tom = '0067' where uf = 9 and upper(trim(unaccent(nome))) like 'VILA BOA'; 
update cidade set cod_tom = '1068' where uf = 9 and upper(trim(unaccent(nome))) like 'VILA PROPICIO'; 
