update cidade set cod_tom = '5601' where uf = 8 and upper(trim(unaccent(nome))) like 'AFONSO CLAUDIO'; 
update cidade set cod_tom = '5717' where uf = 8 and upper(trim(unaccent(nome))) like 'AGUA DOCE DO NORTE'; 
update cidade set cod_tom = '5733' where uf = 8 and upper(trim(unaccent(nome))) like 'AGUIA BRANCA'; 
update cidade set cod_tom = '5603' where uf = 8 and upper(trim(unaccent(nome))) like 'ALEGRE'; 
update cidade set cod_tom = '5605' where uf = 8 and upper(trim(unaccent(nome))) like 'ALFREDO CHAVES'; 
update cidade set cod_tom = '5719' where uf = 8 and upper(trim(unaccent(nome))) like 'ALTO RIO NOVO'; 
update cidade set cod_tom = '5607' where uf = 8 and upper(trim(unaccent(nome))) like 'ANCHIETA'; 
update cidade set cod_tom = '5609' where uf = 8 and upper(trim(unaccent(nome))) like 'APIACA'; 
update cidade set cod_tom = '5611' where uf = 8 and upper(trim(unaccent(nome))) like 'ARACRUZ'; 
update cidade set cod_tom = '5613' where uf = 8 and upper(trim(unaccent(nome))) like 'ATILIO VIVACQUA'; 
update cidade set cod_tom = '5615' where uf = 8 and upper(trim(unaccent(nome))) like 'BAIXO GUANDU'; 
update cidade set cod_tom = '5617' where uf = 8 and upper(trim(unaccent(nome))) like 'BARRA DE SAO FRANCISCO'; 
update cidade set cod_tom = '5619' where uf = 8 and upper(trim(unaccent(nome))) like 'BOA ESPERANCA'; 
update cidade set cod_tom = '5621' where uf = 8 and upper(trim(unaccent(nome))) like 'BOM JESUS DO NORTE'; 
update cidade set cod_tom = '0758' where uf = 8 and upper(trim(unaccent(nome))) like 'BREJETUBA'; 
update cidade set cod_tom = '5623' where uf = 8 and upper(trim(unaccent(nome))) like 'CACHOEIRO DE ITAPEMIRIM'; 
update cidade set cod_tom = '5625' where uf = 8 and upper(trim(unaccent(nome))) like 'CARIACICA'; 
update cidade set cod_tom = '5627' where uf = 8 and upper(trim(unaccent(nome))) like 'CASTELO'; 
update cidade set cod_tom = '5629' where uf = 8 and upper(trim(unaccent(nome))) like 'COLATINA'; 
update cidade set cod_tom = '5631' where uf = 8 and upper(trim(unaccent(nome))) like 'CONCEICAO DA BARRA'; 
update cidade set cod_tom = '5633' where uf = 8 and upper(trim(unaccent(nome))) like 'CONCEICAO DO CASTELO'; 
update cidade set cod_tom = '5635' where uf = 8 and upper(trim(unaccent(nome))) like 'DIVINO DE SAO LOURENCO'; 
update cidade set cod_tom = '5637' where uf = 8 and upper(trim(unaccent(nome))) like 'DOMINGOS MARTINS'; 
update cidade set cod_tom = '5639' where uf = 8 and upper(trim(unaccent(nome))) like 'DORES DO RIO PRETO'; 
update cidade set cod_tom = '5641' where uf = 8 and upper(trim(unaccent(nome))) like 'ECOPORANGA'; 
update cidade set cod_tom = '5643' where uf = 8 and upper(trim(unaccent(nome))) like 'FUNDAO'; 
update cidade set cod_tom = '1114' where uf = 8 and upper(trim(unaccent(nome))) like 'GOVERNADOR LINDENBERG'; 
update cidade set cod_tom = '5645' where uf = 8 and upper(trim(unaccent(nome))) like 'GUACUI'; 
update cidade set cod_tom = '5647' where uf = 8 and upper(trim(unaccent(nome))) like 'GUARAPARI'; 
update cidade set cod_tom = '5709' where uf = 8 and upper(trim(unaccent(nome))) like 'IBATIBA'; 
update cidade set cod_tom = '5649' where uf = 8 and upper(trim(unaccent(nome))) like 'IBIRACU'; 
update cidade set cod_tom = '6011' where uf = 8 and upper(trim(unaccent(nome))) like 'IBITIRAMA'; 
update cidade set cod_tom = '5651' where uf = 8 and upper(trim(unaccent(nome))) like 'ICONHA'; 
update cidade set cod_tom = '2931' where uf = 8 and upper(trim(unaccent(nome))) like 'IRUPI'; 
update cidade set cod_tom = '5653' where uf = 8 and upper(trim(unaccent(nome))) like 'ITAGUACU'; 
update cidade set cod_tom = '5655' where uf = 8 and upper(trim(unaccent(nome))) like 'ITAPEMIRIM'; 
update cidade set cod_tom = '5657' where uf = 8 and upper(trim(unaccent(nome))) like 'ITARANA'; 
update cidade set cod_tom = '5659' where uf = 8 and upper(trim(unaccent(nome))) like 'IUNA'; 
update cidade set cod_tom = '5713' where uf = 8 and upper(trim(unaccent(nome))) like 'JAGUARE'; 
update cidade set cod_tom = '5661' where uf = 8 and upper(trim(unaccent(nome))) like 'JERONIMO MONTEIRO'; 
update cidade set cod_tom = '5721' where uf = 8 and upper(trim(unaccent(nome))) like 'JOAO NEIVA'; 
update cidade set cod_tom = '5723' where uf = 8 and upper(trim(unaccent(nome))) like 'LARANJA DA TERRA'; 
update cidade set cod_tom = '5663' where uf = 8 and upper(trim(unaccent(nome))) like 'LINHARES'; 
update cidade set cod_tom = '5665' where uf = 8 and upper(trim(unaccent(nome))) like 'MANTENOPOLIS'; 
update cidade set cod_tom = '0760' where uf = 8 and upper(trim(unaccent(nome))) like 'MARATAIZES'; 
update cidade set cod_tom = '2929' where uf = 8 and upper(trim(unaccent(nome))) like 'MARECHAL FLORIANO'; 
update cidade set cod_tom = '5707' where uf = 8 and upper(trim(unaccent(nome))) like 'MARILANDIA'; 
update cidade set cod_tom = '5667' where uf = 8 and upper(trim(unaccent(nome))) like 'MIMOSO DO SUL'; 
update cidade set cod_tom = '5669' where uf = 8 and upper(trim(unaccent(nome))) like 'MONTANHA'; 
update cidade set cod_tom = '5671' where uf = 8 and upper(trim(unaccent(nome))) like 'MUCURICI'; 
update cidade set cod_tom = '5673' where uf = 8 and upper(trim(unaccent(nome))) like 'MUNIZ FREIRE'; 
update cidade set cod_tom = '5675' where uf = 8 and upper(trim(unaccent(nome))) like 'MUQUI'; 
update cidade set cod_tom = '5677' where uf = 8 and upper(trim(unaccent(nome))) like 'NOVA VENECIA'; 
update cidade set cod_tom = '5679' where uf = 8 and upper(trim(unaccent(nome))) like 'PANCAS'; 
update cidade set cod_tom = '5715' where uf = 8 and upper(trim(unaccent(nome))) like 'PEDRO CANARIO'; 
update cidade set cod_tom = '5681' where uf = 8 and upper(trim(unaccent(nome))) like 'PINHEIROS'; 
update cidade set cod_tom = '5683' where uf = 8 and upper(trim(unaccent(nome))) like 'PIUMA'; 
update cidade set cod_tom = '0762' where uf = 8 and upper(trim(unaccent(nome))) like 'PONTO BELO'; 
update cidade set cod_tom = '5685' where uf = 8 and upper(trim(unaccent(nome))) like 'PRESIDENTE KENNEDY'; 
update cidade set cod_tom = '5711' where uf = 8 and upper(trim(unaccent(nome))) like 'RIO BANANAL'; 
update cidade set cod_tom = '5687' where uf = 8 and upper(trim(unaccent(nome))) like 'RIO NOVO DO SUL'; 
update cidade set cod_tom = '5689' where uf = 8 and upper(trim(unaccent(nome))) like 'SANTA LEOPOLDINA'; 
update cidade set cod_tom = '5725' where uf = 8 and upper(trim(unaccent(nome))) like 'SANTA MARIA DE JETIBA'; 
update cidade set cod_tom = '5691' where uf = 8 and upper(trim(unaccent(nome))) like 'SANTA TERESA'; 
update cidade set cod_tom = '2933' where uf = 8 and upper(trim(unaccent(nome))) like 'SAO DOMINGOS DO NORTE'; 
update cidade set cod_tom = '5693' where uf = 8 and upper(trim(unaccent(nome))) like 'SAO GABRIEL DA PALHA'; 
update cidade set cod_tom = '5695' where uf = 8 and upper(trim(unaccent(nome))) like 'SAO JOSE DO CALCADO'; 
update cidade set cod_tom = '5697' where uf = 8 and upper(trim(unaccent(nome))) like 'SAO MATEUS'; 
update cidade set cod_tom = '0764' where uf = 8 and upper(trim(unaccent(nome))) like 'SAO ROQUE DO CANAA'; 
update cidade set cod_tom = '0764' where uf = 8 and upper(trim(unaccent(nome))) like 'SAO ROQUE DO CANAA'; 
update cidade set cod_tom = '5699' where uf = 8 and upper(trim(unaccent(nome))) like 'SERRA'; 
update cidade set cod_tom = '0766' where uf = 8 and upper(trim(unaccent(nome))) like 'SOORETAMA'; 
update cidade set cod_tom = '5727' where uf = 8 and upper(trim(unaccent(nome))) like 'VARGEM ALTA'; 
update cidade set cod_tom = '5729' where uf = 8 and upper(trim(unaccent(nome))) like 'VENDA NOVA DO IMIGRANTE'; 
update cidade set cod_tom = '5701' where uf = 8 and upper(trim(unaccent(nome))) like 'VIANA'; 
update cidade set cod_tom = '2935' where uf = 8 and upper(trim(unaccent(nome))) like 'VILA PAVAO'; 
update cidade set cod_tom = '0768' where uf = 8 and upper(trim(unaccent(nome))) like 'VILA VALERIO'; 
update cidade set cod_tom = '5703' where uf = 8 and upper(trim(unaccent(nome))) like 'VILA VELHA'; 
update cidade set cod_tom = '5705' where uf = 8 and upper(trim(unaccent(nome))) like 'VITORIA'; 
