update cidade set cod_tom = '0289' where uf = 3 and upper(trim(unaccent(nome))) like 'ALVARAES'; 
update cidade set cod_tom = '0291' where uf = 3 and upper(trim(unaccent(nome))) like 'AMATURA'; 
update cidade set cod_tom = '0293' where uf = 3 and upper(trim(unaccent(nome))) like 'ANAMA'; 
update cidade set cod_tom = '0203' where uf = 3 and upper(trim(unaccent(nome))) like 'ANORI'; 
update cidade set cod_tom = '0969' where uf = 3 and upper(trim(unaccent(nome))) like 'APUI'; 
update cidade set cod_tom = '0205' where uf = 3 and upper(trim(unaccent(nome))) like 'ATALAIA DO NORTE'; 
update cidade set cod_tom = '0207' where uf = 3 and upper(trim(unaccent(nome))) like 'AUTAZES'; 
update cidade set cod_tom = '0209' where uf = 3 and upper(trim(unaccent(nome))) like 'BARCELOS'; 
update cidade set cod_tom = '0211' where uf = 3 and upper(trim(unaccent(nome))) like 'BARREIRINHA'; 
update cidade set cod_tom = '0213' where uf = 3 and upper(trim(unaccent(nome))) like 'BENJAMIN CONSTANT'; 
update cidade set cod_tom = '0295' where uf = 3 and upper(trim(unaccent(nome))) like 'BERURI'; 
update cidade set cod_tom = '0297' where uf = 3 and upper(trim(unaccent(nome))) like 'BOA VISTA DO RAMOS'; 
update cidade set cod_tom = '0215' where uf = 3 and upper(trim(unaccent(nome))) like 'BOCA DO ACRE'; 
update cidade set cod_tom = '0217' where uf = 3 and upper(trim(unaccent(nome))) like 'BORBA'; 
update cidade set cod_tom = '0299' where uf = 3 and upper(trim(unaccent(nome))) like 'CAAPIRANGA'; 
update cidade set cod_tom = '0219' where uf = 3 and upper(trim(unaccent(nome))) like 'CANUTAMA'; 
update cidade set cod_tom = '0221' where uf = 3 and upper(trim(unaccent(nome))) like 'CARAUARI'; 
update cidade set cod_tom = '0223' where uf = 3 and upper(trim(unaccent(nome))) like 'CAREIRO'; 
update cidade set cod_tom = '0965' where uf = 3 and upper(trim(unaccent(nome))) like 'CAREIRO DA VARZEA'; 
update cidade set cod_tom = '0225' where uf = 3 and upper(trim(unaccent(nome))) like 'COARI'; 
update cidade set cod_tom = '0227' where uf = 3 and upper(trim(unaccent(nome))) like 'CODAJAS'; 
update cidade set cod_tom = '0229' where uf = 3 and upper(trim(unaccent(nome))) like 'EIRUNEPE'; 
update cidade set cod_tom = '0231' where uf = 3 and upper(trim(unaccent(nome))) like 'ENVIRA'; 
update cidade set cod_tom = '0233' where uf = 3 and upper(trim(unaccent(nome))) like 'FONTE BOA'; 
update cidade set cod_tom = '0967' where uf = 3 and upper(trim(unaccent(nome))) like 'GUAJARA'; 
update cidade set cod_tom = '0235' where uf = 3 and upper(trim(unaccent(nome))) like 'HUMAITA'; 
update cidade set cod_tom = '0239' where uf = 3 and upper(trim(unaccent(nome))) like 'IPIXUNA'; 
update cidade set cod_tom = '9835' where uf = 3 and upper(trim(unaccent(nome))) like 'IRANDUBA'; 
update cidade set cod_tom = '0241' where uf = 3 and upper(trim(unaccent(nome))) like 'ITACOATIARA'; 
update cidade set cod_tom = '9837' where uf = 3 and upper(trim(unaccent(nome))) like 'ITAMARATI'; 
update cidade set cod_tom = '0243' where uf = 3 and upper(trim(unaccent(nome))) like 'ITAPIRANGA'; 
update cidade set cod_tom = '0245' where uf = 3 and upper(trim(unaccent(nome))) like 'JAPURA'; 
update cidade set cod_tom = '0247' where uf = 3 and upper(trim(unaccent(nome))) like 'JURUA'; 
update cidade set cod_tom = '0249' where uf = 3 and upper(trim(unaccent(nome))) like 'JUTAI'; 
update cidade set cod_tom = '0251' where uf = 3 and upper(trim(unaccent(nome))) like 'LABREA'; 
update cidade set cod_tom = '0253' where uf = 3 and upper(trim(unaccent(nome))) like 'MANACAPURU'; 
update cidade set cod_tom = '9839' where uf = 3 and upper(trim(unaccent(nome))) like 'MANAQUIRI'; 
update cidade set cod_tom = '0255' where uf = 3 and upper(trim(unaccent(nome))) like 'MANAUS'; 
update cidade set cod_tom = '0257' where uf = 3 and upper(trim(unaccent(nome))) like 'MANICORE'; 
update cidade set cod_tom = '0259' where uf = 3 and upper(trim(unaccent(nome))) like 'MARAA'; 
update cidade set cod_tom = '0261' where uf = 3 and upper(trim(unaccent(nome))) like 'MAUES'; 
update cidade set cod_tom = '0263' where uf = 3 and upper(trim(unaccent(nome))) like 'NHAMUNDA'; 
update cidade set cod_tom = '0265' where uf = 3 and upper(trim(unaccent(nome))) like 'NOVA OLINDA DO NORTE'; 
update cidade set cod_tom = '0201' where uf = 3 and upper(trim(unaccent(nome))) like 'NOVO AIRAO'; 
update cidade set cod_tom = '0267' where uf = 3 and upper(trim(unaccent(nome))) like 'NOVO ARIPUANA'; 
update cidade set cod_tom = '0269' where uf = 3 and upper(trim(unaccent(nome))) like 'PARINTINS'; 
update cidade set cod_tom = '0271' where uf = 3 and upper(trim(unaccent(nome))) like 'PAUINI'; 
update cidade set cod_tom = '9841' where uf = 3 and upper(trim(unaccent(nome))) like 'PRESIDENTE FIGUEIREDO'; 
update cidade set cod_tom = '9843' where uf = 3 and upper(trim(unaccent(nome))) like 'RIO PRETO DA EVA'; 
update cidade set cod_tom = '0237' where uf = 3 and upper(trim(unaccent(nome))) like 'SANTA ISABEL DO RIO NEGRO'; 
update cidade set cod_tom = '0273' where uf = 3 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO ICA'; 
update cidade set cod_tom = '0283' where uf = 3 and upper(trim(unaccent(nome))) like 'SAO GABRIEL DA CACHOEIRA'; 
update cidade set cod_tom = '0275' where uf = 3 and upper(trim(unaccent(nome))) like 'SAO PAULO DE OLIVENCA'; 
update cidade set cod_tom = '9845' where uf = 3 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO DO UATUMA'; 
update cidade set cod_tom = '0277' where uf = 3 and upper(trim(unaccent(nome))) like 'SILVES'; 
update cidade set cod_tom = '9847' where uf = 3 and upper(trim(unaccent(nome))) like 'TABATINGA'; 
update cidade set cod_tom = '0279' where uf = 3 and upper(trim(unaccent(nome))) like 'TAPAUA'; 
update cidade set cod_tom = '0281' where uf = 3 and upper(trim(unaccent(nome))) like 'TEFE'; 
update cidade set cod_tom = '9851' where uf = 3 and upper(trim(unaccent(nome))) like 'TONANTINS'; 
update cidade set cod_tom = '9849' where uf = 3 and upper(trim(unaccent(nome))) like 'UARINI'; 
update cidade set cod_tom = '0285' where uf = 3 and upper(trim(unaccent(nome))) like 'URUCARA'; 
update cidade set cod_tom = '0287' where uf = 3 and upper(trim(unaccent(nome))) like 'URUCURITUBA'; 
