update cidade set cod_tom = '0961' where uf = 10 and upper(trim(unaccent(nome))) like 'ACAILANDIA'; 
update cidade set cod_tom = '0701' where uf = 10 and upper(trim(unaccent(nome))) like 'AFONSO CUNHA'; 
update cidade set cod_tom = '0104' where uf = 10 and upper(trim(unaccent(nome))) like 'AGUA DOCE DO MARANHAO'; 
update cidade set cod_tom = '0703' where uf = 10 and upper(trim(unaccent(nome))) like 'ALCANTARA'; 
update cidade set cod_tom = '0705' where uf = 10 and upper(trim(unaccent(nome))) like 'ALDEIAS ALTAS'; 
update cidade set cod_tom = '0707' where uf = 10 and upper(trim(unaccent(nome))) like 'ALTAMIRA DO MARANHAO'; 
update cidade set cod_tom = '0106' where uf = 10 and upper(trim(unaccent(nome))) like 'ALTO ALEGRE DO MARANHAO'; 
update cidade set cod_tom = '0108' where uf = 10 and upper(trim(unaccent(nome))) like 'ALTO ALEGRE DO PINDARE'; 
update cidade set cod_tom = '0709' where uf = 10 and upper(trim(unaccent(nome))) like 'ALTO PARNAIBA'; 
update cidade set cod_tom = '0110' where uf = 10 and upper(trim(unaccent(nome))) like 'AMAPA DO MARANHAO'; 
update cidade set cod_tom = '0711' where uf = 10 and upper(trim(unaccent(nome))) like 'AMARANTE DO MARANHAO'; 
update cidade set cod_tom = '0713' where uf = 10 and upper(trim(unaccent(nome))) like 'ANAJATUBA'; 
update cidade set cod_tom = '0715' where uf = 10 and upper(trim(unaccent(nome))) like 'ANAPURUS'; 
update cidade set cod_tom = '0112' where uf = 10 and upper(trim(unaccent(nome))) like 'APICUM-ACU'; 
update cidade set cod_tom = '0114' where uf = 10 and upper(trim(unaccent(nome))) like 'ARAGUANA'; 
update cidade set cod_tom = '0717' where uf = 10 and upper(trim(unaccent(nome))) like 'ARAIOSES'; 
update cidade set cod_tom = '1281' where uf = 10 and upper(trim(unaccent(nome))) like 'ARAME'; 
update cidade set cod_tom = '0719' where uf = 10 and upper(trim(unaccent(nome))) like 'ARARI'; 
update cidade set cod_tom = '0721' where uf = 10 and upper(trim(unaccent(nome))) like 'AXIXA'; 
update cidade set cod_tom = '0723' where uf = 10 and upper(trim(unaccent(nome))) like 'BACABAL'; 
update cidade set cod_tom = '0116' where uf = 10 and upper(trim(unaccent(nome))) like 'BACABEIRA'; 
update cidade set cod_tom = '0725' where uf = 10 and upper(trim(unaccent(nome))) like 'BACURI'; 
update cidade set cod_tom = '0118' where uf = 10 and upper(trim(unaccent(nome))) like 'BACURITUBA'; 
update cidade set cod_tom = '0727' where uf = 10 and upper(trim(unaccent(nome))) like 'BALSAS'; 
update cidade set cod_tom = '0729' where uf = 10 and upper(trim(unaccent(nome))) like 'BARAO DE GRAJAU'; 
update cidade set cod_tom = '0731' where uf = 10 and upper(trim(unaccent(nome))) like 'BARRA DO CORDA'; 
update cidade set cod_tom = '0733' where uf = 10 and upper(trim(unaccent(nome))) like 'BARREIRINHAS'; 
update cidade set cod_tom = '0122' where uf = 10 and upper(trim(unaccent(nome))) like 'BELA VISTA DO MARANHAO'; 
update cidade set cod_tom = '0120' where uf = 10 and upper(trim(unaccent(nome))) like 'BELAGUA'; 
update cidade set cod_tom = '0735' where uf = 10 and upper(trim(unaccent(nome))) like 'BENEDITO LEITE'; 
update cidade set cod_tom = '0737' where uf = 10 and upper(trim(unaccent(nome))) like 'BEQUIMAO'; 
update cidade set cod_tom = '0124' where uf = 10 and upper(trim(unaccent(nome))) like 'BERNARDO DO MEARIM'; 
update cidade set cod_tom = '0126' where uf = 10 and upper(trim(unaccent(nome))) like 'BOA VISTA DO GURUPI'; 
update cidade set cod_tom = '0955' where uf = 10 and upper(trim(unaccent(nome))) like 'BOM JARDIM'; 
update cidade set cod_tom = '0128' where uf = 10 and upper(trim(unaccent(nome))) like 'BOM JESUS DAS SELVAS'; 
update cidade set cod_tom = '0130' where uf = 10 and upper(trim(unaccent(nome))) like 'BOM LUGAR'; 
update cidade set cod_tom = '0739' where uf = 10 and upper(trim(unaccent(nome))) like 'BREJO'; 
update cidade set cod_tom = '0132' where uf = 10 and upper(trim(unaccent(nome))) like 'BREJO DE AREIA'; 
update cidade set cod_tom = '0741' where uf = 10 and upper(trim(unaccent(nome))) like 'BURITI'; 
update cidade set cod_tom = '0743' where uf = 10 and upper(trim(unaccent(nome))) like 'BURITI BRAVO'; 
update cidade set cod_tom = '0134' where uf = 10 and upper(trim(unaccent(nome))) like 'BURITICUPU'; 
update cidade set cod_tom = '0136' where uf = 10 and upper(trim(unaccent(nome))) like 'BURITIRANA'; 
update cidade set cod_tom = '0138' where uf = 10 and upper(trim(unaccent(nome))) like 'CACHOEIRA GRANDE'; 
update cidade set cod_tom = '0745' where uf = 10 and upper(trim(unaccent(nome))) like 'CAJAPIO'; 
update cidade set cod_tom = '0747' where uf = 10 and upper(trim(unaccent(nome))) like 'CAJARI'; 
update cidade set cod_tom = '0140' where uf = 10 and upper(trim(unaccent(nome))) like 'CAMPESTRE DO MARANHAO'; 
update cidade set cod_tom = '0749' where uf = 10 and upper(trim(unaccent(nome))) like 'CANDIDO MENDES'; 
update cidade set cod_tom = '0751' where uf = 10 and upper(trim(unaccent(nome))) like 'CANTANHEDE'; 
update cidade set cod_tom = '0142' where uf = 10 and upper(trim(unaccent(nome))) like 'CAPINZAL DO NORTE'; 
update cidade set cod_tom = '0753' where uf = 10 and upper(trim(unaccent(nome))) like 'CAROLINA'; 
update cidade set cod_tom = '0755' where uf = 10 and upper(trim(unaccent(nome))) like 'CARUTAPERA'; 
update cidade set cod_tom = '0757' where uf = 10 and upper(trim(unaccent(nome))) like 'CAXIAS'; 
update cidade set cod_tom = '0759' where uf = 10 and upper(trim(unaccent(nome))) like 'CEDRAL'; 
update cidade set cod_tom = '0144' where uf = 10 and upper(trim(unaccent(nome))) like 'CENTRAL DO MARANHAO'; 
update cidade set cod_tom = '0146' where uf = 10 and upper(trim(unaccent(nome))) like 'CENTRO DO GUILHERME'; 
update cidade set cod_tom = '0148' where uf = 10 and upper(trim(unaccent(nome))) like 'CENTRO NOVO DO MARANHAO'; 
update cidade set cod_tom = '0761' where uf = 10 and upper(trim(unaccent(nome))) like 'CHAPADINHA'; 
update cidade set cod_tom = '0150' where uf = 10 and upper(trim(unaccent(nome))) like 'CIDELANDIA'; 
update cidade set cod_tom = '0763' where uf = 10 and upper(trim(unaccent(nome))) like 'CODO'; 
update cidade set cod_tom = '0765' where uf = 10 and upper(trim(unaccent(nome))) like 'COELHO NETO'; 
update cidade set cod_tom = '0767' where uf = 10 and upper(trim(unaccent(nome))) like 'COLINAS'; 
update cidade set cod_tom = '0152' where uf = 10 and upper(trim(unaccent(nome))) like 'CONCEICAO DO LAGO-ACU'; 
update cidade set cod_tom = '0769' where uf = 10 and upper(trim(unaccent(nome))) like 'COROATA'; 
update cidade set cod_tom = '0771' where uf = 10 and upper(trim(unaccent(nome))) like 'CURURUPU'; 
update cidade set cod_tom = '0154' where uf = 10 and upper(trim(unaccent(nome))) like 'DAVINOPOLIS'; 
update cidade set cod_tom = '0773' where uf = 10 and upper(trim(unaccent(nome))) like 'DOM PEDRO'; 
update cidade set cod_tom = '0775' where uf = 10 and upper(trim(unaccent(nome))) like 'DUQUE BACELAR'; 
update cidade set cod_tom = '0777' where uf = 10 and upper(trim(unaccent(nome))) like 'ESPERANTINOPOLIS'; 
update cidade set cod_tom = '0963' where uf = 10 and upper(trim(unaccent(nome))) like 'ESTREITO'; 
update cidade set cod_tom = '0156' where uf = 10 and upper(trim(unaccent(nome))) like 'FEIRA NOVA DO MARANHAO'; 
update cidade set cod_tom = '0158' where uf = 10 and upper(trim(unaccent(nome))) like 'FERNANDO FALCAO'; 
update cidade set cod_tom = '0160' where uf = 10 and upper(trim(unaccent(nome))) like 'FORMOSA DA SERRA NEGRA'; 
update cidade set cod_tom = '0779' where uf = 10 and upper(trim(unaccent(nome))) like 'FORTALEZA DOS NOGUEIRAS'; 
update cidade set cod_tom = '0781' where uf = 10 and upper(trim(unaccent(nome))) like 'FORTUNA'; 
update cidade set cod_tom = '0783' where uf = 10 and upper(trim(unaccent(nome))) like 'GODOFREDO VIANA'; 
update cidade set cod_tom = '0785' where uf = 10 and upper(trim(unaccent(nome))) like 'GONCALVES DIAS'; 
update cidade set cod_tom = '0787' where uf = 10 and upper(trim(unaccent(nome))) like 'GOVERNADOR ARCHER'; 
update cidade set cod_tom = '0162' where uf = 10 and upper(trim(unaccent(nome))) like 'GOVERNADOR EDISON LOBAO'; 
update cidade set cod_tom = '0789' where uf = 10 and upper(trim(unaccent(nome))) like 'GOVERNADOR EUGENIO BARROS'; 
update cidade set cod_tom = '0164' where uf = 10 and upper(trim(unaccent(nome))) like 'GOVERNADOR LUIZ ROCHA'; 
update cidade set cod_tom = '0166' where uf = 10 and upper(trim(unaccent(nome))) like 'GOVERNADOR NEWTON BELLO'; 
update cidade set cod_tom = '0168' where uf = 10 and upper(trim(unaccent(nome))) like 'GOVERNADOR NUNES FREIRE'; 
update cidade set cod_tom = '0791' where uf = 10 and upper(trim(unaccent(nome))) like 'GRACA ARANHA'; 
update cidade set cod_tom = '0793' where uf = 10 and upper(trim(unaccent(nome))) like 'GRAJAU'; 
update cidade set cod_tom = '0795' where uf = 10 and upper(trim(unaccent(nome))) like 'GUIMARAES'; 
update cidade set cod_tom = '0797' where uf = 10 and upper(trim(unaccent(nome))) like 'HUMBERTO DE CAMPOS'; 
update cidade set cod_tom = '0799' where uf = 10 and upper(trim(unaccent(nome))) like 'ICATU'; 
update cidade set cod_tom = '0170' where uf = 10 and upper(trim(unaccent(nome))) like 'IGARAPE DO MEIO'; 
update cidade set cod_tom = '0801' where uf = 10 and upper(trim(unaccent(nome))) like 'IGARAPE GRANDE'; 
update cidade set cod_tom = '0803' where uf = 10 and upper(trim(unaccent(nome))) like 'IMPERATRIZ'; 
update cidade set cod_tom = '0172' where uf = 10 and upper(trim(unaccent(nome))) like 'ITAIPAVA DO GRAJAU'; 
update cidade set cod_tom = '0807' where uf = 10 and upper(trim(unaccent(nome))) like 'ITAPECURU MIRIM'; 
update cidade set cod_tom = '0174' where uf = 10 and upper(trim(unaccent(nome))) like 'ITINGA DO MARANHAO'; 
update cidade set cod_tom = '0176' where uf = 10 and upper(trim(unaccent(nome))) like 'JATOBA'; 
update cidade set cod_tom = '0178' where uf = 10 and upper(trim(unaccent(nome))) like 'JENIPAPO DOS VIEIRAS'; 
update cidade set cod_tom = '0809' where uf = 10 and upper(trim(unaccent(nome))) like 'JOAO LISBOA'; 
update cidade set cod_tom = '0811' where uf = 10 and upper(trim(unaccent(nome))) like 'JOSELANDIA'; 
update cidade set cod_tom = '0180' where uf = 10 and upper(trim(unaccent(nome))) like 'JUNCO DO MARANHAO'; 
update cidade set cod_tom = '0813' where uf = 10 and upper(trim(unaccent(nome))) like 'LAGO DA PEDRA'; 
update cidade set cod_tom = '0815' where uf = 10 and upper(trim(unaccent(nome))) like 'LAGO DO JUNCO'; 
update cidade set cod_tom = '0184' where uf = 10 and upper(trim(unaccent(nome))) like 'LAGO DOS RODRIGUES'; 
update cidade set cod_tom = '0817' where uf = 10 and upper(trim(unaccent(nome))) like 'LAGO VERDE'; 
update cidade set cod_tom = '0182' where uf = 10 and upper(trim(unaccent(nome))) like 'LAGOA DO MATO'; 
update cidade set cod_tom = '0186' where uf = 10 and upper(trim(unaccent(nome))) like 'LAGOA GRANDE DO MARANHAO'; 
update cidade set cod_tom = '0188' where uf = 10 and upper(trim(unaccent(nome))) like 'LAJEADO NOVO'; 
update cidade set cod_tom = '0819' where uf = 10 and upper(trim(unaccent(nome))) like 'LIMA CAMPOS'; 
update cidade set cod_tom = '0821' where uf = 10 and upper(trim(unaccent(nome))) like 'LORETO'; 
update cidade set cod_tom = '0823' where uf = 10 and upper(trim(unaccent(nome))) like 'LUIS DOMINGUES'; 
update cidade set cod_tom = '0825' where uf = 10 and upper(trim(unaccent(nome))) like 'MAGALHAES DE ALMEIDA'; 
update cidade set cod_tom = '0190' where uf = 10 and upper(trim(unaccent(nome))) like 'MARACACUME'; 
update cidade set cod_tom = '0192' where uf = 10 and upper(trim(unaccent(nome))) like 'MARAJA DO SENA'; 
update cidade set cod_tom = '0194' where uf = 10 and upper(trim(unaccent(nome))) like 'MARANHAOZINHO'; 
update cidade set cod_tom = '0827' where uf = 10 and upper(trim(unaccent(nome))) like 'MATA ROMA'; 
update cidade set cod_tom = '0829' where uf = 10 and upper(trim(unaccent(nome))) like 'MATINHA'; 
update cidade set cod_tom = '0831' where uf = 10 and upper(trim(unaccent(nome))) like 'MATOES'; 
update cidade set cod_tom = '0196' where uf = 10 and upper(trim(unaccent(nome))) like 'MATOES DO NORTE'; 
update cidade set cod_tom = '0198' where uf = 10 and upper(trim(unaccent(nome))) like 'MILAGRES DO MARANHAO'; 
update cidade set cod_tom = '0833' where uf = 10 and upper(trim(unaccent(nome))) like 'MIRADOR'; 
update cidade set cod_tom = '1283' where uf = 10 and upper(trim(unaccent(nome))) like 'MIRANDA DO NORTE'; 
update cidade set cod_tom = '0835' where uf = 10 and upper(trim(unaccent(nome))) like 'MIRINZAL'; 
update cidade set cod_tom = '0837' where uf = 10 and upper(trim(unaccent(nome))) like 'MONCAO'; 
update cidade set cod_tom = '0839' where uf = 10 and upper(trim(unaccent(nome))) like 'MONTES ALTOS'; 
update cidade set cod_tom = '0841' where uf = 10 and upper(trim(unaccent(nome))) like 'MORROS'; 
update cidade set cod_tom = '0843' where uf = 10 and upper(trim(unaccent(nome))) like 'NINA RODRIGUES'; 
update cidade set cod_tom = '0200' where uf = 10 and upper(trim(unaccent(nome))) like 'NOVA COLINAS'; 
update cidade set cod_tom = '0845' where uf = 10 and upper(trim(unaccent(nome))) like 'NOVA IORQUE'; 
update cidade set cod_tom = '0202' where uf = 10 and upper(trim(unaccent(nome))) like 'NOVA OLINDA DO MARANHAO'; 
update cidade set cod_tom = '0847' where uf = 10 and upper(trim(unaccent(nome))) like 'OLHO D`AGUA DAS CUNHAS'; 
update cidade set cod_tom = '0204' where uf = 10 and upper(trim(unaccent(nome))) like 'OLINDA NOVA DO MARANHAO'; 
update cidade set cod_tom = '0849' where uf = 10 and upper(trim(unaccent(nome))) like 'PACO DO LUMIAR'; 
update cidade set cod_tom = '0851' where uf = 10 and upper(trim(unaccent(nome))) like 'PALMEIRANDIA'; 
update cidade set cod_tom = '0853' where uf = 10 and upper(trim(unaccent(nome))) like 'PARAIBANO'; 
update cidade set cod_tom = '0855' where uf = 10 and upper(trim(unaccent(nome))) like 'PARNARAMA'; 
update cidade set cod_tom = '0857' where uf = 10 and upper(trim(unaccent(nome))) like 'PASSAGEM FRANCA'; 
update cidade set cod_tom = '0859' where uf = 10 and upper(trim(unaccent(nome))) like 'PASTOS BONS'; 
update cidade set cod_tom = '0206' where uf = 10 and upper(trim(unaccent(nome))) like 'PAULINO NEVES'; 
update cidade set cod_tom = '0959' where uf = 10 and upper(trim(unaccent(nome))) like 'PAULO RAMOS'; 
update cidade set cod_tom = '0861' where uf = 10 and upper(trim(unaccent(nome))) like 'PEDREIRAS'; 
update cidade set cod_tom = '0208' where uf = 10 and upper(trim(unaccent(nome))) like 'PEDRO DO ROSARIO'; 
update cidade set cod_tom = '0863' where uf = 10 and upper(trim(unaccent(nome))) like 'PENALVA'; 
update cidade set cod_tom = '0865' where uf = 10 and upper(trim(unaccent(nome))) like 'PERI MIRIM'; 
update cidade set cod_tom = '0210' where uf = 10 and upper(trim(unaccent(nome))) like 'PERITORO'; 
update cidade set cod_tom = '0867' where uf = 10 and upper(trim(unaccent(nome))) like 'PINDARE MIRIM'; 
update cidade set cod_tom = '0869' where uf = 10 and upper(trim(unaccent(nome))) like 'PINHEIRO'; 
update cidade set cod_tom = '0871' where uf = 10 and upper(trim(unaccent(nome))) like 'PIO XII'; 
update cidade set cod_tom = '0873' where uf = 10 and upper(trim(unaccent(nome))) like 'PIRAPEMAS'; 
update cidade set cod_tom = '0875' where uf = 10 and upper(trim(unaccent(nome))) like 'POCAO DE PEDRAS'; 
update cidade set cod_tom = '0877' where uf = 10 and upper(trim(unaccent(nome))) like 'PORTO FRANCO'; 
update cidade set cod_tom = '0212' where uf = 10 and upper(trim(unaccent(nome))) like 'PORTO RICO DO MARANHAO'; 
update cidade set cod_tom = '0879' where uf = 10 and upper(trim(unaccent(nome))) like 'PRESIDENTE DUTRA'; 
update cidade set cod_tom = '0881' where uf = 10 and upper(trim(unaccent(nome))) like 'PRESIDENTE JUSCELINO'; 
update cidade set cod_tom = '0214' where uf = 10 and upper(trim(unaccent(nome))) like 'PRESIDENTE MEDICI'; 
update cidade set cod_tom = '0216' where uf = 10 and upper(trim(unaccent(nome))) like 'PRESIDENTE SARNEY'; 
update cidade set cod_tom = '0883' where uf = 10 and upper(trim(unaccent(nome))) like 'PRESIDENTE VARGAS'; 
update cidade set cod_tom = '0885' where uf = 10 and upper(trim(unaccent(nome))) like 'PRIMEIRA CRUZ'; 
update cidade set cod_tom = '0218' where uf = 10 and upper(trim(unaccent(nome))) like 'RAPOSA'; 
update cidade set cod_tom = '0887' where uf = 10 and upper(trim(unaccent(nome))) like 'RIACHAO'; 
update cidade set cod_tom = '0220' where uf = 10 and upper(trim(unaccent(nome))) like 'RIBAMAR FIQUENE'; 
update cidade set cod_tom = '0891' where uf = 10 and upper(trim(unaccent(nome))) like 'ROSARIO'; 
update cidade set cod_tom = '0893' where uf = 10 and upper(trim(unaccent(nome))) like 'SAMBAIBA'; 
update cidade set cod_tom = '0222' where uf = 10 and upper(trim(unaccent(nome))) like 'SANTA FILOMENA DO MARANHAO'; 
update cidade set cod_tom = '0895' where uf = 10 and upper(trim(unaccent(nome))) like 'SANTA HELENA'; 
update cidade set cod_tom = '0957' where uf = 10 and upper(trim(unaccent(nome))) like 'SANTA INES'; 
update cidade set cod_tom = '0897' where uf = 10 and upper(trim(unaccent(nome))) like 'SANTA LUZIA'; 
update cidade set cod_tom = '1285' where uf = 10 and upper(trim(unaccent(nome))) like 'SANTA LUZIA DO PARUA'; 
update cidade set cod_tom = '0899' where uf = 10 and upper(trim(unaccent(nome))) like 'SANTA QUITERIA DO MARANHAO'; 
update cidade set cod_tom = '0901' where uf = 10 and upper(trim(unaccent(nome))) like 'SANTA RITA'; 
update cidade set cod_tom = '0224' where uf = 10 and upper(trim(unaccent(nome))) like 'SANTANA DO MARANHAO'; 
update cidade set cod_tom = '0226' where uf = 10 and upper(trim(unaccent(nome))) like 'SANTO AMARO DO MARANHAO'; 
update cidade set cod_tom = '0903' where uf = 10 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DOS LOPES'; 
update cidade set cod_tom = '0905' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO BENEDITO DO RIO PRETO'; 
update cidade set cod_tom = '0907' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO BENTO'; 
update cidade set cod_tom = '0909' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO BERNARDO'; 
update cidade set cod_tom = '0228' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO DOMINGOS DO AZEITAO'; 
update cidade set cod_tom = '0911' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO DOMINGOS DO MARANHAO'; 
update cidade set cod_tom = '0913' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO FELIX DE BALSAS'; 
update cidade set cod_tom = '0230' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO DO BREJAO'; 
update cidade set cod_tom = '0915' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO DO MARANHAO'; 
update cidade set cod_tom = '0917' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO JOAO BATISTA'; 
update cidade set cod_tom = '0232' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO JOAO DO CARU'; 
update cidade set cod_tom = '0234' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO JOAO DO PARAISO'; 
update cidade set cod_tom = '0236' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO JOAO DO SOTER'; 
update cidade set cod_tom = '0919' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO JOAO DOS PATOS'; 
update cidade set cod_tom = '0889' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO JOSE DE RIBAMAR'; 
update cidade set cod_tom = '0238' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO JOSE DOS BASILIOS'; 
update cidade set cod_tom = '0921' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO LUIS'; 
update cidade set cod_tom = '0805' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO LUIS GONZAGA DO MARANHAO'; 
update cidade set cod_tom = '0923' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO MATEUS DO MARANHAO'; 
update cidade set cod_tom = '0240' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO PEDRO DA AGUA BRANCA'; 
update cidade set cod_tom = '0242' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO PEDRO DOS CRENTES'; 
update cidade set cod_tom = '0925' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO RAIMUNDO DAS MANGABEIRAS'; 
update cidade set cod_tom = '0244' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO RAIMUNDO DO DOCA BEZERRA'; 
update cidade set cod_tom = '0246' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO ROBERTO'; 
update cidade set cod_tom = '0927' where uf = 10 and upper(trim(unaccent(nome))) like 'SAO VICENTE FERRER'; 
update cidade set cod_tom = '0248' where uf = 10 and upper(trim(unaccent(nome))) like 'SATUBINHA'; 
update cidade set cod_tom = '0250' where uf = 10 and upper(trim(unaccent(nome))) like 'SENADOR ALEXANDRE COSTA'; 
update cidade set cod_tom = '0252' where uf = 10 and upper(trim(unaccent(nome))) like 'SENADOR LA ROCQUE'; 
update cidade set cod_tom = '0254' where uf = 10 and upper(trim(unaccent(nome))) like 'SERRANO DO MARANHAO'; 
update cidade set cod_tom = '0929' where uf = 10 and upper(trim(unaccent(nome))) like 'SITIO NOVO'; 
update cidade set cod_tom = '0931' where uf = 10 and upper(trim(unaccent(nome))) like 'SUCUPIRA DO NORTE'; 
update cidade set cod_tom = '0256' where uf = 10 and upper(trim(unaccent(nome))) like 'SUCUPIRA DO RIACHAO'; 
update cidade set cod_tom = '0933' where uf = 10 and upper(trim(unaccent(nome))) like 'TASSO FRAGOSO'; 
update cidade set cod_tom = '0935' where uf = 10 and upper(trim(unaccent(nome))) like 'TIMBIRAS'; 
update cidade set cod_tom = '0937' where uf = 10 and upper(trim(unaccent(nome))) like 'TIMON'; 
update cidade set cod_tom = '0258' where uf = 10 and upper(trim(unaccent(nome))) like 'TRIZIDELA DO VALE'; 
update cidade set cod_tom = '0260' where uf = 10 and upper(trim(unaccent(nome))) like 'TUFILANDIA'; 
update cidade set cod_tom = '0939' where uf = 10 and upper(trim(unaccent(nome))) like 'TUNTUM'; 
update cidade set cod_tom = '0941' where uf = 10 and upper(trim(unaccent(nome))) like 'TURIACU'; 
update cidade set cod_tom = '0262' where uf = 10 and upper(trim(unaccent(nome))) like 'TURILANDIA'; 
update cidade set cod_tom = '0943' where uf = 10 and upper(trim(unaccent(nome))) like 'TUTOIA'; 
update cidade set cod_tom = '0945' where uf = 10 and upper(trim(unaccent(nome))) like 'URBANO SANTOS'; 
update cidade set cod_tom = '0947' where uf = 10 and upper(trim(unaccent(nome))) like 'VARGEM GRANDE'; 
update cidade set cod_tom = '0949' where uf = 10 and upper(trim(unaccent(nome))) like 'VIANA'; 
update cidade set cod_tom = '0264' where uf = 10 and upper(trim(unaccent(nome))) like 'VILA NOVA DOS MARTIRIOS'; 
update cidade set cod_tom = '0951' where uf = 10 and upper(trim(unaccent(nome))) like 'VITORIA DO MEARIM'; 
update cidade set cod_tom = '0953' where uf = 10 and upper(trim(unaccent(nome))) like 'VITORINO FREIRE'; 
update cidade set cod_tom = '1287' where uf = 10 and upper(trim(unaccent(nome))) like 'ZE DOCA'; 
