update cidade set cod_tom = '0033' where uf = 21 and upper(trim(unaccent(nome))) like 'ALTA FLORESTA D`OESTE'; 
update cidade set cod_tom = '0002' where uf = 21 and upper(trim(unaccent(nome))) like 'ALTO ALEGRE DOS PARECIS'; 
update cidade set cod_tom = '0675' where uf = 21 and upper(trim(unaccent(nome))) like 'ALTO PARAISO'; 
update cidade set cod_tom = '0035' where uf = 21 and upper(trim(unaccent(nome))) like 'ALVORADA D`OESTE'; 
update cidade set cod_tom = '0007' where uf = 21 and upper(trim(unaccent(nome))) like 'ARIQUEMES'; 
update cidade set cod_tom = '0' where uf = 21 and upper(trim(unaccent(nome))) like 'BAIXA GRANDE DO RIBEIRO'; 
update cidade set cod_tom = '0004' where uf = 21 and upper(trim(unaccent(nome))) like 'BURITIS'; 
update cidade set cod_tom = '0037' where uf = 21 and upper(trim(unaccent(nome))) like 'CABIXI'; 
update cidade set cod_tom = '0' where uf = 21 and upper(trim(unaccent(nome))) like 'CACAIEIROS'; 
update cidade set cod_tom = '0677' where uf = 21 and upper(trim(unaccent(nome))) like 'CACAULANDIA'; 
update cidade set cod_tom = '0009' where uf = 21 and upper(trim(unaccent(nome))) like 'CACOAL'; 
update cidade set cod_tom = '0679' where uf = 21 and upper(trim(unaccent(nome))) like 'CAMPO NOVO DE RONDONIA'; 
update cidade set cod_tom = '0681' where uf = 21 and upper(trim(unaccent(nome))) like 'CANDEIAS DO JAMARI'; 
update cidade set cod_tom = '0691' where uf = 21 and upper(trim(unaccent(nome))) like 'CASTANHEIRAS'; 
update cidade set cod_tom = '0027' where uf = 21 and upper(trim(unaccent(nome))) like 'CEREJEIRAS'; 
update cidade set cod_tom = '0006' where uf = 21 and upper(trim(unaccent(nome))) like 'CHUPINGUAIA'; 
update cidade set cod_tom = '0023' where uf = 21 and upper(trim(unaccent(nome))) like 'COLORADO DO OESTE'; 
update cidade set cod_tom = '0981' where uf = 21 and upper(trim(unaccent(nome))) like 'CORUMBIARA'; 
update cidade set cod_tom = '0021' where uf = 21 and upper(trim(unaccent(nome))) like 'COSTA MARQUES'; 
update cidade set cod_tom = '0008' where uf = 21 and upper(trim(unaccent(nome))) like 'CUJUBIM'; 
update cidade set cod_tom = '0025' where uf = 21 and upper(trim(unaccent(nome))) like 'ESPIGAO D`OESTE'; 
update cidade set cod_tom = '0693' where uf = 21 and upper(trim(unaccent(nome))) like 'GOVERNADOR JORGE TEIXEIRA'; 
update cidade set cod_tom = '0001' where uf = 21 and upper(trim(unaccent(nome))) like 'GUAJARA-MIRIM'; 
update cidade set cod_tom = '0683' where uf = 21 and upper(trim(unaccent(nome))) like 'ITAPUA DO OESTE'; 
update cidade set cod_tom = '0683' where uf = 21 and upper(trim(unaccent(nome))) like 'JAMARI'; 
update cidade set cod_tom = '0015' where uf = 21 and upper(trim(unaccent(nome))) like 'JARU'; 
update cidade set cod_tom = '0005' where uf = 21 and upper(trim(unaccent(nome))) like 'JI-PARANA'; 
update cidade set cod_tom = '0039' where uf = 21 and upper(trim(unaccent(nome))) like 'MACHADINHO D`OESTE'; 
update cidade set cod_tom = '0695' where uf = 21 and upper(trim(unaccent(nome))) like 'MINISTRO ANDREAZZA'; 
update cidade set cod_tom = '0697' where uf = 21 and upper(trim(unaccent(nome))) like 'MIRANTE DA SERRA'; 
update cidade set cod_tom = '0685' where uf = 21 and upper(trim(unaccent(nome))) like 'MONTE NEGRO'; 
update cidade set cod_tom = '0041' where uf = 21 and upper(trim(unaccent(nome))) like 'NOVA BRASILANDIA D`OESTE'; 
update cidade set cod_tom = '0047' where uf = 21 and upper(trim(unaccent(nome))) like 'NOVA MAMORE'; 
update cidade set cod_tom = '0010' where uf = 21 and upper(trim(unaccent(nome))) like 'NOVA UNIAO'; 
update cidade set cod_tom = '0689' where uf = 21 and upper(trim(unaccent(nome))) like 'NOVO HORIZONTE DO OESTE'; 
update cidade set cod_tom = '0017' where uf = 21 and upper(trim(unaccent(nome))) like 'OURO PRETO DO OESTE'; 
update cidade set cod_tom = '0012' where uf = 21 and upper(trim(unaccent(nome))) like 'PARECIS'; 
update cidade set cod_tom = '0011' where uf = 21 and upper(trim(unaccent(nome))) like 'PIMENTA BUENO'; 
update cidade set cod_tom = '0014' where uf = 21 and upper(trim(unaccent(nome))) like 'PIMENTEIRAS DO OESTE'; 
update cidade set cod_tom = '0003' where uf = 21 and upper(trim(unaccent(nome))) like 'PORTO VELHO'; 
update cidade set cod_tom = '0019' where uf = 21 and upper(trim(unaccent(nome))) like 'PRESIDENTE MEDICI'; 
update cidade set cod_tom = '0016' where uf = 21 and upper(trim(unaccent(nome))) like 'PRIMAVERA DE RONDONIA'; 
update cidade set cod_tom = '0687' where uf = 21 and upper(trim(unaccent(nome))) like 'RIO CRESPO'; 
update cidade set cod_tom = '0029' where uf = 21 and upper(trim(unaccent(nome))) like 'ROLIM DE MOURA'; 
update cidade set cod_tom = '0043' where uf = 21 and upper(trim(unaccent(nome))) like 'SANTA LUZIA D`OESTE'; 
update cidade set cod_tom = '0018' where uf = 21 and upper(trim(unaccent(nome))) like 'SAO FELIPE D`OESTE'; 
update cidade set cod_tom = '0020' where uf = 21 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO DO GUAPORE'; 
update cidade set cod_tom = '0045' where uf = 21 and upper(trim(unaccent(nome))) like 'SAO MIGUEL DO GUAPORE'; 
update cidade set cod_tom = '0699' where uf = 21 and upper(trim(unaccent(nome))) like 'SERINGUEIRAS'; 
update cidade set cod_tom = '0022' where uf = 21 and upper(trim(unaccent(nome))) like 'TEIXEIROPOLIS'; 
update cidade set cod_tom = '0975' where uf = 21 and upper(trim(unaccent(nome))) like 'THEOBROMA'; 
update cidade set cod_tom = '0977' where uf = 21 and upper(trim(unaccent(nome))) like 'URUPA'; 
update cidade set cod_tom = '0024' where uf = 21 and upper(trim(unaccent(nome))) like 'VALE DO ANARI'; 
update cidade set cod_tom = '0979' where uf = 21 and upper(trim(unaccent(nome))) like 'VALE DO PARAISO'; 
update cidade set cod_tom = '0013' where uf = 21 and upper(trim(unaccent(nome))) like 'VILHENA'; 
