update cidade set cod_tom = '7401' where uf = 18 and upper(trim(unaccent(nome))) like 'ABATIA'; 
update cidade set cod_tom = '7403' where uf = 18 and upper(trim(unaccent(nome))) like 'ADRIANOPOLIS'; 
update cidade set cod_tom = '7405' where uf = 18 and upper(trim(unaccent(nome))) like 'AGUDOS DO SUL'; 
update cidade set cod_tom = '7407' where uf = 18 and upper(trim(unaccent(nome))) like 'ALMIRANTE TAMANDARE'; 
update cidade set cod_tom = '8455' where uf = 18 and upper(trim(unaccent(nome))) like 'ALTAMIRA DO PARANA'; 
update cidade set cod_tom = '5523' where uf = 18 and upper(trim(unaccent(nome))) like 'ALTO PARAISO'; 
update cidade set cod_tom = '7409' where uf = 18 and upper(trim(unaccent(nome))) like 'ALTO PARANA'; 
update cidade set cod_tom = '7411' where uf = 18 and upper(trim(unaccent(nome))) like 'ALTO PIQUIRI'; 
update cidade set cod_tom = '7951' where uf = 18 and upper(trim(unaccent(nome))) like 'ALTONIA'; 
update cidade set cod_tom = '7413' where uf = 18 and upper(trim(unaccent(nome))) like 'ALVORADA DO SUL'; 
update cidade set cod_tom = '7415' where uf = 18 and upper(trim(unaccent(nome))) like 'AMAPORA'; 
update cidade set cod_tom = '7417' where uf = 18 and upper(trim(unaccent(nome))) like 'AMPERE'; 
update cidade set cod_tom = '5463' where uf = 18 and upper(trim(unaccent(nome))) like 'ANAHY'; 
update cidade set cod_tom = '7419' where uf = 18 and upper(trim(unaccent(nome))) like 'ANDIRA'; 
update cidade set cod_tom = '5509' where uf = 18 and upper(trim(unaccent(nome))) like 'ANGULO'; 
update cidade set cod_tom = '7421' where uf = 18 and upper(trim(unaccent(nome))) like 'ANTONINA'; 
update cidade set cod_tom = '7423' where uf = 18 and upper(trim(unaccent(nome))) like 'ANTONIO OLINTO'; 
update cidade set cod_tom = '7425' where uf = 18 and upper(trim(unaccent(nome))) like 'APUCARANA'; 
update cidade set cod_tom = '7427' where uf = 18 and upper(trim(unaccent(nome))) like 'ARAPONGAS'; 
update cidade set cod_tom = '7429' where uf = 18 and upper(trim(unaccent(nome))) like 'ARAPOTI'; 
update cidade set cod_tom = '0830' where uf = 18 and upper(trim(unaccent(nome))) like 'ARAPUA'; 
update cidade set cod_tom = '7431' where uf = 18 and upper(trim(unaccent(nome))) like 'ARARUNA'; 
update cidade set cod_tom = '7435' where uf = 18 and upper(trim(unaccent(nome))) like 'ARAUCARIA'; 
update cidade set cod_tom = '0832' where uf = 18 and upper(trim(unaccent(nome))) like 'ARIRANHA DO IVAI'; 
update cidade set cod_tom = '7437' where uf = 18 and upper(trim(unaccent(nome))) like 'ASSAI'; 
update cidade set cod_tom = '7953' where uf = 18 and upper(trim(unaccent(nome))) like 'ASSIS CHATEAUBRIAND'; 
update cidade set cod_tom = '7439' where uf = 18 and upper(trim(unaccent(nome))) like 'ASTORGA'; 
update cidade set cod_tom = '7441' where uf = 18 and upper(trim(unaccent(nome))) like 'ATALAIA'; 
update cidade set cod_tom = '7443' where uf = 18 and upper(trim(unaccent(nome))) like 'BALSA NOVA'; 
update cidade set cod_tom = '7445' where uf = 18 and upper(trim(unaccent(nome))) like 'BANDEIRANTES'; 
update cidade set cod_tom = '7447' where uf = 18 and upper(trim(unaccent(nome))) like 'BARBOSA FERRAZ'; 
update cidade set cod_tom = '7451' where uf = 18 and upper(trim(unaccent(nome))) like 'BARRA DO JACARE'; 
update cidade set cod_tom = '7449' where uf = 18 and upper(trim(unaccent(nome))) like 'BARRACAO'; 
update cidade set cod_tom = '0834' where uf = 18 and upper(trim(unaccent(nome))) like 'BELA VISTA DO CAROBA'; 
update cidade set cod_tom = '7453' where uf = 18 and upper(trim(unaccent(nome))) like 'BELA VISTA DO PARAISO'; 
update cidade set cod_tom = '7455' where uf = 18 and upper(trim(unaccent(nome))) like 'BITURUNA'; 
update cidade set cod_tom = '7457' where uf = 18 and upper(trim(unaccent(nome))) like 'BOA ESPERANCA'; 
update cidade set cod_tom = '5471' where uf = 18 and upper(trim(unaccent(nome))) like 'BOA ESPERANCA DO IGUACU'; 
update cidade set cod_tom = '0836' where uf = 18 and upper(trim(unaccent(nome))) like 'BOA VENTURA DE SAO ROQUE'; 
update cidade set cod_tom = '7981' where uf = 18 and upper(trim(unaccent(nome))) like 'BOA VISTA DA APARECIDA'; 
update cidade set cod_tom = '7459' where uf = 18 and upper(trim(unaccent(nome))) like 'BOCAIUVA DO SUL'; 
update cidade set cod_tom = '0838' where uf = 18 and upper(trim(unaccent(nome))) like 'BOM JESUS DO SUL'; 
update cidade set cod_tom = '7461' where uf = 18 and upper(trim(unaccent(nome))) like 'BOM SUCESSO'; 
update cidade set cod_tom = '9979' where uf = 18 and upper(trim(unaccent(nome))) like 'BOM SUCESSO DO SUL'; 
update cidade set cod_tom = '7463' where uf = 18 and upper(trim(unaccent(nome))) like 'BORRAZOPOLIS'; 
update cidade set cod_tom = '7983' where uf = 18 and upper(trim(unaccent(nome))) like 'BRAGANEY'; 
update cidade set cod_tom = '5521' where uf = 18 and upper(trim(unaccent(nome))) like 'BRASILANDIA DO SUL'; 
update cidade set cod_tom = '7465' where uf = 18 and upper(trim(unaccent(nome))) like 'CAFEARA'; 
update cidade set cod_tom = '7985' where uf = 18 and upper(trim(unaccent(nome))) like 'CAFELANDIA'; 
update cidade set cod_tom = '5491' where uf = 18 and upper(trim(unaccent(nome))) like 'CAFEZAL DO SUL'; 
update cidade set cod_tom = '7467' where uf = 18 and upper(trim(unaccent(nome))) like 'CALIFORNIA'; 
update cidade set cod_tom = '7469' where uf = 18 and upper(trim(unaccent(nome))) like 'CAMBARA'; 
update cidade set cod_tom = '7471' where uf = 18 and upper(trim(unaccent(nome))) like 'CAMBE'; 
update cidade set cod_tom = '7473' where uf = 18 and upper(trim(unaccent(nome))) like 'CAMBIRA'; 
update cidade set cod_tom = '7475' where uf = 18 and upper(trim(unaccent(nome))) like 'CAMPINA DA LAGOA'; 
update cidade set cod_tom = '0840' where uf = 18 and upper(trim(unaccent(nome))) like 'CAMPINA DO SIMAO'; 
update cidade set cod_tom = '7477' where uf = 18 and upper(trim(unaccent(nome))) like 'CAMPINA GRANDE DO SUL'; 
update cidade set cod_tom = '8475' where uf = 18 and upper(trim(unaccent(nome))) like 'CAMPO BONITO'; 
update cidade set cod_tom = '7479' where uf = 18 and upper(trim(unaccent(nome))) like 'CAMPO DO TENENTE'; 
update cidade set cod_tom = '7481' where uf = 18 and upper(trim(unaccent(nome))) like 'CAMPO LARGO'; 
update cidade set cod_tom = '0842' where uf = 18 and upper(trim(unaccent(nome))) like 'CAMPO MAGRO'; 
update cidade set cod_tom = '7483' where uf = 18 and upper(trim(unaccent(nome))) like 'CAMPO MOURAO'; 
update cidade set cod_tom = '7485' where uf = 18 and upper(trim(unaccent(nome))) like 'CANDIDO DE ABREU'; 
update cidade set cod_tom = '5499' where uf = 18 and upper(trim(unaccent(nome))) like 'CANDOI'; 
update cidade set cod_tom = '8451' where uf = 18 and upper(trim(unaccent(nome))) like 'CANTAGALO'; 
update cidade set cod_tom = '7487' where uf = 18 and upper(trim(unaccent(nome))) like 'CAPANEMA'; 
update cidade set cod_tom = '7489' where uf = 18 and upper(trim(unaccent(nome))) like 'CAPITAO LEONIDAS MARQUES'; 
update cidade set cod_tom = '0844' where uf = 18 and upper(trim(unaccent(nome))) like 'CARAMBEI'; 
update cidade set cod_tom = '7491' where uf = 18 and upper(trim(unaccent(nome))) like 'CARLOPOLIS'; 
update cidade set cod_tom = '7493' where uf = 18 and upper(trim(unaccent(nome))) like 'CASCAVEL'; 
update cidade set cod_tom = '7495' where uf = 18 and upper(trim(unaccent(nome))) like 'CASTRO'; 
update cidade set cod_tom = '7497' where uf = 18 and upper(trim(unaccent(nome))) like 'CATANDUVAS'; 
update cidade set cod_tom = '7499' where uf = 18 and upper(trim(unaccent(nome))) like 'CENTENARIO DO SUL'; 
update cidade set cod_tom = '7501' where uf = 18 and upper(trim(unaccent(nome))) like 'CERRO AZUL'; 
update cidade set cod_tom = '7957' where uf = 18 and upper(trim(unaccent(nome))) like 'CEU AZUL'; 
update cidade set cod_tom = '7503' where uf = 18 and upper(trim(unaccent(nome))) like 'CHOPINZINHO'; 
update cidade set cod_tom = '7505' where uf = 18 and upper(trim(unaccent(nome))) like 'CIANORTE'; 
update cidade set cod_tom = '7507' where uf = 18 and upper(trim(unaccent(nome))) like 'CIDADE GAUCHA'; 
update cidade set cod_tom = '7509' where uf = 18 and upper(trim(unaccent(nome))) like 'CLEVELANDIA'; 
update cidade set cod_tom = '7513' where uf = 18 and upper(trim(unaccent(nome))) like 'COLOMBO'; 
update cidade set cod_tom = '7515' where uf = 18 and upper(trim(unaccent(nome))) like 'COLORADO'; 
update cidade set cod_tom = '7517' where uf = 18 and upper(trim(unaccent(nome))) like 'CONGONHINHAS'; 
update cidade set cod_tom = '7519' where uf = 18 and upper(trim(unaccent(nome))) like 'CONSELHEIRO MAIRINCK'; 
update cidade set cod_tom = '7521' where uf = 18 and upper(trim(unaccent(nome))) like 'CONTENDA'; 
update cidade set cod_tom = '7523' where uf = 18 and upper(trim(unaccent(nome))) like 'CORBELIA'; 
update cidade set cod_tom = '7525' where uf = 18 and upper(trim(unaccent(nome))) like 'CORNELIO PROCOPIO'; 
update cidade set cod_tom = '0846' where uf = 18 and upper(trim(unaccent(nome))) like 'CORONEL DOMINGOS SOARES'; 
update cidade set cod_tom = '7527' where uf = 18 and upper(trim(unaccent(nome))) like 'CORONEL VIVIDA'; 
update cidade set cod_tom = '8479' where uf = 18 and upper(trim(unaccent(nome))) like 'CORUMBATAI DO SUL'; 
update cidade set cod_tom = '7533' where uf = 18 and upper(trim(unaccent(nome))) like 'CRUZ MACHADO'; 
update cidade set cod_tom = '5473' where uf = 18 and upper(trim(unaccent(nome))) like 'CRUZEIRO DO IGUACU'; 
update cidade set cod_tom = '7529' where uf = 18 and upper(trim(unaccent(nome))) like 'CRUZEIRO DO OESTE'; 
update cidade set cod_tom = '7531' where uf = 18 and upper(trim(unaccent(nome))) like 'CRUZEIRO DO SUL'; 
update cidade set cod_tom = '0848' where uf = 18 and upper(trim(unaccent(nome))) like 'CRUZMALTINA'; 
update cidade set cod_tom = '7535' where uf = 18 and upper(trim(unaccent(nome))) like 'CURITIBA'; 
update cidade set cod_tom = '7537' where uf = 18 and upper(trim(unaccent(nome))) like 'CURIUVA'; 
update cidade set cod_tom = '7539' where uf = 18 and upper(trim(unaccent(nome))) like 'DIAMANTE DO NORTE'; 
update cidade set cod_tom = '5465' where uf = 18 and upper(trim(unaccent(nome))) like 'DIAMANTE DO SUL'; 
update cidade set cod_tom = '9915' where uf = 18 and upper(trim(unaccent(nome))) like 'DIAMANTE D`OESTE'; 
update cidade set cod_tom = '7541' where uf = 18 and upper(trim(unaccent(nome))) like 'DOIS VIZINHOS'; 
update cidade set cod_tom = '8465' where uf = 18 and upper(trim(unaccent(nome))) like 'DOURADINA'; 
update cidade set cod_tom = '7543' where uf = 18 and upper(trim(unaccent(nome))) like 'DOUTOR CAMARGO'; 
update cidade set cod_tom = '5449' where uf = 18 and upper(trim(unaccent(nome))) like 'DOUTOR ULYSSES'; 
update cidade set cod_tom = '7545' where uf = 18 and upper(trim(unaccent(nome))) like 'ENEAS MARQUES'; 
update cidade set cod_tom = '7547' where uf = 18 and upper(trim(unaccent(nome))) like 'ENGENHEIRO BELTRAO'; 
update cidade set cod_tom = '5529' where uf = 18 and upper(trim(unaccent(nome))) like 'ENTRE RIOS DO OESTE'; 
update cidade set cod_tom = '0850' where uf = 18 and upper(trim(unaccent(nome))) like 'ESPERANCA NOVA'; 
update cidade set cod_tom = '0852' where uf = 18 and upper(trim(unaccent(nome))) like 'ESPIGAO ALTO DO IGUACU'; 
update cidade set cod_tom = '5511' where uf = 18 and upper(trim(unaccent(nome))) like 'FAROL'; 
update cidade set cod_tom = '7549' where uf = 18 and upper(trim(unaccent(nome))) like 'FAXINAL'; 
update cidade set cod_tom = '9983' where uf = 18 and upper(trim(unaccent(nome))) like 'FAZENDA RIO GRANDE'; 
update cidade set cod_tom = '7551' where uf = 18 and upper(trim(unaccent(nome))) like 'FENIX'; 
update cidade set cod_tom = '0854' where uf = 18 and upper(trim(unaccent(nome))) like 'FERNANDES PINHEIRO'; 
update cidade set cod_tom = '8457' where uf = 18 and upper(trim(unaccent(nome))) like 'FIGUEIRA'; 
update cidade set cod_tom = '5475' where uf = 18 and upper(trim(unaccent(nome))) like 'FLOR DA SERRA DO SUL'; 
update cidade set cod_tom = '7553' where uf = 18 and upper(trim(unaccent(nome))) like 'FLORAI'; 
update cidade set cod_tom = '7555' where uf = 18 and upper(trim(unaccent(nome))) like 'FLORESTA'; 
update cidade set cod_tom = '7557' where uf = 18 and upper(trim(unaccent(nome))) like 'FLORESTOPOLIS'; 
update cidade set cod_tom = '7559' where uf = 18 and upper(trim(unaccent(nome))) like 'FLORIDA'; 
update cidade set cod_tom = '7561' where uf = 18 and upper(trim(unaccent(nome))) like 'FORMOSA DO OESTE'; 
update cidade set cod_tom = '7563' where uf = 18 and upper(trim(unaccent(nome))) like 'FOZ DO IGUACU'; 
update cidade set cod_tom = '0856' where uf = 18 and upper(trim(unaccent(nome))) like 'FOZ DO JORDAO'; 
update cidade set cod_tom = '7977' where uf = 18 and upper(trim(unaccent(nome))) like 'FRANCISCO ALVES'; 
update cidade set cod_tom = '7565' where uf = 18 and upper(trim(unaccent(nome))) like 'FRANCISCO BELTRAO'; 
update cidade set cod_tom = '7567' where uf = 18 and upper(trim(unaccent(nome))) like 'GENERAL CARNEIRO'; 
update cidade set cod_tom = '9947' where uf = 18 and upper(trim(unaccent(nome))) like 'GODOY MOREIRA'; 
update cidade set cod_tom = '7569' where uf = 18 and upper(trim(unaccent(nome))) like 'GOIOERE'; 
update cidade set cod_tom = '0858' where uf = 18 and upper(trim(unaccent(nome))) like 'GOIOXIM'; 
update cidade set cod_tom = '7959' where uf = 18 and upper(trim(unaccent(nome))) like 'GRANDES RIOS'; 
update cidade set cod_tom = '7571' where uf = 18 and upper(trim(unaccent(nome))) like 'GUAIRA'; 
update cidade set cod_tom = '7573' where uf = 18 and upper(trim(unaccent(nome))) like 'GUAIRACA'; 
update cidade set cod_tom = '0860' where uf = 18 and upper(trim(unaccent(nome))) like 'GUAMIRANGA'; 
update cidade set cod_tom = '7575' where uf = 18 and upper(trim(unaccent(nome))) like 'GUAPIRAMA'; 
update cidade set cod_tom = '7577' where uf = 18 and upper(trim(unaccent(nome))) like 'GUAPOREMA'; 
update cidade set cod_tom = '7579' where uf = 18 and upper(trim(unaccent(nome))) like 'GUARACI'; 
update cidade set cod_tom = '7581' where uf = 18 and upper(trim(unaccent(nome))) like 'GUARANIACU'; 
update cidade set cod_tom = '7583' where uf = 18 and upper(trim(unaccent(nome))) like 'GUARAPUAVA'; 
update cidade set cod_tom = '7585' where uf = 18 and upper(trim(unaccent(nome))) like 'GUARAQUECABA'; 
update cidade set cod_tom = '7587' where uf = 18 and upper(trim(unaccent(nome))) like 'GUARATUBA'; 
update cidade set cod_tom = '9981' where uf = 18 and upper(trim(unaccent(nome))) like 'HONORIO SERPA'; 
update cidade set cod_tom = '7589' where uf = 18 and upper(trim(unaccent(nome))) like 'IBAITI'; 
update cidade set cod_tom = '9949' where uf = 18 and upper(trim(unaccent(nome))) like 'IBEMA'; 
update cidade set cod_tom = '7591' where uf = 18 and upper(trim(unaccent(nome))) like 'IBIPORA'; 
update cidade set cod_tom = '7593' where uf = 18 and upper(trim(unaccent(nome))) like 'ICARAIMA'; 
update cidade set cod_tom = '7595' where uf = 18 and upper(trim(unaccent(nome))) like 'IGUARACU'; 
update cidade set cod_tom = '5467' where uf = 18 and upper(trim(unaccent(nome))) like 'IGUATU'; 
update cidade set cod_tom = '0862' where uf = 18 and upper(trim(unaccent(nome))) like 'IMBAU'; 
update cidade set cod_tom = '7597' where uf = 18 and upper(trim(unaccent(nome))) like 'IMBITUVA'; 
update cidade set cod_tom = '7599' where uf = 18 and upper(trim(unaccent(nome))) like 'INACIO MARTINS'; 
update cidade set cod_tom = '7601' where uf = 18 and upper(trim(unaccent(nome))) like 'INAJA'; 
update cidade set cod_tom = '7961' where uf = 18 and upper(trim(unaccent(nome))) like 'INDIANOPOLIS'; 
update cidade set cod_tom = '7603' where uf = 18 and upper(trim(unaccent(nome))) like 'IPIRANGA'; 
update cidade set cod_tom = '7605' where uf = 18 and upper(trim(unaccent(nome))) like 'IPORA'; 
update cidade set cod_tom = '5485' where uf = 18 and upper(trim(unaccent(nome))) like 'IRACEMA DO OESTE'; 
update cidade set cod_tom = '7607' where uf = 18 and upper(trim(unaccent(nome))) like 'IRATI'; 
update cidade set cod_tom = '7609' where uf = 18 and upper(trim(unaccent(nome))) like 'IRETAMA'; 
update cidade set cod_tom = '7611' where uf = 18 and upper(trim(unaccent(nome))) like 'ITAGUAJE'; 
update cidade set cod_tom = '5525' where uf = 18 and upper(trim(unaccent(nome))) like 'ITAIPULANDIA'; 
update cidade set cod_tom = '7613' where uf = 18 and upper(trim(unaccent(nome))) like 'ITAMBARACA'; 
update cidade set cod_tom = '7615' where uf = 18 and upper(trim(unaccent(nome))) like 'ITAMBE'; 
update cidade set cod_tom = '7617' where uf = 18 and upper(trim(unaccent(nome))) like 'ITAPEJARA D`OESTE'; 
update cidade set cod_tom = '5451' where uf = 18 and upper(trim(unaccent(nome))) like 'ITAPERUCU'; 
update cidade set cod_tom = '7619' where uf = 18 and upper(trim(unaccent(nome))) like 'ITAUNA DO SUL'; 
update cidade set cod_tom = '7621' where uf = 18 and upper(trim(unaccent(nome))) like 'IVAI'; 
update cidade set cod_tom = '7623' where uf = 18 and upper(trim(unaccent(nome))) like 'IVAIPORA'; 
update cidade set cod_tom = '9955' where uf = 18 and upper(trim(unaccent(nome))) like 'IVATE'; 
update cidade set cod_tom = '7625' where uf = 18 and upper(trim(unaccent(nome))) like 'IVATUBA'; 
update cidade set cod_tom = '7627' where uf = 18 and upper(trim(unaccent(nome))) like 'JABOTI'; 
update cidade set cod_tom = '7629' where uf = 18 and upper(trim(unaccent(nome))) like 'JACAREZINHO'; 
update cidade set cod_tom = '7631' where uf = 18 and upper(trim(unaccent(nome))) like 'JAGUAPITA'; 
update cidade set cod_tom = '7633' where uf = 18 and upper(trim(unaccent(nome))) like 'JAGUARIAIVA'; 
update cidade set cod_tom = '7635' where uf = 18 and upper(trim(unaccent(nome))) like 'JANDAIA DO SUL'; 
update cidade set cod_tom = '7637' where uf = 18 and upper(trim(unaccent(nome))) like 'JANIOPOLIS'; 
update cidade set cod_tom = '7639' where uf = 18 and upper(trim(unaccent(nome))) like 'JAPIRA'; 
update cidade set cod_tom = '7641' where uf = 18 and upper(trim(unaccent(nome))) like 'JAPURA'; 
update cidade set cod_tom = '7643' where uf = 18 and upper(trim(unaccent(nome))) like 'JARDIM ALEGRE'; 
update cidade set cod_tom = '7645' where uf = 18 and upper(trim(unaccent(nome))) like 'JARDIM OLINDA'; 
update cidade set cod_tom = '7647' where uf = 18 and upper(trim(unaccent(nome))) like 'JATAIZINHO'; 
update cidade set cod_tom = '7997' where uf = 18 and upper(trim(unaccent(nome))) like 'JESUITAS'; 
update cidade set cod_tom = '7649' where uf = 18 and upper(trim(unaccent(nome))) like 'JOAQUIM TAVORA'; 
update cidade set cod_tom = '7651' where uf = 18 and upper(trim(unaccent(nome))) like 'JUNDIAI DO SUL'; 
update cidade set cod_tom = '8463' where uf = 18 and upper(trim(unaccent(nome))) like 'JURANDA'; 
update cidade set cod_tom = '7653' where uf = 18 and upper(trim(unaccent(nome))) like 'JUSSARA'; 
update cidade set cod_tom = '7655' where uf = 18 and upper(trim(unaccent(nome))) like 'KALORE'; 
update cidade set cod_tom = '7657' where uf = 18 and upper(trim(unaccent(nome))) like 'LAPA'; 
update cidade set cod_tom = '5501' where uf = 18 and upper(trim(unaccent(nome))) like 'LARANJAL'; 
update cidade set cod_tom = '7659' where uf = 18 and upper(trim(unaccent(nome))) like 'LARANJEIRAS DO SUL'; 
update cidade set cod_tom = '7661' where uf = 18 and upper(trim(unaccent(nome))) like 'LEOPOLIS'; 
update cidade set cod_tom = '5507' where uf = 18 and upper(trim(unaccent(nome))) like 'LIDIANOPOLIS'; 
update cidade set cod_tom = '9959' where uf = 18 and upper(trim(unaccent(nome))) like 'LINDOESTE'; 
update cidade set cod_tom = '7663' where uf = 18 and upper(trim(unaccent(nome))) like 'LOANDA'; 
update cidade set cod_tom = '7665' where uf = 18 and upper(trim(unaccent(nome))) like 'LOBATO'; 
update cidade set cod_tom = '7667' where uf = 18 and upper(trim(unaccent(nome))) like 'LONDRINA'; 
update cidade set cod_tom = '8481' where uf = 18 and upper(trim(unaccent(nome))) like 'LUIZIANA'; 
update cidade set cod_tom = '8459' where uf = 18 and upper(trim(unaccent(nome))) like 'LUNARDELLI'; 
update cidade set cod_tom = '7669' where uf = 18 and upper(trim(unaccent(nome))) like 'LUPIONOPOLIS'; 
update cidade set cod_tom = '7671' where uf = 18 and upper(trim(unaccent(nome))) like 'MALLET'; 
update cidade set cod_tom = '7673' where uf = 18 and upper(trim(unaccent(nome))) like 'MAMBORE'; 
update cidade set cod_tom = '7675' where uf = 18 and upper(trim(unaccent(nome))) like 'MANDAGUACU'; 
update cidade set cod_tom = '7677' where uf = 18 and upper(trim(unaccent(nome))) like 'MANDAGUARI'; 
update cidade set cod_tom = '7679' where uf = 18 and upper(trim(unaccent(nome))) like 'MANDIRITUBA'; 
update cidade set cod_tom = '0864' where uf = 18 and upper(trim(unaccent(nome))) like 'MANFRINOPOLIS'; 
update cidade set cod_tom = '7511' where uf = 18 and upper(trim(unaccent(nome))) like 'MANGUEIRINHA'; 
update cidade set cod_tom = '7681' where uf = 18 and upper(trim(unaccent(nome))) like 'MANOEL RIBAS'; 
update cidade set cod_tom = '7683' where uf = 18 and upper(trim(unaccent(nome))) like 'MARECHAL CANDIDO RONDON'; 
update cidade set cod_tom = '7685' where uf = 18 and upper(trim(unaccent(nome))) like 'MARIA HELENA'; 
update cidade set cod_tom = '7687' where uf = 18 and upper(trim(unaccent(nome))) like 'MARIALVA'; 
update cidade set cod_tom = '7433' where uf = 18 and upper(trim(unaccent(nome))) like 'MARILANDIA DO SUL'; 
update cidade set cod_tom = '7975' where uf = 18 and upper(trim(unaccent(nome))) like 'MARILENA'; 
update cidade set cod_tom = '7689' where uf = 18 and upper(trim(unaccent(nome))) like 'MARILUZ'; 
update cidade set cod_tom = '7691' where uf = 18 and upper(trim(unaccent(nome))) like 'MARINGA'; 
update cidade set cod_tom = '7693' where uf = 18 and upper(trim(unaccent(nome))) like 'MARIOPOLIS'; 
update cidade set cod_tom = '5487' where uf = 18 and upper(trim(unaccent(nome))) like 'MARIPA'; 
update cidade set cod_tom = '7695' where uf = 18 and upper(trim(unaccent(nome))) like 'MARMELEIRO'; 
update cidade set cod_tom = '0866' where uf = 18 and upper(trim(unaccent(nome))) like 'MARQUINHO'; 
update cidade set cod_tom = '7697' where uf = 18 and upper(trim(unaccent(nome))) like 'MARUMBI'; 
update cidade set cod_tom = '7699' where uf = 18 and upper(trim(unaccent(nome))) like 'MATELANDIA'; 
update cidade set cod_tom = '7963' where uf = 18 and upper(trim(unaccent(nome))) like 'MATINHOS'; 
update cidade set cod_tom = '5503' where uf = 18 and upper(trim(unaccent(nome))) like 'MATO RICO'; 
update cidade set cod_tom = '5459' where uf = 18 and upper(trim(unaccent(nome))) like 'MAUA DA SERRA'; 
update cidade set cod_tom = '7701' where uf = 18 and upper(trim(unaccent(nome))) like 'MEDIANEIRA'; 
update cidade set cod_tom = '5531' where uf = 18 and upper(trim(unaccent(nome))) like 'MERCEDES'; 
update cidade set cod_tom = '7703' where uf = 18 and upper(trim(unaccent(nome))) like 'MIRADOR'; 
update cidade set cod_tom = '7705' where uf = 18 and upper(trim(unaccent(nome))) like 'MIRASELVA'; 
update cidade set cod_tom = '8469' where uf = 18 and upper(trim(unaccent(nome))) like 'MISSAL'; 
update cidade set cod_tom = '7707' where uf = 18 and upper(trim(unaccent(nome))) like 'MOREIRA SALES'; 
update cidade set cod_tom = '7709' where uf = 18 and upper(trim(unaccent(nome))) like 'MORRETES'; 
update cidade set cod_tom = '7711' where uf = 18 and upper(trim(unaccent(nome))) like 'MUNHOZ DE MELO'; 
update cidade set cod_tom = '7713' where uf = 18 and upper(trim(unaccent(nome))) like 'NOSSA SENHORA DAS GRACAS'; 
update cidade set cod_tom = '7715' where uf = 18 and upper(trim(unaccent(nome))) like 'NOVA ALIANCA DO IVAI'; 
update cidade set cod_tom = '7717' where uf = 18 and upper(trim(unaccent(nome))) like 'NOVA AMERICA DA COLINA'; 
update cidade set cod_tom = '7965' where uf = 18 and upper(trim(unaccent(nome))) like 'NOVA AURORA'; 
update cidade set cod_tom = '7719' where uf = 18 and upper(trim(unaccent(nome))) like 'NOVA CANTU'; 
update cidade set cod_tom = '7721' where uf = 18 and upper(trim(unaccent(nome))) like 'NOVA ESPERANCA'; 
update cidade set cod_tom = '5477' where uf = 18 and upper(trim(unaccent(nome))) like 'NOVA ESPERANCA DO SUDOESTE'; 
update cidade set cod_tom = '7723' where uf = 18 and upper(trim(unaccent(nome))) like 'NOVA FATIMA'; 
update cidade set cod_tom = '5479' where uf = 18 and upper(trim(unaccent(nome))) like 'NOVA LARANJEIRAS'; 
update cidade set cod_tom = '7725' where uf = 18 and upper(trim(unaccent(nome))) like 'NOVA LONDRINA'; 
update cidade set cod_tom = '7967' where uf = 18 and upper(trim(unaccent(nome))) like 'NOVA OLIMPIA'; 
update cidade set cod_tom = '7995' where uf = 18 and upper(trim(unaccent(nome))) like 'NOVA PRATA DO IGUACU'; 
update cidade set cod_tom = '5457' where uf = 18 and upper(trim(unaccent(nome))) like 'NOVA SANTA BARBARA'; 
update cidade set cod_tom = '7979' where uf = 18 and upper(trim(unaccent(nome))) like 'NOVA SANTA ROSA'; 
update cidade set cod_tom = '9913' where uf = 18 and upper(trim(unaccent(nome))) like 'NOVA TEBAS'; 
update cidade set cod_tom = '5517' where uf = 18 and upper(trim(unaccent(nome))) like 'NOVO ITACOLOMI'; 
update cidade set cod_tom = '7727' where uf = 18 and upper(trim(unaccent(nome))) like 'ORTIGUEIRA'; 
update cidade set cod_tom = '7729' where uf = 18 and upper(trim(unaccent(nome))) like 'OURIZONA'; 
update cidade set cod_tom = '9965' where uf = 18 and upper(trim(unaccent(nome))) like 'OURO VERDE DO OESTE'; 
update cidade set cod_tom = '7731' where uf = 18 and upper(trim(unaccent(nome))) like 'PAICANDU'; 
update cidade set cod_tom = '7733' where uf = 18 and upper(trim(unaccent(nome))) like 'PALMAS'; 
update cidade set cod_tom = '7735' where uf = 18 and upper(trim(unaccent(nome))) like 'PALMEIRA'; 
update cidade set cod_tom = '7737' where uf = 18 and upper(trim(unaccent(nome))) like 'PALMITAL'; 
update cidade set cod_tom = '7739' where uf = 18 and upper(trim(unaccent(nome))) like 'PALOTINA'; 
update cidade set cod_tom = '7741' where uf = 18 and upper(trim(unaccent(nome))) like 'PARAISO DO NORTE'; 
update cidade set cod_tom = '7743' where uf = 18 and upper(trim(unaccent(nome))) like 'PARANACITY'; 
update cidade set cod_tom = '7745' where uf = 18 and upper(trim(unaccent(nome))) like 'PARANAGUA'; 
update cidade set cod_tom = '7747' where uf = 18 and upper(trim(unaccent(nome))) like 'PARANAPOEMA'; 
update cidade set cod_tom = '7749' where uf = 18 and upper(trim(unaccent(nome))) like 'PARANAVAI'; 
update cidade set cod_tom = '5533' where uf = 18 and upper(trim(unaccent(nome))) like 'PATO BRAGADO'; 
update cidade set cod_tom = '7751' where uf = 18 and upper(trim(unaccent(nome))) like 'PATO BRANCO'; 
update cidade set cod_tom = '7753' where uf = 18 and upper(trim(unaccent(nome))) like 'PAULA FREITAS'; 
update cidade set cod_tom = '7755' where uf = 18 and upper(trim(unaccent(nome))) like 'PAULO FRONTIN'; 
update cidade set cod_tom = '7757' where uf = 18 and upper(trim(unaccent(nome))) like 'PEABIRU'; 
update cidade set cod_tom = '0868' where uf = 18 and upper(trim(unaccent(nome))) like 'PEROBAL'; 
update cidade set cod_tom = '7969' where uf = 18 and upper(trim(unaccent(nome))) like 'PEROLA'; 
update cidade set cod_tom = '7759' where uf = 18 and upper(trim(unaccent(nome))) like 'PEROLA D`OESTE'; 
update cidade set cod_tom = '7761' where uf = 18 and upper(trim(unaccent(nome))) like 'PIEN'; 
update cidade set cod_tom = '5453' where uf = 18 and upper(trim(unaccent(nome))) like 'PINHAIS'; 
update cidade set cod_tom = '5495' where uf = 18 and upper(trim(unaccent(nome))) like 'PINHAL DO SAO BENTO'; 
update cidade set cod_tom = '7763' where uf = 18 and upper(trim(unaccent(nome))) like 'PINHALAO'; 
update cidade set cod_tom = '7765' where uf = 18 and upper(trim(unaccent(nome))) like 'PINHAO'; 
update cidade set cod_tom = '7767' where uf = 18 and upper(trim(unaccent(nome))) like 'PIRAI DO SUL'; 
update cidade set cod_tom = '7769' where uf = 18 and upper(trim(unaccent(nome))) like 'PIRAQUARA'; 
update cidade set cod_tom = '7771' where uf = 18 and upper(trim(unaccent(nome))) like 'PITANGA'; 
update cidade set cod_tom = '5461' where uf = 18 and upper(trim(unaccent(nome))) like 'PITANGUEIRAS'; 
update cidade set cod_tom = '7773' where uf = 18 and upper(trim(unaccent(nome))) like 'PLANALTINA DO PARANA'; 
update cidade set cod_tom = '7775' where uf = 18 and upper(trim(unaccent(nome))) like 'PLANALTO'; 
update cidade set cod_tom = '7777' where uf = 18 and upper(trim(unaccent(nome))) like 'PONTA GROSSA'; 
update cidade set cod_tom = '0870' where uf = 18 and upper(trim(unaccent(nome))) like 'PONTAL DO PARANA'; 
update cidade set cod_tom = '7779' where uf = 18 and upper(trim(unaccent(nome))) like 'PORECATU'; 
update cidade set cod_tom = '7781' where uf = 18 and upper(trim(unaccent(nome))) like 'PORTO AMAZONAS'; 
update cidade set cod_tom = '0872' where uf = 18 and upper(trim(unaccent(nome))) like 'PORTO BARREIRO'; 
update cidade set cod_tom = '7783' where uf = 18 and upper(trim(unaccent(nome))) like 'PORTO RICO'; 
update cidade set cod_tom = '7785' where uf = 18 and upper(trim(unaccent(nome))) like 'PORTO VITORIA'; 
update cidade set cod_tom = '0874' where uf = 18 and upper(trim(unaccent(nome))) like 'PRADO FERREIRA'; 
update cidade set cod_tom = '7991' where uf = 18 and upper(trim(unaccent(nome))) like 'PRANCHITA'; 
update cidade set cod_tom = '7787' where uf = 18 and upper(trim(unaccent(nome))) like 'PRESIDENTE CASTELO BRANCO'; 
update cidade set cod_tom = '7789' where uf = 18 and upper(trim(unaccent(nome))) like 'PRIMEIRO DE MAIO'; 
update cidade set cod_tom = '7791' where uf = 18 and upper(trim(unaccent(nome))) like 'PRUDENTOPOLIS'; 
update cidade set cod_tom = '0876' where uf = 18 and upper(trim(unaccent(nome))) like 'QUARTO CENTENARIO'; 
update cidade set cod_tom = '7793' where uf = 18 and upper(trim(unaccent(nome))) like 'QUATIGUA'; 
update cidade set cod_tom = '7795' where uf = 18 and upper(trim(unaccent(nome))) like 'QUATRO BARRAS'; 
update cidade set cod_tom = '5535' where uf = 18 and upper(trim(unaccent(nome))) like 'QUATRO PONTES'; 
update cidade set cod_tom = '7955' where uf = 18 and upper(trim(unaccent(nome))) like 'QUEDAS DO IGUACU'; 
update cidade set cod_tom = '7797' where uf = 18 and upper(trim(unaccent(nome))) like 'QUERENCIA DO NORTE'; 
update cidade set cod_tom = '7799' where uf = 18 and upper(trim(unaccent(nome))) like 'QUINTA DO SOL'; 
update cidade set cod_tom = '7801' where uf = 18 and upper(trim(unaccent(nome))) like 'QUITANDINHA'; 
update cidade set cod_tom = '5527' where uf = 18 and upper(trim(unaccent(nome))) like 'RAMILANDIA'; 
update cidade set cod_tom = '7803' where uf = 18 and upper(trim(unaccent(nome))) like 'RANCHO ALEGRE'; 
update cidade set cod_tom = '5513' where uf = 18 and upper(trim(unaccent(nome))) like 'RANCHO ALEGRE D`OESTE'; 
update cidade set cod_tom = '7805' where uf = 18 and upper(trim(unaccent(nome))) like 'REALEZA'; 
update cidade set cod_tom = '7807' where uf = 18 and upper(trim(unaccent(nome))) like 'REBOUCAS'; 
update cidade set cod_tom = '7809' where uf = 18 and upper(trim(unaccent(nome))) like 'RENASCENCA'; 
update cidade set cod_tom = '7811' where uf = 18 and upper(trim(unaccent(nome))) like 'RESERVA'; 
update cidade set cod_tom = '0878' where uf = 18 and upper(trim(unaccent(nome))) like 'RESERVA DO IGUACU'; 
update cidade set cod_tom = '7813' where uf = 18 and upper(trim(unaccent(nome))) like 'RIBEIRAO CLARO'; 
update cidade set cod_tom = '7815' where uf = 18 and upper(trim(unaccent(nome))) like 'RIBEIRAO DO PINHAL'; 
update cidade set cod_tom = '7817' where uf = 18 and upper(trim(unaccent(nome))) like 'RIO AZUL'; 
update cidade set cod_tom = '7819' where uf = 18 and upper(trim(unaccent(nome))) like 'RIO BOM'; 
update cidade set cod_tom = '5481' where uf = 18 and upper(trim(unaccent(nome))) like 'RIO BONITO DO IGUACU'; 
update cidade set cod_tom = '0880' where uf = 18 and upper(trim(unaccent(nome))) like 'RIO BRANCO DO IVAI'; 
update cidade set cod_tom = '7821' where uf = 18 and upper(trim(unaccent(nome))) like 'RIO BRANCO DO SUL'; 
update cidade set cod_tom = '7823' where uf = 18 and upper(trim(unaccent(nome))) like 'RIO NEGRO'; 
update cidade set cod_tom = '7825' where uf = 18 and upper(trim(unaccent(nome))) like 'ROLANDIA'; 
update cidade set cod_tom = '7827' where uf = 18 and upper(trim(unaccent(nome))) like 'RONCADOR'; 
update cidade set cod_tom = '7829' where uf = 18 and upper(trim(unaccent(nome))) like 'RONDON'; 
update cidade set cod_tom = '8473' where uf = 18 and upper(trim(unaccent(nome))) like 'ROSARIO DO IVAI'; 
update cidade set cod_tom = '7831' where uf = 18 and upper(trim(unaccent(nome))) like 'SABAUDIA'; 
update cidade set cod_tom = '7833' where uf = 18 and upper(trim(unaccent(nome))) like 'SALGADO FILHO'; 
update cidade set cod_tom = '7835' where uf = 18 and upper(trim(unaccent(nome))) like 'SALTO DO ITARARE'; 
update cidade set cod_tom = '7837' where uf = 18 and upper(trim(unaccent(nome))) like 'SALTO DO LONTRA'; 
update cidade set cod_tom = '7839' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTA AMELIA'; 
update cidade set cod_tom = '7841' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTA CECILIA DO PAVAO'; 
update cidade set cod_tom = '7843' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTA CRUZ DO MONTE CASTELO'; 
update cidade set cod_tom = '7845' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTA FE'; 
update cidade set cod_tom = '7971' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTA HELENA'; 
update cidade set cod_tom = '7847' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTA INES'; 
update cidade set cod_tom = '7849' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTA ISABEL DO IVAI'; 
update cidade set cod_tom = '7851' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTA IZABEL DO OESTE'; 
update cidade set cod_tom = '5469' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTA LUCIA'; 
update cidade set cod_tom = '5505' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTA MARIA DO OESTE'; 
update cidade set cod_tom = '7853' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTA MARIANA'; 
update cidade set cod_tom = '5519' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTA MONICA'; 
update cidade set cod_tom = '9969' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTA TEREZA DO OESTE'; 
update cidade set cod_tom = '8467' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTA TEREZINHA DE ITAIPU'; 
update cidade set cod_tom = '7855' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTANA DO ITARARE'; 
update cidade set cod_tom = '7859' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DA PLATINA'; 
update cidade set cod_tom = '7861' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO CAIUA'; 
update cidade set cod_tom = '7863' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO PARAISO'; 
update cidade set cod_tom = '7857' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO SUDOESTE'; 
update cidade set cod_tom = '7865' where uf = 18 and upper(trim(unaccent(nome))) like 'SANTO INACIO'; 
update cidade set cod_tom = '7867' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO CARLOS DO IVAI'; 
update cidade set cod_tom = '7869' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO JERONIMO DA SERRA'; 
update cidade set cod_tom = '7871' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO JOAO'; 
update cidade set cod_tom = '7873' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO JOAO DO CAIUA'; 
update cidade set cod_tom = '7875' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO JOAO DO IVAI'; 
update cidade set cod_tom = '7877' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO JOAO DO TRIUNFO'; 
update cidade set cod_tom = '7879' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO JORGE DO IVAI'; 
update cidade set cod_tom = '7999' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO JORGE DO PATROCINIO'; 
update cidade set cod_tom = '7881' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO JORGE D`OESTE'; 
update cidade set cod_tom = '7883' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO JOSE DA BOA VISTA'; 
update cidade set cod_tom = '8471' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO JOSE DAS PALMEIRAS'; 
update cidade set cod_tom = '7885' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO JOSE DOS PINHAIS'; 
update cidade set cod_tom = '5515' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO MANOEL DO PARANA'; 
update cidade set cod_tom = '7887' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO MATEUS DO SUL'; 
update cidade set cod_tom = '7889' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO MIGUEL DO IGUACU'; 
update cidade set cod_tom = '5489' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO PEDRO DO IGUACU'; 
update cidade set cod_tom = '7891' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO PEDRO DO IVAI'; 
update cidade set cod_tom = '7893' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO PEDRO DO PARANA'; 
update cidade set cod_tom = '7895' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO DA AMOREIRA'; 
update cidade set cod_tom = '7897' where uf = 18 and upper(trim(unaccent(nome))) like 'SAO TOME'; 
update cidade set cod_tom = '7899' where uf = 18 and upper(trim(unaccent(nome))) like 'SAPOPEMA'; 
update cidade set cod_tom = '8461' where uf = 18 and upper(trim(unaccent(nome))) like 'SARANDI'; 
update cidade set cod_tom = '5493' where uf = 18 and upper(trim(unaccent(nome))) like 'SAUDADE DO IGUACU'; 
update cidade set cod_tom = '7901' where uf = 18 and upper(trim(unaccent(nome))) like 'SENGES'; 
update cidade set cod_tom = '0882' where uf = 18 and upper(trim(unaccent(nome))) like 'SERRANOPOLIS DO IGUACU'; 
update cidade set cod_tom = '7903' where uf = 18 and upper(trim(unaccent(nome))) like 'SERTANEJA'; 
update cidade set cod_tom = '7905' where uf = 18 and upper(trim(unaccent(nome))) like 'SERTANOPOLIS'; 
update cidade set cod_tom = '7907' where uf = 18 and upper(trim(unaccent(nome))) like 'SIQUEIRA CAMPOS'; 
update cidade set cod_tom = '8477' where uf = 18 and upper(trim(unaccent(nome))) like 'SULINA'; 
update cidade set cod_tom = '0884' where uf = 18 and upper(trim(unaccent(nome))) like 'TAMARANA'; 
update cidade set cod_tom = '7909' where uf = 18 and upper(trim(unaccent(nome))) like 'TAMBOARA'; 
update cidade set cod_tom = '7911' where uf = 18 and upper(trim(unaccent(nome))) like 'TAPEJARA'; 
update cidade set cod_tom = '7973' where uf = 18 and upper(trim(unaccent(nome))) like 'TAPIRA'; 
update cidade set cod_tom = '7913' where uf = 18 and upper(trim(unaccent(nome))) like 'TEIXEIRA SOARES'; 
update cidade set cod_tom = '7915' where uf = 18 and upper(trim(unaccent(nome))) like 'TELEMACO BORBA'; 
update cidade set cod_tom = '7917' where uf = 18 and upper(trim(unaccent(nome))) like 'TERRA BOA'; 
update cidade set cod_tom = '7919' where uf = 18 and upper(trim(unaccent(nome))) like 'TERRA RICA'; 
update cidade set cod_tom = '7921' where uf = 18 and upper(trim(unaccent(nome))) like 'TERRA ROXA'; 
update cidade set cod_tom = '7923' where uf = 18 and upper(trim(unaccent(nome))) like 'TIBAGI'; 
update cidade set cod_tom = '7925' where uf = 18 and upper(trim(unaccent(nome))) like 'TIJUCAS DO SUL'; 
update cidade set cod_tom = '7927' where uf = 18 and upper(trim(unaccent(nome))) like 'TOLEDO'; 
update cidade set cod_tom = '7929' where uf = 18 and upper(trim(unaccent(nome))) like 'TOMAZINA'; 
update cidade set cod_tom = '7987' where uf = 18 and upper(trim(unaccent(nome))) like 'TRES BARRAS DO PARANA'; 
update cidade set cod_tom = '5455' where uf = 18 and upper(trim(unaccent(nome))) like 'TUNAS DO PARANA'; 
update cidade set cod_tom = '7931' where uf = 18 and upper(trim(unaccent(nome))) like 'TUNEIRAS DO OESTE'; 
update cidade set cod_tom = '7993' where uf = 18 and upper(trim(unaccent(nome))) like 'TUPASSI'; 
update cidade set cod_tom = '8453' where uf = 18 and upper(trim(unaccent(nome))) like 'TURVO'; 
update cidade set cod_tom = '7933' where uf = 18 and upper(trim(unaccent(nome))) like 'UBIRATA'; 
update cidade set cod_tom = '7935' where uf = 18 and upper(trim(unaccent(nome))) like 'UMUARAMA'; 
update cidade set cod_tom = '7937' where uf = 18 and upper(trim(unaccent(nome))) like 'UNIAO DA VITORIA'; 
update cidade set cod_tom = '7939' where uf = 18 and upper(trim(unaccent(nome))) like 'UNIFLOR'; 
update cidade set cod_tom = '7941' where uf = 18 and upper(trim(unaccent(nome))) like 'URAI'; 
update cidade set cod_tom = '5497' where uf = 18 and upper(trim(unaccent(nome))) like 'VENTANIA'; 
update cidade set cod_tom = '7989' where uf = 18 and upper(trim(unaccent(nome))) like 'VERA CRUZ DO OESTE'; 
update cidade set cod_tom = '7945' where uf = 18 and upper(trim(unaccent(nome))) like 'VERE'; 
update cidade set cod_tom = '5483' where uf = 18 and upper(trim(unaccent(nome))) like 'VIRMOND'; 
update cidade set cod_tom = '7947' where uf = 18 and upper(trim(unaccent(nome))) like 'VITORINO'; 
update cidade set cod_tom = '7943' where uf = 18 and upper(trim(unaccent(nome))) like 'WENCESLAU BRAZ'; 
update cidade set cod_tom = '7949' where uf = 18 and upper(trim(unaccent(nome))) like 'XAMBRE'; 
