update cidade set cod_tom = '9001' where uf = 13 and upper(trim(unaccent(nome))) like 'ACORIZAL'; 
update cidade set cod_tom = '9191' where uf = 13 and upper(trim(unaccent(nome))) like 'AGUA BOA'; 
update cidade set cod_tom = '8987' where uf = 13 and upper(trim(unaccent(nome))) like 'ALTA FLORESTA'; 
update cidade set cod_tom = '9005' where uf = 13 and upper(trim(unaccent(nome))) like 'ALTO ARAGUAIA'; 
update cidade set cod_tom = '0127' where uf = 13 and upper(trim(unaccent(nome))) like 'ALTO BOA VISTA'; 
update cidade set cod_tom = '9007' where uf = 13 and upper(trim(unaccent(nome))) like 'ALTO GARCAS'; 
update cidade set cod_tom = '9009' where uf = 13 and upper(trim(unaccent(nome))) like 'ALTO PARAGUAI'; 
update cidade set cod_tom = '9911' where uf = 13 and upper(trim(unaccent(nome))) like 'ALTO TAQUARI'; 
update cidade set cod_tom = '9773' where uf = 13 and upper(trim(unaccent(nome))) like 'APIACAS'; 
update cidade set cod_tom = '9869' where uf = 13 and upper(trim(unaccent(nome))) like 'ARAGUAIANA'; 
update cidade set cod_tom = '9023' where uf = 13 and upper(trim(unaccent(nome))) like 'ARAGUAINHA'; 
update cidade set cod_tom = '8989' where uf = 13 and upper(trim(unaccent(nome))) like 'ARAPUTANGA'; 
update cidade set cod_tom = '9025' where uf = 13 and upper(trim(unaccent(nome))) like 'ARENAPOLIS'; 
update cidade set cod_tom = '9027' where uf = 13 and upper(trim(unaccent(nome))) like 'ARIPUANA'; 
update cidade set cod_tom = '9031' where uf = 13 and upper(trim(unaccent(nome))) like 'BARAO DE MELGACO'; 
update cidade set cod_tom = '9033' where uf = 13 and upper(trim(unaccent(nome))) like 'BARRA DO BUGRES'; 
update cidade set cod_tom = '9035' where uf = 13 and upper(trim(unaccent(nome))) like 'BARRA DO GARCAS'; 
update cidade set cod_tom = '1078' where uf = 13 and upper(trim(unaccent(nome))) like 'BOM JESUS DO ARAGUAIA'; 
update cidade set cod_tom = '9873' where uf = 13 and upper(trim(unaccent(nome))) like 'BRASNORTE'; 
update cidade set cod_tom = '9047' where uf = 13 and upper(trim(unaccent(nome))) like 'CACERES'; 
update cidade set cod_tom = '9863' where uf = 13 and upper(trim(unaccent(nome))) like 'CAMPINAPOLIS'; 
update cidade set cod_tom = '9777' where uf = 13 and upper(trim(unaccent(nome))) like 'CAMPO NOVO DO PARECIS'; 
update cidade set cod_tom = '9779' where uf = 13 and upper(trim(unaccent(nome))) like 'CAMPO VERDE'; 
update cidade set cod_tom = '1032' where uf = 13 and upper(trim(unaccent(nome))) like 'CAMPOS DE JULIO'; 
update cidade set cod_tom = '0129' where uf = 13 and upper(trim(unaccent(nome))) like 'CANABRAVA DO NORTE'; 
update cidade set cod_tom = '9193' where uf = 13 and upper(trim(unaccent(nome))) like 'CANARANA'; 
update cidade set cod_tom = '1034' where uf = 13 and upper(trim(unaccent(nome))) like 'CARLINDA'; 
update cidade set cod_tom = '9783' where uf = 13 and upper(trim(unaccent(nome))) like 'CASTANHEIRA'; 
update cidade set cod_tom = '9059' where uf = 13 and upper(trim(unaccent(nome))) like 'CHAPADA DOS GUIMARAES'; 
update cidade set cod_tom = '9789' where uf = 13 and upper(trim(unaccent(nome))) like 'CLAUDIA'; 
update cidade set cod_tom = '9865' where uf = 13 and upper(trim(unaccent(nome))) like 'COCALINHO'; 
update cidade set cod_tom = '8979' where uf = 13 and upper(trim(unaccent(nome))) like 'COLIDER'; 
update cidade set cod_tom = '1080' where uf = 13 and upper(trim(unaccent(nome))) like 'COLNIZA'; 
update cidade set cod_tom = '9883' where uf = 13 and upper(trim(unaccent(nome))) like 'COMODORO'; 
update cidade set cod_tom = '0131' where uf = 13 and upper(trim(unaccent(nome))) like 'CONFRESA'; 
update cidade set cod_tom = '1082' where uf = 13 and upper(trim(unaccent(nome))) like 'CONQUISTA D`OESTE'; 
update cidade set cod_tom = '0089' where uf = 13 and upper(trim(unaccent(nome))) like 'COTRIGUACU'; 
update cidade set cod_tom = '9067' where uf = 13 and upper(trim(unaccent(nome))) like 'CUIABA'; 
update cidade set cod_tom = '1084' where uf = 13 and upper(trim(unaccent(nome))) like 'CURVELANDIA'; 
update cidade set cod_tom = '9833' where uf = 13 and upper(trim(unaccent(nome))) like 'DENISE'; 
update cidade set cod_tom = '9069' where uf = 13 and upper(trim(unaccent(nome))) like 'DIAMANTINO'; 
update cidade set cod_tom = '9071' where uf = 13 and upper(trim(unaccent(nome))) like 'DOM AQUINO'; 
update cidade set cod_tom = '0' where uf = 13 and upper(trim(unaccent(nome))) like 'ESPERANCA'; 
update cidade set cod_tom = '1036' where uf = 13 and upper(trim(unaccent(nome))) like 'FELIZ NATAL'; 
update cidade set cod_tom = '9881' where uf = 13 and upper(trim(unaccent(nome))) like 'FIGUEIROPOLIS D`OESTE'; 
update cidade set cod_tom = '1038' where uf = 13 and upper(trim(unaccent(nome))) like 'GAUCHA DO NORTE'; 
update cidade set cod_tom = '9077' where uf = 13 and upper(trim(unaccent(nome))) like 'GENERAL CARNEIRO'; 
update cidade set cod_tom = '0135' where uf = 13 and upper(trim(unaccent(nome))) like 'GLORIA D`OESTE'; 
update cidade set cod_tom = '9887' where uf = 13 and upper(trim(unaccent(nome))) like 'GUARANTA DO NORTE'; 
update cidade set cod_tom = '9083' where uf = 13 and upper(trim(unaccent(nome))) like 'GUIRATINGA'; 
update cidade set cod_tom = '9877' where uf = 13 and upper(trim(unaccent(nome))) like 'INDIAVAI'; 
update cidade set cod_tom = '1184' where uf = 13 and upper(trim(unaccent(nome))) like 'IPIRANGA DO NORTE'; 
update cidade set cod_tom = '1186' where uf = 13 and upper(trim(unaccent(nome))) like 'ITANHANGA'; 
update cidade set cod_tom = '9901' where uf = 13 and upper(trim(unaccent(nome))) like 'ITAUBA'; 
update cidade set cod_tom = '9091' where uf = 13 and upper(trim(unaccent(nome))) like 'ITIQUIRA'; 
update cidade set cod_tom = '9095' where uf = 13 and upper(trim(unaccent(nome))) like 'JACIARA'; 
update cidade set cod_tom = '9861' where uf = 13 and upper(trim(unaccent(nome))) like 'JANGADA'; 
update cidade set cod_tom = '8991' where uf = 13 and upper(trim(unaccent(nome))) like 'JAURU'; 
update cidade set cod_tom = '9819' where uf = 13 and upper(trim(unaccent(nome))) like 'JUARA'; 
update cidade set cod_tom = '9831' where uf = 13 and upper(trim(unaccent(nome))) like 'JUINA'; 
update cidade set cod_tom = '9921' where uf = 13 and upper(trim(unaccent(nome))) like 'JURUENA'; 
update cidade set cod_tom = '9189' where uf = 13 and upper(trim(unaccent(nome))) like 'JUSCIMEIRA'; 
update cidade set cod_tom = '0137' where uf = 13 and upper(trim(unaccent(nome))) like 'LAMBARI D`OESTE'; 
update cidade set cod_tom = '9925' where uf = 13 and upper(trim(unaccent(nome))) like 'LUCAS DO RIO VERDE'; 
update cidade set cod_tom = '9105' where uf = 13 and upper(trim(unaccent(nome))) like 'LUCIARA'; 
update cidade set cod_tom = '9899' where uf = 13 and upper(trim(unaccent(nome))) like 'MARCELANDIA'; 
update cidade set cod_tom = '9929' where uf = 13 and upper(trim(unaccent(nome))) like 'MATUPA'; 
update cidade set cod_tom = '9177' where uf = 13 and upper(trim(unaccent(nome))) like 'MIRASSOL D`OESTE'; 
update cidade set cod_tom = '9117' where uf = 13 and upper(trim(unaccent(nome))) like 'NOBRES'; 
update cidade set cod_tom = '9119' where uf = 13 and upper(trim(unaccent(nome))) like 'NORTELANDIA'; 
update cidade set cod_tom = '9121' where uf = 13 and upper(trim(unaccent(nome))) like 'NOSSA SENHORA DO LIVRAMENTO'; 
update cidade set cod_tom = '0117' where uf = 13 and upper(trim(unaccent(nome))) like 'NOVA BANDEIRANTES'; 
update cidade set cod_tom = '8981' where uf = 13 and upper(trim(unaccent(nome))) like 'NOVA BRASILANDIA'; 
update cidade set cod_tom = '9889' where uf = 13 and upper(trim(unaccent(nome))) like 'NOVA CANAA DO NORTE'; 
update cidade set cod_tom = '0121' where uf = 13 and upper(trim(unaccent(nome))) like 'NOVA GUARITA'; 
update cidade set cod_tom = '1040' where uf = 13 and upper(trim(unaccent(nome))) like 'NOVA LACERDA'; 
update cidade set cod_tom = '0103' where uf = 13 and upper(trim(unaccent(nome))) like 'NOVA MARILANDIA'; 
update cidade set cod_tom = '0111' where uf = 13 and upper(trim(unaccent(nome))) like 'NOVA MARINGA'; 
update cidade set cod_tom = '0119' where uf = 13 and upper(trim(unaccent(nome))) like 'NOVA MONTE VERDE'; 
update cidade set cod_tom = '9937' where uf = 13 and upper(trim(unaccent(nome))) like 'NOVA MUTUM'; 
update cidade set cod_tom = '1086' where uf = 13 and upper(trim(unaccent(nome))) like 'NOVA NAZARE'; 
update cidade set cod_tom = '9893' where uf = 13 and upper(trim(unaccent(nome))) like 'NOVA OLIMPIA'; 
update cidade set cod_tom = '1088' where uf = 13 and upper(trim(unaccent(nome))) like 'NOVA SANTA HELENA'; 
update cidade set cod_tom = '1042' where uf = 13 and upper(trim(unaccent(nome))) like 'NOVA UBIRATA'; 
update cidade set cod_tom = '9195' where uf = 13 and upper(trim(unaccent(nome))) like 'NOVA XAVANTINA'; 
update cidade set cod_tom = '9903' where uf = 13 and upper(trim(unaccent(nome))) like 'NOVO HORIZONTE DO NORTE'; 
update cidade set cod_tom = '1044' where uf = 13 and upper(trim(unaccent(nome))) like 'NOVO MUNDO'; 
update cidade set cod_tom = '1090' where uf = 13 and upper(trim(unaccent(nome))) like 'NOVO SANTO ANTONIO'; 
update cidade set cod_tom = '9867' where uf = 13 and upper(trim(unaccent(nome))) like 'NOVO SAO JOAQUIM'; 
update cidade set cod_tom = '9885' where uf = 13 and upper(trim(unaccent(nome))) like 'PARANAITA'; 
update cidade set cod_tom = '8983' where uf = 13 and upper(trim(unaccent(nome))) like 'PARANATINGA'; 
update cidade set cod_tom = '9181' where uf = 13 and upper(trim(unaccent(nome))) like 'PEDRA PRETA'; 
update cidade set cod_tom = '9891' where uf = 13 and upper(trim(unaccent(nome))) like 'PEIXOTO DE AZEVEDO'; 
update cidade set cod_tom = '0091' where uf = 13 and upper(trim(unaccent(nome))) like 'PLANALTO DA SERRA'; 
update cidade set cod_tom = '9129' where uf = 13 and upper(trim(unaccent(nome))) like 'POCONE'; 
update cidade set cod_tom = '0095' where uf = 13 and upper(trim(unaccent(nome))) like 'PONTAL DO ARAGUAIA'; 
update cidade set cod_tom = '9133' where uf = 13 and upper(trim(unaccent(nome))) like 'PONTE BRANCA'; 
update cidade set cod_tom = '8999' where uf = 13 and upper(trim(unaccent(nome))) like 'PONTES E LACERDA'; 
update cidade set cod_tom = '9895' where uf = 13 and upper(trim(unaccent(nome))) like 'PORTO ALEGRE DO NORTE'; 
update cidade set cod_tom = '9135' where uf = 13 and upper(trim(unaccent(nome))) like 'PORTO DOS GAUCHOS'; 
update cidade set cod_tom = '9875' where uf = 13 and upper(trim(unaccent(nome))) like 'PORTO ESPERIDIAO'; 
update cidade set cod_tom = '0101' where uf = 13 and upper(trim(unaccent(nome))) like 'PORTO ESTRELA'; 
update cidade set cod_tom = '9139' where uf = 13 and upper(trim(unaccent(nome))) like 'POXOREO'; 
update cidade set cod_tom = '9871' where uf = 13 and upper(trim(unaccent(nome))) like 'PRIMAVERA DO LESTE'; 
update cidade set cod_tom = '0097' where uf = 13 and upper(trim(unaccent(nome))) like 'QUERENCIA'; 
update cidade set cod_tom = '9879' where uf = 13 and upper(trim(unaccent(nome))) like 'RESERVA DO CABACAL'; 
update cidade set cod_tom = '9741' where uf = 13 and upper(trim(unaccent(nome))) like 'RIBEIRAO CASCALHEIRA'; 
update cidade set cod_tom = '0099' where uf = 13 and upper(trim(unaccent(nome))) like 'RIBEIRAOZINHO'; 
update cidade set cod_tom = '8995' where uf = 13 and upper(trim(unaccent(nome))) like 'RIO BRANCO'; 
update cidade set cod_tom = '1092' where uf = 13 and upper(trim(unaccent(nome))) like 'RONDOLANDIA'; 
update cidade set cod_tom = '9151' where uf = 13 and upper(trim(unaccent(nome))) like 'RONDONOPOLIS'; 
update cidade set cod_tom = '9153' where uf = 13 and upper(trim(unaccent(nome))) like 'ROSARIO OESTE'; 
update cidade set cod_tom = '8997' where uf = 13 and upper(trim(unaccent(nome))) like 'SALTO DO CEU'; 
update cidade set cod_tom = '0123' where uf = 13 and upper(trim(unaccent(nome))) like 'SANTA CARMEN'; 
update cidade set cod_tom = '1094' where uf = 13 and upper(trim(unaccent(nome))) like 'SANTA CRUZ DO XINGU'; 
update cidade set cod_tom = '1096' where uf = 13 and upper(trim(unaccent(nome))) like 'SANTA RITA DO TRIVELATO'; 
update cidade set cod_tom = '9197' where uf = 13 and upper(trim(unaccent(nome))) like 'SANTA TEREZINHA'; 
update cidade set cod_tom = '0115' where uf = 13 and upper(trim(unaccent(nome))) like 'SANTO AFONSO'; 
update cidade set cod_tom = '1098' where uf = 13 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO LESTE'; 
update cidade set cod_tom = '9155' where uf = 13 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO LEVERGER'; 
update cidade set cod_tom = '9183' where uf = 13 and upper(trim(unaccent(nome))) like 'SAO FELIX DO ARAGUAIA'; 
update cidade set cod_tom = '6087' where uf = 13 and upper(trim(unaccent(nome))) like 'SAO JOSE DO POVO'; 
update cidade set cod_tom = '9199' where uf = 13 and upper(trim(unaccent(nome))) like 'SAO JOSE DO RIO CLARO'; 
update cidade set cod_tom = '0133' where uf = 13 and upper(trim(unaccent(nome))) like 'SAO JOSE DO XINGU'; 
update cidade set cod_tom = '8993' where uf = 13 and upper(trim(unaccent(nome))) like 'SAO JOSE DOS QUATRO MARCOS'; 
update cidade set cod_tom = '0093' where uf = 13 and upper(trim(unaccent(nome))) like 'SAO PEDRO DA CIPA'; 
update cidade set cod_tom = '1046' where uf = 13 and upper(trim(unaccent(nome))) like 'SAPEZAL'; 
update cidade set cod_tom = '1100' where uf = 13 and upper(trim(unaccent(nome))) like 'SERRA NOVA DOURADA'; 
update cidade set cod_tom = '8985' where uf = 13 and upper(trim(unaccent(nome))) like 'SINOP'; 
update cidade set cod_tom = '9907' where uf = 13 and upper(trim(unaccent(nome))) like 'SORRISO'; 
update cidade set cod_tom = '0125' where uf = 13 and upper(trim(unaccent(nome))) like 'TABAPORA'; 
update cidade set cod_tom = '9185' where uf = 13 and upper(trim(unaccent(nome))) like 'TANGARA DA SERRA'; 
update cidade set cod_tom = '9763' where uf = 13 and upper(trim(unaccent(nome))) like 'TAPURAH'; 
update cidade set cod_tom = '9909' where uf = 13 and upper(trim(unaccent(nome))) like 'TERRA NOVA DO NORTE'; 
update cidade set cod_tom = '9161' where uf = 13 and upper(trim(unaccent(nome))) like 'TESOURO'; 
update cidade set cod_tom = '9163' where uf = 13 and upper(trim(unaccent(nome))) like 'TORIXOREU'; 
update cidade set cod_tom = '1048' where uf = 13 and upper(trim(unaccent(nome))) like 'UNIAO DO SUL'; 
update cidade set cod_tom = '1102' where uf = 13 and upper(trim(unaccent(nome))) like 'VALE DE SAO DOMINGOS'; 
update cidade set cod_tom = '9167' where uf = 13 and upper(trim(unaccent(nome))) like 'VARZEA GRANDE'; 
update cidade set cod_tom = '9905' where uf = 13 and upper(trim(unaccent(nome))) like 'VERA'; 
update cidade set cod_tom = '9109' where uf = 13 and upper(trim(unaccent(nome))) like 'VILA BELA DA SANTISSIMA TRINDADE'; 
update cidade set cod_tom = '9897' where uf = 13 and upper(trim(unaccent(nome))) like 'VILA RICA'; 
