update cidade set cod_tom = '9939' where uf = 24 and upper(trim(unaccent(nome))) like 'ABDON BATISTA'; 
update cidade set cod_tom = '8001' where uf = 24 and upper(trim(unaccent(nome))) like 'ABELARDO LUZ'; 
update cidade set cod_tom = '8003' where uf = 24 and upper(trim(unaccent(nome))) like 'AGROLANDIA'; 
update cidade set cod_tom = '8005' where uf = 24 and upper(trim(unaccent(nome))) like 'AGRONOMICA'; 
update cidade set cod_tom = '8007' where uf = 24 and upper(trim(unaccent(nome))) like 'AGUA DOCE'; 
update cidade set cod_tom = '8009' where uf = 24 and upper(trim(unaccent(nome))) like 'AGUAS DE CHAPECO'; 
update cidade set cod_tom = '5577' where uf = 24 and upper(trim(unaccent(nome))) like 'AGUAS FRIAS'; 
update cidade set cod_tom = '8011' where uf = 24 and upper(trim(unaccent(nome))) like 'AGUAS MORNAS'; 
update cidade set cod_tom = '8013' where uf = 24 and upper(trim(unaccent(nome))) like 'ALFREDO WAGNER'; 
update cidade set cod_tom = '0886' where uf = 24 and upper(trim(unaccent(nome))) like 'ALTO BELA VISTA'; 
update cidade set cod_tom = '8015' where uf = 24 and upper(trim(unaccent(nome))) like 'ANCHIETA'; 
update cidade set cod_tom = '8017' where uf = 24 and upper(trim(unaccent(nome))) like 'ANGELINA'; 
update cidade set cod_tom = '8019' where uf = 24 and upper(trim(unaccent(nome))) like 'ANITA GARIBALDI'; 
update cidade set cod_tom = '8021' where uf = 24 and upper(trim(unaccent(nome))) like 'ANITAPOLIS'; 
update cidade set cod_tom = '8023' where uf = 24 and upper(trim(unaccent(nome))) like 'ANTONIO CARLOS'; 
update cidade set cod_tom = '9941' where uf = 24 and upper(trim(unaccent(nome))) like 'APIUNA'; 
update cidade set cod_tom = '5597' where uf = 24 and upper(trim(unaccent(nome))) like 'ARABUTA'; 
update cidade set cod_tom = '8025' where uf = 24 and upper(trim(unaccent(nome))) like 'ARAQUARI'; 
update cidade set cod_tom = '8027' where uf = 24 and upper(trim(unaccent(nome))) like 'ARARANGUA'; 
update cidade set cod_tom = '8029' where uf = 24 and upper(trim(unaccent(nome))) like 'ARMAZEM'; 
update cidade set cod_tom = '8031' where uf = 24 and upper(trim(unaccent(nome))) like 'ARROIO TRINTA'; 
update cidade set cod_tom = '5599' where uf = 24 and upper(trim(unaccent(nome))) like 'ARVOREDO'; 
update cidade set cod_tom = '8033' where uf = 24 and upper(trim(unaccent(nome))) like 'ASCURRA'; 
update cidade set cod_tom = '8035' where uf = 24 and upper(trim(unaccent(nome))) like 'ATALANTA'; 
update cidade set cod_tom = '8037' where uf = 24 and upper(trim(unaccent(nome))) like 'AURORA'; 
update cidade set cod_tom = '0888' where uf = 24 and upper(trim(unaccent(nome))) like 'BALNEARIO ARROIO DO SILVA'; 
update cidade set cod_tom = '5549' where uf = 24 and upper(trim(unaccent(nome))) like 'BALNEARIO BARRA DO SUL'; 
update cidade set cod_tom = '8039' where uf = 24 and upper(trim(unaccent(nome))) like 'BALNEARIO CAMBORIU'; 
update cidade set cod_tom = '8251' where uf = 24 and upper(trim(unaccent(nome))) like 'BALNEARIO DE PICARRAS'; 
update cidade set cod_tom = '0890' where uf = 24 and upper(trim(unaccent(nome))) like 'BALNEARIO GAIVOTA'; 
update cidade set cod_tom = '0892' where uf = 24 and upper(trim(unaccent(nome))) like 'BANDEIRANTE'; 
update cidade set cod_tom = '0894' where uf = 24 and upper(trim(unaccent(nome))) like 'BARRA BONITA'; 
update cidade set cod_tom = '8041' where uf = 24 and upper(trim(unaccent(nome))) like 'BARRA VELHA'; 
update cidade set cod_tom = '0896' where uf = 24 and upper(trim(unaccent(nome))) like 'BELA VISTA DO TOLDO'; 
update cidade set cod_tom = '5745' where uf = 24 and upper(trim(unaccent(nome))) like 'BELMONTE'; 
update cidade set cod_tom = '8043' where uf = 24 and upper(trim(unaccent(nome))) like 'BENEDITO NOVO'; 
update cidade set cod_tom = '8045' where uf = 24 and upper(trim(unaccent(nome))) like 'BIGUACU'; 
update cidade set cod_tom = '8047' where uf = 24 and upper(trim(unaccent(nome))) like 'BLUMENAU'; 
update cidade set cod_tom = '0898' where uf = 24 and upper(trim(unaccent(nome))) like 'BOCAINA DO SUL'; 
update cidade set cod_tom = '8389' where uf = 24 and upper(trim(unaccent(nome))) like 'BOM JARDIM DA SERRA'; 
update cidade set cod_tom = '0900' where uf = 24 and upper(trim(unaccent(nome))) like 'BOM JESUS'; 
update cidade set cod_tom = '0902' where uf = 24 and upper(trim(unaccent(nome))) like 'BOM JESUS DO OESTE'; 
update cidade set cod_tom = '8049' where uf = 24 and upper(trim(unaccent(nome))) like 'BOM RETIRO'; 
update cidade set cod_tom = '5537' where uf = 24 and upper(trim(unaccent(nome))) like 'BOMBINHAS'; 
update cidade set cod_tom = '8051' where uf = 24 and upper(trim(unaccent(nome))) like 'BOTUVERA'; 
update cidade set cod_tom = '8053' where uf = 24 and upper(trim(unaccent(nome))) like 'BRACO DO NORTE'; 
update cidade set cod_tom = '5557' where uf = 24 and upper(trim(unaccent(nome))) like 'BRACO DO TROMBUDO'; 
update cidade set cod_tom = '0904' where uf = 24 and upper(trim(unaccent(nome))) like 'BRUNOPOLIS'; 
update cidade set cod_tom = '8055' where uf = 24 and upper(trim(unaccent(nome))) like 'BRUSQUE'; 
update cidade set cod_tom = '8057' where uf = 24 and upper(trim(unaccent(nome))) like 'CACADOR'; 
update cidade set cod_tom = '8059' where uf = 24 and upper(trim(unaccent(nome))) like 'CAIBI'; 
update cidade set cod_tom = '5553' where uf = 24 and upper(trim(unaccent(nome))) like 'CALMON'; 
update cidade set cod_tom = '8061' where uf = 24 and upper(trim(unaccent(nome))) like 'CAMBORIU'; 
update cidade set cod_tom = '8063' where uf = 24 and upper(trim(unaccent(nome))) like 'CAMPO ALEGRE'; 
update cidade set cod_tom = '8065' where uf = 24 and upper(trim(unaccent(nome))) like 'CAMPO BELO DO SUL'; 
update cidade set cod_tom = '8067' where uf = 24 and upper(trim(unaccent(nome))) like 'CAMPO ERE'; 
update cidade set cod_tom = '8069' where uf = 24 and upper(trim(unaccent(nome))) like 'CAMPOS NOVOS'; 
update cidade set cod_tom = '8071' where uf = 24 and upper(trim(unaccent(nome))) like 'CANELINHA'; 
update cidade set cod_tom = '8073' where uf = 24 and upper(trim(unaccent(nome))) like 'CANOINHAS'; 
update cidade set cod_tom = '0906' where uf = 24 and upper(trim(unaccent(nome))) like 'CAPAO ALTO'; 
update cidade set cod_tom = '8075' where uf = 24 and upper(trim(unaccent(nome))) like 'CAPINZAL'; 
update cidade set cod_tom = '5545' where uf = 24 and upper(trim(unaccent(nome))) like 'CAPIVARI DE BAIXO'; 
update cidade set cod_tom = '8077' where uf = 24 and upper(trim(unaccent(nome))) like 'CATANDUVAS'; 
update cidade set cod_tom = '8079' where uf = 24 and upper(trim(unaccent(nome))) like 'CAXAMBU DO SUL'; 
update cidade set cod_tom = '9943' where uf = 24 and upper(trim(unaccent(nome))) like 'CELSO RAMOS'; 
update cidade set cod_tom = '5567' where uf = 24 and upper(trim(unaccent(nome))) like 'CERRO NEGRO'; 
update cidade set cod_tom = '0908' where uf = 24 and upper(trim(unaccent(nome))) like 'CHAPADAO DO LAGEADO'; 
update cidade set cod_tom = '8081' where uf = 24 and upper(trim(unaccent(nome))) like 'CHAPECO'; 
update cidade set cod_tom = '5543' where uf = 24 and upper(trim(unaccent(nome))) like 'COCAL DO SUL'; 
update cidade set cod_tom = '8083' where uf = 24 and upper(trim(unaccent(nome))) like 'CONCORDIA'; 
update cidade set cod_tom = '5579' where uf = 24 and upper(trim(unaccent(nome))) like 'CORDILHEIRA ALTA'; 
update cidade set cod_tom = '8085' where uf = 24 and upper(trim(unaccent(nome))) like 'CORONEL FREITAS'; 
update cidade set cod_tom = '5735' where uf = 24 and upper(trim(unaccent(nome))) like 'CORONEL MARTINS'; 
update cidade set cod_tom = '8395' where uf = 24 and upper(trim(unaccent(nome))) like 'CORREIA PINTO'; 
update cidade set cod_tom = '8087' where uf = 24 and upper(trim(unaccent(nome))) like 'CORUPA'; 
update cidade set cod_tom = '8089' where uf = 24 and upper(trim(unaccent(nome))) like 'CRICIUMA'; 
update cidade set cod_tom = '8091' where uf = 24 and upper(trim(unaccent(nome))) like 'CUNHA PORA'; 
update cidade set cod_tom = '0910' where uf = 24 and upper(trim(unaccent(nome))) like 'CUNHATAI'; 
update cidade set cod_tom = '8093' where uf = 24 and upper(trim(unaccent(nome))) like 'CURITIBANOS'; 
update cidade set cod_tom = '8095' where uf = 24 and upper(trim(unaccent(nome))) like 'DESCANSO'; 
update cidade set cod_tom = '8097' where uf = 24 and upper(trim(unaccent(nome))) like 'DIONISIO CERQUEIRA'; 
update cidade set cod_tom = '8099' where uf = 24 and upper(trim(unaccent(nome))) like 'DONA EMMA'; 
update cidade set cod_tom = '9945' where uf = 24 and upper(trim(unaccent(nome))) like 'DOUTOR PEDRINHO'; 
update cidade set cod_tom = '0912' where uf = 24 and upper(trim(unaccent(nome))) like 'ENTRE RIOS'; 
update cidade set cod_tom = '0914' where uf = 24 and upper(trim(unaccent(nome))) like 'ERMO'; 
update cidade set cod_tom = '8101' where uf = 24 and upper(trim(unaccent(nome))) like 'ERVAL VELHO'; 
update cidade set cod_tom = '8103' where uf = 24 and upper(trim(unaccent(nome))) like 'FAXINAL DOS GUEDES'; 
update cidade set cod_tom = '0916' where uf = 24 and upper(trim(unaccent(nome))) like 'FLOR DO SERTAO'; 
update cidade set cod_tom = '8105' where uf = 24 and upper(trim(unaccent(nome))) like 'FLORIANOPOLIS'; 
update cidade set cod_tom = '5581' where uf = 24 and upper(trim(unaccent(nome))) like 'FORMOSA DO SUL'; 
update cidade set cod_tom = '0973' where uf = 24 and upper(trim(unaccent(nome))) like 'FORQUILHINHA'; 
update cidade set cod_tom = '8107' where uf = 24 and upper(trim(unaccent(nome))) like 'FRAIBURGO'; 
update cidade set cod_tom = '0918' where uf = 24 and upper(trim(unaccent(nome))) like 'FREI ROGERIO'; 
update cidade set cod_tom = '8109' where uf = 24 and upper(trim(unaccent(nome))) like 'GALVAO'; 
update cidade set cod_tom = '8113' where uf = 24 and upper(trim(unaccent(nome))) like 'GAROPABA'; 
update cidade set cod_tom = '8115' where uf = 24 and upper(trim(unaccent(nome))) like 'GARUVA'; 
update cidade set cod_tom = '8117' where uf = 24 and upper(trim(unaccent(nome))) like 'GASPAR'; 
update cidade set cod_tom = '8111' where uf = 24 and upper(trim(unaccent(nome))) like 'GOVERNADOR CELSO RAMOS'; 
update cidade set cod_tom = '8119' where uf = 24 and upper(trim(unaccent(nome))) like 'GRAO PARA'; 
update cidade set cod_tom = '8121' where uf = 24 and upper(trim(unaccent(nome))) like 'GRAVATAL'; 
update cidade set cod_tom = '8123' where uf = 24 and upper(trim(unaccent(nome))) like 'GUABIRUBA'; 
update cidade set cod_tom = '8125' where uf = 24 and upper(trim(unaccent(nome))) like 'GUARACIABA'; 
update cidade set cod_tom = '8127' where uf = 24 and upper(trim(unaccent(nome))) like 'GUARAMIRIM'; 
update cidade set cod_tom = '8129' where uf = 24 and upper(trim(unaccent(nome))) like 'GUARUJA DO SUL'; 
update cidade set cod_tom = '5583' where uf = 24 and upper(trim(unaccent(nome))) like 'GUATAMBU'; 
update cidade set cod_tom = '8131' where uf = 24 and upper(trim(unaccent(nome))) like 'HERVAL D`OESTE'; 
update cidade set cod_tom = '0920' where uf = 24 and upper(trim(unaccent(nome))) like 'IBIAM'; 
update cidade set cod_tom = '8133' where uf = 24 and upper(trim(unaccent(nome))) like 'IBICARE'; 
update cidade set cod_tom = '8135' where uf = 24 and upper(trim(unaccent(nome))) like 'IBIRAMA'; 
update cidade set cod_tom = '8137' where uf = 24 and upper(trim(unaccent(nome))) like 'ICARA'; 
update cidade set cod_tom = '8139' where uf = 24 and upper(trim(unaccent(nome))) like 'ILHOTA'; 
update cidade set cod_tom = '8141' where uf = 24 and upper(trim(unaccent(nome))) like 'IMARUI'; 
update cidade set cod_tom = '8143' where uf = 24 and upper(trim(unaccent(nome))) like 'IMBITUBA'; 
update cidade set cod_tom = '8145' where uf = 24 and upper(trim(unaccent(nome))) like 'IMBUIA'; 
update cidade set cod_tom = '8147' where uf = 24 and upper(trim(unaccent(nome))) like 'INDAIAL'; 
update cidade set cod_tom = '0922' where uf = 24 and upper(trim(unaccent(nome))) like 'IOMERE'; 
update cidade set cod_tom = '8149' where uf = 24 and upper(trim(unaccent(nome))) like 'IPIRA'; 
update cidade set cod_tom = '9951' where uf = 24 and upper(trim(unaccent(nome))) like 'IPORA DO OESTE'; 
update cidade set cod_tom = '5737' where uf = 24 and upper(trim(unaccent(nome))) like 'IPUACU'; 
update cidade set cod_tom = '8151' where uf = 24 and upper(trim(unaccent(nome))) like 'IPUMIRIM'; 
update cidade set cod_tom = '9953' where uf = 24 and upper(trim(unaccent(nome))) like 'IRACEMINHA'; 
update cidade set cod_tom = '8153' where uf = 24 and upper(trim(unaccent(nome))) like 'IRANI'; 
update cidade set cod_tom = '5585' where uf = 24 and upper(trim(unaccent(nome))) like 'IRATI'; 
update cidade set cod_tom = '8155' where uf = 24 and upper(trim(unaccent(nome))) like 'IRINEOPOLIS'; 
update cidade set cod_tom = '8157' where uf = 24 and upper(trim(unaccent(nome))) like 'ITA'; 
update cidade set cod_tom = '8159' where uf = 24 and upper(trim(unaccent(nome))) like 'ITAIOPOLIS'; 
update cidade set cod_tom = '8161' where uf = 24 and upper(trim(unaccent(nome))) like 'ITAJAI'; 
update cidade set cod_tom = '8163' where uf = 24 and upper(trim(unaccent(nome))) like 'ITAPEMA'; 
update cidade set cod_tom = '8165' where uf = 24 and upper(trim(unaccent(nome))) like 'ITAPIRANGA'; 
update cidade set cod_tom = '9985' where uf = 24 and upper(trim(unaccent(nome))) like 'ITAPOA'; 
update cidade set cod_tom = '8167' where uf = 24 and upper(trim(unaccent(nome))) like 'ITUPORANGA'; 
update cidade set cod_tom = '8169' where uf = 24 and upper(trim(unaccent(nome))) like 'JABORA'; 
update cidade set cod_tom = '8171' where uf = 24 and upper(trim(unaccent(nome))) like 'JACINTO MACHADO'; 
update cidade set cod_tom = '8173' where uf = 24 and upper(trim(unaccent(nome))) like 'JAGUARUNA'; 
update cidade set cod_tom = '8175' where uf = 24 and upper(trim(unaccent(nome))) like 'JARAGUA DO SUL'; 
update cidade set cod_tom = '5587' where uf = 24 and upper(trim(unaccent(nome))) like 'JARDINOPOLIS'; 
update cidade set cod_tom = '8177' where uf = 24 and upper(trim(unaccent(nome))) like 'JOACABA'; 
update cidade set cod_tom = '8179' where uf = 24 and upper(trim(unaccent(nome))) like 'JOINVILLE'; 
update cidade set cod_tom = '9957' where uf = 24 and upper(trim(unaccent(nome))) like 'JOSE BOITEUX'; 
update cidade set cod_tom = '0924' where uf = 24 and upper(trim(unaccent(nome))) like 'JUPIA'; 
update cidade set cod_tom = '8181' where uf = 24 and upper(trim(unaccent(nome))) like 'LACERDOPOLIS'; 
update cidade set cod_tom = '5739' where uf = 24 and upper(trim(unaccent(nome))) like 'LAGEADO GRANDE'; 
update cidade set cod_tom = '8183' where uf = 24 and upper(trim(unaccent(nome))) like 'LAGES'; 
update cidade set cod_tom = '8185' where uf = 24 and upper(trim(unaccent(nome))) like 'LAGUNA'; 
update cidade set cod_tom = '8187' where uf = 24 and upper(trim(unaccent(nome))) like 'LAURENTINO'; 
update cidade set cod_tom = '8189' where uf = 24 and upper(trim(unaccent(nome))) like 'LAURO MULLER'; 
update cidade set cod_tom = '8191' where uf = 24 and upper(trim(unaccent(nome))) like 'LEBON REGIS'; 
update cidade set cod_tom = '8193' where uf = 24 and upper(trim(unaccent(nome))) like 'LEOBERTO LEAL'; 
update cidade set cod_tom = '9961' where uf = 24 and upper(trim(unaccent(nome))) like 'LINDOIA DO SUL'; 
update cidade set cod_tom = '8195' where uf = 24 and upper(trim(unaccent(nome))) like 'LONTRAS'; 
update cidade set cod_tom = '8197' where uf = 24 and upper(trim(unaccent(nome))) like 'LUIZ ALVES'; 
update cidade set cod_tom = '0926' where uf = 24 and upper(trim(unaccent(nome))) like 'LUZERNA'; 
update cidade set cod_tom = '5575' where uf = 24 and upper(trim(unaccent(nome))) like 'MACIEIRA'; 
update cidade set cod_tom = '8199' where uf = 24 and upper(trim(unaccent(nome))) like 'MAFRA'; 
update cidade set cod_tom = '8201' where uf = 24 and upper(trim(unaccent(nome))) like 'MAJOR GERCINO'; 
update cidade set cod_tom = '8203' where uf = 24 and upper(trim(unaccent(nome))) like 'MAJOR VIEIRA'; 
update cidade set cod_tom = '8391' where uf = 24 and upper(trim(unaccent(nome))) like 'MARACAJA'; 
update cidade set cod_tom = '8205' where uf = 24 and upper(trim(unaccent(nome))) like 'MARAVILHA'; 
update cidade set cod_tom = '9963' where uf = 24 and upper(trim(unaccent(nome))) like 'MAREMA'; 
update cidade set cod_tom = '8207' where uf = 24 and upper(trim(unaccent(nome))) like 'MASSARANDUBA'; 
update cidade set cod_tom = '8209' where uf = 24 and upper(trim(unaccent(nome))) like 'MATOS COSTA'; 
update cidade set cod_tom = '8211' where uf = 24 and upper(trim(unaccent(nome))) like 'MELEIRO'; 
update cidade set cod_tom = '5559' where uf = 24 and upper(trim(unaccent(nome))) like 'MIRIM DOCE'; 
update cidade set cod_tom = '8213' where uf = 24 and upper(trim(unaccent(nome))) like 'MODELO'; 
update cidade set cod_tom = '8215' where uf = 24 and upper(trim(unaccent(nome))) like 'MONDAI'; 
update cidade set cod_tom = '5561' where uf = 24 and upper(trim(unaccent(nome))) like 'MONTE CARLO'; 
update cidade set cod_tom = '8217' where uf = 24 and upper(trim(unaccent(nome))) like 'MONTE CASTELO'; 
update cidade set cod_tom = '8219' where uf = 24 and upper(trim(unaccent(nome))) like 'MORRO DA FUMACA'; 
update cidade set cod_tom = '5539' where uf = 24 and upper(trim(unaccent(nome))) like 'MORRO GRANDE'; 
update cidade set cod_tom = '8221' where uf = 24 and upper(trim(unaccent(nome))) like 'NAVEGANTES'; 
update cidade set cod_tom = '8223' where uf = 24 and upper(trim(unaccent(nome))) like 'NOVA ERECHIM'; 
update cidade set cod_tom = '5589' where uf = 24 and upper(trim(unaccent(nome))) like 'NOVA ITABERABA'; 
update cidade set cod_tom = '8225' where uf = 24 and upper(trim(unaccent(nome))) like 'NOVA TRENTO'; 
update cidade set cod_tom = '8227' where uf = 24 and upper(trim(unaccent(nome))) like 'NOVA VENEZA'; 
update cidade set cod_tom = '5591' where uf = 24 and upper(trim(unaccent(nome))) like 'NOVO HORIZONTE'; 
update cidade set cod_tom = '8229' where uf = 24 and upper(trim(unaccent(nome))) like 'ORLEANS'; 
update cidade set cod_tom = '8397' where uf = 24 and upper(trim(unaccent(nome))) like 'OTACILIO COSTA'; 
update cidade set cod_tom = '8231' where uf = 24 and upper(trim(unaccent(nome))) like 'OURO'; 
update cidade set cod_tom = '5741' where uf = 24 and upper(trim(unaccent(nome))) like 'OURO VERDE'; 
update cidade set cod_tom = '0928' where uf = 24 and upper(trim(unaccent(nome))) like 'PAIAL'; 
update cidade set cod_tom = '0930' where uf = 24 and upper(trim(unaccent(nome))) like 'PAINEL'; 
update cidade set cod_tom = '8233' where uf = 24 and upper(trim(unaccent(nome))) like 'PALHOCA'; 
update cidade set cod_tom = '8235' where uf = 24 and upper(trim(unaccent(nome))) like 'PALMA SOLA'; 
update cidade set cod_tom = '0932' where uf = 24 and upper(trim(unaccent(nome))) like 'PALMEIRA'; 
update cidade set cod_tom = '8237' where uf = 24 and upper(trim(unaccent(nome))) like 'PALMITOS'; 
update cidade set cod_tom = '8239' where uf = 24 and upper(trim(unaccent(nome))) like 'PAPANDUVA'; 
update cidade set cod_tom = '5747' where uf = 24 and upper(trim(unaccent(nome))) like 'PARAISO'; 
update cidade set cod_tom = '5541' where uf = 24 and upper(trim(unaccent(nome))) like 'PASSO DE TORRES'; 
update cidade set cod_tom = '5743' where uf = 24 and upper(trim(unaccent(nome))) like 'PASSOS MAIA'; 
update cidade set cod_tom = '8241' where uf = 24 and upper(trim(unaccent(nome))) like 'PAULO LOPES'; 
update cidade set cod_tom = '8243' where uf = 24 and upper(trim(unaccent(nome))) like 'PEDRAS GRANDES'; 
update cidade set cod_tom = '8245' where uf = 24 and upper(trim(unaccent(nome))) like 'PENHA'; 
update cidade set cod_tom = '8247' where uf = 24 and upper(trim(unaccent(nome))) like 'PERITIBA'; 
update cidade set cod_tom = '8249' where uf = 24 and upper(trim(unaccent(nome))) like 'PETROLANDIA'; 
update cidade set cod_tom = '8253' where uf = 24 and upper(trim(unaccent(nome))) like 'PINHALZINHO'; 
update cidade set cod_tom = '8255' where uf = 24 and upper(trim(unaccent(nome))) like 'PINHEIRO PRETO'; 
update cidade set cod_tom = '8257' where uf = 24 and upper(trim(unaccent(nome))) like 'PIRATUBA'; 
update cidade set cod_tom = '5593' where uf = 24 and upper(trim(unaccent(nome))) like 'PLANALTO ALEGRE'; 
update cidade set cod_tom = '8259' where uf = 24 and upper(trim(unaccent(nome))) like 'POMERODE'; 
update cidade set cod_tom = '8261' where uf = 24 and upper(trim(unaccent(nome))) like 'PONTE ALTA'; 
update cidade set cod_tom = '5569' where uf = 24 and upper(trim(unaccent(nome))) like 'PONTE ALTA DO NORTE'; 
update cidade set cod_tom = '8263' where uf = 24 and upper(trim(unaccent(nome))) like 'PONTE SERRADA'; 
update cidade set cod_tom = '8265' where uf = 24 and upper(trim(unaccent(nome))) like 'PORTO BELO'; 
update cidade set cod_tom = '8267' where uf = 24 and upper(trim(unaccent(nome))) like 'PORTO UNIAO'; 
update cidade set cod_tom = '8269' where uf = 24 and upper(trim(unaccent(nome))) like 'POUSO REDONDO'; 
update cidade set cod_tom = '8271' where uf = 24 and upper(trim(unaccent(nome))) like 'PRAIA GRANDE'; 
update cidade set cod_tom = '8273' where uf = 24 and upper(trim(unaccent(nome))) like 'PRESIDENTE CASTELO BRANCO'; 
update cidade set cod_tom = '8275' where uf = 24 and upper(trim(unaccent(nome))) like 'PRESIDENTE GETULIO'; 
update cidade set cod_tom = '8277' where uf = 24 and upper(trim(unaccent(nome))) like 'PRESIDENTE NEREU'; 
update cidade set cod_tom = '0934' where uf = 24 and upper(trim(unaccent(nome))) like 'PRINCESA'; 
update cidade set cod_tom = '8279' where uf = 24 and upper(trim(unaccent(nome))) like 'QUILOMBO'; 
update cidade set cod_tom = '8281' where uf = 24 and upper(trim(unaccent(nome))) like 'RANCHO QUEIMADO'; 
update cidade set cod_tom = '8283' where uf = 24 and upper(trim(unaccent(nome))) like 'RIO DAS ANTAS'; 
update cidade set cod_tom = '8285' where uf = 24 and upper(trim(unaccent(nome))) like 'RIO DO CAMPO'; 
update cidade set cod_tom = '8287' where uf = 24 and upper(trim(unaccent(nome))) like 'RIO DO OESTE'; 
update cidade set cod_tom = '8291' where uf = 24 and upper(trim(unaccent(nome))) like 'RIO DO SUL'; 
update cidade set cod_tom = '8289' where uf = 24 and upper(trim(unaccent(nome))) like 'RIO DOS CEDROS'; 
update cidade set cod_tom = '8293' where uf = 24 and upper(trim(unaccent(nome))) like 'RIO FORTUNA'; 
update cidade set cod_tom = '8295' where uf = 24 and upper(trim(unaccent(nome))) like 'RIO NEGRINHO'; 
update cidade set cod_tom = '5571' where uf = 24 and upper(trim(unaccent(nome))) like 'RIO RUFINO'; 
update cidade set cod_tom = '5749' where uf = 24 and upper(trim(unaccent(nome))) like 'RIQUEZA'; 
update cidade set cod_tom = '8297' where uf = 24 and upper(trim(unaccent(nome))) like 'RODEIO'; 
update cidade set cod_tom = '8299' where uf = 24 and upper(trim(unaccent(nome))) like 'ROMELANDIA'; 
update cidade set cod_tom = '8301' where uf = 24 and upper(trim(unaccent(nome))) like 'SALETE'; 
update cidade set cod_tom = '0936' where uf = 24 and upper(trim(unaccent(nome))) like 'SALTINHO'; 
update cidade set cod_tom = '8303' where uf = 24 and upper(trim(unaccent(nome))) like 'SALTO VELOSO'; 
update cidade set cod_tom = '5547' where uf = 24 and upper(trim(unaccent(nome))) like 'SANGAO'; 
update cidade set cod_tom = '8305' where uf = 24 and upper(trim(unaccent(nome))) like 'SANTA CECILIA'; 
update cidade set cod_tom = '5751' where uf = 24 and upper(trim(unaccent(nome))) like 'SANTA HELENA'; 
update cidade set cod_tom = '8307' where uf = 24 and upper(trim(unaccent(nome))) like 'SANTA ROSA DE LIMA'; 
update cidade set cod_tom = '9967' where uf = 24 and upper(trim(unaccent(nome))) like 'SANTA ROSA DO SUL'; 
update cidade set cod_tom = '5555' where uf = 24 and upper(trim(unaccent(nome))) like 'SANTA TEREZINHA'; 
update cidade set cod_tom = '0938' where uf = 24 and upper(trim(unaccent(nome))) like 'SANTA TEREZINHA DO PROGRESSO'; 
update cidade set cod_tom = '0940' where uf = 24 and upper(trim(unaccent(nome))) like 'SANTIAGO DO SUL'; 
update cidade set cod_tom = '8309' where uf = 24 and upper(trim(unaccent(nome))) like 'SANTO AMARO DA IMPERATRIZ'; 
update cidade set cod_tom = '8311' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO BENTO DO SUL'; 
update cidade set cod_tom = '0942' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO BERNARDINO'; 
update cidade set cod_tom = '8313' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO BONIFACIO'; 
update cidade set cod_tom = '8315' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO CARLOS'; 
update cidade set cod_tom = '5573' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO CRISTOVAO DO SUL'; 
update cidade set cod_tom = '8317' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO DOMINGOS'; 
update cidade set cod_tom = '8319' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO DO SUL'; 
update cidade set cod_tom = '8321' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO JOAO BATISTA'; 
update cidade set cod_tom = '5551' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO JOAO DO ITAPERIU'; 
update cidade set cod_tom = '5753' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO JOAO DO OESTE'; 
update cidade set cod_tom = '8323' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO JOAO DO SUL'; 
update cidade set cod_tom = '8325' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO JOAQUIM'; 
update cidade set cod_tom = '8327' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO JOSE'; 
update cidade set cod_tom = '8329' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO JOSE DO CEDRO'; 
update cidade set cod_tom = '8331' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO JOSE DO CERRITO'; 
update cidade set cod_tom = '8333' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO LOURENCO D`OESTE'; 
update cidade set cod_tom = '8335' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO LUDGERO'; 
update cidade set cod_tom = '8337' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO MARTINHO'; 
update cidade set cod_tom = '5755' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO MIGUEL DA BOA VISTA'; 
update cidade set cod_tom = '8339' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO MIGUEL D`OESTE'; 
update cidade set cod_tom = '0944' where uf = 24 and upper(trim(unaccent(nome))) like 'SAO PEDRO DE ALCANTARA'; 
update cidade set cod_tom = '8341' where uf = 24 and upper(trim(unaccent(nome))) like 'SAUDADES'; 
update cidade set cod_tom = '8343' where uf = 24 and upper(trim(unaccent(nome))) like 'SCHROEDER'; 
update cidade set cod_tom = '8345' where uf = 24 and upper(trim(unaccent(nome))) like 'SEARA'; 
update cidade set cod_tom = '9989' where uf = 24 and upper(trim(unaccent(nome))) like 'SERRA ALTA'; 
update cidade set cod_tom = '8347' where uf = 24 and upper(trim(unaccent(nome))) like 'SIDEROPOLIS'; 
update cidade set cod_tom = '8349' where uf = 24 and upper(trim(unaccent(nome))) like 'SOMBRIO'; 
update cidade set cod_tom = '5595' where uf = 24 and upper(trim(unaccent(nome))) like 'SUL BRASIL'; 
update cidade set cod_tom = '8351' where uf = 24 and upper(trim(unaccent(nome))) like 'TAIO'; 
update cidade set cod_tom = '8353' where uf = 24 and upper(trim(unaccent(nome))) like 'TANGARA'; 
update cidade set cod_tom = '0946' where uf = 24 and upper(trim(unaccent(nome))) like 'TIGRINHOS'; 
update cidade set cod_tom = '8355' where uf = 24 and upper(trim(unaccent(nome))) like 'TIJUCAS'; 
update cidade set cod_tom = '8393' where uf = 24 and upper(trim(unaccent(nome))) like 'TIMBE DO SUL'; 
update cidade set cod_tom = '8357' where uf = 24 and upper(trim(unaccent(nome))) like 'TIMBO'; 
update cidade set cod_tom = '9971' where uf = 24 and upper(trim(unaccent(nome))) like 'TIMBO GRANDE'; 
update cidade set cod_tom = '8359' where uf = 24 and upper(trim(unaccent(nome))) like 'TRES BARRAS'; 
update cidade set cod_tom = '0948' where uf = 24 and upper(trim(unaccent(nome))) like 'TREVISO'; 
update cidade set cod_tom = '8361' where uf = 24 and upper(trim(unaccent(nome))) like 'TREZE DE MAIO'; 
update cidade set cod_tom = '8363' where uf = 24 and upper(trim(unaccent(nome))) like 'TREZE TILIAS'; 
update cidade set cod_tom = '8365' where uf = 24 and upper(trim(unaccent(nome))) like 'TROMBUDO CENTRAL'; 
update cidade set cod_tom = '8367' where uf = 24 and upper(trim(unaccent(nome))) like 'TUBARAO'; 
update cidade set cod_tom = '9991' where uf = 24 and upper(trim(unaccent(nome))) like 'TUNAPOLIS'; 
update cidade set cod_tom = '8369' where uf = 24 and upper(trim(unaccent(nome))) like 'TURVO'; 
update cidade set cod_tom = '9973' where uf = 24 and upper(trim(unaccent(nome))) like 'UNIAO DO OESTE'; 
update cidade set cod_tom = '8371' where uf = 24 and upper(trim(unaccent(nome))) like 'URUBICI'; 
update cidade set cod_tom = '9975' where uf = 24 and upper(trim(unaccent(nome))) like 'URUPEMA'; 
update cidade set cod_tom = '8373' where uf = 24 and upper(trim(unaccent(nome))) like 'URUSSANGA'; 
update cidade set cod_tom = '8375' where uf = 24 and upper(trim(unaccent(nome))) like 'VARGEAO'; 
update cidade set cod_tom = '5563' where uf = 24 and upper(trim(unaccent(nome))) like 'VARGEM'; 
update cidade set cod_tom = '5565' where uf = 24 and upper(trim(unaccent(nome))) like 'VARGEM BONITA'; 
update cidade set cod_tom = '8377' where uf = 24 and upper(trim(unaccent(nome))) like 'VIDAL RAMOS'; 
update cidade set cod_tom = '8379' where uf = 24 and upper(trim(unaccent(nome))) like 'VIDEIRA'; 
update cidade set cod_tom = '9977' where uf = 24 and upper(trim(unaccent(nome))) like 'VITOR MEIRELES'; 
update cidade set cod_tom = '8381' where uf = 24 and upper(trim(unaccent(nome))) like 'WITMARSUM'; 
update cidade set cod_tom = '8383' where uf = 24 and upper(trim(unaccent(nome))) like 'XANXERE'; 
update cidade set cod_tom = '8385' where uf = 24 and upper(trim(unaccent(nome))) like 'XAVANTINA'; 
update cidade set cod_tom = '8387' where uf = 24 and upper(trim(unaccent(nome))) like 'XAXIM'; 
update cidade set cod_tom = '0950' where uf = 24 and upper(trim(unaccent(nome))) like 'ZORTEA'; 
