update cidade set cod_tom = '0401' where uf = 14 and upper(trim(unaccent(nome))) like 'ABAETETUBA'; 
update cidade set cod_tom = '0375' where uf = 14 and upper(trim(unaccent(nome))) like 'ABEL FIGUEIREDO'; 
update cidade set cod_tom = '0403' where uf = 14 and upper(trim(unaccent(nome))) like 'ACARA'; 
update cidade set cod_tom = '0405' where uf = 14 and upper(trim(unaccent(nome))) like 'AFUA'; 
update cidade set cod_tom = '0383' where uf = 14 and upper(trim(unaccent(nome))) like 'AGUA AZUL DO NORTE'; 
update cidade set cod_tom = '0407' where uf = 14 and upper(trim(unaccent(nome))) like 'ALENQUER'; 
update cidade set cod_tom = '0409' where uf = 14 and upper(trim(unaccent(nome))) like 'ALMEIRIM'; 
update cidade set cod_tom = '0411' where uf = 14 and upper(trim(unaccent(nome))) like 'ALTAMIRA'; 
update cidade set cod_tom = '0413' where uf = 14 and upper(trim(unaccent(nome))) like 'ANAJAS'; 
update cidade set cod_tom = '0415' where uf = 14 and upper(trim(unaccent(nome))) like 'ANANINDEUA'; 
update cidade set cod_tom = '0040' where uf = 14 and upper(trim(unaccent(nome))) like 'ANAPU'; 
update cidade set cod_tom = '0417' where uf = 14 and upper(trim(unaccent(nome))) like 'AUGUSTO CORREA'; 
update cidade set cod_tom = '0389' where uf = 14 and upper(trim(unaccent(nome))) like 'AURORA DO PARA'; 
update cidade set cod_tom = '0419' where uf = 14 and upper(trim(unaccent(nome))) like 'AVEIRO'; 
update cidade set cod_tom = '0421' where uf = 14 and upper(trim(unaccent(nome))) like 'BAGRE'; 
update cidade set cod_tom = '0423' where uf = 14 and upper(trim(unaccent(nome))) like 'BAIAO'; 
update cidade set cod_tom = '0042' where uf = 14 and upper(trim(unaccent(nome))) like 'BANNACH'; 
update cidade set cod_tom = '0425' where uf = 14 and upper(trim(unaccent(nome))) like 'BARCARENA'; 
update cidade set cod_tom = '0427' where uf = 14 and upper(trim(unaccent(nome))) like 'BELEM'; 
update cidade set cod_tom = '0044' where uf = 14 and upper(trim(unaccent(nome))) like 'BELTERRA'; 
update cidade set cod_tom = '0429' where uf = 14 and upper(trim(unaccent(nome))) like 'BENEVIDES'; 
update cidade set cod_tom = '0575' where uf = 14 and upper(trim(unaccent(nome))) like 'BOM JESUS DO TOCANTINS'; 
update cidade set cod_tom = '0431' where uf = 14 and upper(trim(unaccent(nome))) like 'BONITO'; 
update cidade set cod_tom = '0433' where uf = 14 and upper(trim(unaccent(nome))) like 'BRAGANCA'; 
update cidade set cod_tom = '0639' where uf = 14 and upper(trim(unaccent(nome))) like 'BRASIL NOVO'; 
update cidade set cod_tom = '0577' where uf = 14 and upper(trim(unaccent(nome))) like 'BREJO GRANDE DO ARAGUAIA'; 
update cidade set cod_tom = '0625' where uf = 14 and upper(trim(unaccent(nome))) like 'BREU BRANCO'; 
update cidade set cod_tom = '0435' where uf = 14 and upper(trim(unaccent(nome))) like 'BREVES'; 
update cidade set cod_tom = '0437' where uf = 14 and upper(trim(unaccent(nome))) like 'BUJARU'; 
update cidade set cod_tom = '0439' where uf = 14 and upper(trim(unaccent(nome))) like 'CACHOEIRA DO ARARI'; 
update cidade set cod_tom = '0046' where uf = 14 and upper(trim(unaccent(nome))) like 'CACHOEIRA DO PIRIA'; 
update cidade set cod_tom = '0441' where uf = 14 and upper(trim(unaccent(nome))) like 'CAMETA'; 
update cidade set cod_tom = '0048' where uf = 14 and upper(trim(unaccent(nome))) like 'CANAA DOS CARAJAS'; 
update cidade set cod_tom = '0443' where uf = 14 and upper(trim(unaccent(nome))) like 'CAPANEMA'; 
update cidade set cod_tom = '0445' where uf = 14 and upper(trim(unaccent(nome))) like 'CAPITAO POCO'; 
update cidade set cod_tom = '0447' where uf = 14 and upper(trim(unaccent(nome))) like 'CASTANHAL'; 
update cidade set cod_tom = '0449' where uf = 14 and upper(trim(unaccent(nome))) like 'CHAVES'; 
update cidade set cod_tom = '0451' where uf = 14 and upper(trim(unaccent(nome))) like 'COLARES'; 
update cidade set cod_tom = '0453' where uf = 14 and upper(trim(unaccent(nome))) like 'CONCEICAO DO ARAGUAIA'; 
update cidade set cod_tom = '0579' where uf = 14 and upper(trim(unaccent(nome))) like 'CONCORDIA DO PARA'; 
update cidade set cod_tom = '0385' where uf = 14 and upper(trim(unaccent(nome))) like 'CUMARU DO NORTE'; 
update cidade set cod_tom = '0581' where uf = 14 and upper(trim(unaccent(nome))) like 'CURIONOPOLIS'; 
update cidade set cod_tom = '0455' where uf = 14 and upper(trim(unaccent(nome))) like 'CURRALINHO'; 
update cidade set cod_tom = '0050' where uf = 14 and upper(trim(unaccent(nome))) like 'CURUA'; 
update cidade set cod_tom = '0457' where uf = 14 and upper(trim(unaccent(nome))) like 'CURUCA'; 
update cidade set cod_tom = '0583' where uf = 14 and upper(trim(unaccent(nome))) like 'DOM ELISEU'; 
update cidade set cod_tom = '0377' where uf = 14 and upper(trim(unaccent(nome))) like 'ELDORADO DOS CARAJAS'; 
update cidade set cod_tom = '0459' where uf = 14 and upper(trim(unaccent(nome))) like 'FARO'; 
update cidade set cod_tom = '0052' where uf = 14 and upper(trim(unaccent(nome))) like 'FLORESTA DO ARAGUAIA'; 
update cidade set cod_tom = '0585' where uf = 14 and upper(trim(unaccent(nome))) like 'GARRAFAO DO NORTE'; 
update cidade set cod_tom = '0627' where uf = 14 and upper(trim(unaccent(nome))) like 'GOIANESIA DO PARA'; 
update cidade set cod_tom = '0461' where uf = 14 and upper(trim(unaccent(nome))) like 'GURUPA'; 
update cidade set cod_tom = '0463' where uf = 14 and upper(trim(unaccent(nome))) like 'IGARAPE-ACU'; 
update cidade set cod_tom = '0465' where uf = 14 and upper(trim(unaccent(nome))) like 'IGARAPE-MIRI'; 
update cidade set cod_tom = '0467' where uf = 14 and upper(trim(unaccent(nome))) like 'INHANGAPI'; 
update cidade set cod_tom = '0621' where uf = 14 and upper(trim(unaccent(nome))) like 'IPIXUNA DO PARA'; 
update cidade set cod_tom = '0469' where uf = 14 and upper(trim(unaccent(nome))) like 'IRITUIA'; 
update cidade set cod_tom = '0471' where uf = 14 and upper(trim(unaccent(nome))) like 'ITAITUBA'; 
update cidade set cod_tom = '0473' where uf = 14 and upper(trim(unaccent(nome))) like 'ITUPIRANGA'; 
update cidade set cod_tom = '0631' where uf = 14 and upper(trim(unaccent(nome))) like 'JACAREACANGA'; 
update cidade set cod_tom = '0475' where uf = 14 and upper(trim(unaccent(nome))) like 'JACUNDA'; 
update cidade set cod_tom = '0477' where uf = 14 and upper(trim(unaccent(nome))) like 'JURUTI'; 
update cidade set cod_tom = '0479' where uf = 14 and upper(trim(unaccent(nome))) like 'LIMOEIRO DO AJURU'; 
update cidade set cod_tom = '0587' where uf = 14 and upper(trim(unaccent(nome))) like 'MAE DO RIO'; 
update cidade set cod_tom = '0481' where uf = 14 and upper(trim(unaccent(nome))) like 'MAGALHAES BARATA'; 
update cidade set cod_tom = '0483' where uf = 14 and upper(trim(unaccent(nome))) like 'MARABA'; 
update cidade set cod_tom = '0485' where uf = 14 and upper(trim(unaccent(nome))) like 'MARACANA'; 
update cidade set cod_tom = '0487' where uf = 14 and upper(trim(unaccent(nome))) like 'MARAPANIM'; 
update cidade set cod_tom = '0054' where uf = 14 and upper(trim(unaccent(nome))) like 'MARITUBA'; 
update cidade set cod_tom = '0589' where uf = 14 and upper(trim(unaccent(nome))) like 'MEDICILANDIA'; 
update cidade set cod_tom = '0489' where uf = 14 and upper(trim(unaccent(nome))) like 'MELGACO'; 
update cidade set cod_tom = '0491' where uf = 14 and upper(trim(unaccent(nome))) like 'MOCAJUBA'; 
update cidade set cod_tom = '0493' where uf = 14 and upper(trim(unaccent(nome))) like 'MOJU'; 
update cidade set cod_tom = '0495' where uf = 14 and upper(trim(unaccent(nome))) like 'MONTE ALEGRE'; 
update cidade set cod_tom = '0497' where uf = 14 and upper(trim(unaccent(nome))) like 'MUANA'; 
update cidade set cod_tom = '0391' where uf = 14 and upper(trim(unaccent(nome))) like 'NOVA ESPERANCA DO PIRIA'; 
update cidade set cod_tom = '0056' where uf = 14 and upper(trim(unaccent(nome))) like 'NOVA IPIXUNA'; 
update cidade set cod_tom = '0499' where uf = 14 and upper(trim(unaccent(nome))) like 'NOVA TIMBOTEUA'; 
update cidade set cod_tom = '0633' where uf = 14 and upper(trim(unaccent(nome))) like 'NOVO PROGRESSO'; 
update cidade set cod_tom = '0629' where uf = 14 and upper(trim(unaccent(nome))) like 'NOVO REPARTIMENTO'; 
update cidade set cod_tom = '0501' where uf = 14 and upper(trim(unaccent(nome))) like 'OBIDOS'; 
update cidade set cod_tom = '0503' where uf = 14 and upper(trim(unaccent(nome))) like 'OEIRAS DO PARA'; 
update cidade set cod_tom = '0505' where uf = 14 and upper(trim(unaccent(nome))) like 'ORIXIMINA'; 
update cidade set cod_tom = '0507' where uf = 14 and upper(trim(unaccent(nome))) like 'OUREM'; 
update cidade set cod_tom = '0591' where uf = 14 and upper(trim(unaccent(nome))) like 'OURILANDIA DO NORTE'; 
update cidade set cod_tom = '0593' where uf = 14 and upper(trim(unaccent(nome))) like 'PACAJA'; 
update cidade set cod_tom = '0379' where uf = 14 and upper(trim(unaccent(nome))) like 'PALESTINA DO PARA'; 
update cidade set cod_tom = '0509' where uf = 14 and upper(trim(unaccent(nome))) like 'PARAGOMINAS'; 
update cidade set cod_tom = '0595' where uf = 14 and upper(trim(unaccent(nome))) like 'PARAUAPEBAS'; 
update cidade set cod_tom = '0387' where uf = 14 and upper(trim(unaccent(nome))) like 'PAU D`ARCO'; 
update cidade set cod_tom = '0511' where uf = 14 and upper(trim(unaccent(nome))) like 'PEIXE-BOI'; 
update cidade set cod_tom = '0058' where uf = 14 and upper(trim(unaccent(nome))) like 'PICARRA'; 
update cidade set cod_tom = '0060' where uf = 14 and upper(trim(unaccent(nome))) like 'PLACAS'; 
update cidade set cod_tom = '0513' where uf = 14 and upper(trim(unaccent(nome))) like 'PONTA DE PEDRAS'; 
update cidade set cod_tom = '0515' where uf = 14 and upper(trim(unaccent(nome))) like 'PORTEL'; 
update cidade set cod_tom = '0517' where uf = 14 and upper(trim(unaccent(nome))) like 'PORTO DE MOZ'; 
update cidade set cod_tom = '0' where uf = 14 and upper(trim(unaccent(nome))) like 'PORTO TROMBETA'; 
update cidade set cod_tom = '0519' where uf = 14 and upper(trim(unaccent(nome))) like 'PRAINHA'; 
update cidade set cod_tom = '0521' where uf = 14 and upper(trim(unaccent(nome))) like 'PRIMAVERA'; 
update cidade set cod_tom = '0062' where uf = 14 and upper(trim(unaccent(nome))) like 'QUATIPURU'; 
update cidade set cod_tom = '0567' where uf = 14 and upper(trim(unaccent(nome))) like 'REDENCAO'; 
update cidade set cod_tom = '0569' where uf = 14 and upper(trim(unaccent(nome))) like 'RIO MARIA'; 
update cidade set cod_tom = '0573' where uf = 14 and upper(trim(unaccent(nome))) like 'RONDON DO PARA'; 
update cidade set cod_tom = '0597' where uf = 14 and upper(trim(unaccent(nome))) like 'RUROPOLIS'; 
update cidade set cod_tom = '0523' where uf = 14 and upper(trim(unaccent(nome))) like 'SALINOPOLIS'; 
update cidade set cod_tom = '0525' where uf = 14 and upper(trim(unaccent(nome))) like 'SALVATERRA'; 
update cidade set cod_tom = '0369' where uf = 14 and upper(trim(unaccent(nome))) like 'SANTA BARBARA DO PARA'; 
update cidade set cod_tom = '0527' where uf = 14 and upper(trim(unaccent(nome))) like 'SANTA CRUZ DO ARARI'; 
update cidade set cod_tom = '0529' where uf = 14 and upper(trim(unaccent(nome))) like 'SANTA ISABEL DO PARA'; 
update cidade set cod_tom = '0371' where uf = 14 and upper(trim(unaccent(nome))) like 'SANTA LUZIA DO PARA'; 
update cidade set cod_tom = '0599' where uf = 14 and upper(trim(unaccent(nome))) like 'SANTA MARIA DAS BARREIRAS'; 
update cidade set cod_tom = '0531' where uf = 14 and upper(trim(unaccent(nome))) like 'SANTA MARIA DO PARA'; 
update cidade set cod_tom = '0533' where uf = 14 and upper(trim(unaccent(nome))) like 'SANTANA DO ARAGUAIA'; 
update cidade set cod_tom = '0535' where uf = 14 and upper(trim(unaccent(nome))) like 'SANTAREM'; 
update cidade set cod_tom = '0537' where uf = 14 and upper(trim(unaccent(nome))) like 'SANTAREM NOVO'; 
update cidade set cod_tom = '0539' where uf = 14 and upper(trim(unaccent(nome))) like 'SANTO ANTONIO DO TAUA'; 
update cidade set cod_tom = '0541' where uf = 14 and upper(trim(unaccent(nome))) like 'SAO CAETANO DE ODIVELAS'; 
update cidade set cod_tom = '0381' where uf = 14 and upper(trim(unaccent(nome))) like 'SAO DOMINGOS DO ARAGUAIA'; 
update cidade set cod_tom = '0543' where uf = 14 and upper(trim(unaccent(nome))) like 'SAO DOMINGOS DO CAPIM'; 
update cidade set cod_tom = '0545' where uf = 14 and upper(trim(unaccent(nome))) like 'SAO FELIX DO XINGU'; 
update cidade set cod_tom = '0547' where uf = 14 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO DO PARA'; 
update cidade set cod_tom = '0619' where uf = 14 and upper(trim(unaccent(nome))) like 'SAO GERALDO DO ARAGUAIA'; 
update cidade set cod_tom = '0064' where uf = 14 and upper(trim(unaccent(nome))) like 'SAO JOAO DA PONTA'; 
update cidade set cod_tom = '0393' where uf = 14 and upper(trim(unaccent(nome))) like 'SAO JOAO DE PIRABAS'; 
update cidade set cod_tom = '0549' where uf = 14 and upper(trim(unaccent(nome))) like 'SAO JOAO DO ARAGUAIA'; 
update cidade set cod_tom = '0551' where uf = 14 and upper(trim(unaccent(nome))) like 'SAO MIGUEL DO GUAMA'; 
update cidade set cod_tom = '0553' where uf = 14 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO DA BOA VISTA'; 
update cidade set cod_tom = '0066' where uf = 14 and upper(trim(unaccent(nome))) like 'SAPUCAIA'; 
update cidade set cod_tom = '0555' where uf = 14 and upper(trim(unaccent(nome))) like 'SENADOR JOSE PORFIRIO'; 
update cidade set cod_tom = '0557' where uf = 14 and upper(trim(unaccent(nome))) like 'SOURE'; 
update cidade set cod_tom = '0395' where uf = 14 and upper(trim(unaccent(nome))) like 'TAILANDIA'; 
update cidade set cod_tom = '0373' where uf = 14 and upper(trim(unaccent(nome))) like 'TERRA ALTA'; 
update cidade set cod_tom = '0637' where uf = 14 and upper(trim(unaccent(nome))) like 'TERRA SANTA'; 
update cidade set cod_tom = '0559' where uf = 14 and upper(trim(unaccent(nome))) like 'TOME-ACU'; 
update cidade set cod_tom = '0068' where uf = 14 and upper(trim(unaccent(nome))) like 'TRACUATEUA'; 
update cidade set cod_tom = '0635' where uf = 14 and upper(trim(unaccent(nome))) like 'TRAIRAO'; 
update cidade set cod_tom = '0397' where uf = 14 and upper(trim(unaccent(nome))) like 'TUCUMA'; 
update cidade set cod_tom = '0561' where uf = 14 and upper(trim(unaccent(nome))) like 'TUCURUI'; 
update cidade set cod_tom = '0623' where uf = 14 and upper(trim(unaccent(nome))) like 'ULIANOPOLIS'; 
update cidade set cod_tom = '0399' where uf = 14 and upper(trim(unaccent(nome))) like 'URUARA'; 
update cidade set cod_tom = '0563' where uf = 14 and upper(trim(unaccent(nome))) like 'VIGIA'; 
update cidade set cod_tom = '0565' where uf = 14 and upper(trim(unaccent(nome))) like 'VISEU'; 
update cidade set cod_tom = '0641' where uf = 14 and upper(trim(unaccent(nome))) like 'VITORIA DO XINGU'; 
update cidade set cod_tom = '0571' where uf = 14 and upper(trim(unaccent(nome))) like 'XINGUARA'; 
