update cidade set cod_tom = '2631' where uf = 16 and upper(trim(unaccent(nome))) like 'ABREU E LIMA'; 
update cidade set cod_tom = '2301' where uf = 16 and upper(trim(unaccent(nome))) like 'AFOGADOS DA INGAZEIRA'; 
update cidade set cod_tom = '2303' where uf = 16 and upper(trim(unaccent(nome))) like 'AFRANIO'; 
update cidade set cod_tom = '2305' where uf = 16 and upper(trim(unaccent(nome))) like 'AGRESTINA'; 
update cidade set cod_tom = '2307' where uf = 16 and upper(trim(unaccent(nome))) like 'AGUA PRETA'; 
update cidade set cod_tom = '2309' where uf = 16 and upper(trim(unaccent(nome))) like 'AGUAS BELAS'; 
update cidade set cod_tom = '2311' where uf = 16 and upper(trim(unaccent(nome))) like 'ALAGOINHA'; 
update cidade set cod_tom = '2313' where uf = 16 and upper(trim(unaccent(nome))) like 'ALIANCA'; 
update cidade set cod_tom = '2315' where uf = 16 and upper(trim(unaccent(nome))) like 'ALTINHO'; 
update cidade set cod_tom = '2317' where uf = 16 and upper(trim(unaccent(nome))) like 'AMARAJI'; 
update cidade set cod_tom = '2319' where uf = 16 and upper(trim(unaccent(nome))) like 'ANGELIM'; 
update cidade set cod_tom = '0544' where uf = 16 and upper(trim(unaccent(nome))) like 'ARACOIABA'; 
update cidade set cod_tom = '2321' where uf = 16 and upper(trim(unaccent(nome))) like 'ARARIPINA'; 
update cidade set cod_tom = '2323' where uf = 16 and upper(trim(unaccent(nome))) like 'ARCOVERDE'; 
update cidade set cod_tom = '2325' where uf = 16 and upper(trim(unaccent(nome))) like 'BARRA DE GUABIRABA'; 
update cidade set cod_tom = '2327' where uf = 16 and upper(trim(unaccent(nome))) like 'BARREIROS'; 
update cidade set cod_tom = '2329' where uf = 16 and upper(trim(unaccent(nome))) like 'BELEM DE MARIA'; 
update cidade set cod_tom = '2331' where uf = 16 and upper(trim(unaccent(nome))) like 'BELEM DE SAO FRANCISCO'; 
update cidade set cod_tom = '2333' where uf = 16 and upper(trim(unaccent(nome))) like 'BELO JARDIM'; 
update cidade set cod_tom = '2335' where uf = 16 and upper(trim(unaccent(nome))) like 'BETANIA'; 
update cidade set cod_tom = '2337' where uf = 16 and upper(trim(unaccent(nome))) like 'BEZERROS'; 
update cidade set cod_tom = '2339' where uf = 16 and upper(trim(unaccent(nome))) like 'BODOCO'; 
update cidade set cod_tom = '2341' where uf = 16 and upper(trim(unaccent(nome))) like 'BOM CONSELHO'; 
update cidade set cod_tom = '2343' where uf = 16 and upper(trim(unaccent(nome))) like 'BOM JARDIM'; 
update cidade set cod_tom = '2345' where uf = 16 and upper(trim(unaccent(nome))) like 'BONITO'; 
update cidade set cod_tom = '2347' where uf = 16 and upper(trim(unaccent(nome))) like 'BREJAO'; 
update cidade set cod_tom = '2349' where uf = 16 and upper(trim(unaccent(nome))) like 'BREJINHO'; 
update cidade set cod_tom = '2351' where uf = 16 and upper(trim(unaccent(nome))) like 'BREJO DA MADRE DE DEUS'; 
update cidade set cod_tom = '2353' where uf = 16 and upper(trim(unaccent(nome))) like 'BUENOS AIRES'; 
update cidade set cod_tom = '2355' where uf = 16 and upper(trim(unaccent(nome))) like 'BUIQUE'; 
update cidade set cod_tom = '2357' where uf = 16 and upper(trim(unaccent(nome))) like 'CABO DE SANTO AGOSTINHO'; 
update cidade set cod_tom = '2359' where uf = 16 and upper(trim(unaccent(nome))) like 'CABROBO'; 
update cidade set cod_tom = '2361' where uf = 16 and upper(trim(unaccent(nome))) like 'CACHOEIRINHA'; 
update cidade set cod_tom = '2363' where uf = 16 and upper(trim(unaccent(nome))) like 'CAETES'; 
update cidade set cod_tom = '2365' where uf = 16 and upper(trim(unaccent(nome))) like 'CALCADO'; 
update cidade set cod_tom = '2367' where uf = 16 and upper(trim(unaccent(nome))) like 'CALUMBI'; 
update cidade set cod_tom = '2629' where uf = 16 and upper(trim(unaccent(nome))) like 'CAMARAGIBE'; 
update cidade set cod_tom = '2369' where uf = 16 and upper(trim(unaccent(nome))) like 'CAMOCIM DE SAO FELIX'; 
update cidade set cod_tom = '2371' where uf = 16 and upper(trim(unaccent(nome))) like 'CAMUTANGA'; 
update cidade set cod_tom = '2373' where uf = 16 and upper(trim(unaccent(nome))) like 'CANHOTINHO'; 
update cidade set cod_tom = '2375' where uf = 16 and upper(trim(unaccent(nome))) like 'CAPOEIRAS'; 
update cidade set cod_tom = '2377' where uf = 16 and upper(trim(unaccent(nome))) like 'CARNAIBA'; 
update cidade set cod_tom = '2635' where uf = 16 and upper(trim(unaccent(nome))) like 'CARNAUBEIRA DA PENHA'; 
update cidade set cod_tom = '2379' where uf = 16 and upper(trim(unaccent(nome))) like 'CARPINA'; 
update cidade set cod_tom = '2381' where uf = 16 and upper(trim(unaccent(nome))) like 'CARUARU'; 
update cidade set cod_tom = '0546' where uf = 16 and upper(trim(unaccent(nome))) like 'CASINHAS'; 
update cidade set cod_tom = '2383' where uf = 16 and upper(trim(unaccent(nome))) like 'CATENDE'; 
update cidade set cod_tom = '2385' where uf = 16 and upper(trim(unaccent(nome))) like 'CEDRO'; 
update cidade set cod_tom = '2387' where uf = 16 and upper(trim(unaccent(nome))) like 'CHA DE ALEGRIA'; 
update cidade set cod_tom = '2389' where uf = 16 and upper(trim(unaccent(nome))) like 'CHA GRANDE'; 
update cidade set cod_tom = '2391' where uf = 16 and upper(trim(unaccent(nome))) like 'CONDADO'; 
update cidade set cod_tom = '2393' where uf = 16 and upper(trim(unaccent(nome))) like 'CORRENTES'; 
update cidade set cod_tom = '2395' where uf = 16 and upper(trim(unaccent(nome))) like 'CORTES'; 
update cidade set cod_tom = '2397' where uf = 16 and upper(trim(unaccent(nome))) like 'CUMARU'; 
update cidade set cod_tom = '2399' where uf = 16 and upper(trim(unaccent(nome))) like 'CUPIRA'; 
update cidade set cod_tom = '2401' where uf = 16 and upper(trim(unaccent(nome))) like 'CUSTODIA'; 
update cidade set cod_tom = '2299' where uf = 16 and upper(trim(unaccent(nome))) like 'DORMENTES'; 
update cidade set cod_tom = '2403' where uf = 16 and upper(trim(unaccent(nome))) like 'ESCADA'; 
update cidade set cod_tom = '2405' where uf = 16 and upper(trim(unaccent(nome))) like 'EXU'; 
update cidade set cod_tom = '2407' where uf = 16 and upper(trim(unaccent(nome))) like 'FEIRA NOVA'; 
update cidade set cod_tom = '3001' where uf = 16 and upper(trim(unaccent(nome))) like 'FERNANDO DE NORONHA'; 
update cidade set cod_tom = '2409' where uf = 16 and upper(trim(unaccent(nome))) like 'FERREIROS'; 
update cidade set cod_tom = '2411' where uf = 16 and upper(trim(unaccent(nome))) like 'FLORES'; 
update cidade set cod_tom = '2413' where uf = 16 and upper(trim(unaccent(nome))) like 'FLORESTA'; 
update cidade set cod_tom = '2415' where uf = 16 and upper(trim(unaccent(nome))) like 'FREI MIGUELINHO'; 
update cidade set cod_tom = '2417' where uf = 16 and upper(trim(unaccent(nome))) like 'GAMELEIRA'; 
update cidade set cod_tom = '2419' where uf = 16 and upper(trim(unaccent(nome))) like 'GARANHUNS'; 
update cidade set cod_tom = '2421' where uf = 16 and upper(trim(unaccent(nome))) like 'GLORIA DO GOITA'; 
update cidade set cod_tom = '2423' where uf = 16 and upper(trim(unaccent(nome))) like 'GOIANA'; 
update cidade set cod_tom = '2425' where uf = 16 and upper(trim(unaccent(nome))) like 'GRANITO'; 
update cidade set cod_tom = '2427' where uf = 16 and upper(trim(unaccent(nome))) like 'GRAVATA'; 
update cidade set cod_tom = '2429' where uf = 16 and upper(trim(unaccent(nome))) like 'IATI'; 
update cidade set cod_tom = '2431' where uf = 16 and upper(trim(unaccent(nome))) like 'IBIMIRIM'; 
update cidade set cod_tom = '2433' where uf = 16 and upper(trim(unaccent(nome))) like 'IBIRAJUBA'; 
update cidade set cod_tom = '2435' where uf = 16 and upper(trim(unaccent(nome))) like 'IGARASSU'; 
update cidade set cod_tom = '2437' where uf = 16 and upper(trim(unaccent(nome))) like 'IGUARACI'; 
update cidade set cod_tom = '2451' where uf = 16 and upper(trim(unaccent(nome))) like 'ILHA DE ITAMARACA'; 
update cidade set cod_tom = '2439' where uf = 16 and upper(trim(unaccent(nome))) like 'INAJA'; 
update cidade set cod_tom = '2441' where uf = 16 and upper(trim(unaccent(nome))) like 'INGAZEIRA'; 
update cidade set cod_tom = '2443' where uf = 16 and upper(trim(unaccent(nome))) like 'IPOJUCA'; 
update cidade set cod_tom = '2445' where uf = 16 and upper(trim(unaccent(nome))) like 'IPUBI'; 
update cidade set cod_tom = '2447' where uf = 16 and upper(trim(unaccent(nome))) like 'ITACURUBA'; 
update cidade set cod_tom = '2449' where uf = 16 and upper(trim(unaccent(nome))) like 'ITAIBA'; 
update cidade set cod_tom = '2597' where uf = 16 and upper(trim(unaccent(nome))) like 'ITAMBE'; 
update cidade set cod_tom = '2453' where uf = 16 and upper(trim(unaccent(nome))) like 'ITAPETIM'; 
update cidade set cod_tom = '2633' where uf = 16 and upper(trim(unaccent(nome))) like 'ITAPISSUMA'; 
update cidade set cod_tom = '2455' where uf = 16 and upper(trim(unaccent(nome))) like 'ITAQUITINGA'; 
update cidade set cod_tom = '2457' where uf = 16 and upper(trim(unaccent(nome))) like 'JABOATAO DOS GUARARAPES'; 
update cidade set cod_tom = '0548' where uf = 16 and upper(trim(unaccent(nome))) like 'JAQUEIRA'; 
update cidade set cod_tom = '2459' where uf = 16 and upper(trim(unaccent(nome))) like 'JATAUBA'; 
update cidade set cod_tom = '0550' where uf = 16 and upper(trim(unaccent(nome))) like 'JATOBA'; 
update cidade set cod_tom = '2461' where uf = 16 and upper(trim(unaccent(nome))) like 'JOAO ALFREDO'; 
update cidade set cod_tom = '2463' where uf = 16 and upper(trim(unaccent(nome))) like 'JOAQUIM NABUCO'; 
update cidade set cod_tom = '2295' where uf = 16 and upper(trim(unaccent(nome))) like 'JUCATI'; 
update cidade set cod_tom = '2465' where uf = 16 and upper(trim(unaccent(nome))) like 'JUPI'; 
update cidade set cod_tom = '2467' where uf = 16 and upper(trim(unaccent(nome))) like 'JUREMA'; 
update cidade set cod_tom = '2289' where uf = 16 and upper(trim(unaccent(nome))) like 'LAGOA DO CARRO'; 
update cidade set cod_tom = '2469' where uf = 16 and upper(trim(unaccent(nome))) like 'LAGOA DO ITAENGA'; 
update cidade set cod_tom = '2471' where uf = 16 and upper(trim(unaccent(nome))) like 'LAGOA DO OURO'; 
update cidade set cod_tom = '2473' where uf = 16 and upper(trim(unaccent(nome))) like 'LAGOA DOS GATOS'; 
update cidade set cod_tom = '0552' where uf = 16 and upper(trim(unaccent(nome))) like 'LAGOA GRANDE'; 
update cidade set cod_tom = '2475' where uf = 16 and upper(trim(unaccent(nome))) like 'LAJEDO'; 
update cidade set cod_tom = '2477' where uf = 16 and upper(trim(unaccent(nome))) like 'LIMOEIRO'; 
update cidade set cod_tom = '2479' where uf = 16 and upper(trim(unaccent(nome))) like 'MACAPARANA'; 
update cidade set cod_tom = '2481' where uf = 16 and upper(trim(unaccent(nome))) like 'MACHADOS'; 
update cidade set cod_tom = '0554' where uf = 16 and upper(trim(unaccent(nome))) like 'MANARI'; 
update cidade set cod_tom = '2483' where uf = 16 and upper(trim(unaccent(nome))) like 'MARAIAL'; 
update cidade set cod_tom = '2485' where uf = 16 and upper(trim(unaccent(nome))) like 'MIRANDIBA'; 
update cidade set cod_tom = '2585' where uf = 16 and upper(trim(unaccent(nome))) like 'MOREILANDIA'; 
update cidade set cod_tom = '2487' where uf = 16 and upper(trim(unaccent(nome))) like 'MORENO'; 
update cidade set cod_tom = '2489' where uf = 16 and upper(trim(unaccent(nome))) like 'NAZARE DA MATA'; 
update cidade set cod_tom = '2491' where uf = 16 and upper(trim(unaccent(nome))) like 'OLINDA'; 
update cidade set cod_tom = '2493' where uf = 16 and upper(trim(unaccent(nome))) like 'OROBO'; 
update cidade set cod_tom = '2495' where uf = 16 and upper(trim(unaccent(nome))) like 'OROCO'; 
update cidade set cod_tom = '2497' where uf = 16 and upper(trim(unaccent(nome))) like 'OURICURI'; 
update cidade set cod_tom = '2499' where uf = 16 and upper(trim(unaccent(nome))) like 'PALMARES'; 
update cidade set cod_tom = '2501' where uf = 16 and upper(trim(unaccent(nome))) like 'PALMEIRINA'; 
update cidade set cod_tom = '2503' where uf = 16 and upper(trim(unaccent(nome))) like 'PANELAS'; 
update cidade set cod_tom = '2505' where uf = 16 and upper(trim(unaccent(nome))) like 'PARANATAMA'; 
update cidade set cod_tom = '2507' where uf = 16 and upper(trim(unaccent(nome))) like 'PARNAMIRIM'; 
update cidade set cod_tom = '2509' where uf = 16 and upper(trim(unaccent(nome))) like 'PASSIRA'; 
update cidade set cod_tom = '2511' where uf = 16 and upper(trim(unaccent(nome))) like 'PAUDALHO'; 
update cidade set cod_tom = '2513' where uf = 16 and upper(trim(unaccent(nome))) like 'PAULISTA'; 
update cidade set cod_tom = '2515' where uf = 16 and upper(trim(unaccent(nome))) like 'PEDRA'; 
update cidade set cod_tom = '2517' where uf = 16 and upper(trim(unaccent(nome))) like 'PESQUEIRA'; 
update cidade set cod_tom = '2519' where uf = 16 and upper(trim(unaccent(nome))) like 'PETROLANDIA'; 
update cidade set cod_tom = '2521' where uf = 16 and upper(trim(unaccent(nome))) like 'PETROLINA'; 
update cidade set cod_tom = '2523' where uf = 16 and upper(trim(unaccent(nome))) like 'POCAO'; 
update cidade set cod_tom = '2525' where uf = 16 and upper(trim(unaccent(nome))) like 'POMBOS'; 
update cidade set cod_tom = '2527' where uf = 16 and upper(trim(unaccent(nome))) like 'PRIMAVERA'; 
update cidade set cod_tom = '2529' where uf = 16 and upper(trim(unaccent(nome))) like 'QUIPAPA'; 
update cidade set cod_tom = '2637' where uf = 16 and upper(trim(unaccent(nome))) like 'QUIXABA'; 
update cidade set cod_tom = '2531' where uf = 16 and upper(trim(unaccent(nome))) like 'RECIFE'; 
update cidade set cod_tom = '2533' where uf = 16 and upper(trim(unaccent(nome))) like 'RIACHO DAS ALMAS'; 
update cidade set cod_tom = '2535' where uf = 16 and upper(trim(unaccent(nome))) like 'RIBEIRAO'; 
update cidade set cod_tom = '2537' where uf = 16 and upper(trim(unaccent(nome))) like 'RIO FORMOSO'; 
update cidade set cod_tom = '2539' where uf = 16 and upper(trim(unaccent(nome))) like 'SAIRE'; 
update cidade set cod_tom = '2541' where uf = 16 and upper(trim(unaccent(nome))) like 'SALGADINHO'; 
update cidade set cod_tom = '2543' where uf = 16 and upper(trim(unaccent(nome))) like 'SALGUEIRO'; 
update cidade set cod_tom = '2545' where uf = 16 and upper(trim(unaccent(nome))) like 'SALOA'; 
update cidade set cod_tom = '2547' where uf = 16 and upper(trim(unaccent(nome))) like 'SANHARO'; 
update cidade set cod_tom = '2297' where uf = 16 and upper(trim(unaccent(nome))) like 'SANTA CRUZ'; 
update cidade set cod_tom = '2639' where uf = 16 and upper(trim(unaccent(nome))) like 'SANTA CRUZ DA BAIXA VERDE'; 
update cidade set cod_tom = '2549' where uf = 16 and upper(trim(unaccent(nome))) like 'SANTA CRUZ DO CAPIBARIBE'; 
update cidade set cod_tom = '0556' where uf = 16 and upper(trim(unaccent(nome))) like 'SANTA FILOMENA'; 
update cidade set cod_tom = '2551' where uf = 16 and upper(trim(unaccent(nome))) like 'SANTA MARIA DA BOA VISTA'; 
update cidade set cod_tom = '2553' where uf = 16 and upper(trim(unaccent(nome))) like 'SANTA MARIA DO CAMBUCA'; 
update cidade set cod_tom = '2555' where uf = 16 and upper(trim(unaccent(nome))) like 'SANTA TEREZINHA'; 
update cidade set cod_tom = '2557' where uf = 16 and upper(trim(unaccent(nome))) like 'SAO BENEDITO DO SUL'; 
update cidade set cod_tom = '2559' where uf = 16 and upper(trim(unaccent(nome))) like 'SAO BENTO DO UNA'; 
update cidade set cod_tom = '2561' where uf = 16 and upper(trim(unaccent(nome))) like 'SAO CAITANO'; 
update cidade set cod_tom = '2563' where uf = 16 and upper(trim(unaccent(nome))) like 'SAO JOAO'; 
update cidade set cod_tom = '2565' where uf = 16 and upper(trim(unaccent(nome))) like 'SAO JOAQUIM DO MONTE'; 
update cidade set cod_tom = '2567' where uf = 16 and upper(trim(unaccent(nome))) like 'SAO JOSE DA COROA GRANDE'; 
update cidade set cod_tom = '2569' where uf = 16 and upper(trim(unaccent(nome))) like 'SAO JOSE DO BELMONTE'; 
update cidade set cod_tom = '2571' where uf = 16 and upper(trim(unaccent(nome))) like 'SAO JOSE DO EGITO'; 
update cidade set cod_tom = '2573' where uf = 16 and upper(trim(unaccent(nome))) like 'SAO LOURENCO DA MATA'; 
update cidade set cod_tom = '2575' where uf = 16 and upper(trim(unaccent(nome))) like 'SAO VICENTE FERRER'; 
update cidade set cod_tom = '2577' where uf = 16 and upper(trim(unaccent(nome))) like 'SERRA TALHADA'; 
update cidade set cod_tom = '2579' where uf = 16 and upper(trim(unaccent(nome))) like 'SERRITA'; 
update cidade set cod_tom = '2581' where uf = 16 and upper(trim(unaccent(nome))) like 'SERTANIA'; 
update cidade set cod_tom = '2583' where uf = 16 and upper(trim(unaccent(nome))) like 'SIRINHAEM'; 
update cidade set cod_tom = '0' where uf = 16 and upper(trim(unaccent(nome))) like 'SITIO DOS MOREIRAS'; 
update cidade set cod_tom = '2587' where uf = 16 and upper(trim(unaccent(nome))) like 'SOLIDAO'; 
update cidade set cod_tom = '2589' where uf = 16 and upper(trim(unaccent(nome))) like 'SURUBIM'; 
update cidade set cod_tom = '2591' where uf = 16 and upper(trim(unaccent(nome))) like 'TABIRA'; 
update cidade set cod_tom = '2593' where uf = 16 and upper(trim(unaccent(nome))) like 'TACAIMBO'; 
update cidade set cod_tom = '2595' where uf = 16 and upper(trim(unaccent(nome))) like 'TACARATU'; 
update cidade set cod_tom = '0558' where uf = 16 and upper(trim(unaccent(nome))) like 'TAMANDARE'; 
update cidade set cod_tom = '2599' where uf = 16 and upper(trim(unaccent(nome))) like 'TAQUARITINGA DO NORTE'; 
update cidade set cod_tom = '2601' where uf = 16 and upper(trim(unaccent(nome))) like 'TEREZINHA'; 
update cidade set cod_tom = '2603' where uf = 16 and upper(trim(unaccent(nome))) like 'TERRA NOVA'; 
update cidade set cod_tom = '2605' where uf = 16 and upper(trim(unaccent(nome))) like 'TIMBAUBA'; 
update cidade set cod_tom = '2607' where uf = 16 and upper(trim(unaccent(nome))) like 'TORITAMA'; 
update cidade set cod_tom = '2609' where uf = 16 and upper(trim(unaccent(nome))) like 'TRACUNHAEM'; 
update cidade set cod_tom = '2611' where uf = 16 and upper(trim(unaccent(nome))) like 'TRINDADE'; 
update cidade set cod_tom = '2613' where uf = 16 and upper(trim(unaccent(nome))) like 'TRIUNFO'; 
update cidade set cod_tom = '2615' where uf = 16 and upper(trim(unaccent(nome))) like 'TUPANATINGA'; 
update cidade set cod_tom = '2617' where uf = 16 and upper(trim(unaccent(nome))) like 'TUPARETAMA'; 
update cidade set cod_tom = '2619' where uf = 16 and upper(trim(unaccent(nome))) like 'VENTUROSA'; 
update cidade set cod_tom = '2621' where uf = 16 and upper(trim(unaccent(nome))) like 'VERDEJANTE'; 
update cidade set cod_tom = '2291' where uf = 16 and upper(trim(unaccent(nome))) like 'VERTENTE DO LERIO'; 
update cidade set cod_tom = '2623' where uf = 16 and upper(trim(unaccent(nome))) like 'VERTENTES'; 
update cidade set cod_tom = '2625' where uf = 16 and upper(trim(unaccent(nome))) like 'VICENCIA'; 
update cidade set cod_tom = '2627' where uf = 16 and upper(trim(unaccent(nome))) like 'VITORIA DE SANTO ANTAO'; 
update cidade set cod_tom = '2293' where uf = 16 and upper(trim(unaccent(nome))) like 'XEXEU'; 
