update cidade set cod_tom = '1301' where uf = 6 and upper(trim(unaccent(nome))) like 'ABAIARA'; 
update cidade set cod_tom = '1231' where uf = 6 and upper(trim(unaccent(nome))) like 'ACARAPE'; 
update cidade set cod_tom = '1303' where uf = 6 and upper(trim(unaccent(nome))) like 'ACARAU'; 
update cidade set cod_tom = '1305' where uf = 6 and upper(trim(unaccent(nome))) like 'ACOPIARA'; 
update cidade set cod_tom = '1307' where uf = 6 and upper(trim(unaccent(nome))) like 'AIUABA'; 
update cidade set cod_tom = '1309' where uf = 6 and upper(trim(unaccent(nome))) like 'ALCANTARAS'; 
update cidade set cod_tom = '1311' where uf = 6 and upper(trim(unaccent(nome))) like 'ALTANEIRA'; 
update cidade set cod_tom = '1313' where uf = 6 and upper(trim(unaccent(nome))) like 'ALTO SANTO'; 
update cidade set cod_tom = '1587' where uf = 6 and upper(trim(unaccent(nome))) like 'AMONTADA'; 
update cidade set cod_tom = '1315' where uf = 6 and upper(trim(unaccent(nome))) like 'ANTONINA DO NORTE'; 
update cidade set cod_tom = '1317' where uf = 6 and upper(trim(unaccent(nome))) like 'APUIARES'; 
update cidade set cod_tom = '1319' where uf = 6 and upper(trim(unaccent(nome))) like 'AQUIRAZ'; 
update cidade set cod_tom = '1321' where uf = 6 and upper(trim(unaccent(nome))) like 'ARACATI'; 
update cidade set cod_tom = '1323' where uf = 6 and upper(trim(unaccent(nome))) like 'ARACOIABA'; 
update cidade set cod_tom = '0989' where uf = 6 and upper(trim(unaccent(nome))) like 'ARARENDA'; 
update cidade set cod_tom = '1325' where uf = 6 and upper(trim(unaccent(nome))) like 'ARARIPE'; 
update cidade set cod_tom = '1327' where uf = 6 and upper(trim(unaccent(nome))) like 'ARATUBA'; 
update cidade set cod_tom = '1329' where uf = 6 and upper(trim(unaccent(nome))) like 'ARNEIROZ'; 
update cidade set cod_tom = '1331' where uf = 6 and upper(trim(unaccent(nome))) like 'ASSARE'; 
update cidade set cod_tom = '1333' where uf = 6 and upper(trim(unaccent(nome))) like 'AURORA'; 
update cidade set cod_tom = '1335' where uf = 6 and upper(trim(unaccent(nome))) like 'BAIXIO'; 
update cidade set cod_tom = '1233' where uf = 6 and upper(trim(unaccent(nome))) like 'BANABUIU'; 
update cidade set cod_tom = '1337' where uf = 6 and upper(trim(unaccent(nome))) like 'BARBALHA'; 
update cidade set cod_tom = '1235' where uf = 6 and upper(trim(unaccent(nome))) like 'BARREIRA'; 
update cidade set cod_tom = '1339' where uf = 6 and upper(trim(unaccent(nome))) like 'BARRO'; 
update cidade set cod_tom = '1237' where uf = 6 and upper(trim(unaccent(nome))) like 'BARROQUINHA'; 
update cidade set cod_tom = '1341' where uf = 6 and upper(trim(unaccent(nome))) like 'BATURITE'; 
update cidade set cod_tom = '1343' where uf = 6 and upper(trim(unaccent(nome))) like 'BEBERIBE'; 
update cidade set cod_tom = '1345' where uf = 6 and upper(trim(unaccent(nome))) like 'BELA CRUZ'; 
update cidade set cod_tom = '1347' where uf = 6 and upper(trim(unaccent(nome))) like 'BOA VIAGEM'; 
update cidade set cod_tom = '1349' where uf = 6 and upper(trim(unaccent(nome))) like 'BREJO SANTO'; 
update cidade set cod_tom = '1351' where uf = 6 and upper(trim(unaccent(nome))) like 'CAMOCIM'; 
update cidade set cod_tom = '1353' where uf = 6 and upper(trim(unaccent(nome))) like 'CAMPOS SALES'; 
update cidade set cod_tom = '1355' where uf = 6 and upper(trim(unaccent(nome))) like 'CANINDE'; 
update cidade set cod_tom = '1357' where uf = 6 and upper(trim(unaccent(nome))) like 'CAPISTRANO'; 
update cidade set cod_tom = '1359' where uf = 6 and upper(trim(unaccent(nome))) like 'CARIDADE'; 
update cidade set cod_tom = '1361' where uf = 6 and upper(trim(unaccent(nome))) like 'CARIRE'; 
update cidade set cod_tom = '1363' where uf = 6 and upper(trim(unaccent(nome))) like 'CARIRIACU'; 
update cidade set cod_tom = '1365' where uf = 6 and upper(trim(unaccent(nome))) like 'CARIUS'; 
update cidade set cod_tom = '1367' where uf = 6 and upper(trim(unaccent(nome))) like 'CARNAUBAL'; 
update cidade set cod_tom = '1369' where uf = 6 and upper(trim(unaccent(nome))) like 'CASCAVEL'; 
update cidade set cod_tom = '1371' where uf = 6 and upper(trim(unaccent(nome))) like 'CATARINA'; 
update cidade set cod_tom = '0983' where uf = 6 and upper(trim(unaccent(nome))) like 'CATUNDA'; 
update cidade set cod_tom = '1373' where uf = 6 and upper(trim(unaccent(nome))) like 'CAUCAIA'; 
update cidade set cod_tom = '1375' where uf = 6 and upper(trim(unaccent(nome))) like 'CEDRO'; 
update cidade set cod_tom = '1377' where uf = 6 and upper(trim(unaccent(nome))) like 'CHAVAL'; 
update cidade set cod_tom = '0993' where uf = 6 and upper(trim(unaccent(nome))) like 'CHORO'; 
update cidade set cod_tom = '1239' where uf = 6 and upper(trim(unaccent(nome))) like 'CHOROZINHO'; 
update cidade set cod_tom = '1381' where uf = 6 and upper(trim(unaccent(nome))) like 'COREAU'; 
update cidade set cod_tom = '1383' where uf = 6 and upper(trim(unaccent(nome))) like 'CRATEUS'; 
update cidade set cod_tom = '1385' where uf = 6 and upper(trim(unaccent(nome))) like 'CRATO'; 
update cidade set cod_tom = '1241' where uf = 6 and upper(trim(unaccent(nome))) like 'CROATA'; 
update cidade set cod_tom = '1589' where uf = 6 and upper(trim(unaccent(nome))) like 'CRUZ'; 
update cidade set cod_tom = '1243' where uf = 6 and upper(trim(unaccent(nome))) like 'DEPUTADO IRAPUAN PINHEIRO'; 
update cidade set cod_tom = '1245' where uf = 6 and upper(trim(unaccent(nome))) like 'ERERE'; 
update cidade set cod_tom = '1247' where uf = 6 and upper(trim(unaccent(nome))) like 'EUSEBIO'; 
update cidade set cod_tom = '1387' where uf = 6 and upper(trim(unaccent(nome))) like 'FARIAS BRITO'; 
update cidade set cod_tom = '1591' where uf = 6 and upper(trim(unaccent(nome))) like 'FORQUILHA'; 
update cidade set cod_tom = '1389' where uf = 6 and upper(trim(unaccent(nome))) like 'FORTALEZA'; 
update cidade set cod_tom = '0987' where uf = 6 and upper(trim(unaccent(nome))) like 'FORTIM'; 
update cidade set cod_tom = '1391' where uf = 6 and upper(trim(unaccent(nome))) like 'FRECHEIRINHA'; 
update cidade set cod_tom = '1393' where uf = 6 and upper(trim(unaccent(nome))) like 'GENERAL SAMPAIO'; 
update cidade set cod_tom = '1249' where uf = 6 and upper(trim(unaccent(nome))) like 'GRACA'; 
update cidade set cod_tom = '1395' where uf = 6 and upper(trim(unaccent(nome))) like 'GRANJA'; 
update cidade set cod_tom = '1397' where uf = 6 and upper(trim(unaccent(nome))) like 'GRANJEIRO'; 
update cidade set cod_tom = '1399' where uf = 6 and upper(trim(unaccent(nome))) like 'GROAIRAS'; 
update cidade set cod_tom = '1251' where uf = 6 and upper(trim(unaccent(nome))) like 'GUAIUBA'; 
update cidade set cod_tom = '1401' where uf = 6 and upper(trim(unaccent(nome))) like 'GUARACIABA DO NORTE'; 
update cidade set cod_tom = '1403' where uf = 6 and upper(trim(unaccent(nome))) like 'GUARAMIRANGA'; 
update cidade set cod_tom = '1405' where uf = 6 and upper(trim(unaccent(nome))) like 'HIDROLANDIA'; 
update cidade set cod_tom = '1253' where uf = 6 and upper(trim(unaccent(nome))) like 'HORIZONTE'; 
update cidade set cod_tom = '1255' where uf = 6 and upper(trim(unaccent(nome))) like 'IBARETAMA'; 
update cidade set cod_tom = '1407' where uf = 6 and upper(trim(unaccent(nome))) like 'IBIAPINA'; 
update cidade set cod_tom = '1257' where uf = 6 and upper(trim(unaccent(nome))) like 'IBICUITINGA'; 
update cidade set cod_tom = '1593' where uf = 6 and upper(trim(unaccent(nome))) like 'ICAPUI'; 
update cidade set cod_tom = '1409' where uf = 6 and upper(trim(unaccent(nome))) like 'ICO'; 
update cidade set cod_tom = '1411' where uf = 6 and upper(trim(unaccent(nome))) like 'IGUATU'; 
update cidade set cod_tom = '1413' where uf = 6 and upper(trim(unaccent(nome))) like 'INDEPENDENCIA'; 
update cidade set cod_tom = '1259' where uf = 6 and upper(trim(unaccent(nome))) like 'IPAPORANGA'; 
update cidade set cod_tom = '1415' where uf = 6 and upper(trim(unaccent(nome))) like 'IPAUMIRIM'; 
update cidade set cod_tom = '1417' where uf = 6 and upper(trim(unaccent(nome))) like 'IPU'; 
update cidade set cod_tom = '1419' where uf = 6 and upper(trim(unaccent(nome))) like 'IPUEIRAS'; 
update cidade set cod_tom = '1421' where uf = 6 and upper(trim(unaccent(nome))) like 'IRACEMA'; 
update cidade set cod_tom = '1423' where uf = 6 and upper(trim(unaccent(nome))) like 'IRAUCUBA'; 
update cidade set cod_tom = '1425' where uf = 6 and upper(trim(unaccent(nome))) like 'ITAICABA'; 
update cidade set cod_tom = '0991' where uf = 6 and upper(trim(unaccent(nome))) like 'ITAITINGA'; 
update cidade set cod_tom = '1427' where uf = 6 and upper(trim(unaccent(nome))) like 'ITAPAGE'; 
update cidade set cod_tom = '1429' where uf = 6 and upper(trim(unaccent(nome))) like 'ITAPIPOCA'; 
update cidade set cod_tom = '1431' where uf = 6 and upper(trim(unaccent(nome))) like 'ITAPIUNA'; 
update cidade set cod_tom = '1595' where uf = 6 and upper(trim(unaccent(nome))) like 'ITAREMA'; 
update cidade set cod_tom = '1433' where uf = 6 and upper(trim(unaccent(nome))) like 'ITATIRA'; 
update cidade set cod_tom = '1435' where uf = 6 and upper(trim(unaccent(nome))) like 'JAGUARETAMA'; 
update cidade set cod_tom = '1437' where uf = 6 and upper(trim(unaccent(nome))) like 'JAGUARIBARA'; 
update cidade set cod_tom = '1439' where uf = 6 and upper(trim(unaccent(nome))) like 'JAGUARIBE'; 
update cidade set cod_tom = '1441' where uf = 6 and upper(trim(unaccent(nome))) like 'JAGUARUANA'; 
update cidade set cod_tom = '1443' where uf = 6 and upper(trim(unaccent(nome))) like 'JARDIM'; 
update cidade set cod_tom = '1445' where uf = 6 and upper(trim(unaccent(nome))) like 'JATI'; 
update cidade set cod_tom = '0985' where uf = 6 and upper(trim(unaccent(nome))) like 'JIJOCA DE JERICOACOARA'; 
update cidade set cod_tom = '1447' where uf = 6 and upper(trim(unaccent(nome))) like 'JUAZEIRO DO NORTE'; 
update cidade set cod_tom = '1449' where uf = 6 and upper(trim(unaccent(nome))) like 'JUCAS'; 
update cidade set cod_tom = '1451' where uf = 6 and upper(trim(unaccent(nome))) like 'LAVRAS DA MANGABEIRA'; 
update cidade set cod_tom = '1453' where uf = 6 and upper(trim(unaccent(nome))) like 'LIMOEIRO DO NORTE'; 
update cidade set cod_tom = '1261' where uf = 6 and upper(trim(unaccent(nome))) like 'MADALENA'; 
update cidade set cod_tom = '1585' where uf = 6 and upper(trim(unaccent(nome))) like 'MARACANAU'; 
update cidade set cod_tom = '1455' where uf = 6 and upper(trim(unaccent(nome))) like 'MARANGUAPE'; 
update cidade set cod_tom = '1457' where uf = 6 and upper(trim(unaccent(nome))) like 'MARCO'; 
update cidade set cod_tom = '1459' where uf = 6 and upper(trim(unaccent(nome))) like 'MARTINOPOLE'; 
update cidade set cod_tom = '1461' where uf = 6 and upper(trim(unaccent(nome))) like 'MASSAPE'; 
update cidade set cod_tom = '1463' where uf = 6 and upper(trim(unaccent(nome))) like 'MAURITI'; 
update cidade set cod_tom = '1465' where uf = 6 and upper(trim(unaccent(nome))) like 'MERUOCA'; 
update cidade set cod_tom = '1467' where uf = 6 and upper(trim(unaccent(nome))) like 'MILAGRES'; 
update cidade set cod_tom = '1597' where uf = 6 and upper(trim(unaccent(nome))) like 'MILHA'; 
update cidade set cod_tom = '1263' where uf = 6 and upper(trim(unaccent(nome))) like 'MIRAIMA'; 
update cidade set cod_tom = '1469' where uf = 6 and upper(trim(unaccent(nome))) like 'MISSAO VELHA'; 
update cidade set cod_tom = '1471' where uf = 6 and upper(trim(unaccent(nome))) like 'MOMBACA'; 
update cidade set cod_tom = '1473' where uf = 6 and upper(trim(unaccent(nome))) like 'MONSENHOR TABOSA'; 
update cidade set cod_tom = '1475' where uf = 6 and upper(trim(unaccent(nome))) like 'MORADA NOVA'; 
update cidade set cod_tom = '1477' where uf = 6 and upper(trim(unaccent(nome))) like 'MORAUJO'; 
update cidade set cod_tom = '1479' where uf = 6 and upper(trim(unaccent(nome))) like 'MORRINHOS'; 
update cidade set cod_tom = '1481' where uf = 6 and upper(trim(unaccent(nome))) like 'MUCAMBO'; 
update cidade set cod_tom = '1483' where uf = 6 and upper(trim(unaccent(nome))) like 'MULUNGU'; 
update cidade set cod_tom = '1485' where uf = 6 and upper(trim(unaccent(nome))) like 'NOVA OLINDA'; 
update cidade set cod_tom = '1487' where uf = 6 and upper(trim(unaccent(nome))) like 'NOVA RUSSAS'; 
update cidade set cod_tom = '1489' where uf = 6 and upper(trim(unaccent(nome))) like 'NOVO ORIENTE'; 
update cidade set cod_tom = '1265' where uf = 6 and upper(trim(unaccent(nome))) like 'OCARA'; 
update cidade set cod_tom = '1491' where uf = 6 and upper(trim(unaccent(nome))) like 'OROS'; 
update cidade set cod_tom = '1493' where uf = 6 and upper(trim(unaccent(nome))) like 'PACAJUS'; 
update cidade set cod_tom = '1495' where uf = 6 and upper(trim(unaccent(nome))) like 'PACATUBA'; 
update cidade set cod_tom = '1497' where uf = 6 and upper(trim(unaccent(nome))) like 'PACOTI'; 
update cidade set cod_tom = '1499' where uf = 6 and upper(trim(unaccent(nome))) like 'PACUJA'; 
update cidade set cod_tom = '1501' where uf = 6 and upper(trim(unaccent(nome))) like 'PALHANO'; 
update cidade set cod_tom = '1503' where uf = 6 and upper(trim(unaccent(nome))) like 'PALMACIA'; 
update cidade set cod_tom = '1505' where uf = 6 and upper(trim(unaccent(nome))) like 'PARACURU'; 
update cidade set cod_tom = '1599' where uf = 6 and upper(trim(unaccent(nome))) like 'PARAIPABA'; 
update cidade set cod_tom = '1507' where uf = 6 and upper(trim(unaccent(nome))) like 'PARAMBU'; 
update cidade set cod_tom = '1509' where uf = 6 and upper(trim(unaccent(nome))) like 'PARAMOTI'; 
update cidade set cod_tom = '1511' where uf = 6 and upper(trim(unaccent(nome))) like 'PEDRA BRANCA'; 
update cidade set cod_tom = '1513' where uf = 6 and upper(trim(unaccent(nome))) like 'PENAFORTE'; 
update cidade set cod_tom = '1515' where uf = 6 and upper(trim(unaccent(nome))) like 'PENTECOSTE'; 
update cidade set cod_tom = '1517' where uf = 6 and upper(trim(unaccent(nome))) like 'PEREIRO'; 
update cidade set cod_tom = '1267' where uf = 6 and upper(trim(unaccent(nome))) like 'PINDORETAMA'; 
update cidade set cod_tom = '1519' where uf = 6 and upper(trim(unaccent(nome))) like 'PIQUET CARNEIRO'; 
update cidade set cod_tom = '1269' where uf = 6 and upper(trim(unaccent(nome))) like 'PIRES FERREIRA'; 
update cidade set cod_tom = '1521' where uf = 6 and upper(trim(unaccent(nome))) like 'PORANGA'; 
update cidade set cod_tom = '1523' where uf = 6 and upper(trim(unaccent(nome))) like 'PORTEIRAS'; 
update cidade set cod_tom = '1525' where uf = 6 and upper(trim(unaccent(nome))) like 'POTENGI'; 
update cidade set cod_tom = '1271' where uf = 6 and upper(trim(unaccent(nome))) like 'POTIRETAMA'; 
update cidade set cod_tom = '0' where uf = 6 and upper(trim(unaccent(nome))) like 'QUATIS'; 
update cidade set cod_tom = '9917' where uf = 6 and upper(trim(unaccent(nome))) like 'QUITERIANOPOLIS'; 
update cidade set cod_tom = '1527' where uf = 6 and upper(trim(unaccent(nome))) like 'QUIXADA'; 
update cidade set cod_tom = '9853' where uf = 6 and upper(trim(unaccent(nome))) like 'QUIXELO'; 
update cidade set cod_tom = '1529' where uf = 6 and upper(trim(unaccent(nome))) like 'QUIXERAMOBIM'; 
update cidade set cod_tom = '1531' where uf = 6 and upper(trim(unaccent(nome))) like 'QUIXERE'; 
update cidade set cod_tom = '1533' where uf = 6 and upper(trim(unaccent(nome))) like 'REDENCAO'; 
update cidade set cod_tom = '1535' where uf = 6 and upper(trim(unaccent(nome))) like 'RERIUTABA'; 
update cidade set cod_tom = '1537' where uf = 6 and upper(trim(unaccent(nome))) like 'RUSSAS'; 
update cidade set cod_tom = '1539' where uf = 6 and upper(trim(unaccent(nome))) like 'SABOEIRO'; 
update cidade set cod_tom = '1273' where uf = 6 and upper(trim(unaccent(nome))) like 'SALITRE'; 
update cidade set cod_tom = '1545' where uf = 6 and upper(trim(unaccent(nome))) like 'SANTA QUITERIA'; 
update cidade set cod_tom = '1541' where uf = 6 and upper(trim(unaccent(nome))) like 'SANTANA DO ACARAU'; 
update cidade set cod_tom = '1543' where uf = 6 and upper(trim(unaccent(nome))) like 'SANTANA DO CARIRI'; 
update cidade set cod_tom = '1547' where uf = 6 and upper(trim(unaccent(nome))) like 'SAO BENEDITO'; 
update cidade set cod_tom = '1549' where uf = 6 and upper(trim(unaccent(nome))) like 'SAO GONCALO DO AMARANTE'; 
update cidade set cod_tom = '1551' where uf = 6 and upper(trim(unaccent(nome))) like 'SAO JOAO DO JAGUARIBE'; 
update cidade set cod_tom = '1553' where uf = 6 and upper(trim(unaccent(nome))) like 'SAO LUIS DO CURU'; 
update cidade set cod_tom = '1555' where uf = 6 and upper(trim(unaccent(nome))) like 'SENADOR POMPEU'; 
update cidade set cod_tom = '1557' where uf = 6 and upper(trim(unaccent(nome))) like 'SENADOR SA'; 
update cidade set cod_tom = '1559' where uf = 6 and upper(trim(unaccent(nome))) like 'SOBRAL'; 
update cidade set cod_tom = '1561' where uf = 6 and upper(trim(unaccent(nome))) like 'SOLONOPOLE'; 
update cidade set cod_tom = '1563' where uf = 6 and upper(trim(unaccent(nome))) like 'TABULEIRO DO NORTE'; 
update cidade set cod_tom = '1565' where uf = 6 and upper(trim(unaccent(nome))) like 'TAMBORIL'; 
update cidade set cod_tom = '1275' where uf = 6 and upper(trim(unaccent(nome))) like 'TARRAFAS'; 
update cidade set cod_tom = '1567' where uf = 6 and upper(trim(unaccent(nome))) like 'TAUA'; 
update cidade set cod_tom = '1277' where uf = 6 and upper(trim(unaccent(nome))) like 'TEJUCUOCA'; 
update cidade set cod_tom = '1569' where uf = 6 and upper(trim(unaccent(nome))) like 'TIANGUA'; 
update cidade set cod_tom = '1571' where uf = 6 and upper(trim(unaccent(nome))) like 'TRAIRI'; 
update cidade set cod_tom = '1279' where uf = 6 and upper(trim(unaccent(nome))) like 'TURURU'; 
update cidade set cod_tom = '1573' where uf = 6 and upper(trim(unaccent(nome))) like 'UBAJARA'; 
update cidade set cod_tom = '1575' where uf = 6 and upper(trim(unaccent(nome))) like 'UMARI'; 
update cidade set cod_tom = '9855' where uf = 6 and upper(trim(unaccent(nome))) like 'UMIRIM'; 
update cidade set cod_tom = '1577' where uf = 6 and upper(trim(unaccent(nome))) like 'URUBURETAMA'; 
update cidade set cod_tom = '1579' where uf = 6 and upper(trim(unaccent(nome))) like 'URUOCA'; 
update cidade set cod_tom = '9857' where uf = 6 and upper(trim(unaccent(nome))) like 'VARJOTA'; 
update cidade set cod_tom = '1581' where uf = 6 and upper(trim(unaccent(nome))) like 'VARZEA ALEGRE'; 
update cidade set cod_tom = '1583' where uf = 6 and upper(trim(unaccent(nome))) like 'VICOSA DO CEARA'; 
