update cidade set cod_tom = '9003' where uf = 12 and upper(trim(unaccent(nome))) like 'AGUA CLARA'; 
update cidade set cod_tom = '0141' where uf = 12 and upper(trim(unaccent(nome))) like 'ALCINOPOLIS'; 
update cidade set cod_tom = '9011' where uf = 12 and upper(trim(unaccent(nome))) like 'AMAMBAI'; 
update cidade set cod_tom = '9013' where uf = 12 and upper(trim(unaccent(nome))) like 'ANASTACIO'; 
update cidade set cod_tom = '9015' where uf = 12 and upper(trim(unaccent(nome))) like 'ANAURILANDIA'; 
update cidade set cod_tom = '9169' where uf = 12 and upper(trim(unaccent(nome))) like 'ANGELICA'; 
update cidade set cod_tom = '9017' where uf = 12 and upper(trim(unaccent(nome))) like 'ANTONIO JOAO'; 
update cidade set cod_tom = '9019' where uf = 12 and upper(trim(unaccent(nome))) like 'APARECIDA DO TABOADO'; 
update cidade set cod_tom = '9021' where uf = 12 and upper(trim(unaccent(nome))) like 'AQUIDAUANA'; 
update cidade set cod_tom = '9171' where uf = 12 and upper(trim(unaccent(nome))) like 'ARAL MOREIRA'; 
update cidade set cod_tom = '9029' where uf = 12 and upper(trim(unaccent(nome))) like 'BANDEIRANTES'; 
update cidade set cod_tom = '9037' where uf = 12 and upper(trim(unaccent(nome))) like 'BATAGUASSU'; 
update cidade set cod_tom = '9039' where uf = 12 and upper(trim(unaccent(nome))) like 'BATAYPORA'; 
update cidade set cod_tom = '9041' where uf = 12 and upper(trim(unaccent(nome))) like 'BELA VISTA'; 
update cidade set cod_tom = '9801' where uf = 12 and upper(trim(unaccent(nome))) like 'BODOQUENA'; 
update cidade set cod_tom = '9043' where uf = 12 and upper(trim(unaccent(nome))) like 'BONITO'; 
update cidade set cod_tom = '9045' where uf = 12 and upper(trim(unaccent(nome))) like 'BRASILANDIA'; 
update cidade set cod_tom = '9055' where uf = 12 and upper(trim(unaccent(nome))) like 'CAARAPO'; 
update cidade set cod_tom = '9049' where uf = 12 and upper(trim(unaccent(nome))) like 'CAMAPUA'; 
update cidade set cod_tom = '9051' where uf = 12 and upper(trim(unaccent(nome))) like 'CAMPO GRANDE'; 
update cidade set cod_tom = '9053' where uf = 12 and upper(trim(unaccent(nome))) like 'CARACOL'; 
update cidade set cod_tom = '9057' where uf = 12 and upper(trim(unaccent(nome))) like 'CASSILANDIA'; 
update cidade set cod_tom = '9787' where uf = 12 and upper(trim(unaccent(nome))) like 'CHAPADAO DO SUL'; 
update cidade set cod_tom = '9061' where uf = 12 and upper(trim(unaccent(nome))) like 'CORGUINHO'; 
update cidade set cod_tom = '9997' where uf = 12 and upper(trim(unaccent(nome))) like 'CORONEL SAPUCAIA'; 
update cidade set cod_tom = '9063' where uf = 12 and upper(trim(unaccent(nome))) like 'CORUMBA'; 
update cidade set cod_tom = '9803' where uf = 12 and upper(trim(unaccent(nome))) like 'COSTA RICA'; 
update cidade set cod_tom = '9065' where uf = 12 and upper(trim(unaccent(nome))) like 'COXIM'; 
update cidade set cod_tom = '9175' where uf = 12 and upper(trim(unaccent(nome))) like 'DEODAPOLIS'; 
update cidade set cod_tom = '9793' where uf = 12 and upper(trim(unaccent(nome))) like 'DOIS IRMAOS DO BURITI'; 
update cidade set cod_tom = '9805' where uf = 12 and upper(trim(unaccent(nome))) like 'DOURADINA'; 
update cidade set cod_tom = '9073' where uf = 12 and upper(trim(unaccent(nome))) like 'DOURADOS'; 
update cidade set cod_tom = '9173' where uf = 12 and upper(trim(unaccent(nome))) like 'ELDORADO'; 
update cidade set cod_tom = '9075' where uf = 12 and upper(trim(unaccent(nome))) like 'FATIMA DO SUL'; 
update cidade set cod_tom = '1178' where uf = 12 and upper(trim(unaccent(nome))) like 'FIGUEIRAO'; 
update cidade set cod_tom = '9079' where uf = 12 and upper(trim(unaccent(nome))) like 'GLORIA DE DOURADOS'; 
update cidade set cod_tom = '9081' where uf = 12 and upper(trim(unaccent(nome))) like 'GUIA LOPES DA LAGUNA'; 
update cidade set cod_tom = '9085' where uf = 12 and upper(trim(unaccent(nome))) like 'IGUATEMI'; 
update cidade set cod_tom = '9087' where uf = 12 and upper(trim(unaccent(nome))) like 'INOCENCIA'; 
update cidade set cod_tom = '9089' where uf = 12 and upper(trim(unaccent(nome))) like 'ITAPORA'; 
update cidade set cod_tom = '9807' where uf = 12 and upper(trim(unaccent(nome))) like 'ITAQUIRAI'; 
update cidade set cod_tom = '9093' where uf = 12 and upper(trim(unaccent(nome))) like 'IVINHEMA'; 
update cidade set cod_tom = '0161' where uf = 12 and upper(trim(unaccent(nome))) like 'JAPORA'; 
update cidade set cod_tom = '9097' where uf = 12 and upper(trim(unaccent(nome))) like 'JARAGUARI'; 
update cidade set cod_tom = '9099' where uf = 12 and upper(trim(unaccent(nome))) like 'JARDIM'; 
update cidade set cod_tom = '9101' where uf = 12 and upper(trim(unaccent(nome))) like 'JATEI'; 
update cidade set cod_tom = '9923' where uf = 12 and upper(trim(unaccent(nome))) like 'JUTI'; 
update cidade set cod_tom = '9103' where uf = 12 and upper(trim(unaccent(nome))) like 'LADARIO'; 
update cidade set cod_tom = '0163' where uf = 12 and upper(trim(unaccent(nome))) like 'LAGUNA CARAPA'; 
update cidade set cod_tom = '9107' where uf = 12 and upper(trim(unaccent(nome))) like 'MARACAJU'; 
update cidade set cod_tom = '9111' where uf = 12 and upper(trim(unaccent(nome))) like 'MIRANDA'; 
update cidade set cod_tom = '9179' where uf = 12 and upper(trim(unaccent(nome))) like 'MUNDO NOVO'; 
update cidade set cod_tom = '9113' where uf = 12 and upper(trim(unaccent(nome))) like 'NAVIRAI'; 
update cidade set cod_tom = '9115' where uf = 12 and upper(trim(unaccent(nome))) like 'NIOAQUE'; 
update cidade set cod_tom = '0143' where uf = 12 and upper(trim(unaccent(nome))) like 'NOVA ALVORADA DO SUL'; 
update cidade set cod_tom = '9123' where uf = 12 and upper(trim(unaccent(nome))) like 'NOVA ANDRADINA'; 
update cidade set cod_tom = '0159' where uf = 12 and upper(trim(unaccent(nome))) like 'NOVO HORIZONTE DO SUL'; 
update cidade set cod_tom = '9125' where uf = 12 and upper(trim(unaccent(nome))) like 'PARANAIBA'; 
update cidade set cod_tom = '9739' where uf = 12 and upper(trim(unaccent(nome))) like 'PARANHOS'; 
update cidade set cod_tom = '9127' where uf = 12 and upper(trim(unaccent(nome))) like 'PEDRO GOMES'; 
update cidade set cod_tom = '9131' where uf = 12 and upper(trim(unaccent(nome))) like 'PONTA PORA'; 
update cidade set cod_tom = '9137' where uf = 12 and upper(trim(unaccent(nome))) like 'PORTO MURTINHO'; 
update cidade set cod_tom = '9141' where uf = 12 and upper(trim(unaccent(nome))) like 'RIBAS DO RIO PARDO'; 
update cidade set cod_tom = '9143' where uf = 12 and upper(trim(unaccent(nome))) like 'RIO BRILHANTE'; 
update cidade set cod_tom = '9145' where uf = 12 and upper(trim(unaccent(nome))) like 'RIO NEGRO'; 
update cidade set cod_tom = '9147' where uf = 12 and upper(trim(unaccent(nome))) like 'RIO VERDE DE MATO GROSSO'; 
update cidade set cod_tom = '9149' where uf = 12 and upper(trim(unaccent(nome))) like 'ROCHEDO'; 
update cidade set cod_tom = '9745' where uf = 12 and upper(trim(unaccent(nome))) like 'SANTA RITA DO PARDO'; 
update cidade set cod_tom = '9809' where uf = 12 and upper(trim(unaccent(nome))) like 'SAO GABRIEL DO OESTE'; 
update cidade set cod_tom = '9811' where uf = 12 and upper(trim(unaccent(nome))) like 'SELVIRIA'; 
update cidade set cod_tom = '9813' where uf = 12 and upper(trim(unaccent(nome))) like 'SETE QUEDAS'; 
update cidade set cod_tom = '9157' where uf = 12 and upper(trim(unaccent(nome))) like 'SIDROLANDIA'; 
update cidade set cod_tom = '9757' where uf = 12 and upper(trim(unaccent(nome))) like 'SONORA'; 
update cidade set cod_tom = '9815' where uf = 12 and upper(trim(unaccent(nome))) like 'TACURU'; 
update cidade set cod_tom = '9817' where uf = 12 and upper(trim(unaccent(nome))) like 'TAQUARUSSU'; 
update cidade set cod_tom = '9159' where uf = 12 and upper(trim(unaccent(nome))) like 'TERENOS'; 
update cidade set cod_tom = '9165' where uf = 12 and upper(trim(unaccent(nome))) like 'TRES LAGOAS'; 
update cidade set cod_tom = '9187' where uf = 12 and upper(trim(unaccent(nome))) like 'VICENTINA';