update cidade set cod_tom = '3101' where uf = 25 and upper(trim(unaccent(nome))) like 'AMPARO DE SAO FRANCISCO'; 
update cidade set cod_tom = '3103' where uf = 25 and upper(trim(unaccent(nome))) like 'AQUIDABA'; 
update cidade set cod_tom = '3105' where uf = 25 and upper(trim(unaccent(nome))) like 'ARACAJU'; 
update cidade set cod_tom = '3107' where uf = 25 and upper(trim(unaccent(nome))) like 'ARAUA'; 
update cidade set cod_tom = '3109' where uf = 25 and upper(trim(unaccent(nome))) like 'AREIA BRANCA'; 
update cidade set cod_tom = '3111' where uf = 25 and upper(trim(unaccent(nome))) like 'BARRA DOS COQUEIROS'; 
update cidade set cod_tom = '3115' where uf = 25 and upper(trim(unaccent(nome))) like 'BOQUIM'; 
update cidade set cod_tom = '3113' where uf = 25 and upper(trim(unaccent(nome))) like 'BREJO GRANDE'; 
update cidade set cod_tom = '3119' where uf = 25 and upper(trim(unaccent(nome))) like 'CAMPO DO BRITO'; 
update cidade set cod_tom = '3121' where uf = 25 and upper(trim(unaccent(nome))) like 'CANHOBA'; 
update cidade set cod_tom = '3123' where uf = 25 and upper(trim(unaccent(nome))) like 'CANINDE DE SAO FRANCISCO'; 
update cidade set cod_tom = '3125' where uf = 25 and upper(trim(unaccent(nome))) like 'CAPELA'; 
update cidade set cod_tom = '3127' where uf = 25 and upper(trim(unaccent(nome))) like 'CARIRA'; 
update cidade set cod_tom = '3129' where uf = 25 and upper(trim(unaccent(nome))) like 'CARMOPOLIS'; 
update cidade set cod_tom = '3131' where uf = 25 and upper(trim(unaccent(nome))) like 'CEDRO DE SAO JOAO'; 
update cidade set cod_tom = '3133' where uf = 25 and upper(trim(unaccent(nome))) like 'CRISTINAPOLIS'; 
update cidade set cod_tom = '3137' where uf = 25 and upper(trim(unaccent(nome))) like 'CUMBE'; 
update cidade set cod_tom = '3139' where uf = 25 and upper(trim(unaccent(nome))) like 'DIVINA PASTORA'; 
update cidade set cod_tom = '3141' where uf = 25 and upper(trim(unaccent(nome))) like 'ESTANCIA'; 
update cidade set cod_tom = '3143' where uf = 25 and upper(trim(unaccent(nome))) like 'FEIRA NOVA'; 
update cidade set cod_tom = '3145' where uf = 25 and upper(trim(unaccent(nome))) like 'FREI PAULO'; 
update cidade set cod_tom = '3149' where uf = 25 and upper(trim(unaccent(nome))) like 'GARARU'; 
update cidade set cod_tom = '3147' where uf = 25 and upper(trim(unaccent(nome))) like 'GENERAL MAYNARD'; 
update cidade set cod_tom = '3151' where uf = 25 and upper(trim(unaccent(nome))) like 'GRACCHO CARDOSO'; 
update cidade set cod_tom = '3153' where uf = 25 and upper(trim(unaccent(nome))) like 'ILHA DAS FLORES'; 
update cidade set cod_tom = '3155' where uf = 25 and upper(trim(unaccent(nome))) like 'INDIAROBA'; 
update cidade set cod_tom = '3157' where uf = 25 and upper(trim(unaccent(nome))) like 'ITABAIANA'; 
update cidade set cod_tom = '3159' where uf = 25 and upper(trim(unaccent(nome))) like 'ITABAIANINHA'; 
update cidade set cod_tom = '3161' where uf = 25 and upper(trim(unaccent(nome))) like 'ITABI'; 
update cidade set cod_tom = '3163' where uf = 25 and upper(trim(unaccent(nome))) like 'ITAPORANGA D`AJUDA'; 
update cidade set cod_tom = '3165' where uf = 25 and upper(trim(unaccent(nome))) like 'JAPARATUBA'; 
update cidade set cod_tom = '3167' where uf = 25 and upper(trim(unaccent(nome))) like 'JAPOATA'; 
update cidade set cod_tom = '3169' where uf = 25 and upper(trim(unaccent(nome))) like 'LAGARTO'; 
update cidade set cod_tom = '3171' where uf = 25 and upper(trim(unaccent(nome))) like 'LARANJEIRAS'; 
update cidade set cod_tom = '3173' where uf = 25 and upper(trim(unaccent(nome))) like 'MACAMBIRA'; 
update cidade set cod_tom = '3175' where uf = 25 and upper(trim(unaccent(nome))) like 'MALHADA DOS BOIS'; 
update cidade set cod_tom = '3177' where uf = 25 and upper(trim(unaccent(nome))) like 'MALHADOR'; 
update cidade set cod_tom = '3179' where uf = 25 and upper(trim(unaccent(nome))) like 'MARUIM'; 
update cidade set cod_tom = '3181' where uf = 25 and upper(trim(unaccent(nome))) like 'MOITA BONITA'; 
update cidade set cod_tom = '3183' where uf = 25 and upper(trim(unaccent(nome))) like 'MONTE ALEGRE DE SERGIPE'; 
update cidade set cod_tom = '3185' where uf = 25 and upper(trim(unaccent(nome))) like 'MURIBECA'; 
update cidade set cod_tom = '3187' where uf = 25 and upper(trim(unaccent(nome))) like 'NEOPOLIS'; 
update cidade set cod_tom = '3135' where uf = 25 and upper(trim(unaccent(nome))) like 'NOSSA SENHORA APARECIDA'; 
update cidade set cod_tom = '3189' where uf = 25 and upper(trim(unaccent(nome))) like 'NOSSA SENHORA DA GLORIA'; 
update cidade set cod_tom = '3191' where uf = 25 and upper(trim(unaccent(nome))) like 'NOSSA SENHORA DAS DORES'; 
update cidade set cod_tom = '3193' where uf = 25 and upper(trim(unaccent(nome))) like 'NOSSA SENHORA DE LOURDES'; 
update cidade set cod_tom = '3195' where uf = 25 and upper(trim(unaccent(nome))) like 'NOSSA SENHORA DO SOCORRO'; 
update cidade set cod_tom = '3197' where uf = 25 and upper(trim(unaccent(nome))) like 'PACATUBA'; 
update cidade set cod_tom = '3199' where uf = 25 and upper(trim(unaccent(nome))) like 'PEDRA MOLE'; 
update cidade set cod_tom = '3201' where uf = 25 and upper(trim(unaccent(nome))) like 'PEDRINHAS'; 
update cidade set cod_tom = '3203' where uf = 25 and upper(trim(unaccent(nome))) like 'PINHAO'; 
update cidade set cod_tom = '3205' where uf = 25 and upper(trim(unaccent(nome))) like 'PIRAMBU'; 
update cidade set cod_tom = '3207' where uf = 25 and upper(trim(unaccent(nome))) like 'POCO REDONDO'; 
update cidade set cod_tom = '3209' where uf = 25 and upper(trim(unaccent(nome))) like 'POCO VERDE'; 
update cidade set cod_tom = '3211' where uf = 25 and upper(trim(unaccent(nome))) like 'PORTO DA FOLHA'; 
update cidade set cod_tom = '3213' where uf = 25 and upper(trim(unaccent(nome))) like 'PROPRIA'; 
update cidade set cod_tom = '3215' where uf = 25 and upper(trim(unaccent(nome))) like 'RIACHAO DO DANTAS'; 
update cidade set cod_tom = '3217' where uf = 25 and upper(trim(unaccent(nome))) like 'RIACHUELO'; 
update cidade set cod_tom = '3219' where uf = 25 and upper(trim(unaccent(nome))) like 'RIBEIROPOLIS'; 
update cidade set cod_tom = '3221' where uf = 25 and upper(trim(unaccent(nome))) like 'ROSARIO DO CATETE'; 
update cidade set cod_tom = '3223' where uf = 25 and upper(trim(unaccent(nome))) like 'SALGADO'; 
update cidade set cod_tom = '3225' where uf = 25 and upper(trim(unaccent(nome))) like 'SANTA LUZIA DO ITANHY'; 
update cidade set cod_tom = '3229' where uf = 25 and upper(trim(unaccent(nome))) like 'SANTA ROSA DE LIMA'; 
update cidade set cod_tom = '2647' where uf = 25 and upper(trim(unaccent(nome))) like 'SANTANA DO SAO FRANCISCO'; 
update cidade set cod_tom = '3231' where uf = 25 and upper(trim(unaccent(nome))) like 'SANTO AMARO DAS BROTAS'; 
update cidade set cod_tom = '3233' where uf = 25 and upper(trim(unaccent(nome))) like 'SAO CRISTOVAO'; 
update cidade set cod_tom = '3235' where uf = 25 and upper(trim(unaccent(nome))) like 'SAO DOMINGOS'; 
update cidade set cod_tom = '3237' where uf = 25 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO'; 
update cidade set cod_tom = '3239' where uf = 25 and upper(trim(unaccent(nome))) like 'SAO MIGUEL DO ALEIXO'; 
update cidade set cod_tom = '3241' where uf = 25 and upper(trim(unaccent(nome))) like 'SIMAO DIAS'; 
update cidade set cod_tom = '3243' where uf = 25 and upper(trim(unaccent(nome))) like 'SIRIRI'; 
update cidade set cod_tom = '3245' where uf = 25 and upper(trim(unaccent(nome))) like 'TELHA'; 
update cidade set cod_tom = '3247' where uf = 25 and upper(trim(unaccent(nome))) like 'TOBIAS BARRETO'; 
update cidade set cod_tom = '3249' where uf = 25 and upper(trim(unaccent(nome))) like 'TOMAR DO GERU'; 
update cidade set cod_tom = '3251' where uf = 25 and upper(trim(unaccent(nome))) like 'UMBAUBA';