update cidade set cod_tom = '1901' where uf = 15 and upper(trim(unaccent(nome))) like 'AGUA BRANCA'; 
update cidade set cod_tom = '1903' where uf = 15 and upper(trim(unaccent(nome))) like 'AGUIAR'; 
update cidade set cod_tom = '1905' where uf = 15 and upper(trim(unaccent(nome))) like 'ALAGOA GRANDE'; 
update cidade set cod_tom = '1907' where uf = 15 and upper(trim(unaccent(nome))) like 'ALAGOA NOVA'; 
update cidade set cod_tom = '1909' where uf = 15 and upper(trim(unaccent(nome))) like 'ALAGOINHA'; 
update cidade set cod_tom = '0440' where uf = 15 and upper(trim(unaccent(nome))) like 'ALCANTIL'; 
update cidade set cod_tom = '0442' where uf = 15 and upper(trim(unaccent(nome))) like 'ALGODAO DE JANDAIRA'; 
update cidade set cod_tom = '1911' where uf = 15 and upper(trim(unaccent(nome))) like 'ALHANDRA'; 
update cidade set cod_tom = '0444' where uf = 15 and upper(trim(unaccent(nome))) like 'AMPARO'; 
update cidade set cod_tom = '0446' where uf = 15 and upper(trim(unaccent(nome))) like 'APARECIDA'; 
update cidade set cod_tom = '1915' where uf = 15 and upper(trim(unaccent(nome))) like 'ARACAGI'; 
update cidade set cod_tom = '1917' where uf = 15 and upper(trim(unaccent(nome))) like 'ARARA'; 
update cidade set cod_tom = '1919' where uf = 15 and upper(trim(unaccent(nome))) like 'ARARUNA'; 
update cidade set cod_tom = '1921' where uf = 15 and upper(trim(unaccent(nome))) like 'AREIA'; 
update cidade set cod_tom = '0448' where uf = 15 and upper(trim(unaccent(nome))) like 'AREIA DE BARAUNAS'; 
update cidade set cod_tom = '1923' where uf = 15 and upper(trim(unaccent(nome))) like 'AREIAL'; 
update cidade set cod_tom = '1925' where uf = 15 and upper(trim(unaccent(nome))) like 'AROEIRAS'; 
update cidade set cod_tom = '0' where uf = 15 and upper(trim(unaccent(nome))) like 'ASSIS CHATEAUBRIAND'; 
update cidade set cod_tom = '0450' where uf = 15 and upper(trim(unaccent(nome))) like 'ASSUNCAO'; 
update cidade set cod_tom = '1929' where uf = 15 and upper(trim(unaccent(nome))) like 'BAIA DA TRAICAO'; 
update cidade set cod_tom = '1931' where uf = 15 and upper(trim(unaccent(nome))) like 'BANANEIRAS'; 
update cidade set cod_tom = '0452' where uf = 15 and upper(trim(unaccent(nome))) like 'BARAUNA'; 
update cidade set cod_tom = '1933' where uf = 15 and upper(trim(unaccent(nome))) like 'BARRA DE SANTA ROSA'; 
update cidade set cod_tom = '0454' where uf = 15 and upper(trim(unaccent(nome))) like 'BARRA DE SANTANA'; 
update cidade set cod_tom = '1935' where uf = 15 and upper(trim(unaccent(nome))) like 'BARRA DE SAO MIGUEL'; 
update cidade set cod_tom = '1937' where uf = 15 and upper(trim(unaccent(nome))) like 'BAYEUX'; 
update cidade set cod_tom = '1939' where uf = 15 and upper(trim(unaccent(nome))) like 'BELEM'; 
update cidade set cod_tom = '1941' where uf = 15 and upper(trim(unaccent(nome))) like 'BELEM DO BREJO DO CRUZ'; 
update cidade set cod_tom = '0456' where uf = 15 and upper(trim(unaccent(nome))) like 'BERNARDINO BATISTA'; 
update cidade set cod_tom = '1943' where uf = 15 and upper(trim(unaccent(nome))) like 'BOA VENTURA'; 
update cidade set cod_tom = '0458' where uf = 15 and upper(trim(unaccent(nome))) like 'BOA VISTA'; 
update cidade set cod_tom = '1945' where uf = 15 and upper(trim(unaccent(nome))) like 'BOM JESUS'; 
update cidade set cod_tom = '1947' where uf = 15 and upper(trim(unaccent(nome))) like 'BOM SUCESSO'; 
update cidade set cod_tom = '1949' where uf = 15 and upper(trim(unaccent(nome))) like 'BONITO DE SANTA FE'; 
update cidade set cod_tom = '1951' where uf = 15 and upper(trim(unaccent(nome))) like 'BOQUEIRAO'; 
update cidade set cod_tom = '0' where uf = 15 and upper(trim(unaccent(nome))) like 'BOQUEIRAO DOS COCHOS'; 
update cidade set cod_tom = '1955' where uf = 15 and upper(trim(unaccent(nome))) like 'BORBOREMA'; 
update cidade set cod_tom = '1957' where uf = 15 and upper(trim(unaccent(nome))) like 'BREJO DO CRUZ'; 
update cidade set cod_tom = '1959' where uf = 15 and upper(trim(unaccent(nome))) like 'BREJO DOS SANTOS'; 
update cidade set cod_tom = '1961' where uf = 15 and upper(trim(unaccent(nome))) like 'CAAPORA'; 
update cidade set cod_tom = '1963' where uf = 15 and upper(trim(unaccent(nome))) like 'CABACEIRAS'; 
update cidade set cod_tom = '1965' where uf = 15 and upper(trim(unaccent(nome))) like 'CABEDELO'; 
update cidade set cod_tom = '1967' where uf = 15 and upper(trim(unaccent(nome))) like 'CACHOEIRA DOS INDIOS'; 
update cidade set cod_tom = '1969' where uf = 15 and upper(trim(unaccent(nome))) like 'CACIMBA DE AREIA'; 
update cidade set cod_tom = '1971' where uf = 15 and upper(trim(unaccent(nome))) like 'CACIMBA DE DENTRO'; 
update cidade set cod_tom = '0460' where uf = 15 and upper(trim(unaccent(nome))) like 'CACIMBAS'; 
update cidade set cod_tom = '1973' where uf = 15 and upper(trim(unaccent(nome))) like 'CAICARA'; 
update cidade set cod_tom = '1975' where uf = 15 and upper(trim(unaccent(nome))) like 'CAJAZEIRAS'; 
update cidade set cod_tom = '0462' where uf = 15 and upper(trim(unaccent(nome))) like 'CAJAZEIRINHAS'; 
update cidade set cod_tom = '1977' where uf = 15 and upper(trim(unaccent(nome))) like 'CALDAS BRANDAO'; 
update cidade set cod_tom = '1979' where uf = 15 and upper(trim(unaccent(nome))) like 'CAMALAU'; 
update cidade set cod_tom = '1981' where uf = 15 and upper(trim(unaccent(nome))) like 'CAMPINA GRANDE'; 
update cidade set cod_tom = '2229' where uf = 15 and upper(trim(unaccent(nome))) like 'CAMPO DE SANTANA'; 
update cidade set cod_tom = '0464' where uf = 15 and upper(trim(unaccent(nome))) like 'CAPIM'; 
update cidade set cod_tom = '0466' where uf = 15 and upper(trim(unaccent(nome))) like 'CARAUBAS'; 
update cidade set cod_tom = '1983' where uf = 15 and upper(trim(unaccent(nome))) like 'CARRAPATEIRA'; 
update cidade set cod_tom = '0468' where uf = 15 and upper(trim(unaccent(nome))) like 'CASSERENGUE'; 
update cidade set cod_tom = '1985' where uf = 15 and upper(trim(unaccent(nome))) like 'CATINGUEIRA'; 
update cidade set cod_tom = '1987' where uf = 15 and upper(trim(unaccent(nome))) like 'CATOLE DO ROCHA'; 
update cidade set cod_tom = '0470' where uf = 15 and upper(trim(unaccent(nome))) like 'CATURITE'; 
update cidade set cod_tom = '1989' where uf = 15 and upper(trim(unaccent(nome))) like 'CONCEICAO'; 
update cidade set cod_tom = '1991' where uf = 15 and upper(trim(unaccent(nome))) like 'CONDADO'; 
update cidade set cod_tom = '1993' where uf = 15 and upper(trim(unaccent(nome))) like 'CONDE'; 
update cidade set cod_tom = '1995' where uf = 15 and upper(trim(unaccent(nome))) like 'CONGO'; 
update cidade set cod_tom = '1997' where uf = 15 and upper(trim(unaccent(nome))) like 'COREMAS'; 
update cidade set cod_tom = '0472' where uf = 15 and upper(trim(unaccent(nome))) like 'COXIXOLA'; 
update cidade set cod_tom = '1999' where uf = 15 and upper(trim(unaccent(nome))) like 'CRUZ DO ESPIRITO SANTO'; 
update cidade set cod_tom = '2001' where uf = 15 and upper(trim(unaccent(nome))) like 'CUBATI'; 
update cidade set cod_tom = '2003' where uf = 15 and upper(trim(unaccent(nome))) like 'CUITE'; 
update cidade set cod_tom = '0474' where uf = 15 and upper(trim(unaccent(nome))) like 'CUITE DE MAMANGUAPE'; 
update cidade set cod_tom = '2005' where uf = 15 and upper(trim(unaccent(nome))) like 'CUITEGI'; 
update cidade set cod_tom = '0476' where uf = 15 and upper(trim(unaccent(nome))) like 'CURRAL DE CIMA'; 
update cidade set cod_tom = '2007' where uf = 15 and upper(trim(unaccent(nome))) like 'CURRAL VELHO'; 
update cidade set cod_tom = '0478' where uf = 15 and upper(trim(unaccent(nome))) like 'DAMIAO'; 
update cidade set cod_tom = '2009' where uf = 15 and upper(trim(unaccent(nome))) like 'DESTERRO'; 
update cidade set cod_tom = '0' where uf = 15 and upper(trim(unaccent(nome))) like 'DESTERRO DE MALTA'; 
update cidade set cod_tom = '2013' where uf = 15 and upper(trim(unaccent(nome))) like 'DIAMANTE'; 
update cidade set cod_tom = '2015' where uf = 15 and upper(trim(unaccent(nome))) like 'DONA INES'; 
update cidade set cod_tom = '2017' where uf = 15 and upper(trim(unaccent(nome))) like 'DUAS ESTRADAS'; 
update cidade set cod_tom = '2019' where uf = 15 and upper(trim(unaccent(nome))) like 'EMAS'; 
update cidade set cod_tom = '2021' where uf = 15 and upper(trim(unaccent(nome))) like 'ESPERANCA'; 
update cidade set cod_tom = '2023' where uf = 15 and upper(trim(unaccent(nome))) like 'FAGUNDES'; 
update cidade set cod_tom = '2025' where uf = 15 and upper(trim(unaccent(nome))) like 'FREI MARTINHO'; 
update cidade set cod_tom = '0480' where uf = 15 and upper(trim(unaccent(nome))) like 'GADO BRAVO'; 
update cidade set cod_tom = '2027' where uf = 15 and upper(trim(unaccent(nome))) like 'GUARABIRA'; 
update cidade set cod_tom = '2029' where uf = 15 and upper(trim(unaccent(nome))) like 'GURINHEM'; 
update cidade set cod_tom = '2031' where uf = 15 and upper(trim(unaccent(nome))) like 'GURJAO'; 
update cidade set cod_tom = '2033' where uf = 15 and upper(trim(unaccent(nome))) like 'IBIARA'; 
update cidade set cod_tom = '1953' where uf = 15 and upper(trim(unaccent(nome))) like 'IGARACY'; 
update cidade set cod_tom = '2035' where uf = 15 and upper(trim(unaccent(nome))) like 'IMACULADA'; 
update cidade set cod_tom = '2037' where uf = 15 and upper(trim(unaccent(nome))) like 'INGA'; 
update cidade set cod_tom = '2039' where uf = 15 and upper(trim(unaccent(nome))) like 'ITABAIANA'; 
update cidade set cod_tom = '2041' where uf = 15 and upper(trim(unaccent(nome))) like 'ITAPORANGA'; 
update cidade set cod_tom = '2043' where uf = 15 and upper(trim(unaccent(nome))) like 'ITAPOROROCA'; 
update cidade set cod_tom = '2045' where uf = 15 and upper(trim(unaccent(nome))) like 'ITATUBA'; 
update cidade set cod_tom = '2047' where uf = 15 and upper(trim(unaccent(nome))) like 'JACARAU'; 
update cidade set cod_tom = '2049' where uf = 15 and upper(trim(unaccent(nome))) like 'JERICO'; 
update cidade set cod_tom = '2051' where uf = 15 and upper(trim(unaccent(nome))) like 'JOAO PESSOA'; 
update cidade set cod_tom = '2053' where uf = 15 and upper(trim(unaccent(nome))) like 'JUAREZ TAVORA'; 
update cidade set cod_tom = '2055' where uf = 15 and upper(trim(unaccent(nome))) like 'JUAZEIRINHO'; 
update cidade set cod_tom = '2057' where uf = 15 and upper(trim(unaccent(nome))) like 'JUNCO DO SERIDO'; 
update cidade set cod_tom = '2059' where uf = 15 and upper(trim(unaccent(nome))) like 'JURIPIRANGA'; 
update cidade set cod_tom = '2061' where uf = 15 and upper(trim(unaccent(nome))) like 'JURU'; 
update cidade set cod_tom = '2063' where uf = 15 and upper(trim(unaccent(nome))) like 'LAGOA'; 
update cidade set cod_tom = '2065' where uf = 15 and upper(trim(unaccent(nome))) like 'LAGOA DE DENTRO'; 
update cidade set cod_tom = '2067' where uf = 15 and upper(trim(unaccent(nome))) like 'LAGOA SECA'; 
update cidade set cod_tom = '2069' where uf = 15 and upper(trim(unaccent(nome))) like 'LASTRO'; 
update cidade set cod_tom = '2071' where uf = 15 and upper(trim(unaccent(nome))) like 'LIVRAMENTO'; 
update cidade set cod_tom = '0482' where uf = 15 and upper(trim(unaccent(nome))) like 'LOGRADOURO'; 
update cidade set cod_tom = '2073' where uf = 15 and upper(trim(unaccent(nome))) like 'LUCENA'; 
update cidade set cod_tom = '2075' where uf = 15 and upper(trim(unaccent(nome))) like 'MAE D`AGUA'; 
update cidade set cod_tom = '2077' where uf = 15 and upper(trim(unaccent(nome))) like 'MALTA'; 
update cidade set cod_tom = '2079' where uf = 15 and upper(trim(unaccent(nome))) like 'MAMANGUAPE'; 
update cidade set cod_tom = '2081' where uf = 15 and upper(trim(unaccent(nome))) like 'MANAIRA'; 
update cidade set cod_tom = '0484' where uf = 15 and upper(trim(unaccent(nome))) like 'MARCACAO'; 
update cidade set cod_tom = '2083' where uf = 15 and upper(trim(unaccent(nome))) like 'MARI'; 
update cidade set cod_tom = '0486' where uf = 15 and upper(trim(unaccent(nome))) like 'MARIZOPOLIS'; 
update cidade set cod_tom = '2085' where uf = 15 and upper(trim(unaccent(nome))) like 'MASSARANDUBA'; 
update cidade set cod_tom = '2087' where uf = 15 and upper(trim(unaccent(nome))) like 'MATARACA'; 
update cidade set cod_tom = '0488' where uf = 15 and upper(trim(unaccent(nome))) like 'MATINHAS'; 
update cidade set cod_tom = '0490' where uf = 15 and upper(trim(unaccent(nome))) like 'MATO GROSSO'; 
update cidade set cod_tom = '0492' where uf = 15 and upper(trim(unaccent(nome))) like 'MATUREIA'; 
update cidade set cod_tom = '2089' where uf = 15 and upper(trim(unaccent(nome))) like 'MOGEIRO'; 
update cidade set cod_tom = '2091' where uf = 15 and upper(trim(unaccent(nome))) like 'MONTADAS'; 
update cidade set cod_tom = '2093' where uf = 15 and upper(trim(unaccent(nome))) like 'MONTE HOREBE'; 
update cidade set cod_tom = '2095' where uf = 15 and upper(trim(unaccent(nome))) like 'MONTEIRO'; 
update cidade set cod_tom = '2097' where uf = 15 and upper(trim(unaccent(nome))) like 'MULUNGU'; 
update cidade set cod_tom = '2099' where uf = 15 and upper(trim(unaccent(nome))) like 'NATUBA'; 
update cidade set cod_tom = '2101' where uf = 15 and upper(trim(unaccent(nome))) like 'NAZAREZINHO'; 
update cidade set cod_tom = '2103' where uf = 15 and upper(trim(unaccent(nome))) like 'NOVA FLORESTA'; 
update cidade set cod_tom = '2105' where uf = 15 and upper(trim(unaccent(nome))) like 'NOVA OLINDA'; 
update cidade set cod_tom = '2107' where uf = 15 and upper(trim(unaccent(nome))) like 'NOVA PALMEIRA'; 
update cidade set cod_tom = '2109' where uf = 15 and upper(trim(unaccent(nome))) like 'OLHO D`AGUA'; 
update cidade set cod_tom = '2111' where uf = 15 and upper(trim(unaccent(nome))) like 'OLIVEDOS'; 
update cidade set cod_tom = '2113' where uf = 15 and upper(trim(unaccent(nome))) like 'OURO VELHO'; 
update cidade set cod_tom = '0494' where uf = 15 and upper(trim(unaccent(nome))) like 'PARARI'; 
update cidade set cod_tom = '2115' where uf = 15 and upper(trim(unaccent(nome))) like 'PASSAGEM'; 
update cidade set cod_tom = '2117' where uf = 15 and upper(trim(unaccent(nome))) like 'PATOS'; 
update cidade set cod_tom = '2119' where uf = 15 and upper(trim(unaccent(nome))) like 'PAULISTA'; 
update cidade set cod_tom = '2121' where uf = 15 and upper(trim(unaccent(nome))) like 'PEDRA BRANCA'; 
update cidade set cod_tom = '2123' where uf = 15 and upper(trim(unaccent(nome))) like 'PEDRA LAVRADA'; 
update cidade set cod_tom = '2125' where uf = 15 and upper(trim(unaccent(nome))) like 'PEDRAS DE FOGO'; 
update cidade set cod_tom = '0500' where uf = 15 and upper(trim(unaccent(nome))) like 'PEDRO REGIS'; 
update cidade set cod_tom = '2127' where uf = 15 and upper(trim(unaccent(nome))) like 'PIANCO'; 
update cidade set cod_tom = '2129' where uf = 15 and upper(trim(unaccent(nome))) like 'PICUI'; 
update cidade set cod_tom = '2131' where uf = 15 and upper(trim(unaccent(nome))) like 'PILAR'; 
update cidade set cod_tom = '2133' where uf = 15 and upper(trim(unaccent(nome))) like 'PILOES'; 
update cidade set cod_tom = '2135' where uf = 15 and upper(trim(unaccent(nome))) like 'PILOEZINHOS'; 
update cidade set cod_tom = '2137' where uf = 15 and upper(trim(unaccent(nome))) like 'PIRPIRITUBA'; 
update cidade set cod_tom = '2139' where uf = 15 and upper(trim(unaccent(nome))) like 'PITIMBU'; 
update cidade set cod_tom = '2141' where uf = 15 and upper(trim(unaccent(nome))) like 'POCINHOS'; 
update cidade set cod_tom = '0496' where uf = 15 and upper(trim(unaccent(nome))) like 'POCO DANTAS'; 
update cidade set cod_tom = '0498' where uf = 15 and upper(trim(unaccent(nome))) like 'POCO DE JOSE DE MOURA'; 
update cidade set cod_tom = '2143' where uf = 15 and upper(trim(unaccent(nome))) like 'POMBAL'; 
update cidade set cod_tom = '2145' where uf = 15 and upper(trim(unaccent(nome))) like 'PRATA'; 
update cidade set cod_tom = '2147' where uf = 15 and upper(trim(unaccent(nome))) like 'PRINCESA ISABEL'; 
update cidade set cod_tom = '2149' where uf = 15 and upper(trim(unaccent(nome))) like 'PUXINANA'; 
update cidade set cod_tom = '2151' where uf = 15 and upper(trim(unaccent(nome))) like 'QUEIMADAS'; 
update cidade set cod_tom = '2153' where uf = 15 and upper(trim(unaccent(nome))) like 'QUIXABA'; 
update cidade set cod_tom = '2155' where uf = 15 and upper(trim(unaccent(nome))) like 'REMIGIO'; 
update cidade set cod_tom = '0502' where uf = 15 and upper(trim(unaccent(nome))) like 'RIACHAO'; 
update cidade set cod_tom = '0504' where uf = 15 and upper(trim(unaccent(nome))) like 'RIACHAO DO BACAMARTE'; 
update cidade set cod_tom = '0506' where uf = 15 and upper(trim(unaccent(nome))) like 'RIACHAO DO POCO'; 
update cidade set cod_tom = '0508' where uf = 15 and upper(trim(unaccent(nome))) like 'RIACHO DE SANTO ANTONIO'; 
update cidade set cod_tom = '2157' where uf = 15 and upper(trim(unaccent(nome))) like 'RIACHO DOS CAVALOS'; 
update cidade set cod_tom = '2159' where uf = 15 and upper(trim(unaccent(nome))) like 'RIO TINTO'; 
update cidade set cod_tom = '2161' where uf = 15 and upper(trim(unaccent(nome))) like 'SALGADINHO'; 
update cidade set cod_tom = '2163' where uf = 15 and upper(trim(unaccent(nome))) like 'SALGADO DE SAO FELIX'; 
update cidade set cod_tom = '0510' where uf = 15 and upper(trim(unaccent(nome))) like 'SANTA CECILIA'; 
update cidade set cod_tom = '2165' where uf = 15 and upper(trim(unaccent(nome))) like 'SANTA CRUZ'; 
update cidade set cod_tom = '2167' where uf = 15 and upper(trim(unaccent(nome))) like 'SANTA HELENA'; 
update cidade set cod_tom = '0512' where uf = 15 and upper(trim(unaccent(nome))) like 'SANTA INES'; 
update cidade set cod_tom = '2169' where uf = 15 and upper(trim(unaccent(nome))) like 'SANTA LUZIA'; 
update cidade set cod_tom = '2175' where uf = 15 and upper(trim(unaccent(nome))) like 'SANTA RITA'; 
update cidade set cod_tom = '2177' where uf = 15 and upper(trim(unaccent(nome))) like 'SANTA TERESINHA'; 
update cidade set cod_tom = '2171' where uf = 15 and upper(trim(unaccent(nome))) like 'SANTANA DE MANGUEIRA'; 
update cidade set cod_tom = '2173' where uf = 15 and upper(trim(unaccent(nome))) like 'SANTANA DOS GARROTES'; 
update cidade set cod_tom = '0514' where uf = 15 and upper(trim(unaccent(nome))) like 'SANTAREM'; 
update cidade set cod_tom = '0516' where uf = 15 and upper(trim(unaccent(nome))) like 'SANTO ANDRE'; 
update cidade set cod_tom = '0518' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO BENTINHO'; 
update cidade set cod_tom = '2179' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO BENTO'; 
update cidade set cod_tom = '0522' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO DOMINGOS DE POMBAL'; 
update cidade set cod_tom = '0520' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO DOMINGOS DO CARIRI'; 
update cidade set cod_tom = '0524' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO FRANCISCO'; 
update cidade set cod_tom = '2181' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO JOAO DO CARIRI'; 
update cidade set cod_tom = '1913' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO JOAO DO RIO DO PEIXE'; 
update cidade set cod_tom = '2183' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO JOAO DO TIGRE'; 
update cidade set cod_tom = '2185' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO JOSE DA LAGOA TAPADA'; 
update cidade set cod_tom = '2187' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO JOSE DE CAIANA'; 
update cidade set cod_tom = '2189' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO JOSE DE ESPINHARAS'; 
update cidade set cod_tom = '2191' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO JOSE DE PIRANHAS'; 
update cidade set cod_tom = '0528' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO JOSE DE PRINCESA'; 
update cidade set cod_tom = '2193' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO JOSE DO BONFIM'; 
update cidade set cod_tom = '0530' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO JOSE DO BREJO DO CRUZ'; 
update cidade set cod_tom = '2195' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO JOSE DO SABUGI'; 
update cidade set cod_tom = '2197' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO JOSE DOS CORDEIROS'; 
update cidade set cod_tom = '0526' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO JOSE DOS RAMOS'; 
update cidade set cod_tom = '2199' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO MAMEDE'; 
update cidade set cod_tom = '2201' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO MIGUEL DE TAIPU'; 
update cidade set cod_tom = '2203' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO DE LAGOA DE ROCA'; 
update cidade set cod_tom = '2205' where uf = 15 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO DO UMBUZEIRO'; 
update cidade set cod_tom = '2207' where uf = 15 and upper(trim(unaccent(nome))) like 'SAPE'; 
update cidade set cod_tom = '2209' where uf = 15 and upper(trim(unaccent(nome))) like 'SERIDO'; 
update cidade set cod_tom = '2211' where uf = 15 and upper(trim(unaccent(nome))) like 'SERRA BRANCA'; 
update cidade set cod_tom = '2213' where uf = 15 and upper(trim(unaccent(nome))) like 'SERRA DA RAIZ'; 
update cidade set cod_tom = '2215' where uf = 15 and upper(trim(unaccent(nome))) like 'SERRA GRANDE'; 
update cidade set cod_tom = '2217' where uf = 15 and upper(trim(unaccent(nome))) like 'SERRA REDONDA'; 
update cidade set cod_tom = '2219' where uf = 15 and upper(trim(unaccent(nome))) like 'SERRARIA'; 
update cidade set cod_tom = '0532' where uf = 15 and upper(trim(unaccent(nome))) like 'SERTAOZINHO'; 
update cidade set cod_tom = '0534' where uf = 15 and upper(trim(unaccent(nome))) like 'SOBRADO'; 
update cidade set cod_tom = '2221' where uf = 15 and upper(trim(unaccent(nome))) like 'SOLANEA'; 
update cidade set cod_tom = '2223' where uf = 15 and upper(trim(unaccent(nome))) like 'SOLEDADE'; 
update cidade set cod_tom = '0536' where uf = 15 and upper(trim(unaccent(nome))) like 'SOSSEGO'; 
update cidade set cod_tom = '2225' where uf = 15 and upper(trim(unaccent(nome))) like 'SOUSA'; 
update cidade set cod_tom = '2227' where uf = 15 and upper(trim(unaccent(nome))) like 'SUME'; 
update cidade set cod_tom = '2229' where uf = 15 and upper(trim(unaccent(nome))) like 'TACIMA'; 
update cidade set cod_tom = '2231' where uf = 15 and upper(trim(unaccent(nome))) like 'TAPEROA'; 
update cidade set cod_tom = '2233' where uf = 15 and upper(trim(unaccent(nome))) like 'TAVARES'; 
update cidade set cod_tom = '2235' where uf = 15 and upper(trim(unaccent(nome))) like 'TEIXEIRA'; 
update cidade set cod_tom = '0538' where uf = 15 and upper(trim(unaccent(nome))) like 'TENORIO'; 
update cidade set cod_tom = '2237' where uf = 15 and upper(trim(unaccent(nome))) like 'TRIUNFO'; 
update cidade set cod_tom = '2239' where uf = 15 and upper(trim(unaccent(nome))) like 'UIRAUNA'; 
update cidade set cod_tom = '2241' where uf = 15 and upper(trim(unaccent(nome))) like 'UMBUZEIRO'; 
update cidade set cod_tom = '2243' where uf = 15 and upper(trim(unaccent(nome))) like 'VARZEA'; 
update cidade set cod_tom = '0540' where uf = 15 and upper(trim(unaccent(nome))) like 'VIEIROPOLIS'; 
update cidade set cod_tom = '2011' where uf = 15 and upper(trim(unaccent(nome))) like 'VISTA SERRANA'; 
update cidade set cod_tom = '0542' where uf = 15 and upper(trim(unaccent(nome))) like 'ZABELE';