update cidade set cod_tom = '0337' where uf = 27 and upper(trim(unaccent(nome))) like 'ABREULANDIA'; 
update cidade set cod_tom = '0072' where uf = 27 and upper(trim(unaccent(nome))) like 'AGUIARNOPOLIS'; 
update cidade set cod_tom = '9441' where uf = 27 and upper(trim(unaccent(nome))) like 'ALIANCA DO TOCANTINS'; 
update cidade set cod_tom = '9207' where uf = 27 and upper(trim(unaccent(nome))) like 'ALMAS'; 
update cidade set cod_tom = '9213' where uf = 27 and upper(trim(unaccent(nome))) like 'ALVORADA'; 
update cidade set cod_tom = '9219' where uf = 27 and upper(trim(unaccent(nome))) like 'ANANAS'; 
update cidade set cod_tom = '0165' where uf = 27 and upper(trim(unaccent(nome))) like 'ANGICO'; 
update cidade set cod_tom = '9713' where uf = 27 and upper(trim(unaccent(nome))) like 'APARECIDA DO RIO NEGRO'; 
update cidade set cod_tom = '0167' where uf = 27 and upper(trim(unaccent(nome))) like 'ARAGOMINAS'; 
update cidade set cod_tom = '9237' where uf = 27 and upper(trim(unaccent(nome))) like 'ARAGUACEMA'; 
update cidade set cod_tom = '9239' where uf = 27 and upper(trim(unaccent(nome))) like 'ARAGUACU'; 
update cidade set cod_tom = '9241' where uf = 27 and upper(trim(unaccent(nome))) like 'ARAGUAINA'; 
update cidade set cod_tom = '0169' where uf = 27 and upper(trim(unaccent(nome))) like 'ARAGUANA'; 
update cidade set cod_tom = '9243' where uf = 27 and upper(trim(unaccent(nome))) like 'ARAGUATINS'; 
update cidade set cod_tom = '9245' where uf = 27 and upper(trim(unaccent(nome))) like 'ARAPOEMA'; 
update cidade set cod_tom = '9247' where uf = 27 and upper(trim(unaccent(nome))) like 'ARRAIAS'; 
update cidade set cod_tom = '9685' where uf = 27 and upper(trim(unaccent(nome))) like 'AUGUSTINOPOLIS'; 
update cidade set cod_tom = '9253' where uf = 27 and upper(trim(unaccent(nome))) like 'AURORA DO TOCANTINS'; 
update cidade set cod_tom = '9257' where uf = 27 and upper(trim(unaccent(nome))) like 'AXIXA DO TOCANTINS'; 
update cidade set cod_tom = '9259' where uf = 27 and upper(trim(unaccent(nome))) like 'BABACULANDIA'; 
update cidade set cod_tom = '0074' where uf = 27 and upper(trim(unaccent(nome))) like 'BANDEIRANTES DO TOCANTINS'; 
update cidade set cod_tom = '0076' where uf = 27 and upper(trim(unaccent(nome))) like 'BARRA DO OURO'; 
update cidade set cod_tom = '9693' where uf = 27 and upper(trim(unaccent(nome))) like 'BARROLANDIA'; 
update cidade set cod_tom = '9695' where uf = 27 and upper(trim(unaccent(nome))) like 'BERNARDO SAYAO'; 
update cidade set cod_tom = '0341' where uf = 27 and upper(trim(unaccent(nome))) like 'BOM JESUS DO TOCANTINS'; 
update cidade set cod_tom = '0339' where uf = 27 and upper(trim(unaccent(nome))) like 'BRASILANDIA DO TOCANTINS'; 
update cidade set cod_tom = '9273' where uf = 27 and upper(trim(unaccent(nome))) like 'BREJINHO DE NAZARE'; 
update cidade set cod_tom = '9715' where uf = 27 and upper(trim(unaccent(nome))) like 'BURITI DO TOCANTINS'; 
update cidade set cod_tom = '0171' where uf = 27 and upper(trim(unaccent(nome))) like 'CACHOEIRINHA'; 
update cidade set cod_tom = '0173' where uf = 27 and upper(trim(unaccent(nome))) like 'CAMPOS LINDOS'; 
update cidade set cod_tom = '0327' where uf = 27 and upper(trim(unaccent(nome))) like 'CARIRI DO TOCANTINS'; 
update cidade set cod_tom = '0175' where uf = 27 and upper(trim(unaccent(nome))) like 'CARMOLANDIA'; 
update cidade set cod_tom = '0177' where uf = 27 and upper(trim(unaccent(nome))) like 'CARRASCO BONITO'; 
update cidade set cod_tom = '9717' where uf = 27 and upper(trim(unaccent(nome))) like 'CASEARA'; 
update cidade set cod_tom = '0343' where uf = 27 and upper(trim(unaccent(nome))) like 'CENTENARIO'; 
update cidade set cod_tom = '0080' where uf = 27 and upper(trim(unaccent(nome))) like 'CHAPADA DA NATIVIDADE'; 
update cidade set cod_tom = '0078' where uf = 27 and upper(trim(unaccent(nome))) like 'CHAPADA DE AREIA'; 
update cidade set cod_tom = '9311' where uf = 27 and upper(trim(unaccent(nome))) like 'COLINAS DO TOCANTINS'; 
update cidade set cod_tom = '9529' where uf = 27 and upper(trim(unaccent(nome))) like 'COLMEIA'; 
update cidade set cod_tom = '9697' where uf = 27 and upper(trim(unaccent(nome))) like 'COMBINADO'; 
update cidade set cod_tom = '9313' where uf = 27 and upper(trim(unaccent(nome))) like 'CONCEICAO DO TOCANTINS'; 
update cidade set cod_tom = '9321' where uf = 27 and upper(trim(unaccent(nome))) like 'COUTO DE MAGALHAES'; 
update cidade set cod_tom = '9323' where uf = 27 and upper(trim(unaccent(nome))) like 'CRISTALANDIA'; 
update cidade set cod_tom = '0082' where uf = 27 and upper(trim(unaccent(nome))) like 'CRIXAS DO TOCANTINS'; 
update cidade set cod_tom = '0179' where uf = 27 and upper(trim(unaccent(nome))) like 'DARCINOPOLIS'; 
update cidade set cod_tom = '9341' where uf = 27 and upper(trim(unaccent(nome))) like 'DIANOPOLIS'; 
update cidade set cod_tom = '9719' where uf = 27 and upper(trim(unaccent(nome))) like 'DIVINOPOLIS DO TOCANTINS'; 
update cidade set cod_tom = '9345' where uf = 27 and upper(trim(unaccent(nome))) like 'DOIS IRMAOS DO TOCANTINS'; 
update cidade set cod_tom = '9347' where uf = 27 and upper(trim(unaccent(nome))) like 'DUERE'; 
update cidade set cod_tom = '0181' where uf = 27 and upper(trim(unaccent(nome))) like 'ESPERANTINA'; 
update cidade set cod_tom = '9683' where uf = 27 and upper(trim(unaccent(nome))) like 'FATIMA'; 
update cidade set cod_tom = '9667' where uf = 27 and upper(trim(unaccent(nome))) like 'FIGUEIROPOLIS'; 
update cidade set cod_tom = '9355' where uf = 27 and upper(trim(unaccent(nome))) like 'FILADELFIA'; 
update cidade set cod_tom = '9365' where uf = 27 and upper(trim(unaccent(nome))) like 'FORMOSO DO ARAGUAIA'; 
update cidade set cod_tom = '0345' where uf = 27 and upper(trim(unaccent(nome))) like 'FORTALEZA DO TABOCAO'; 
update cidade set cod_tom = '9699' where uf = 27 and upper(trim(unaccent(nome))) like 'GOIANORTE'; 
update cidade set cod_tom = '9533' where uf = 27 and upper(trim(unaccent(nome))) like 'GOIATINS'; 
update cidade set cod_tom = '9627' where uf = 27 and upper(trim(unaccent(nome))) like 'GUARAI'; 
update cidade set cod_tom = '9385' where uf = 27 and upper(trim(unaccent(nome))) like 'GURUPI'; 
update cidade set cod_tom = '0084' where uf = 27 and upper(trim(unaccent(nome))) like 'IPUEIRAS'; 
update cidade set cod_tom = '9405' where uf = 27 and upper(trim(unaccent(nome))) like 'ITACAJA'; 
update cidade set cod_tom = '9409' where uf = 27 and upper(trim(unaccent(nome))) like 'ITAGUATINS'; 
update cidade set cod_tom = '0347' where uf = 27 and upper(trim(unaccent(nome))) like 'ITAPIRATINS'; 
update cidade set cod_tom = '9417' where uf = 27 and upper(trim(unaccent(nome))) like 'ITAPORA DO TOCANTINS'; 
update cidade set cod_tom = '0329' where uf = 27 and upper(trim(unaccent(nome))) like 'JAU DO TOCANTINS'; 
update cidade set cod_tom = '0349' where uf = 27 and upper(trim(unaccent(nome))) like 'JUARINA'; 
update cidade set cod_tom = '0367' where uf = 27 and upper(trim(unaccent(nome))) like 'LAGOA DA CONFUSAO'; 
update cidade set cod_tom = '0353' where uf = 27 and upper(trim(unaccent(nome))) like 'LAGOA DO TOCANTINS'; 
update cidade set cod_tom = '0351' where uf = 27 and upper(trim(unaccent(nome))) like 'LAJEADO'; 
update cidade set cod_tom = '0086' where uf = 27 and upper(trim(unaccent(nome))) like 'LAVANDEIRA'; 
update cidade set cod_tom = '9569' where uf = 27 and upper(trim(unaccent(nome))) like 'LIZARDA'; 
update cidade set cod_tom = '0088' where uf = 27 and upper(trim(unaccent(nome))) like 'LUZINOPOLIS'; 
update cidade set cod_tom = '9711' where uf = 27 and upper(trim(unaccent(nome))) like 'MARIANOPOLIS DO TOCANTINS'; 
update cidade set cod_tom = '0317' where uf = 27 and upper(trim(unaccent(nome))) like 'MATEIROS'; 
update cidade set cod_tom = '0183' where uf = 27 and upper(trim(unaccent(nome))) like 'MAURILANDIA DO TOCANTINS'; 
update cidade set cod_tom = '9461' where uf = 27 and upper(trim(unaccent(nome))) like 'MIRACEMA DO TOCANTINS'; 
update cidade set cod_tom = '9463' where uf = 27 and upper(trim(unaccent(nome))) like 'MIRANORTE'; 
update cidade set cod_tom = '9469' where uf = 27 and upper(trim(unaccent(nome))) like 'MONTE DO CARMO'; 
update cidade set cod_tom = '0090' where uf = 27 and upper(trim(unaccent(nome))) like 'MONTE SANTO DO TOCANTINS'; 
update cidade set cod_tom = '0' where uf = 27 and upper(trim(unaccent(nome))) like 'MOSQUITO'; 
update cidade set cod_tom = '0187' where uf = 27 and upper(trim(unaccent(nome))) like 'MURICILANDIA'; 
update cidade set cod_tom = '9481' where uf = 27 and upper(trim(unaccent(nome))) like 'NATIVIDADE'; 
update cidade set cod_tom = '9483' where uf = 27 and upper(trim(unaccent(nome))) like 'NAZARE'; 
update cidade set cod_tom = '9663' where uf = 27 and upper(trim(unaccent(nome))) like 'NOVA OLINDA'; 
update cidade set cod_tom = '9721' where uf = 27 and upper(trim(unaccent(nome))) like 'NOVA ROSALANDIA'; 
update cidade set cod_tom = '9499' where uf = 27 and upper(trim(unaccent(nome))) like 'NOVO ACORDO'; 
update cidade set cod_tom = '9703' where uf = 27 and upper(trim(unaccent(nome))) like 'NOVO ALEGRE'; 
update cidade set cod_tom = '0321' where uf = 27 and upper(trim(unaccent(nome))) like 'NOVO JARDIM'; 
update cidade set cod_tom = '0092' where uf = 27 and upper(trim(unaccent(nome))) like 'OLIVEIRA DE FATIMA'; 
update cidade set cod_tom = '9733' where uf = 27 and upper(trim(unaccent(nome))) like 'PALMAS'; 
update cidade set cod_tom = '0189' where uf = 27 and upper(trim(unaccent(nome))) like 'PALMEIRANTE'; 
update cidade set cod_tom = '0185' where uf = 27 and upper(trim(unaccent(nome))) like 'PALMEIRAS DO TOCANTINS'; 
update cidade set cod_tom = '9649' where uf = 27 and upper(trim(unaccent(nome))) like 'PALMEIROPOLIS'; 
update cidade set cod_tom = '9519' where uf = 27 and upper(trim(unaccent(nome))) like 'PARAISO DO TOCANTINS'; 
update cidade set cod_tom = '9521' where uf = 27 and upper(trim(unaccent(nome))) like 'PARANA'; 
update cidade set cod_tom = '0191' where uf = 27 and upper(trim(unaccent(nome))) like 'PAU D`ARCO'; 
update cidade set cod_tom = '9525' where uf = 27 and upper(trim(unaccent(nome))) like 'PEDRO AFONSO'; 
update cidade set cod_tom = '9527' where uf = 27 and upper(trim(unaccent(nome))) like 'PEIXE'; 
update cidade set cod_tom = '9705' where uf = 27 and upper(trim(unaccent(nome))) like 'PEQUIZEIRO'; 
update cidade set cod_tom = '9537' where uf = 27 and upper(trim(unaccent(nome))) like 'PINDORAMA DO TOCANTINS'; 
update cidade set cod_tom = '0355' where uf = 27 and upper(trim(unaccent(nome))) like 'PIRAQUE'; 
update cidade set cod_tom = '9547' where uf = 27 and upper(trim(unaccent(nome))) like 'PIUM'; 
update cidade set cod_tom = '9551' where uf = 27 and upper(trim(unaccent(nome))) like 'PONTE ALTA DO BOM JESUS'; 
update cidade set cod_tom = '9553' where uf = 27 and upper(trim(unaccent(nome))) like 'PONTE ALTA DO TOCANTINS'; 
update cidade set cod_tom = '9723' where uf = 27 and upper(trim(unaccent(nome))) like 'PORTO ALEGRE DO TOCANTINS'; 
update cidade set cod_tom = '9559' where uf = 27 and upper(trim(unaccent(nome))) like 'PORTO NACIONAL'; 
update cidade set cod_tom = '9725' where uf = 27 and upper(trim(unaccent(nome))) like 'PRAIA NORTE'; 
update cidade set cod_tom = '9629' where uf = 27 and upper(trim(unaccent(nome))) like 'PRESIDENTE KENNEDY'; 
update cidade set cod_tom = '0094' where uf = 27 and upper(trim(unaccent(nome))) like 'PUGMIL'; 
update cidade set cod_tom = '0357' where uf = 27 and upper(trim(unaccent(nome))) like 'RECURSOLANDIA'; 
update cidade set cod_tom = '0193' where uf = 27 and upper(trim(unaccent(nome))) like 'RIACHINHO'; 
update cidade set cod_tom = '0323' where uf = 27 and upper(trim(unaccent(nome))) like 'RIO DA CONCEICAO'; 
update cidade set cod_tom = '0359' where uf = 27 and upper(trim(unaccent(nome))) like 'RIO DOS BOIS'; 
update cidade set cod_tom = '9679' where uf = 27 and upper(trim(unaccent(nome))) like 'RIO SONO'; 
update cidade set cod_tom = '9727' where uf = 27 and upper(trim(unaccent(nome))) like 'SAMPAIO'; 
update cidade set cod_tom = '0331' where uf = 27 and upper(trim(unaccent(nome))) like 'SANDOLANDIA'; 
update cidade set cod_tom = '0195' where uf = 27 and upper(trim(unaccent(nome))) like 'SANTA FE DO ARAGUAIA'; 
update cidade set cod_tom = '0361' where uf = 27 and upper(trim(unaccent(nome))) like 'SANTA MARIA DO TOCANTINS'; 
update cidade set cod_tom = '0096' where uf = 27 and upper(trim(unaccent(nome))) like 'SANTA RITA DO TOCANTINS'; 
update cidade set cod_tom = '9729' where uf = 27 and upper(trim(unaccent(nome))) like 'SANTA ROSA DO TOCANTINS'; 
update cidade set cod_tom = '9731' where uf = 27 and upper(trim(unaccent(nome))) like 'SANTA TEREZA DO TOCANTINS'; 
update cidade set cod_tom = '0098' where uf = 27 and upper(trim(unaccent(nome))) like 'SANTA TEREZINHA DO TOCANTINS'; 
update cidade set cod_tom = '0197' where uf = 27 and upper(trim(unaccent(nome))) like 'SAO BENTO DO TOCANTINS'; 
update cidade set cod_tom = '0363' where uf = 27 and upper(trim(unaccent(nome))) like 'SAO FELIX DO TOCANTINS'; 
update cidade set cod_tom = '0199' where uf = 27 and upper(trim(unaccent(nome))) like 'SAO MIGUEL DO TOCANTINS'; 
update cidade set cod_tom = '0333' where uf = 27 and upper(trim(unaccent(nome))) like 'SAO SALVADOR DO TOCANTINS'; 
update cidade set cod_tom = '9603' where uf = 27 and upper(trim(unaccent(nome))) like 'SAO SEBASTIAO DO TOCANTINS'; 
update cidade set cod_tom = '9691' where uf = 27 and upper(trim(unaccent(nome))) like 'SAO VALERIO DA NATIVIDADE'; 
update cidade set cod_tom = '9659' where uf = 27 and upper(trim(unaccent(nome))) like 'SILVANOPOLIS'; 
update cidade set cod_tom = '9613' where uf = 27 and upper(trim(unaccent(nome))) like 'SITIO NOVO DO TOCANTINS'; 
update cidade set cod_tom = '0335' where uf = 27 and upper(trim(unaccent(nome))) like 'SUCUPIRA'; 
update cidade set cod_tom = '9615' where uf = 27 and upper(trim(unaccent(nome))) like 'TAGUATINGA'; 
update cidade set cod_tom = '0325' where uf = 27 and upper(trim(unaccent(nome))) like 'TAIPAS DO TOCANTINS'; 
update cidade set cod_tom = '0100' where uf = 27 and upper(trim(unaccent(nome))) like 'TALISMA'; 
update cidade set cod_tom = '9619' where uf = 27 and upper(trim(unaccent(nome))) like 'TOCANTINIA'; 
update cidade set cod_tom = '9621' where uf = 27 and upper(trim(unaccent(nome))) like 'TOCANTINOPOLIS'; 
update cidade set cod_tom = '0102' where uf = 27 and upper(trim(unaccent(nome))) like 'TUPIRAMA'; 
update cidade set cod_tom = '0365' where uf = 27 and upper(trim(unaccent(nome))) like 'TUPIRATINS'; 
update cidade set cod_tom = '9665' where uf = 27 and upper(trim(unaccent(nome))) like 'WANDERLANDIA'; 
update cidade set cod_tom = '9643' where uf = 27 and upper(trim(unaccent(nome))) like 'XAMBIOA';